### ISSUE TITLE
Ubuntu 16.04 run problems

### ISSUE THREAD

**Issue by bmustiata** [kovidgoyal/kitty#1125]
```
$curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8249  100  8249    0     0  24180      0 --:--:-- --:--:-- --:--:-- 24190
Using python executable: /home/raptor/programs/python3.6/bin/python3
Checking for latest release on GitHub...
Will download and install kitty-0.12.3-x86_64.txz
Downloaded 8100112 bytes 
Extracting tarball...
kitty successfully installed to /home/raptor/.local/kitty.app
Use /home/raptor/.local/kitty.app/bin/kitty to run kitty
Traceback (most recent call last):
  File "python3.7/runpy.py", line 280, in run_path
  File "python3.7/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 117, in <module>
  File "kitty/__main__.py", line 110, in main
  File "kitty/main.py", line 10, in <module>
  File "kitty/borders.py", line 7, in <module>
ImportError: /home/raptor/.local/kitty.app/bin/../lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
```

**Comment by kovidgoyal** [comment]
The version of freetype on your system is too old, update it and you
will be fine.

**Comment by bmustiata** [comment]
Is there some installation procedure that doesn't involve destroying my Ubuntu? :)
```
$ sudo apt update
Hit:1 http://at.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://at.archive.ubuntu.com/ubuntu xenial-updates InRelease                                                                                                             
Hit:3 http://at.archive.ubuntu.com/ubuntu xenial-backports InRelease                                                                                                           
Hit:4 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu xenial InRelease                                                                                                          
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]                                                                                                 
Ign:6 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                         
Hit:7 http://ppa.launchpad.net/maarten-baert/simplescreenrecorder/ubuntu xenial InRelease                                                                                            
Hit:8 https://apt.dockerproject.org/repo ubuntu-xenial InRelease                                                                                                                      
Hit:9 https://download.docker.com/linux/ubuntu xenial InRelease                                                                                                                       
Hit:10 http://ppa.launchpad.net/obsproject/obs-studio/ubuntu xenial InRelease                                                  
Hit:11 http://ppa.launchpad.net/pypy/ppa/ubuntu xenial InRelease                              
Hit:12 https://dl.winehq.org/wine-builds/ubuntu xenial InRelease        
Hit:14 http://dl.google.com/linux/chrome/deb stable Release             
Ign:15 https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client xenial InRelease
Hit:13 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
Hit:16 https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client xenial Release
Hit:19 https://s3-us-west-2.amazonaws.com/brave-apt xenial InRelease
Fetched 107 kB in 1s (96.9 kB/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
$ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$ curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8249  100  8249    0     0  36502      0 --:--:-- --:--:-- --:--:-- 36662
Using python executable: /usr/bin/python3
Checking for latest release on GitHub...
Using previously downloaded kitty-0.12.3-x86_64.txz
Extracting tarball...
kitty successfully installed to /home/raptor/.local/kitty.app
Use /home/raptor/.local/kitty.app/bin/kitty to run kitty
Traceback (most recent call last):
  File "python3.7/runpy.py", line 280, in run_path
  File "python3.7/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 117, in <module>
  File "kitty/__main__.py", line 110, in main
  File "kitty/main.py", line 10, in <module>
  File "kitty/borders.py", line 7, in <module>
ImportError: /home/raptor/.local/kitty.app/bin/../lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
$ 
```

**Comment by kovidgoyal** [comment]
yes, update to the next LTS ubuntu release. Or install freetype by hand
in somewhere and use that with kitty, by using PKGCONFIG_PATH

See https://github.com/kovidgoyal/kitty/issues/595
