### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1156]
Since I'm hearing a lecture about fuzzers and I wanted to apply my knowledge to kitty, I wrote a simple fuzzer, which caused the following exception:
```pytb
Traceback (most recent call last):
  File "/path/to/kitty.app/Contents/MacOS/../Frameworks/kitty/kitty/window.py", line 341, in set_color_table_color
    for c, val in parse_color_set(value):
  File "/path/to/kitty.app/Contents/MacOS/../Frameworks/kitty/kitty/utils.py", line 64, in parse_color_set
    for c, spec in [parts[i:i + 2] for i in range(0, len(parts), 2)]:
ValueError: not enough values to unpack (expected 2, got 1)
```
The fix is probably to check if `parts` has the right number of elements.

**Comment by Luflosi** [comment]
The line number in window.py is a little off because the kitty version I used was maybe a day or two behind your master branch, the line number with the latest version is 360.
