### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1166]
I got this segmentation fault in a Linux VM after running a simple fuzzer for a couple hours. I fuzzed my kitty fork (with AddressSanitizer), I should probably use your master version. I hope this information is still useful to you.
```
/home/u/Desktop/sf_kitty_luflosi/kitty/screen.c:971:23: runtime error: store to null pointer of type 'struct ScreenModes'
ASAN:DEADLYSIGNAL
=================================================================
==1678==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f787d9d0071 bp 0x7ffcb79b5f40 sp 0x7ffcb79b5f20 T0)
==1678==The signal is caused by a WRITE memory access.
==1678==Hint: address points to the zero page.
    #0 0x7f787d9d0070 in screen_restore_modes /home/u/Desktop/sf_kitty_luflosi/kitty/screen.c:971
    #1 0x7f787d925536 in dispatch_csi /home/u/Desktop/sf_kitty_luflosi/kitty/parser.c:756
    #2 0x7f787d92ecb6 in _parse_bytes_watching_for_pending /home/u/Desktop/sf_kitty_luflosi/kitty/parser.c:1105
    #3 0x7f787d92ecb6 in do_parse_bytes /home/u/Desktop/sf_kitty_luflosi/kitty/parser.c:1223
    #4 0x7f787d932ca4 in parse_worker /home/u/Desktop/sf_kitty_luflosi/kitty/parser.c:1278
    #5 0x7f787d955294 in do_parse /home/u/Desktop/sf_kitty_luflosi/kitty/child-monitor.c:336
    #6 0x7f787d955294 in parse_input /home/u/Desktop/sf_kitty_luflosi/kitty/child-monitor.c:406
    #7 0x7f787d959dff in main_loop /home/u/Desktop/sf_kitty_luflosi/kitty/child-monitor.c:795
    #8 0x503090  (/usr/bin/python3.6+0x503090)
    #9 0x506858 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x506858)
    #10 0x502208  (/usr/bin/python3.6+0x502208)
    #11 0x502f3c  (/usr/bin/python3.6+0x502f3c)
    #12 0x506858 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x506858)
    #13 0x502208  (/usr/bin/python3.6+0x502208)
    #14 0x502f3c  (/usr/bin/python3.6+0x502f3c)
    #15 0x506858 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x506858)
    #16 0x502208  (/usr/bin/python3.6+0x502208)
    #17 0x502f3c  (/usr/bin/python3.6+0x502f3c)
    #18 0x506858 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x506858)
    #19 0x502208  (/usr/bin/python3.6+0x502208)
    #20 0x502f3c  (/usr/bin/python3.6+0x502f3c)
    #21 0x506858 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x506858)
    #22 0x502208  (/usr/bin/python3.6+0x502208)
    #23 0x502f3c  (/usr/bin/python3.6+0x502f3c)
    #24 0x506858 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x506858)
    #25 0x504c27  (/usr/bin/python3.6+0x504c27)
    #26 0x511d77  (/usr/bin/python3.6+0x511d77)
    #27 0x502d6e  (/usr/bin/python3.6+0x502d6e)
    #28 0x506858 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x506858)
    #29 0x504c27  (/usr/bin/python3.6+0x504c27)
    #30 0x50253f  (/usr/bin/python3.6+0x50253f)
    #31 0x502f3c  (/usr/bin/python3.6+0x502f3c)
    #32 0x506858 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x506858)
    #33 0x504c27  (/usr/bin/python3.6+0x504c27)
    #34 0x50253f  (/usr/bin/python3.6+0x50253f)
    #35 0x502f3c  (/usr/bin/python3.6+0x502f3c)
    #36 0x507640 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x507640)
    #37 0x504c27  (/usr/bin/python3.6+0x504c27)
    #38 0x506392 in PyEval_EvalCode (/usr/bin/python3.6+0x506392)
    #39 0x634d51  (/usr/bin/python3.6+0x634d51)
    #40 0x634e09 in PyRun_FileExFlags (/usr/bin/python3.6+0x634e09)
    #41 0x6385c7 in PyRun_SimpleFileExFlags (/usr/bin/python3.6+0x6385c7)
    #42 0x639159 in Py_Main (/usr/bin/python3.6+0x639159)
    #43 0x4a6f0f in main (/usr/bin/python3.6+0x4a6f0f)
    #44 0x7f7882a02b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #45 0x5afa09 in _start (/usr/bin/python3.6+0x5afa09)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/u/Desktop/sf_kitty_luflosi/kitty/screen.c:971 in screen_restore_modes
==1678==ABORTING
```

**Comment by Luflosi** [comment]
Here is what looks like the same crash with your latest master branch:
```
/home/u/Desktop/kitty/kitty/screen.c:981:23: runtime error: store to null pointer of type 'struct ScreenModes'
ASAN:DEADLYSIGNAL
=================================================================
==2021==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fe8753cb39e bp 0x7fff30cc0fa0 sp 0x7fff30cc0f80 T0)
==2021==The signal is caused by a WRITE memory access.
==2021==Hint: address points to the zero page.
    #0 0x7fe8753cb39d in screen_restore_modes /home/u/Desktop/kitty/kitty/screen.c:981
    #1 0x7fe875355ea8 in dispatch_csi /home/u/Desktop/kitty/kitty/parser.c:756
    #2 0x7fe87535f628 in _parse_bytes_watching_for_pending /home/u/Desktop/kitty/kitty/parser.c:1105
    #3 0x7fe87535f628 in do_parse_bytes /home/u/Desktop/kitty/kitty/parser.c:1223
    #4 0x7fe875363616 in parse_worker /home/u/Desktop/kitty/kitty/parser.c:1278
    #5 0x7fe875402f71 in do_parse /home/u/Desktop/kitty/kitty/child-monitor.c:336
    #6 0x7fe875402f71 in parse_input /home/u/Desktop/kitty/kitty/child-monitor.c:406
    #7 0x7fe875407a63 in main_loop /home/u/Desktop/kitty/kitty/child-monitor.c:795
    #8 0x503090  (/usr/bin/python3.6+0x503090)
    #9 0x506858 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x506858)
    #10 0x502208  (/usr/bin/python3.6+0x502208)
    #11 0x502f3c  (/usr/bin/python3.6+0x502f3c)
    #12 0x506858 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x506858)
    #13 0x502208  (/usr/bin/python3.6+0x502208)
    #14 0x502f3c  (/usr/bin/python3.6+0x502f3c)
    #15 0x506858 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x506858)
    #16 0x502208  (/usr/bin/python3.6+0x502208)
    #17 0x502f3c  (/usr/bin/python3.6+0x502f3c)
    #18 0x506858 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x506858)
    #19 0x502208  (/usr/bin/python3.6+0x502208)
    #20 0x502f3c  (/usr/bin/python3.6+0x502f3c)
    #21 0x506858 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x506858)
    #22 0x502208  (/usr/bin/python3.6+0x502208)
    #23 0x502f3c  (/usr/bin/python3.6+0x502f3c)
    #24 0x506858 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x506858)
    #25 0x504c27  (/usr/bin/python3.6+0x504c27)
    #26 0x511d77  (/usr/bin/python3.6+0x511d77)
    #27 0x502d6e  (/usr/bin/python3.6+0x502d6e)
    #28 0x506858 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x506858)
    #29 0x504c27  (/usr/bin/python3.6+0x504c27)
    #30 0x50253f  (/usr/bin/python3.6+0x50253f)
    #31 0x502f3c  (/usr/bin/python3.6+0x502f3c)
    #32 0x506858 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x506858)
    #33 0x504c27  (/usr/bin/python3.6+0x504c27)
    #34 0x50253f  (/usr/bin/python3.6+0x50253f)
    #35 0x502f3c  (/usr/bin/python3.6+0x502f3c)
    #36 0x507640 in _PyEval_EvalFrameDefault (/usr/bin/python3.6+0x507640)
    #37 0x504c27  (/usr/bin/python3.6+0x504c27)
    #38 0x506392 in PyEval_EvalCode (/usr/bin/python3.6+0x506392)
    #39 0x634d51  (/usr/bin/python3.6+0x634d51)
    #40 0x634e09 in PyRun_FileExFlags (/usr/bin/python3.6+0x634e09)
    #41 0x6385c7 in PyRun_SimpleFileExFlags (/usr/bin/python3.6+0x6385c7)
    #42 0x639159 in Py_Main (/usr/bin/python3.6+0x639159)
    #43 0x4a6f0f in main (/usr/bin/python3.6+0x4a6f0f)
    #44 0x7fe87a442b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #45 0x5afa09 in _start (/usr/bin/python3.6+0x5afa09)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/u/Desktop/kitty/kitty/screen.c:981 in screen_restore_modes
==2021==ABORTING
```
