### ISSUE TITLE
Cannot set layout in a `tmux` session

### ISSUE THREAD

**Issue by lenormf** [kovidgoyal/kitty#1169]
Hi,

I'm running `tmux` v2.8 in `kitty` v0.12.3.

Reproducer:

```
$ tmux
$ kitty @ goto-layout fat
```

Outcome:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main                                   
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code                                              
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 117, in <module>                                        
    main()
  File "/usr/bin/../lib/kitty/__main__.py", line 113, in main                                            
    func(sys.argv[1:])
  File "/usr/bin/../lib/kitty/__main__.py", line 22, in remote_control                                   
    main(args)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 176, in main                                
    response = do_io(global_opts.to, send, no_response)                                                  
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 124, in do_io                               
    received = io.recv(timeout=10)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 104, in recv                                
    read_command_response(self.tty_fd, timeout, ans)
TimeoutError: Timed out while waiting to read cmd response   
```

The command works as expected outside of `tmux`.

**Comment by kovidgoyal** [comment]
tmux intercepts and filters out escape codes, so it is not surprising that functionality that uses escape codes wont work with it. Use a socket based communication method instead (see the --to argu for kitty @) or get tmux to pass through the escape codes kitty uses.
