### ISSUE TITLE
Kitty remote control from neovim

### ISSUE THREAD

**Issue by knubie** [kovidgoyal/kitty#1262]
Trying to call `kitty @ new-window` from neovim, but running into some issues.

I believe it's related to this [issue](https://github.com/neovim/neovim/issues/1496), because it works fine with vim.

`:!kitty @ new-window` from neovim outputs the following:
```
:!kitty @ new-window
Traceback (most recent call last):
  File "Python/runpy.py", line 280, in run_path
  File "Python/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 117, in <module>
  File "kitty/__main__.py", line 113, in main
  File "kitty/__main__.py", line 22, in remote_control
  File "kitty/remote_control.py", line 176, in main
  File "kitty/remote_control.py", line 120, in do_io
  File "kitty/utils.py", line 376, in __enter__
OSError: [Errno 6] Device not configured

shell returned 1

Press ENTER or type command to continue
```

`:!kitty "@ new-window"` outputs:
```
:!kitty "@ new-window"
 new-window is not a known command. Known commands are: close-tab, close-window, focus-tab, focus-window, get-colors, get-text, goto-layout, kitten, last-used-layout, ls, new-wi
ndow, resize-window, send-text, set-background-opacity, set-colors, set-font-size, set-tab-title, set-window-title

shell returned 1

Press ENTER or type command to continue
```

and `:call system("kitty @ new-window")` just doesn't do anything.

**Comment by knubie** [comment]
Thanks @kovidgoyal that works. This might be a silly question, but; how can I run kitty with options without keeping a second terminal open? Right now I'm running `kitty --some-options` from... kitty, which launches another instance of kitty, and if I close the first one, it closes the second one as well.

**Comment by kovidgoyal** [comment]
create an alias or a launch script or if you are on macOS use the cmdline facility described in the kitty FAQ

**Comment by knubie** [comment]
I ended up writing this vim plugin: [vim-kitty-navigator](https://github.com/knubie/vim-kitty-navigator). Maybe someone will find it useful.
