### ISSUE TITLE
Error running from source on macos: ImportError: cannot import name 'fast_data_types'

### ISSUE THREAD

**Issue by jwkvam** [kovidgoyal/kitty#129]
Thanks for fixing #120, unfortunately now I'm having trouble running from source.

There are some deprecation warnings
```
CC: gcc (4, 2)
gcc -Wextra -Wno-missing-field-initializers -Wall -std=c99 -D_XOPEN_SOURCE=700 -pedantic-errors -Werror -O3 -DNDEBUG -fwrapv -fstack-protector -Wno-missing-braces -pipe -march=native -fvisibility=hidden -pthread -DPRIMARY_VERSION=4000 -DSECONDARY_VERSION=3 -I/usr/local/Cellar/glfw/3.2.1/include -I/Users/jacques/miniconda/include/python3.6m -I/Users/jacques/miniconda/include/python3.6m -c /Users/jacques/src/kitty/kitty/child-monitor.c -o /Users/jacques/src/kitty/build/fast_data_types-child-monitor.c.o
gcc -Wextra -Wno-missing-field-initializers -Wall -std=c99 -D_XOPEN_SOURCE=700 -pedantic-errors -Werror -O3 -DNDEBUG -fwrapv -fstack-protector -Wno-missing-braces -pipe -march=native -fvisibility=hidden -pthread -DPRIMARY_VERSION=4000 -DSECONDARY_VERSION=3 -I/usr/local/Cellar/glfw/3.2.1/include -I/Users/jacques/miniconda/include/python3.6m -I/Users/jacques/miniconda/include/python3.6m -c /Users/jacques/src/kitty/kitty/cocoa_window.m -o /Users/jacques/src/kitty/build/fast_data_types-cocoa_window.m.o
/Users/jacques/src/kitty/kitty/cocoa_window.m:95:38: error: 'NSAlternateKeyMask' is deprecated: first deprecated in macOS 10.12 [-Werror,-Wdeprecated-declarations]
        setKeyEquivalentModifierMask:NSAlternateKeyMask | NSCommandKeyMask];
                                     ^~~~~~~~~~~~~~~~~~
                                     NSEventModifierFlagOption
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:184:35: note: 'NSAlternateKeyMask' has been explicitly marked deprecated here
static const NSEventModifierFlags NSAlternateKeyMask          API_DEPRECATED_WITH_REPLACEMENT("NSEventModifierFlagOption", macosx(10.0, 10.12)) = NSEventModifierFlagOption;
                                  ^
/Users/jacques/src/kitty/kitty/cocoa_window.m:95:59: error: 'NSCommandKeyMask' is deprecated: first deprecated in macOS 10.12 [-Werror,-Wdeprecated-declarations]
        setKeyEquivalentModifierMask:NSAlternateKeyMask | NSCommandKeyMask];
                                                          ^~~~~~~~~~~~~~~~
                                                          NSEventModifierFlagCommand
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:185:35: note: 'NSCommandKeyMask' has been explicitly marked deprecated here
static const NSEventModifierFlags NSCommandKeyMask            API_DEPRECATED_WITH_REPLACEMENT("NSEventModifierFlagCommand", macosx(10.0, 10.12)) = NSEventModifierFlagCommand;
                                  ^
/Users/jacques/src/kitty/kitty/cocoa_window.m:135:35: error: 'NSControlKeyMask' is deprecated: first deprecated in macOS 10.12 [-Werror,-Wdeprecated-declarations]
     setKeyEquivalentModifierMask:NSControlKeyMask | NSCommandKeyMask];
                                  ^~~~~~~~~~~~~~~~
                                  NSEventModifierFlagControl
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:183:35: note: 'NSControlKeyMask' has been explicitly marked deprecated here
static const NSEventModifierFlags NSControlKeyMask            API_DEPRECATED_WITH_REPLACEMENT("NSEventModifierFlagControl", macosx(10.0, 10.12)) = NSEventModifierFlagControl;
                                  ^
/Users/jacques/src/kitty/kitty/cocoa_window.m:135:54: error: 'NSCommandKeyMask' is deprecated: first deprecated in macOS 10.12 [-Werror,-Wdeprecated-declarations]
     setKeyEquivalentModifierMask:NSControlKeyMask | NSCommandKeyMask];
                                                     ^~~~~~~~~~~~~~~~
                                                     NSEventModifierFlagCommand
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:185:35: note: 'NSCommandKeyMask' has been explicitly marked deprecated here
static const NSEventModifierFlags NSCommandKeyMask            API_DEPRECATED_WITH_REPLACEMENT("NSEventModifierFlagCommand", macosx(10.0, 10.12)) = NSEventModifierFlagCommand;
                                  ^
4 errors generated.
```
I do get `fast_data_types-child-monitor.c.o` in build. If I try to run kitty I get the following traceback:
```
Traceback (most recent call last):
  File "/Users/jacques/miniconda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/jacques/miniconda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kitty/__main__.py", line 8, in <module>
    from kitty.main import main  # noqa
  File "kitty/kitty/main.py", line 12, in <module>
    from .boss import Boss
  File "kitty/kitty/boss.py", line 8, in <module>
    from .config import MINIMUM_FONT_SIZE
  File "kitty/kitty/config.py", line 14, in <module>
    from . import fast_data_types as defines
ImportError: cannot import name 'fast_data_types'
```

**Comment by koekeishiya** [comment]
The cocoa eventflags used are deprecated in 10.12 and newer, and this causes warnings. Kitty tries to compile with `-Werror` which is why this happened.

I have fixed this in the following commit in my fork: https://github.com/koekeishiya/kitty/commit/2fd00269655e524a36396ef50aacd622fd139cc5

I would offer a PR but I have done some other changes that does not belong upstream. Hopefully the above diff is good enough for @kovidgoyal to quickly solve this. Note that the changes made in the commit I linked will break support for macOS < 10.12
