### ISSUE TITLE
build fails on macOS

### ISSUE THREAD

**Issue by andrewrech** [kovidgoyal/kitty#1354]
Beginning in d3ad15dc516515329fb4f85f43867168d1dd30a7 but not before:

```
cd /path/to/kitty/repo
python3 .
```

```
[033 04:47:35.163860] Traceback (most recent call last):
  File "./kitty/main.py", line 276, in main
    _main()
  File "./kitty/main.py", line 269, in _main
    run_app(opts, args)
  File "./kitty/main.py", line 145, in run_app
    _run_app(opts, args)
  File "./kitty/main.py", line 133, in _run_app
    boss.start()
  File "./kitty/boss.py", line 364, in start
    run_update_check(self.opts.update_check_interval * 60 * 60)
  File "./kitty/update_check.py", line 108, in run_update_check
    update_check()
  File "./kitty/update_check.py", line 102, in update_check
    ], stdout=subprocess.PIPE)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'kitty'

[1]    45105 exit 1     python3 .
```

```
git checkout d3ad15dc516515329fb4f85f43867168d1dd30a7
make clean
make --debug
```

```
GNU Make 4.2.1
Built for x86_64-apple-darwin16.5.0
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Updating makefiles....
Updating goal targets....
 File 'all' does not exist.
Must remake target 'all'.
python3 setup.py 
CC: clang (4, 2)
Compiling kitty/cocoa_window.m ...
Compiling kitty/screen.c ...
Compiling kitty/graphics.c ...
Compiling kitty/gl-wrapper.c ...
Compiling kitty/line-buf.c ...
Compiling kitty/core_text.m ...
Compiling kitty/cursor.c ...
Compiling kitty/keys.c ...
Compiling kitty/unicode-data.c ...
Compiling kitty/png-reader.c ...
Compiling kitty/macos_process_info.c ...
Compiling kitty/logging.c ...
Compiling kitty/kittens.c ...
Compiling kitty/parser_dump.c ...
Linking kitty/fast_data_types ...
Compiling glfw/context.c ...
Compiling glfw/init.c ...
Compiling glfw/input.c ...
Compiling glfw/monitor.c ...
Compiling glfw/vulkan.c ...
Compiling glfw/window.c ...
Compiling glfw/cocoa_init.m ...
Compiling glfw/cocoa_joystick.m ...
Compiling glfw/cocoa_monitor.m ...
Compiling glfw/cocoa_window.m ...
Compiling glfw/cocoa_time.c ...
Compiling glfw/posix_thread.c ...
Compiling glfw/nsgl_context.m ...
Compiling glfw/egl_context.c ...
Compiling glfw/osmesa_context.c ...
Linking kitty/glfw-cocoa ...
Compiling kittens/unicode_input/unicode_names.c ...
^[Linking kittens/unicode_input/unicode_names ...
Compiling kittens/diff/speedup.c ...
Linking kittens/diff/diff_speedup ...
Compiling kitty/charsets.c ...
Compiling kittens/choose/unix_compat.c ...
Compiling kittens/choose/main.c ...
Compiling kittens/choose/score.c ...
Compiling kittens/choose/output.c ...
Linking kittens/choose/subseq_matcher ...
Successfully remade target file 'all'.
```

System

```
Darwin xxx 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

Python 3.7.2

compiler
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by kovidgoyal** [comment]
this should already be fixed by https://github.com/kovidgoyal/kitty/commit/13d478ffcad35a90f89d6af4c80b604e1fc85632

**Comment by andrewrech** [comment]
@kovidgoyal 

Every commit after d3ad15d fails with the above message including 13d478f

```
~/kitty master~2* 36s
❯ python3 .
[033 05:49:32.112609] Traceback (most recent call last):
  File "./kitty/main.py", line 276, in main
    _main()
  File "./kitty/main.py", line 269, in _main
    run_app(opts, args)
  File "./kitty/main.py", line 145, in run_app
    _run_app(opts, args)
  File "./kitty/main.py", line 133, in _run_app
    boss.start()
  File "./kitty/boss.py", line 364, in start
    run_update_check(self.opts.update_check_interval * 60 * 60)
  File "./kitty/update_check.py", line 108, in run_update_check
    update_check()
  File "./kitty/update_check.py", line 102, in update_check
    ], stdout=subprocess.PIPE)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/usr/local/bin/kitty'

[1]    4382 exit 1     python3 .
```

**Comment by kovidgoyal** [comment]
Delete /usr/local/nin/kitty and update to HEAD whre I have changed it to ignore this failure.
