### ISSUE TITLE
Kitty will crash if the font is set too small

### ISSUE THREAD

**Issue by fdev31** [kovidgoyal/kitty#1378]
Using the keyboard to reduce the font size, one may crash kitty by testing extreme (or by mistake).
I don't do a pull request since I don't have the right patch, I had to use a magic value to "fix" the issue:
```diff
diff --git a/kitty/boss.py b/kitty/boss.py
index 7475f179..5e8a55d1 100644
--- a/kitty/boss.py
+++ b/kitty/boss.py
@@ -454,7 +454,7 @@ class Boss:
     def _change_font_size(self, sz_map):
         for os_window_id, sz in sz_map.items():
             tm = self.os_window_map.get(os_window_id)
-            if tm is not None:
+            if tm is not None and sz > 4:
                 os_window_font_size(os_window_id, sz)
                 tm.resize()
```
It prevents the following unhandled exception:
```Traceback (most recent call last):
  File "/tmp/kitty/kitty/fonts/render.py", line 206, in prerender_function
    cells = f(1), f(2), f(3), f(0, True), f(missing=True), c(1), c(2), c(3)
  File "/tmp/kitty/kitty/fonts/render.py", line 158, in render_special
    dl([None, add_line, add_dline, add_curl][underline], underline_position, t, cell_height)
  File "/tmp/kitty/kitty/fonts/render.py", line 152, in dl
    f(ans, cell_width, *a)
  File "/tmp/kitty/kitty/fonts/render.py", line 119, in add_curl
    xfactor = 2.0 * pi / max_x
ZeroDivisionError: float division by zero
```

**Comment by kovidgoyal** [comment]
I cannot reproduce, reducing font sizes simply stops at a minimum value. Are you using adjust_cell_width?
