### ISSUE TITLE
"Failed to compile shader" on OSX 10.11.6

### ISSUE THREAD

**Issue by Alok** [kovidgoyal/kitty#140]
I clone the repo, run `python3.6 setup.py build`, and then run `python3.6 kitty` and get this error:

```
$ python3.6 kitty
Ignoring unknown config key: cursor_opacity
2017-10-11 23:18:28.385 Python[22856:42444587] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/52/pd9v2v217dqdkj574btgbn4h0000gp/T/org.python.python.savedState
Failed to compile GLSL shader!
ERROR: 0:9: Invalid call of undeclared identifier 'texture2D'
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kitty/__main__.py", line 13, in <module>
  File "kitty/kitty/main.py", line 287, in main
  File "kitty/kitty/main.py", line 195, in run_app
  File "kitty/kitty/boss.py", line 73, in __init__
  File "kitty/kitty/window.py", line 65, in load_shader_programs
ValueError: Failed to compile shader   
```

**Comment by Alok** [comment]
That works, except that when I run kitty, all the text is invisible, and opening vim is also invisible.

**Comment by kovidgoyal** [comment]
Sigh OpenGL on macs is so underpowered. I'll look at it when I have a moment.

**Comment by kovidgoyal** [comment]
Should be fixed by https://github.com/kovidgoyal/kitty/commit/555409ea73ad51f5e47f84d11350fb3ad6987342

**Comment by Alok** [comment]
Nope, text is still invisible.
