### ISSUE TITLE
diff kitten: crash with `ValueError: line too long`

### ISSUE THREAD

**Issue by 4e554c4c** [kovidgoyal/kitty#1433]
Hello, when running `kitty +kitten diff` on a project i work on i am getting the following error after adding quite a long line.
```
Exception in callback DiffHandler.syntax_highlight.<locals>.highlighting_done({'/tmp/git-dif....component.ts': [[Segment(start...de='\x1b[39m'), Segment(start...de='\x1b[39m'), Segment(start...de='\x1b[39m'), Segment(start...de='\x1b[39m')7…
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/bin/../lib/kitty/kittens/diff/main.py", line 163, in highlighting_done
    self.render_diff()
  File "/usr/bin/../lib/kitty/kittens/diff/main.py", line 180, in render_diff
    self.diff_lines = tuple(render_diff(self.collection, self.diff_map, self.args, self.screen_size.cols, self.image_manager))
  File "/usr/bin/../lib/kitty/kittens/diff/render.py", line 488, in render_diff
    yield from ans
  File "/usr/bin/../lib/kitty/kittens/diff/render.py", line 337, in lines_for_diff
    yield from lines_for_chunk(data, hunk_num, chunk, cnum)
  File "/usr/bin/../lib/kitty/kittens/diff/render.py", line 308, in lines_for_chunk
    None if chunk.centers is None else chunk.centers[i]))
  File "/usr/bin/../lib/kitty/kittens/diff/render.py", line 262, in render_half_line
    lines = split_with_highlights(line, available_cols, highlights, bg_highlight)
  File "/usr/bin/../lib/kitty/kittens/diff/render.py", line 198, in split_with_highlights
    return _split_with_highlights(line, truncate_pts, highlights, bg_highlight)
ValueError: line too long
```

**Comment by kovidgoyal** [comment]
There is currently a 4KB limit on how long a line the diff kitten will
process, this could of course be removed, but doing so is not worth the
effort to me since such long lines are pretty rare, and viewing diffs of
them is pretty useless. Patches are however, welcome.
