### ISSUE TITLE
ValueError:  Can only assign sequence of same size

### ISSUE THREAD

**Issue by Anonrate** [kovidgoyal/kitty#154]
I have forked Kitty in attempt to add support for bitmapped fonts.  I am currently getting this error.

```
Traceback (most recent call last):
  File "./kitty/fonts/render.py", line 84, in render_cell_wrapper
    first, second = render_cell(text, bold, italic, underline, strikethrough)
  File "./kitty/fonts/render.py", line 55, in render_cell
    first, second = rc(text, bold, italic)
  File "./kitty/fonts/freetype.py", line 272, in render_cell
    first = place_char_in_cell(bitmap_char)
  File "./kitty/fonts/freetype.py", line 210, in place_char_in_cell
    src_start_column, dest_start_column, column_count
  File "./kitty/fonts/freetype.py", line 288, in create_cell_buffer
    dest[dr:dr + column_count] = src[sr:sr + column_count]
ValueError: Can only assign sequence of same size
Rendering of a cell failed, aborting
```

My version may look different from yours, so here is a link to mine if you need to take a closer look.  [freetype.py:288][1]

I apologize  if  you don't have don't have time to assist me in this.  I do know that using bitmapped fonts does not peek your interest.  I just have no idea where to even start when it comes to freetype.  

I have already gone and made a few modifications such as changing `allow_bitmaped_fonts=False` to `allow_bitmaped_fonts=True`<sup>[[freetype.py:44][2]]</sup>

I have commented out lines [120-124][3] (It seemed like the right thing to do.  Lol)

I have set the corresponding ptsize for the bitmap I'm trying to use in the conf file.  This is the formula I used:
`24 / 108 * 72 = 16` 

Further modifications are adding the `FT_LOAD_MONOCHROME` flag [freetype.c:168][4]
Did the same for [freetype.c:418][5]

And lastly, I commented out `PyModule_AddIntMacro(m, FT_LOAD_TARGET_NORMAL);` and `PyModule_AddIntMacro(m, FT_LOAD_TARGET_LIGHT);`.  <sup>[[freetype.c:419-420][6]]</sup>

I am pretty sure that is all I have changed other than just reformatting the code.  Any help would be awesome, even direction to somewhere else to get help is great as well.  I hope this is not being intrusive asking for this kind of help.

[1]: https://github.com/Anonrate/kitty/blob/master/kitty/fonts/freetype.py#L288
[2]: https://github.com/Anonrate/kitty/blob/master/kitty/fonts/freetype.py#L44
[3]: https://github.com/Anonrate/kitty/blob/master/kitty/fonts/freetype.py#L120-L124
[4]: https://github.com/Anonrate/kitty/blob/master/kitty/freetype.c#L168
[5]: https://github.com/Anonrate/kitty/blob/master/kitty/freetype.c#L418
[6]: https://github.com/Anonrate/kitty/blob/master/kitty/freetype.c#L419-L420

**Comment by kovidgoyal** [comment]
Sorry I dont have the time to help with this. But from your traceback, I'd guess your buffers contain data of different types. The buffers kitty expects contain one byte per pixel. If you get freetype to render without antialiasing it will give you a buffer with one bit per pixel instead. You would need to convert that to one byte per pixel manually.

**Comment by Anonrate** [comment]
Thank you for your response.
