### ISSUE TITLE
Issues with running

### ISSUE THREAD

**Issue by SeunLanLege** [kovidgoyal/kitty#178]
I installed kitty via `nix-env`

`nix-env --install kitty`

when i try to run kitty i get 

I'm running ubuntu 16.04 LTS

```
➜ kitty                                                                                          ⏎ master
Traceback (most recent call last):
  File "/nix/store/166s7l3yjqfc8dj5hfqjb09dbfvp1850-python3-3.6.3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nix/store/166s7l3yjqfc8dj5hfqjb09dbfvp1850-python3-3.6.3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nix/store/gmavxgg6gf4lalybf4f9givj0m6sdkql-kitty-0.4.2/bin/../lib/kitty/__main__.py", line 12, in <module>
    from kitty.main import main
  File "/nix/store/gmavxgg6gf4lalybf4f9givj0m6sdkql-kitty-0.4.2/bin/../lib/kitty/kitty/main.py", line 13, in <module>
    from .boss import Boss
  File "/nix/store/gmavxgg6gf4lalybf4f9givj0m6sdkql-kitty-0.4.2/bin/../lib/kitty/kitty/boss.py", line 8, in <module>
    from .config import MINIMUM_FONT_SIZE
  File "/nix/store/gmavxgg6gf4lalybf4f9givj0m6sdkql-kitty-0.4.2/bin/../lib/kitty/kitty/config.py", line 15, in <module>
    from .constants import config_dir
  File "/nix/store/gmavxgg6gf4lalybf4f9givj0m6sdkql-kitty-0.4.2/bin/../lib/kitty/kitty/constants.py", line 70, in <module>
    shell_path = pwd.getpwuid(os.geteuid()).pw_shell or '/bin/sh'
KeyError: 'getpwuid(): uid not found: 1000'
```

**Comment by SeunLanLege** [comment]
Has this update been pushed to nix? because i just tried updating kitty and i don't think it updated.

**Comment by kovidgoyal** [comment]
No idea, I dont use/maintain the nixpkg.
