### ISSUE TITLE
Starting Kitty via i3 crashes Xorg

### ISSUE THREAD

**Issue by SoptikHa2** [kovidgoyal/kitty#1905]
Kitty version 0.14.3
I installed Kitty via pacman.
ArchLinux x86_64
i3
Xorg

---

I decided to change my terminal to kitty. So I went to my i3 config and changed terminal that is launched after pressing alt+enter. The config line looks like this:
```
bindsym $mod+Return exec kitty
```
When I run kitty via `% kitty` or `% exec kitty`, everything works. However, when I press alt+enter (so i3 launches kitty), xorg crashes. I didn't see anything suspicious in xorg log, but it printed this to my screen after crash:
```
(EE) Server terminated with error (1). Closing log file.
(xinit complaining about not being able to connect to xorg)
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 314 in main _main() 
  File "/usr/bin/../lib/kitty/kitty/main.py", line 303 in _main setup_environment(opts, args)
  File "/usr/bin/../lib/kitty/kitty/main.py" line 227 in setup_environment shell_env = read_shell_environment(opts)
  File "/usr/bin/../lib/kitty/kitty/main.py" line 220 in read_shell_environment return read_shell_environment.ans
  AttributeError: 'function' object has no attribute 'ans'
```

**Comment by Luflosi** [comment]
This is fixed in the latest master, see #1869.
As a workaround, either change the `editor` config option to something like `/usr/bin/vim`, see https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.editor or alternatively set the `EDITOR` environment variable system-wide.
