### ISSUE TITLE
error when executing undefined symbol: glfwSetWindowIcon

### ISSUE THREAD

**Issue by LaBatata101** [kovidgoyal/kitty#191]
After the commit [8961eaa](https://github.com/kovidgoyal/kitty/commit/8961eaaa9dc35c6654ff1651c4729253e3d2c628) I still get compile errors, so I tried to fix myself.
Now I get this when I execute:
```bash
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/la-batata101/kitty/linux-package/bin/../lib/kitty/__main__.py", line 14, in <module>
    from kitty.main import main
  File "/home/la-batata101/kitty/linux-package/bin/../lib/kitty/kitty/main.py", line 13, in <module>
    from .boss import Boss
  File "/home/la-batata101/kitty/linux-package/bin/../lib/kitty/kitty/boss.py", line 8, in <module>
    from .config import MINIMUM_FONT_SIZE
  File "/home/la-batata101/kitty/linux-package/bin/../lib/kitty/kitty/config.py", line 14, in <module>
    from . import fast_data_types as defines
ImportError: /home/la-batata101/kitty/linux-package/bin/../lib/kitty/kitty/fast_data_types.so: undefined symbol: glfwSetWindowIcon
```

**Comment by kovidgoyal** [comment]
That indicates glfw on your system is missing the glfwSetWindowIcon function. Either switch to the win branch in which kitty includes its own copy of glfw or update the glfw on your system.
