### ISSUE TITLE
ZeroDivisionError in xmonad

### ISSUE THREAD

**Issue by saraedum** [kovidgoyal/kitty#1910]
When creating a new window in xmonad, it seems  to have zero size sometimes initially. This leads to the following:

```
~ ❯ kitty --version
kitty 0.14.3 created by Kovid Goyal
~ ❯ kitty
[229 13:50:47.005400] Invalid geometry ignored: framebuffer: 46x1062 window: 46x1062

[229 13:50:47.016240] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 314, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 307, in _main
    run_app(opts, args, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 149, in run_app
    _run_app(opts, args, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 134, in _run_app
    boss = Boss(window_id, opts, args, cached_values, new_os_window_trigger)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 138, in __init__
    self.add_os_window(startup_session, os_window_id=os_window_id)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 158, in add_os_window
    tm = TabManager(os_window_id, self.opts, self.args, startup_session)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 397, in __init__
    self._add_tab(Tab(self, session_tab=t))
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 72, in __init__
    self.startup(session_tab)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 82, in startup
    self.new_special_window(cmd)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 249, in new_special_window
    return self.new_window(False, *special_window, location=location)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 244, in new_window
    self.active_window_idx = self.current_layout.add_window(self.windows, window, self.active_window_idx, location)
  File "/usr/bin/../lib/kitty/kitty/layout.py", line 294, in add_window
    self(all_windows, active_window_idx)
  File "/usr/bin/../lib/kitty/kitty/layout.py", line 369, in __call__
    self.do_layout(windows, active_window_idx)
  File "/usr/bin/../lib/kitty/kitty/layout.py", line 550, in do_layout
    return self.layout_single_window(windows[0])
  File "/usr/bin/../lib/kitty/kitty/layout.py", line 377, in layout_single_window
    w.set_geometry(0, wg)
  File "/usr/bin/../lib/kitty/kitty/window.py", line 235, in set_geometry
    sg = self.update_position(new_geometry)
  File "/usr/bin/../lib/kitty/kitty/window.py", line 223, in update_position
    self.screen_geometry = sg = calculate_gl_geometry(window_geometry, vw, vh, cw, ch)
  File "/usr/bin/../lib/kitty/kitty/window.py", line 51, in calculate_gl_geometry
    dx, dy = 2 * cell_width / viewport_width, 2 * cell_height / viewport_height
ZeroDivisionError: division by zero
```

Could we just do something like `viewport_width = viewport_width or 1` in the line before?

**Comment by saraedum** [comment]
(This is with the default configuration.)

**Comment by saraedum** [comment]
Adding
```
    viewport_width = viewport_width or 1
    viewport_height = viewport_height or 1
```
does not really fix it. The exception is gone but I get a window containing only the blinking cursor filling the entire window.

**Comment by saraedum** [comment]
This fixes it. Why was this code block necessary?

```
diff --git a/kitty/glfw.c b/kitty/glfw.c
index 6874575c..5c58d3df 100644
--- a/kitty/glfw.c
+++ b/kitty/glfw.c
@@ -44,10 +44,6 @@ update_os_window_viewport(OSWindow *window, bool notify_boss) {
     if (fw == window->viewport_width && fh == window->viewport_height && w == window->window_width && h == window->window_height) {
         return; // no change, ignore
     }
-    if (fw / w > 5 || fh / h > 5 || fw < min_width || fh < min_height || fw < w || fh < h) {
-        log_error("Invalid geometry ignored: framebuffer: %dx%d window: %dx%d\n", fw, fh, w, h);
-        return;
-    }
     window->viewport_width = fw; window->viewport_height = fh;
     double xr = window->viewport_x_ratio, yr = window->viewport_y_ratio;
     window->viewport_x_ratio = w > 0 ? (double)window->viewport_width / (double)w : xr;
```
