### ISSUE TITLE
Calling kitty from emacs results in "OSError: [Errno 6] Device not configured"

### ISSUE THREAD

**Issue by datafux** [kovidgoyal/kitty#2025]
I try to open a new terminal window with "kitty @ new-window" from within emacs with the elisp function "call-process". kitty gives me the following error like in #1462

```
Traceback (most recent call last):
  File "Python/runpy.py", line 280, in run_path
  File "Python/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 117, in <module>
  File "kitty/__main__.py", line 113, in main
  File "kitty/__main__.py", line 22, in remote_control
  File "kitty/remote_control.py", line 175, in main
  File "kitty/remote_control.py", line 119, in do_io
  File "kitty/utils.py", line 371, in __enter__
OSError: [Errno 6] Device not configured
```
The same error occurs with "shell-command" function. 

MacOS 10.14.5
emacs 26.3
kitty 14.6

**Comment by kovidgoyal** [comment]
kitty needs a proper terminal device, presumably emacs is not giving it
one.

**Comment by Luflosi** [comment]
Would it be possible to detect this sort of thing and give a more helpful error message?

**Comment by Luflosi** [comment]
f9e4e71285899b5f8fd06f2e08c4f91b78e8f581 👍.
