### ISSUE TITLE
ValueError: Failed to get primary monitor size

### ISSUE THREAD

**Issue by boojum** [kovidgoyal/kitty#204]
Latest `kitty` via AUR [kitty-git](https://aur.archlinux.org/packages/kitty-git/) package. I'm getting the following error when trying to start it:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 15, in <module>
    main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 297, in main
    run_app(opts, args)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 207, in run_app
    boss = Boss(window, opts, args)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 79, in __init__
    self.tab_manager.init(startup_session)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 323, in init
    self._add_tab(Tab(self.opts, self.args, self.title_changed, t))
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 45, in __init__
    borders = Borders(opts)
  File "/usr/bin/../lib/kitty/kitty/borders.py", line 38, in __init__
    self.border_width = pt_to_px(opts.window_border_width)
  File "/usr/bin/../lib/kitty/kitty/utils.py", line 55, in pt_to_px
    dpix, dpiy = get_dpi()['logical']
  File "/usr/bin/../lib/kitty/kitty/utils.py", line 134, in get_dpi
    pdpi = glfw_get_physical_dpi()
ValueError: Failed to get primary monitor size
```
Same error with "regular" [kitty](https://aur.archlinux.org/packages/kitty/) from AUR. Am I missing some dependecies, is it a `kitty` bug or perhaps problem with `glfw-x11`? As for that last one, both packages depend on `3.2.1` version of it.

**Comment by kovidgoyal** [comment]
That error occurs when glfw returns zero as the width or height of your primary monitor. I'm not familiar enought oglfw to tell you what conditions that might happen under. Offhand I'd suspect a broken/missing XRANDR extension or similar.
