### ISSUE TITLE
A new kitty launched with the same listen-on address breaks remote control for already running kitty

### ISSUE THREAD

**Issue by strogonoff** [kovidgoyal/kitty#2085]
I believe if multiple kitty instances are launched with the same `listen-on` address, the newer instance kicks the older one from it forever.

Steps: Launch two Kitty instances with the same `--listen-on` argument. Remote control commands (e.g., `kitty @ set-colors`) will only apply to the newer instance. Quit the newer instance. Remote control will fail with traceback as below, and the older instance won’t ever be remote controllable again.

Expected: The original instance hangs on to its listening address. New instance fails to launch if it can’t listen to the same `listen-on` address without disrupting the already running instance. (Ideally multiple instances could listen to the same address, and be simultaneously remote controllable.)

I’m not sure if the expected behavior is technically possible. I hope it is, it’s not fun to recreate the whole work session after accidentally launching another kitty and ruining shortcuts for the primary instance.

```console
me@me $ kitty @ set-colors -a ~/.config/kitty/DimmedMonokai.conf
Traceback (most recent call last):
  File "Python/runpy.py", line 280, in run_path
  File "Python/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 117, in <module>
  File "kitty/__main__.py", line 113, in main
  File "kitty/__main__.py", line 22, in remote_control
  File "kitty/remote_control.py", line 175, in main
  File "kitty/remote_control.py", line 119, in do_io
  File "kitty/remote_control.py", line 67, in __enter__
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by kovidgoyal** [comment]
It depends on socket type, IIRC. For example

```
kitty --listen-on=unix:@test -o allow_remote_control=y
sleep 2s; kitty --listen-on=unix:@test -o allow_remote_control=y
```

and the second one will fail with:

```
  File "/home/kovid/work/kitty/kitty/launcher/../../kitty/main.py", line 338, in main
    _main()
  File "/home/kovid/work/kitty/kitty/launcher/../../kitty/main.py", line 331, in _main
    run_app(opts, args, bad_lines)
  File "/home/kovid/work/kitty/kitty/launcher/../../kitty/main.py", line 149, in run_app
    _run_app(opts, args, bad_lines)
  File "/home/kovid/work/kitty/kitty/launcher/../../kitty/main.py", line 134, in _run_app
    boss = Boss(window_id, opts, args, cached_values, new_os_window_trigger)
  File "/home/kovid/work/kitty/kitty/launcher/../../kitty/boss.py", line 125, in __init__
    listen_fd = listen_on(args.listen_on)
  File "/home/kovid/work/kitty/kitty/launcher/../../kitty/boss.py", line 49, in listen_on
    s.bind(address)
OSError: [Errno 98] Address already in use
```


In any case the fix for your issue is to simply change the kitty command
line to add --single-instance. Or run from master and use the new
shortcut for setting colors facility.

**Comment by strogonoff** [comment]
Thank you for both pointers, I definitely should change my approach and use the single instance switch.

Hopefully this issue will help if someone else runs into it
