### ISSUE TITLE
When setting 'enabled_layouts' to anything (stack,tall or one of them) but '*' kitty fails to start

### ISSUE THREAD

**Issue by gavocanov** [kovidgoyal/kitty#211]
Hi !

I do not like the default tall layout so I tried to put 
`enabled_layouts  stack` in my kitty.conf, but when I change this setting to anything but * kitty won't start.

The error is:
```
Traceback (most recent call last):
  File "Python/runpy.py", line 280, in run_path
  File "Python/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 15, in <module>
  File "kitty/main.py", line 295, in main
  File "kitty/main.py", line 205, in run_app
  File "kitty/boss.py", line 79, in __init__
  File "kitty/tabs.py", line 323, in init
  File "kitty/tabs.py", line 43, in __init__
TypeError: 'NoneType' object is not iterable
```

**Comment by gavocanov** [comment]
thnx for the fast fix!!
is there any way I could build kitty as an osx app myself?
tried with `python3 setup.py osx-bundle` but the resulting bundle is not working, is there something else I should do?

**Comment by kovidgoyal** [comment]
Building bundles is not that easy :) I use the kitty branch of https://github.com/kovidgoyal/build-calibre to create the dmg. Easiest for you would be to simply replace the affected python file inside the existing bundle.

**Comment by gavocanov** [comment]
yeah, that works, thx!
