### ISSUE TITLE
Failed to set locale with LANG

### ISSUE THREAD

**Issue by gbvanrenswoude** [kovidgoyal/kitty#2129]
Running into this issue when lauching kitty:
```
./kitty
Failed to set locale with LANG: en_NL.UTF-8
```
Setting LANG to en_US solves showing that error but kitty does not respond and hangs after. In Console the problematic line is:
```
Failed to set locale with LANG: en_NL.UTF-8
```

**Comment by kovidgoyal** [comment]
On Tue, Nov 12, 2019 at 05:52:43AM -0800, Gijsbert van Renswoude wrote:
> Running into this issue when lauching kitty:
> ```
> ./kitty
> Failed to set locale with LANG: en_NL.UTF-8
> ```

That's not an actual error. kitty will ignore LANG in such a case and
simply use the C locale.

> Setting LANG to en_US solves showing that error but kitty does not respond and hangs after. In Console the problematic line is:

Where are you setting LANG? And what does hang mean? Does it not respond
to key prsees, mouse input? What shell are you running. What operating
system? What kitty version? Post the output of kitty --debug-config

**Comment by gbvanrenswoude** [comment]
Hey, 

```
./kitty --debug-config
kitty 0.14.6 created by Kovid Goyal
Darwin thule-MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.14.6 BuildVersion:	18G1012

Config options different from defaults:
```

**Comment by gbvanrenswoude** [comment]
Console:
```
default	16:21:48.149735 +0100	loginwindow	-[PersistentAppsSupport applicationReady:] | App: kitty, ready, updating active tracking timer
default	16:21:48.149779 +0100	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : kitty
default	16:21:48.225908 +0100	kitty	Failed to set locale with LANG: en_NL.UTF-8
default	16:21:48.254621 +0100	launchservicesd	CHECKIN:0x0-0x4b04b 1697 net.kovidgoyal.kitty
default	16:21:48.255451 +0100	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : kitty
default	16:21:48.280287 +0100	kitty	Current system appearance, (HLTB: 1), (SLS: 0)
default	16:21:48.282994 +0100	kitty	Post-registration system appearance: (HLTB: 1)
default	16:21:48.288242 +0100	distnoted	register name: com.apple.xctest.FakeForceTouchDevice object: net.kovidgoyal.kitty token: f4263 pid: 1697
default	16:21:53.153851 +0100	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : kitty
default	16:21:53.153868 +0100	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: kitty
default	16:21:53.153894 +0100	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Adding to relaunchArray: kitty
default	16:21:53.161112 +0100	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Contents:(
        {
        BackgroundState = 2;
        BundleID = "com.apple.console";
        Hide = 0;
        Path = "/Applications/Utilities/Console.app";
    },
        {
        BackgroundState = 0;
        BundleID = "net.kovidgoyal.kitty";
        Hide = 0;
        Path = "/Applications/kitty.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.google.chrome";
        Hide = 0;
        Path = "/Applications/Google Chrome.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.googlecode.iterm2";
        Hide = 0;
        Path = "/Applications/iTerm.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.github.atom";
        Hide = 0;
        Path = "/Applications/Atom.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.tinyspeck.slackmacgap";
        Hide = 0;
        Path = "/Applications/Slack.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    },
        {
        BackgroundState = 0;
        BundleID = "com.apple.terminal";
        Hide = 0;
        Path = "/Applications/Utilities/Terminal.app";
    }
)
default	16:21:58.287812 +0100	kitty	LSExceptions shared instance invalidated for timeout.
```

**Comment by kovidgoyal** [comment]
Where are you setting LANG? And what does hang mean? Does it not respond
to key presses, mouse input? Does pressing ⌘+n pen a new window? What shell are you running.

**Comment by gbvanrenswoude** [comment]
Thanks for the quick reply! I set lang in my .bashrc file. There are no terminal windows to show/popping up after running Kitty from the GUI. Kitty shows as not responding and does not relaxt to any keys or clicks. xterm-kitty.

**Comment by mighty9245** [comment]
tried to reproduce this issue... is this expected behaviour? no new windows were spawned
```
cockbox:~$ LANG=en_NL.UTF-8 kitty
[317 00:42:35.410545] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 338, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 278, in _main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

also, @gbvanrenswoude, are you sure that your locale is overall valid? i can't find it in the `locale.gen` file on my linux system:
```
cockbox:~$ cat /etc/locale.gen | grep NL
#fy_NL UTF-8  
#li_NL UTF-8  
#nds_NL UTF-8  
#nl_NL.UTF-8 UTF-8  
#nl_NL ISO-8859-1  
#nl_NL@euro ISO-8859-15  
```

**Comment by kovidgoyal** [comment]
@mighty9245 Onlinux it is since on linux there is no problem with unsupported locales unles you deliberately set one like you did just now. On macOS the exception is ignored and kitty will start anywya using the C locale.

**Comment by kovidgoyal** [comment]
And I tried running

LANG=en_NL.UTF-8 kitty

on my macOs machine and as expected it ignored that error and worked. So I doubt this issue has anything to do with locales. Try running cat as your shell in kitty.conf and see if it still freezes.

**Comment by gbvanrenswoude** [comment]
I will close this issue and create a new one, since this seems more related to a hang in the application that is unrelated to the LANG error, since that will be ignored.
