### ISSUE TITLE
Python error with python 3.8

### ISSUE THREAD

**Issue by bthiebault** [kovidgoyal/kitty#2163]
Since I updated to python 3.8, my .xsession-errors file contains the following errors:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 117, in <module>
    main()
  File "/usr/bin/../lib/kitty/__main__.py", line 113, in main
    func(sys.argv[1:])
  File "/usr/bin/../lib/kitty/__main__.py", line 22, in remote_control
    main(args)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 175, in main
    response = do_io(global_opts.to, send, no_response)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 119, in do_io
    with io:
  File "/usr/bin/../lib/kitty/kitty/utils.py", line 371, in __enter__
    self.tty_fd, self.original_termios = open_tty(True)
OSError: [Errno 6] No such device or address
```
Kitty seems to be working however.

I'm using kitty 0.14.6-2 on Arch Linux

**Comment by kovidgoyal** [comment]
That error indicates you are running kitty @ in a context with no
controlling terminal, dont do that.

**Comment by Luflosi** [comment]
Could we provide a more helpful error message?

**Comment by kovidgoyal** [comment]
This should technically never happen, since a controlling tty should be
present for all processes, so I dont think it is worth special casing an
error message for.
