### ISSUE TITLE
kitty (latest git commit #2045055a) fails to start with 'Failed to compile GLSL shader!'

### ISSUE THREAD

**Issue by wimstefan** [kovidgoyal/kitty#2277]
That's the complete error message:
```
[012 15:11:08.747440] Failed to compile GLSL shader!
0(204) : error C1101: ambiguous overloaded function reference "step(uint, uint)"
    (0) : gp5 superp float step(superp float, superp float)
    (0) : ps gp5 gp4 cp50 fp50 vp50 gp50 cpf fpf vpf gpf lowp float step(lowp float, lowp float)
    (0) : ps gp5 gp4 cp50 fp50 vp50 gp50 cpf fpf vpf gpf mediump float step(mediump float, mediump float)
    (0) : float step(float, float)

[012 15:11:08.757023] Traceback (most recent call last):
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 350, in main
    _main()
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 343, in _main
    run_app(opts, args, bad_lines)
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 145, in run_app
    _run_app(opts, args, bad_lines)
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 129, in _run_app
    args.cls or appname, load_all_shaders)
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 83, in load_all_shaders
    load_shader_programs(semi_transparent)
  File "/usr/bin/../lib64/kitty/kitty/window.py", line 83, in load_shader_programs
    compile_program(p, vv, ff)
ValueError: Failed to compile shader
```

Installed mesa version: 19.3.2

**Comment by wimstefan** [comment]
Fixed indeed :)
Thanks for the lightning fast reaction!!!
