### ISSUE TITLE
'neighboring_window' command does not work after  'nex_layout'  command triggered

### ISSUE THREAD

**Issue by zk4** [kovidgoyal/kitty#2377]
## Issue
'neighboring_window' command does not work after  'nex_layout'  command triggered.
##  Env 
kitty 0.16.0 release
Mac 10.12.6

## My Config
```
map cmd+shift+d next_layout
map cmd+d     new_window_with_cwd
enabled_layouts Horizontal,Vertical,Grid,Tall,Stack,Fat


map ctrl+cmd+h neighboring_window left
map ctrl+cmd+l neighboring_window right
map ctrl+cmd+j neighboring_window down
map ctrl+cmd+k neighboring_window up
```

## How to reproduce the issue 
1. Open kitty 0.16.0 `kitty --listen-on unix:/tmp/mykitty --debug-keyboard`
2. Press  cmd+d twice to create two window
3. ctrl+cmd+h / j /k /l  works fine.
4. Press  cmd+shift+d  to change layout to the above.
![image](https://user-images.githubusercontent.com/996674/74819896-0f6a7680-533c-11ea-80f0-278a40d1b27e.png)
5. Issue happended, ctrl+cmd+h / j /k /l  won't work.

## logs 
```
on_key_input: glfw key: 74 native_code: 0x26 action: PRESS mods: 0xa text: '' state: 0 Traceback (most recent call last):
  File "kitty/boss.py", line 540, in dispatch_special_key
  File "kitty/boss.py", line 612, in dispatch_action
  File "kitty/tabs.py", line 401, in neighboring_window
  File "kitty/layout.py", line 238, in neighbors
  File "kitty/layout.py", line 800, in neighbors_for_window
  File "kitty/layout.py", line 548, in neighbors_for_window
AttributeError: 'Grid' object has no attribute 'num_full_size_windows'
sent key to child
```

and kitty 0.15.1 works fine

**Comment by kovidgoyal** [comment]
Works for me. You forgot to specify what layouts you are using.

**Comment by zk4** [comment]
@kovidgoyal  
layout sequence:
`enabled_layouts Horizontal,Vertical,Grid,Tall,Stack,Fat`

**Comment by zk4** [comment]
in step 5:  
with  `kitty --listen-on unix:/tmp/mykitty --debug-keyboard`
kitty 0.16.0 produce this log 

```
on_key_input: glfw key: 74 native_code: 0x26 action: PRESS mods: 0xa text: '' state: 0 Traceback (most recent call last):
  File "kitty/boss.py", line 540, in dispatch_special_key
  File "kitty/boss.py", line 612, in dispatch_action
  File "kitty/tabs.py", line 401, in neighboring_window
  File "kitty/layout.py", line 238, in neighbors
  File "kitty/layout.py", line 800, in neighbors_for_window
  File "kitty/layout.py", line 548, in neighbors_for_window
AttributeError: 'Grid' object has no attribute 'num_full_size_windows'
sent key to child
```

**Comment by zk4** [comment]
@kovidgoyal  You are just amazing!
