### ISSUE TITLE
Crash on macOS

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#2420]
The first commit with this problem is 308d171dae7712a37a7a73ba97bdec442fac02e1.
The following was compiled from the latest master commit, ac2c21e046bb0622880571360cb6a7fd5eb6ddf2.
```
$ make debug && kitty/launcher/kitty
Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/path/to/kitty/kitty/launcher/kitty.app/Contents/MacOS/../../../../../__main__.py", line 119, in <module>
    main()
  File "/path/to/kitty/kitty/launcher/kitty.app/Contents/MacOS/../../../../../__main__.py", line 112, in main
    from kitty.main import main as kitty_main
  File "/path/to/kitty/kitty/launcher/kitty.app/Contents/MacOS/../../../../../kitty/main.py", line 13, in <module>
    from .boss import Boss
  File "/path/to/kitty/kitty/launcher/kitty.app/Contents/MacOS/../../../../../kitty/boss.py", line 215
    pat: MatchPatternType = re.compile(kp), re.compile(vp)
                                          ^
SyntaxError: invalid syntax
```

```
$ make app
*** Error compiling 'kitty.app/lib/kitty/kittens/unicode_input/main.py'...
  File "main.py", line 303
    q: Tuple[str, Optional[Union[str, Sequence[int]]]] = self.mode, None
                                                                  ^
SyntaxError: invalid syntax

*** Error compiling 'kitty.app/lib/kitty/kitty/boss.py'...
  File "boss.py", line 215
    pat: MatchPatternType = re.compile(kp), re.compile(vp)
                                          ^
SyntaxError: invalid syntax

*** Error compiling 'kitty.app/lib/kitty/kitty/rc/scroll_window.py'...
  File "scroll_window.py", line 38
    amount: Tuple[Union[str, int], Optional[str]] = amt, None
                                                       ^
SyntaxError: invalid syntax

*** Error compiling 'kitty.app/lib/kitty/kittens/unicode_input/main.py'...
  File "main.py", line 303
    q: Tuple[str, Optional[Union[str, Sequence[int]]]] = self.mode, None
                                                                  ^
SyntaxError: invalid syntax

*** Error compiling 'kitty.app/lib/kitty/kitty/boss.py'...
  File "boss.py", line 215
    pat: MatchPatternType = re.compile(kp), re.compile(vp)
                                          ^
SyntaxError: invalid syntax

*** Error compiling 'kitty.app/lib/kitty/kitty/rc/scroll_window.py'...
  File "scroll_window.py", line 38
    amount: Tuple[Union[str, int], Optional[str]] = amt, None
                                                       ^
SyntaxError: invalid syntax

*** Error compiling 'kitty.app/lib/kitty/kittens/unicode_input/main.py'...
  File "main.py", line 303
    q: Tuple[str, Optional[Union[str, Sequence[int]]]] = self.mode, None
                                                                  ^
SyntaxError: invalid syntax

*** Error compiling 'kitty.app/lib/kitty/kitty/boss.py'...
  File "boss.py", line 215
    pat: MatchPatternType = re.compile(kp), re.compile(vp)
                                          ^
SyntaxError: invalid syntax

*** Error compiling 'kitty.app/lib/kitty/kitty/rc/scroll_window.py'...
  File "scroll_window.py", line 38
    amount: Tuple[Union[str, int], Optional[str]] = amt, None
                                                       ^
SyntaxError: invalid syntax

kitty.app successfully built!
```

The `kitty.app successfully built!` at the end is also a bit confusing.

**Comment by kovidgoyal** [comment]
I dont see what's invalid in that syntax. Try () around the expression
after the =

**Comment by Luflosi** [comment]
Putting () in the three places fixes the issue.

**Comment by Luflosi** [comment]
```diff
diff --git a/kittens/unicode_input/main.py b/kittens/unicode_input/main.py
index 6f92adac..7b19f044 100644
--- a/kittens/unicode_input/main.py
+++ b/kittens/unicode_input/main.py
@@ -300,7 +300,7 @@ class UnicodeInput(Handler):
     def update_codepoints(self):
         codepoints = None
         if self.mode is HEX:
-            q: Tuple[str, Optional[Union[str, Sequence[int]]]] = self.mode, None
+            q: Tuple[str, Optional[Union[str, Sequence[int]]]] = (self.mode, None)
             codepoints = self.recent
         elif self.mode is EMOTICONS:
             q = self.mode, None
diff --git a/kitty/boss.py b/kitty/boss.py
index ebd2573b..aa6cf5db 100644
--- a/kitty/boss.py
+++ b/kitty/boss.py
@@ -212,7 +212,7 @@ class Boss:
         if field == 'env':
             kp, vp = exp.partition('=')[::2]
             if vp:
-                pat: MatchPatternType = re.compile(kp), re.compile(vp)
+                pat: MatchPatternType = (re.compile(kp), re.compile(vp))
             else:
                 pat = re.compile(kp), None
         else:
diff --git a/kitty/rc/scroll_window.py b/kitty/rc/scroll_window.py
index 3699a7ce..dc8ed695 100644
--- a/kitty/rc/scroll_window.py
+++ b/kitty/rc/scroll_window.py
@@ -35,7 +35,7 @@ class ScrollWindow(RemoteCommand):
 
     def message_to_kitty(self, global_opts: RCOptions, opts: 'CLIOptions', args: ArgsType) -> PayloadType:
         amt = args[0]
-        amount: Tuple[Union[str, int], Optional[str]] = amt, None
+        amount: Tuple[Union[str, int], Optional[str]] = (amt, None)
         if amt not in ('start', 'end'):
             pages = 'p' in amt
             amt = amt.replace('p', '')
```
to be more specific.
