### ISSUE TITLE
kitty (latest git commit) fails to compile with "ImportError: cannot import name 'Pattern'"

### ISSUE THREAD

**Issue by wimstefan** [kovidgoyal/kitty#2428]
System: Gentoo ~AMD64
And here is the complete output of the sphinx error log:
```python
  # Sphinx version: 2.4.4
  # Python version: 3.6.10 (CPython)
  # Docutils version: 0.16 release
  # Jinja2 version: 2.11.1
  # Last messages:

  # Loaded extensions:
  Traceback (most recent call last):
    File "/usr/lib64/python3.6/site-packages/sphinx/cmd/build.py", line 275, in build_main
      args.tags, args.verbosity, args.jobs, args.keep_going)
    File "/usr/lib64/python3.6/site-packages/sphinx/application.py", line 259, in __init__
      self.config.setup(self)
    File "/usr/local/src/Tools/kitty.git/docs/conf.py", line 603, in setup
      write_cli_docs(kn)
    File "/usr/local/src/Tools/kitty.git/docs/conf.py", line 253, in write_cli_docs
      from kitty.launch import options_spec as launch_options_spec
    File "/usr/local/src/Tools/kitty.git/kitty/launch.py", line 14, in <module>
      from .window import Window
    File "/usr/local/src/Tools/kitty.git/kitty/window.py", line 12, in <module>
      from re import Pattern
  ImportError: cannot import name 'Pattern'
```
The same happen with Python 3.8.2 ...
Please let me know if you need more information!

**Comment by wimstefan** [comment]
Thanks for the lightning fast reaction! Unfortunately there's a new problem now:
```python
 # Sphinx version: 2.4.4
  # Python version: 3.6.10 (CPython)
  # Docutils version: 0.16 release
  # Jinja2 version: 2.11.1
  # Last messages:

  # Loaded extensions:
  Traceback (most recent call last):
    File "/usr/local/src/Tools/kitty.git/kitty/rc/base.py", line 179, in all_command_names
      from importlib.resources import contents
  ModuleNotFoundError: No module named 'importlib.resources'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/lib64/python3.6/site-packages/sphinx/cmd/build.py", line 275, in build_main
      args.tags, args.verbosity, args.jobs, args.keep_going)
    File "/usr/lib64/python3.6/site-packages/sphinx/application.py", line 259, in __init__
      self.config.setup(self)
    File "/usr/local/src/Tools/kitty.git/docs/conf.py", line 603, in setup
      write_cli_docs(kn)
    File "/usr/local/src/Tools/kitty.git/docs/conf.py", line 277, in write_cli_docs
      for cmd_name in all_command_names():
    File "/usr/local/src/Tools/kitty.git/kitty/rc/base.py", line 181, in all_command_names
      from importlib_resources import contents  # type:ignore
  ModuleNotFoundError: No module named 'importlib_resources'
```

**Comment by kovidgoyal** [comment]
If you are going to use python 3.6 then you need to install the
importlib_resources package.

**Comment by wimstefan** [comment]
That fault was with 3.8.2 ...
Installing the importlib_resources packages (which pulled in  a couple of other packages as well) did resolve the problem though 🏽

**Comment by kovidgoyal** [comment]
According to the traceback the import error was in python 3.6. In fact both of the errors you reported happen only in python 3.6

**Comment by wimstefan** [comment]
As you wish ...
Thanks for the fast & immediate support!
