### ISSUE TITLE
kitty (latest git) crash on evoking hints

### ISSUE THREAD

**Issue by wimstefan** [kovidgoyal/kitty#2434]
This is the error message when I invoke hints with `ctrl-shift-e`:
```python
Traceback (most recent call last):
  File "/usr/bin/../lib64/kitty/kittens/hints/main.py", line 380, in run
    pattern, post_processors = functions_for(args)
  File "/usr/bin/../lib64/kitty/kittens/hints/main.py", line 305, in functions_for
    url_prefixes = kitty_common_opts()['url_prefixes']
  File "/usr/bin/../lib64/kitty/kittens/hints/main.py", line 39, in kitty_common_opts
    return cast(KittyCommonOpts, json.loads(v))
NameError: name 'KittyCommonOpts' is not defined
Press Enter to quit.
```
The output of `kitty --debug-config`:
```python
kitty 0.16.0 (dfb543bd94) created by Kovid Goyal
Linux swimmer 5.5.8-gentoo #1 SMP Mon Mar 9 14:59:11 CET 2020 x86_64
This is \n.\O (\s \m \r) \t
Loaded config files: /home/swimmer/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
active_border_color   Color(red=43, green=189, blue=114)
allow_remote_control  y
background            Color(red=239, green=241, blue=244)
bell_border_color     Color(red=229, green=115, blue=115)
bold_font             Iosevka Artesanal Bold
bold_italic_font      Iosevka Artesanal Bold Italic
color0                Color(red=25, green=28, blue=34)
color1                Color(red=174, green=21, blue=40)
color10               Color(red=0, green=154, blue=90)
color11               Color(red=255, green=140, blue=0)
color12               Color(red=0, green=75, blue=180)
color13               Color(red=179, green=0, blue=164)
color14               Color(red=0, green=164, blue=179)
color15               Color(red=159, green=159, blue=159)
color2                Color(red=0, green=154, blue=90)
color3                Color(red=255, green=140, blue=0)
color4                Color(red=0, green=75, blue=180)
color5                Color(red=179, green=0, blue=164)
color6                Color(red=0, green=164, blue=179)
color7                Color(red=184, green=184, blue=184)
color8                Color(red=119, green=131, blue=155)
color9                Color(red=174, green=21, blue=40)
cursor                Color(red=46, green=52, blue=64)
cursor_text_color     None
enable_audio_bell     False
font_family           Iosevka Artesanal
font_size             11.4
foreground            Color(red=46, green=52, blue=64)
italic_font           Iosevka Artesanal Italic
selection_background  Color(red=205, green=210, blue=219)
selection_foreground  None
strip_trailing_spaces smart
url_color             Color(red=129, green=161, blue=193)
url_style             1
window_padding_width  8.0
Added shortcuts:
         shift+control+z KeyAction(func='kitten', args=['unicode_input'])
Changed shortcuts:
         shift+control+minus KeyAction(func='change_font_size', args=(True, '-', 1.0))
         shift+control+equal KeyAction(func='change_font_size', args=(True, '+', 1.0))
```

**Comment by wimstefan** [comment]
Solved! Many thanks :+1: 
You keep amazing me with your lightning fast response on issues reported :-)

**Comment by kovidgoyal** [comment]
You're welcome :) I like to keep on top of things.
