### ISSUE TITLE
ValueError from pre-render on font resize—cannot convert float NaN to integer

### ISSUE THREAD

**Issue by timtro** [kovidgoyal/kitty#2446]
Thanks in advance. I'm sorry if this is something silly.

I've been running into this bug for a little while now, but unfortunately, I can't pin a specific commit to it. It is, however, still present in the [commit](https://github.com/kovidgoyal/kitty/commit/342f0981d8c75f03ada405dfc933e5ef75ffa118) pushed today. Happens across several systems configured similarly.

When resizing font, I get an exception thrown:
```
Traceback (most recent call last):
  File "…/kitty/kitty/fonts/render.py", line 284, in prerender_function
    cells = f(1), f(2), f(3), f(0, True), f(missing=True), c(1), c(2), c(3)
  File "…/kitty/kitty/fonts/render.py", line 256, in render_cursor
    horz('bottom', cursor_underline_thickness)
  File "…/kitty/kitty/fonts/render.py", line 246, in horz
    height = max(1, min(int(round(height_pt * dpi_y / 72.0)), cell_height))
ValueError: cannot convert float NaN to integer
```
The floating point is blowing up somewhere, so I checked my config for any rendering-related values set to zero (in case this was a div-by-zero), but nothing jumped out at me.

System info:
```
 OS: Ubuntu 19.04 x86_64 
 Kernel: 5.0.0-38-generic 
 Shell: zsh 5.5.1 
 Resolution: 1920x1200, 1920x1200 
 DE: xmonad 
 WM: LG3D 
 CPU: Intel i7-4790K (8) @ 4.400GHz 
 GPU: NVIDIA GeForce GTX 960
```
From my environment:
```
XDG_SESSION_TYPE=x11

xdpyinfo | grep -B 2 resolution
screen #0:
  dimensions:    3840x1200 pixels (1108x350 millimeters)
  resolution:    88x87 dots per inch

Xft.hintstyle:	hintslight
Xft.dpi:	92
Xft.rgba:	rgb
Xft.hinting:	true
Xft.antialias:	true
```

Config:
```
font_family      Hasklig
italic_font      Hasklig-italic
bold_font        Hasklig-bold
bold_italic_font Hasklig-bolditalic
font_size 11
adjust_line_height  0
adjust_column_width 0
disable_ligatures never
box_drawing_scale 0.1, 1, 1.5, 2
cursor #cccccc
cursor_text_color #111111
cursor_shape block
cursor_blink_interval -1
cursor_stop_blinking_after 15
scrollback_lines 2000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
scrollback_pager_history_size 0
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 1.0
mouse_hide_wait 3.0
url_color #0087bd
url_style curly
open_url_modifiers kitty_mod
open_url_with default
copy_on_select yes
strip_trailing_spaces never
rectangle_select_modifiers ctrl+alt
terminal_select_modifiers shift
select_by_word_characters :@-./_~?&=%+#
click_interval -1.0
focus_follows_mouse no
pointer_shape_when_grabbed arrow
repaint_delay 10
input_delay 3
sync_to_monitor yes
enable_audio_bell yes
visual_bell_duration 0.0
window_alert_on_bell yes
bell_on_tab yes
command_on_bell none
remember_window_size  yes
initial_window_width  640
initial_window_height 400
enabled_layouts *
window_resize_step_cells 2
window_resize_step_lines 2
window_border_width 0
draw_minimal_borders yes
window_margin_width 0.0
single_window_margin_width -1000.0
window_padding_width 0.0
placement_strategy center
active_border_color #00ff00
inactive_border_color #cccccc
bell_border_color #ff5a00
inactive_text_alpha 1.0
hide_window_decorations no
resize_debounce_time 0.1
resize_draw_strategy static
tab_bar_edge bottom
tab_bar_margin_width 0.0
tab_bar_style fade
tab_bar_min_tabs 2
tab_switch_strategy previous
tab_fade 0.25 0.5 0.75 1
tab_separator " ┇"
tab_title_template {title}
active_tab_foreground   #eee
active_tab_background   #111
active_tab_font_style   bold
inactive_tab_foreground #666
inactive_tab_background #000
inactive_tab_font_style italic
foreground #dddddd
background #000000
background_opacity 0.78
dynamic_background_opacity yes
dim_opacity 0.75
selection_foreground #000000
selection_background #fffacd
color0 #000000
color8 #767676
color1 #cc0403
color9 #f2201f
color2  #19cb00
color10 #23fd00
color3  #cecb00
color11 #fffd00
color4  #0d73cc
color12 #1a8fff
color5  #cb1ed1
color13 #fd28ff
color6  #0dcdcd
color14 #14ffff
color7  #dddddd
color15 #ffffff
shell .
editor .
close_on_child_death no
allow_remote_control no
update_check_interval 24
startup_session none
clipboard_control write-clipboard write-primary
term xterm-kitty
macos_titlebar_color system
macos_option_as_alt no
macos_hide_from_tasks no
macos_quit_when_last_window_closed no
macos_window_resizable yes
macos_thicken_font 0
macos_traditional_fullscreen no
macos_show_window_title_in all
macos_custom_beam_cursor no
linux_display_server auto
kitty_mod ctrl+shift
clear_all_shortcuts no
map kitty_mod+c copy_to_clipboard
map kitty_mod+v  paste_from_clipboard
map kitty_mod+s  paste_from_selection
map shift+insert paste_from_selection
map kitty_mod+o  pass_selection_to_program
map kitty_mod+up        scroll_line_up
map kitty_mod+k         scroll_line_up
map kitty_mod+down      scroll_line_down
map kitty_mod+j         scroll_line_down
map kitty_mod+page_up   scroll_page_up
map kitty_mod+page_down scroll_page_down
map kitty_mod+home      scroll_home
map kitty_mod+end       scroll_end
map kitty_mod+h         show_scrollback
map kitty_mod+enter new_window
map kitty_mod+n new_os_window
map kitty_mod+w close_window
map kitty_mod+] next_window
map kitty_mod+[ previous_window
map kitty_mod+f move_window_forward
map kitty_mod+b move_window_backward
map kitty_mod+` move_window_to_top
map kitty_mod+r start_resizing_window
map kitty_mod+1 first_window
map kitty_mod+2 second_window
map kitty_mod+3 third_window
map kitty_mod+4 fourth_window
map kitty_mod+5 fifth_window
map kitty_mod+6 sixth_window
map kitty_mod+7 seventh_window
map kitty_mod+8 eighth_window
map kitty_mod+9 ninth_window
map kitty_mod+0 tenth_window
map kitty_mod+right next_tab
map kitty_mod+left  previous_tab
map kitty_mod+t     new_tab_with_cwd
map kitty_mod+q     close_tab
map kitty_mod+.     move_tab_forward
map kitty_mod+,     move_tab_backward
map kitty_mod+alt+t set_tab_title
map kitty_mod+l next_layout
map kitty_mod+equal     change_font_size all +2.0
map kitty_mod+minus     change_font_size all -2.0
map kitty_mod+backspace change_font_size all 0
map kitty_mod+e kitten hints
map kitty_mod+p>f kitten hints --type path --program -
map kitty_mod+p>shift+f kitten hints --type path
map kitty_mod+p>l kitten hints --type line --program -
map kitty_mod+p>w kitten hints --type word --program -
map kitty_mod+p>h kitten hints --type hash --program -
map kitty_mod+f11    toggle_fullscreen
map kitty_mod+f10    toggle_maximized
map kitty_mod+u      kitten unicode_input
map kitty_mod+f2     edit_config_file
map kitty_mod+escape kitty_shell window
map kitty_mod+a>m    set_background_opacity +0.1
map kitty_mod+a>l    set_background_opacity -0.1
map kitty_mod+a>1    set_background_opacity 1
map kitty_mod+a>d    set_background_opacity default
map kitty_mod+delete clear_terminal reset active
```

**Comment by kovidgoyal** [comment]
stick a print in there and see which is NaN dpi_y or height_pt. And does
it happen with --config NONE (if not bisect your config file to find the
setting causing the issue)

**Comment by kovidgoyal** [comment]
I am going to guess it is height_pt and therefore cursor_underline_thickness

**Comment by timtro** [comment]
Thanks, Kovid. If I were thinking, I would have done that to start to save you the time.

Looks like `dpi_y` is the culprit:
```
$:> kitty
horiz(…) called:
  height_pt:  91.99999809265137 
  dpi_y:  -7.810449627990344e-293
horiz(…) called:
  height_pt:  1 
  dpi_y:  -7.810449627990344e-293
horiz(…) called:
  height_pt:  1 
  dpi_y:  -7.810449627990344e-293

# Now I hit <CTRL>-<SHIFT>-<+> to resize

horiz(…) called:
  height_pt:  91.99999809265137 
  dpi_y:  nan
Traceback (most recent call last):
  File "…/kitty/kitty/fonts/render.py", line 285, in prerender_function
    cells = f(1), f(2), f(3), f(0, True), f(missing=True), c(1), c(2), c(3)
  File "…/kitty/kitty/fonts/render.py", line 257, in render_cursor
    horz('bottom', cursor_underline_thickness)
  File "…/kitty/kitty/fonts/render.py", line 247, in horz
    height = max(1, min(int(round(height_pt * dpi_y / 72.0)), cell_height))
ValueError: cannot convert float NaN to integer
[078 13:24:54.971510] Failed to pre-render cells
```

Works fine with `--config NONE`.

I dug around a bit in `kitty/fonts.c` and got the impression that `dpi_y` may be related to the font. Sure enough, I changed the font to "Ubuntu Mono" and everything is fine. I still get whacky values for `dpi_y` bring printed, but everything renders fine with no exceptions/NaNs.

But digging deeper in `kitty/glfw.c`, I see `ydpi` coming from the OS window. So I don't know why changing the font worked. I don't pretend to understand anything about the internals, I'm just a speedreading tourist. I'm curious about any insights you can provide.

**Comment by kovidgoyal** [comment]
dpi definitely comes from the OS, on X11 it will come from either Xft.dpi if you have that set or failing that from the dpi values reported from EDID. Check in get_window_content_scale()
