### ISSUE TITLE
WARNING: Unable to retrieve infocmp for type xterm-kitty

### ISSUE THREAD

**Issue by bhougland18** [kovidgoyal/kitty#2459]
I received the following error when I tried to launch a Clojure repl from the terminal.  I issued this command:

  clojure -Sdeps "{:deps {viebel/klipse-repl {:mvn/version \"0.2.3\"}}}" -m klipse-repl.main --port 5556

I received the following "logging" informaiton while the repl loaded.  It did finally load, but this does not happen on gnome-terminal.  Here is the ouput the repl printed before it loaded:

 launching socket repl on port 5556
Mar 22, 2020 3:53:45 PM org.jline.utils.Log logr
WARNING: Unable to retrieve infocmp for type xterm-kitty
java.io.IOException: Cannot run program "infocmp": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at org.jline.utils.InfoCmp.getInfoCmp(InfoCmp.java:548)
	at org.jline.terminal.impl.AbstractTerminal.parseInfoCmp(AbstractTerminal.java:168)
	at org.jline.terminal.impl.PosixSysTerminal.<init>(PosixSysTerminal.java:43)
	at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:325)
	at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:219)
	at rebel_readline.jline_api$create_terminal.invokeStatic(jline_api.clj:62)
	at rebel_readline.jline_api$create_terminal.doInvoke(jline_api.clj:59)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at klipse_repl.repl$create_repl.invokeStatic(repl.clj:33)
	at klipse_repl.repl$create_repl.invoke(repl.clj:29)
	at klipse_repl.main$_main.invokeStatic(main.clj:58)
	at klipse_repl.main$_main.doInvoke(main.clj:54)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:514)
	at clojure.main$main_opt.invoke(main.clj:510)
	at clojure.main$main.invokeStatic(main.clj:664)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 23 more

**Comment by mighty9245** [comment]
looks like you are missing infocmp? can you launch `infocmp` in your terminal?

**Comment by kovidgoyal** [comment]
As far as I can see your system is missing infocmp or it is not in the PATH. Nothing kitty can do about it.

**Comment by bhougland18** [comment]
Yes, sorry there is a bug in the ncurses Nixos package.
