### ISSUE TITLE
build fail with 0.17.0

### ISSUE THREAD

**Issue by jubalh** [kovidgoyal/kitty#2463]
I think the problem is on my end but I don't see right now what it is.
Maybe you can help me.

When running `python3 setup.py --verbose linux-package --prefix %{buildroot}%{_prefix}` I get:

```
[   22s] gcc -Wextra -Wno-missing-field-initializers -Wall -Wstrict-prototypes -std=c11 -O3 -fwrapv -fstack-protector-strong -Wno-missing-braces -pipe -fvisibility=hidden -D_FORTIFY_SOURCE=2 -fPIC -flto -Ikitty -I/usr/include/python3.8 -Wall -O3 -shared -flto build/subseq_matcher-charsets.c.o build/subseq_matcher-main.c.o build/subseq_matcher-output.c.o build/subseq_matcher-score.c.o build/subseq_matcher-unix_compat.c.o -lcrypt -lpthread -ldl -lutil -lm -lm -L/usr/lib64 -lpython3.8 -Xlinker -export-dynamic -o build/kittens/choose/subseq_matcher.so          
[   22s] Traceback (most recent call last):
[   22s]   File "setup.py", line 1114, in <module>                                           
[   22s]     main()
[   22s]   File "setup.py", line 1097, in main
[   22s]     package(args, bundle_type='linux-package')                                      
[   22s]   File "setup.py", line 930, in package                                             
[   22s]     build_terminfo['compile_terminfo'](odir)                                        
[   22s]   File "build-terminfo", line 16, in compile_terminfo                               
[   22s]     proc = subprocess.run(['tic', '-x', '-o' + tdir, 'terminfo/kitty.terminfo'], check=True, stderr=subprocess.PIPE)
[   22s]   File "/usr/lib64/python3.8/subprocess.py", line 512, in run                       
[   22s]     raise CalledProcessError(retcode, process.args,                                 
[   22s] subprocess.CalledProcessError: Command '['tic', '-x', '-o/tmp/tmpfwzn5hbf', 'terminfo/kitty.terminfo']' returned non-zero exit status 1.    
```

tic is installed. This is run in OBS buildroot.

**Comment by kovidgoyal** [comment]
That indicates tic is failing on your system. Is it up-to-date? Can you
run it manually?

**Comment by jubalh** [comment]
On my system tic comes from ncurses-devel-6.2-3.
The path to kitty.terminfo is a relative path right? Because it is run in a buildroot I thought maybe I need to adapt the path if it's absolute.

**Comment by kovidgoyal** [comment]
You can see the command line in the stack trace above, it is

tic -x -o/tmp/tmpWhatever terminfo/kitty.terminfo

**Comment by jubalh** [comment]
I ran it manually:

```
tic -x -o/tmp/tmpWhatever terminfo/kitty.terminfo
tic: /lib64/libtinfo.so.6: version `NCURSES6_TINFO_6.2.20200212' not found (required by tic)
```

But ncurses-devel-6.2-3 is installed

**Comment by kovidgoyal** [comment]
That's a broken tic/ncurses installation, their versions are mismatched, nothing to do with kitty.
