### ISSUE TITLE
Got an error after installing kitty (cannot convert float NaN to integer)

### ISSUE THREAD

**Issue by wijhuang** [kovidgoyal/kitty#2467]
After manual install, I cannot run the kitty v0.17.0 the problem was
```
Traceback (most recent call last):
  File "kitty/render.py", line 284, in prerender_function
  File "kitty/render.py", line 256, in render_cursor
  File "kitty/render.py", line 246, in horz
ValueError: cannot convert float NaN to integer
[084 18:12:09.675422] Failed to pre-render cells
```

**Comment by kovidgoyal** [comment]
This is most likely already fixed in master by https://github.com/kovidgoyal/kitty/commit/5227b1f98b5353a1a0f4e58ae19335ffa89257e3
