### ISSUE TITLE
Segfault in libpython3

### ISSUE THREAD

**Issue by LouisTakePILLz** [kovidgoyal/kitty#2506]
Kitty (v0.17.1) suddenly closed a couple days ago. I don't exactly remember what I was doing when it crashed.

journalctl:
```
Mar 31 15:02:07 peelz-pc kernel: .kitty-wrapped[4658]: segfault at 8 ip 00007f88b138b083 sp 00007ffeea820460 error 4 in libpython3.7m.so.1.0[7f88b12d0000+1b1000]
Mar 31 15:02:07 peelz-pc kernel: Code: 49 89 ff 48 85 f6 74 0e 85 c9 74 0a 32 46 20 31 c9 a8 1c 0f 94 c1 49 83 c4 01 4c 39 e2 0f 8e 9c 01 00 00 4a 8b 04 e3 4c 89 ce <48> 8b 40 08 4e 8b 0c e3 f6 80 ab 00 00 00 10 0f 84 a8 00 00 00 41
Mar 31 15:02:07 peelz-pc systemd[1]: Started Process Core Dump (PID 9290/UID 0).
Mar 31 15:02:08 peelz-pc systemd-coredump[9291]: Process 4658 (.kitty-wrapped) of user 1000 dumped core.
Mar 31 15:02:08 peelz-pc systemd[1]: systemd-coredump@1-9290-0.service: Succeeded.
Mar 31 15:02:08 peelz-pc systemd[1]: systemd-coredump@1-9290-0.service: Consumed 1.186s CPU time, no IP traffic.
```

I recompiled 0.17.1 with debugging symbols and loaded the coredump in gdb to get the call stack:
```
#0  0x00007f88b138b083 in _PyUnicode_JoinArray () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#1  0x00007f88b138b4b2 in PyUnicode_Join () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#2  0x00007f88b1303364 in _PyMethodDef_RawFastCallKeywords () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#3  0x00007f88b130bf0a in _PyMethodDescr_FastCallKeywords () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#4  0x00007f88b12d7b49 in call_function () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#5  0x00007f88b12d9838 in _PyEval_EvalFrameDefault () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#6  0x00007f88b12d665b in function_code_fastcall () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#7  0x00007f88b12d78f5 in call_function () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#8  0x00007f88b12d9838 in _PyEval_EvalFrameDefault () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#9  0x00007f88b12d665b in function_code_fastcall () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#10 0x00007f88b1302e1a in _PyFunction_FastCallDict () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#11 0x00007f88b1303fad in _PyObject_Call_Prepend () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#12 0x00007f88b1303c8a in _PyObject_FastCallDict () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#13 0x00007f88b1304226 in _PyObject_CallMethod_SizeT () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#14 0x00007f88a8c20566 in screen_update_selection () from /nix/store/90diiavvswg3p4lbqw75lv18c4kxl03p-kitty-0.17.1/bin/../lib/kitty/kitty/fast_data_types.so
#15 0x00007f88a8c3a67b in mouse_event () from /nix/store/90diiavvswg3p4lbqw75lv18c4kxl03p-kitty-0.17.1/bin/../lib/kitty/kitty/fast_data_types.so
#16 0x00007f88a8c6361e in mouse_button_callback () from /nix/store/90diiavvswg3p4lbqw75lv18c4kxl03p-kitty-0.17.1/bin/../lib/kitty/kitty/fast_data_types.so
#17 0x00007f88a7d8aa42 in _glfwDispatchX11Events.lto_priv.0 () from /nix/store/90diiavvswg3p4lbqw75lv18c4kxl03p-kitty-0.17.1/lib/kitty/kitty/glfw-x11.so
#18 0x00007f88a7d93b63 in glfwRunMainLoop () from /nix/store/90diiavvswg3p4lbqw75lv18c4kxl03p-kitty-0.17.1/lib/kitty/kitty/glfw-x11.so
#19 0x00007f88a8c77768 in main_loop () from /nix/store/90diiavvswg3p4lbqw75lv18c4kxl03p-kitty-0.17.1/bin/../lib/kitty/kitty/fast_data_types.so
#20 0x00007f88b1303182 in _PyMethodDef_RawFastCallKeywords () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#21 0x00007f88b130bf0a in _PyMethodDescr_FastCallKeywords () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#22 0x00007f88b12d7b49 in call_function () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#23 0x00007f88b12d9838 in _PyEval_EvalFrameDefault () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#24 0x00007f88b13d368d in _PyEval_EvalCodeWithName () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#25 0x00007f88b1302eb9 in _PyFunction_FastCallKeywords () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#26 0x00007f88b12d78f5 in call_function () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#27 0x00007f88b12dc5d1 in _PyEval_EvalFrameDefault () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#28 0x00007f88b13d368d in _PyEval_EvalCodeWithName () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#29 0x00007f88b1302d00 in _PyFunction_FastCallDict () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#30 0x00007f88b1303fad in _PyObject_Call_Prepend () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#31 0x00007f88b1361ec6 in slot_tp_call () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#32 0x00007f88b1303567 in _PyObject_FastCallKeywords () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#33 0x00007f88b12d78a3 in call_function () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#34 0x00007f88b12dc5d1 in _PyEval_EvalFrameDefault () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#35 0x00007f88b12d665b in function_code_fastcall () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#36 0x00007f88b12d78f5 in call_function () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#37 0x00007f88b12dc5d1 in _PyEval_EvalFrameDefault () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#38 0x00007f88b12d665b in function_code_fastcall () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#39 0x00007f88b12d78f5 in call_function () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#40 0x00007f88b12dc5d1 in _PyEval_EvalFrameDefault () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#41 0x00007f88b12d665b in function_code_fastcall () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#42 0x00007f88b12d78f5 in call_function () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#43 0x00007f88b12dc5d1 in _PyEval_EvalFrameDefault () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#44 0x00007f88b13d368d in _PyEval_EvalCodeWithName () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#45 0x00007f88b13d390e in PyEval_EvalCodeEx () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#46 0x00007f88b13d393b in PyEval_EvalCode () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#47 0x00007f88b13d0e4d in builtin_exec () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#48 0x00007f88b1303385 in _PyMethodDef_RawFastCallKeywords () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#49 0x00007f88b1303478 in _PyCFunction_FastCallKeywords () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#50 0x00007f88b12d7b30 in call_function () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#51 0x00007f88b12dc5d1 in _PyEval_EvalFrameDefault () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#52 0x00007f88b13d368d in _PyEval_EvalCodeWithName () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#53 0x00007f88b1302eb9 in _PyFunction_FastCallKeywords () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#54 0x00007f88b12d78f5 in call_function () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#55 0x00007f88b12dc5d1 in _PyEval_EvalFrameDefault () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#56 0x00007f88b13d368d in _PyEval_EvalCodeWithName () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#57 0x00007f88b1302d00 in _PyFunction_FastCallDict () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#58 0x00007f88b14219ee in pymain_run_module () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#59 0x00007f88b142785e in pymain_main () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#60 0x00007f88b1427db3 in Py_Main () from /nix/store/xb1mp0f16lv23rwhfdc1665v5r20jfmm-python3-3.7.6/lib/libpython3.7m.so.1.0
#61 0x000000000040132e in main ()
```

**Comment by kovidgoyal** [comment]
That looks like it involves selecting with the mouse, however the
backtrace is not very useful I'm going to need some way to reproduce.

**Comment by LouisTakePILLz** [comment]
I have no idea how it happened. Feel free to close the issue; I'll try to post with more info if it happens again.
