### ISSUE TITLE
Issues when running on freebsd

### ISSUE THREAD

**Issue by epsilon-phase** [kovidgoyal/kitty#2529]
Hi, there are a few issues that exist when running kitty on FreeBSD, for instance, when starting up, you receive this message from bash:

```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```

Also,the following happens when you use emoji selector kitten or use `kitty icat`:

```
Unhandled exception running kitten:
Traceback (most recent call last):
  File "~/.local/bin/../lib/kitty/kittens/runner.py", line 161, in main
    launch(args)
  File "~/.local/bin/../lib/kitty/kittens/runner.py", line 75, in launch
    result = m['start'](args)
  File "~/.local/bin/../lib/kitty/kittens/unicode_input/main.py", line 565, in main
    loop.loop(handler)
  File "~/.local/bin/../lib/kitty/kittens/tui/loop.py", line 391, in loop
    with TermManager() as term_manager, signal_manager:
  File "~/.local/bin/../lib/kitty/kittens/tui/loop.py", line 85, in __enter__
    self.tty_fd, self.original_termios = open_tty()
OSError: Failed to open controlling terminal: /dev/ctty (identified with ctermid()) with error: Device not configured
```

**Comment by kovidgoyal** [comment]
I'm afraid I'm not familiar with BSDs, but patches are most welcome.
Both those issues look to be about controlling terminals, see lines
96-99 in child.c
