### ISSUE TITLE
Fail to start

### ISSUE THREAD

**Issue by notramo** [kovidgoyal/kitty#258]
Installed from AUR `kitty-git` package.
X11
glxinfo output:
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org R300 Project (0x1002)
    Device: ATI RV515 (0x714a)
    Version: 17.3.0
    Accelerated: yes
    Video memory: 64MB
    Unified memory: no
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL vendor string: X.Org R300 Project
OpenGL renderer string: ATI RV515
OpenGL version string: 2.1 Mesa 17.3.0
OpenGL shading language version string: 1.20

OpenGL ES profile version string: OpenGL ES 2.0 Mesa 17.3.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```
Error message:
```
[glfw error 65543]: GLX: Failed to create context: GLXBadFBConfig
Failed to create a window at size: 640x400, using a standard size instead.
[glfw error 65543]: GLX: Failed to create context: GLXBadFBConfig
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 15, in <module>
    main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 149, in main
    run_app(opts, args)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 45, in run_app
    window_id = create_os_window(w, h, appname, args.name or args.cls or appname, args.cls or appname, load_all_shaders)
ValueError: Failed to create GLFWwindow
```

**Comment by kovidgoyal** [comment]
You dont have a good enough video card/drivers to run kitty. kitty needs OpenGL 3.3 (which is about eight years old).

**Comment by notramo** [comment]
Yes, my machine is quite old (2006).
But if the video card is not supported, `kitty` should inform the user about it.
