### ISSUE TITLE
undefined symbol problem in the supplied harfbuzz library

### ISSUE THREAD

**Issue by rwdavis3rd** [kovidgoyal/kitty#2680]
For Kitty binary releases 0.17.4 and 0.17.3 (the prebuilt Linux amd64 binary bundles) run on Ubuntu 16.04 (LTS):

Starting the kitty binary results in an undefined symbol problem in the supplied harfbuzz library: 

```
~$ '/home/10613/kitty.0.17.3/bin/kitty' 
Traceback (most recent call last):
  File "python3.7/runpy.py", line 280, in run_path
  File "python3.7/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 121, in <module>
  File "kitty/__main__.py", line 114, in main
  File "kitty/main.py", line 12, in <module>
  File "kitty/borders.py", line 9, in <module>
	ImportError: /home/10613/kitty.0.17.3/bin/../lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
```
The error report is the same for both versions.

**Comment by Luflosi** [comment]
The freetype library on your system is too old. See #595 and https://github.com/kovidgoyal/kitty/issues/992#issuecomment-526740224.

**Comment by rwdavis3rd** [comment]
Yup, I see... thanks!
