### ISSUE TITLE
kitty --debug-config segfault when remapping mouse scroll events

### ISSUE THREAD

**Issue by coffeemug** [kovidgoyal/kitty#2697]
**Describe the bug**
I wanted to map ctrl+ScrollUp and ctrl+ScrollDown to set_background_opacity +/- 0.1. When I do, the mappings appear to have no effect, and `kitty --debug-config` segfaults on startup.

**To Reproduce**
Add the following to the config file:

```
map CTRL+XF86ScrollDown set_background_opacity +0.1
map CTRL+XF86ScrollUp set_background_opacity -0.1
```

Then run this command:

```
kitty --debug-config
```

**Expected behavior**
Two things should happen instead:

1. `kitty --debug-config` shouldn't crash
2. scrolling the mouse should actually call the command

**Enviroment details**
I'm running on Ubuntu 20.04.

**Comment by kovidgoyal** [comment]
You cannot map scroll events using map, only keys. And I cannot
reproduce your crash 

```
kitty -o 'map CTRL+XF86ScrollDown set_background_opacity +0.1' --debug-config --config NONE                      master 
kitty 0.17.4 (9712be903d) created by Kovid Goyal
Linux getafix 5.6.13-arch1-1 #1 SMP PREEMPT Thu, 14 May 2020 06:52:53 +0000 x86_64
Arch Linux \r (\l)
Running under: X11

Config options different from defaults:
Added shortcuts:
	control+key: -1 native_key: 269025145 KeyAction(func='set_background_opacity', args=['+0.1'])
```

Are you running 0.17.4 and post a backtrace of your crash

echo bt | coredumpctl gdb

**Comment by coffeemug** [comment]
Ah, I'm on 0.15.0 which is what's in aptitude on ubuntu focal. Will post the core dump in a moment, but that might be moot given an old version.

**Comment by coffeemug** [comment]
```
$ echo bt | coredumpctl gdb
           PID: 31396 (kitty)
           UID: 1000 (coffeemug)
           GID: 1000 (coffeemug)
        Signal: 11 (SEGV)
     Timestamp: Tue 2020-05-26 01:03:33 PDT (2s ago)
  Command Line: kitty --debug-config
    Executable: /usr/bin/kitty
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-launched-kitty.desktop-20666.scope
          Unit: user@1000.service
     User Unit: gnome-launched-kitty.desktop-20666.scope
         Slice: user-1000.slice
     Owner UID: 1000 (coffeemug)
       Boot ID: b7674f0d0ce5403a891c1152edf7b75c
    Machine ID: 3b1a5e7d72cf4a1db192887fc2a2c7cf
      Hostname: slava-thinkpad
       Storage: /var/lib/systemd/coredump/core.kitty.1000.b7674f0d0ce5403a891c1152edf7b75c.31396.1590480213000000000000.lz4
       Message: Process 31396 (kitty) of user 1000 dumped core.
                
                Stack trace of thread 31396:
                #0  0x0000000000000000 n/a (n/a + 0x0)

GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/kitty...
(No debugging symbols found in /usr/bin/kitty)
[New LWP 31396]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `kitty --debug-config'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
(gdb) #0  0x0000000000000000 in ?? ()
#1  0x00007f295767b9df in ?? () from /usr/bin/../lib/kitty/kitty/fast_data_types.so
#2  0x00007f295936b227 in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#3  0x00007f295936b697 in _PyObject_MakeTpCall () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#4  0x00007f295913d083 in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#5  0x00007f295914106b in _PyEval_EvalFrameDefault () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#6  0x00007f29591480db in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#7  0x00007f295913cffd in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#8  0x00007f295914106b in _PyEval_EvalFrameDefault () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#9  0x00007f29591480db in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#10 0x00007f295913cffd in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#11 0x00007f295914106b in _PyEval_EvalFrameDefault () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#12 0x00007f295928f88b in _PyEval_EvalCodeWithName () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#13 0x00007f295936acd0 in _PyFunction_Vectorcall () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#14 0x00007f295913cffd in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#15 0x00007f295914106b in _PyEval_EvalFrameDefault () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#16 0x00007f295928f88b in _PyEval_EvalCodeWithName () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#17 0x00007f295936acd0 in _PyFunction_Vectorcall () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#18 0x00007f295913cffd in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#19 0x00007f295914106b in _PyEval_EvalFrameDefault () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#20 0x00007f295928f88b in _PyEval_EvalCodeWithName () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#21 0x00007f295936acd0 in _PyFunction_Vectorcall () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#22 0x00007f295913cffd in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#23 0x00007f29591422a2 in _PyEval_EvalFrameDefault () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#24 0x00007f29591480db in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#25 0x00007f295913cffd in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#26 0x00007f295914106b in _PyEval_EvalFrameDefault () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
--Type <RET> for more, q to quit, c to continue without paging--#27 0x00007f29591480db in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#28 0x00007f295913cffd in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#29 0x00007f295914106b in _PyEval_EvalFrameDefault () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#30 0x00007f29591480db in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#31 0x00007f295913cffd in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#32 0x00007f295914106b in _PyEval_EvalFrameDefault () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#33 0x00007f295928f88b in _PyEval_EvalCodeWithName () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#34 0x00007f295928fc0e in PyEval_EvalCodeEx () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#35 0x00007f295928ffbb in PyEval_EvalCode () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#36 0x00007f2959294441 in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#37 0x00007f2959322f13 in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#38 0x00007f295913cffd in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#39 0x00007f295914106b in _PyEval_EvalFrameDefault () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#40 0x00007f295928f88b in _PyEval_EvalCodeWithName () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#41 0x00007f295936acd0 in _PyFunction_Vectorcall () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#42 0x00007f295913cffd in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#43 0x00007f295914106b in _PyEval_EvalFrameDefault () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#44 0x00007f295928f88b in _PyEval_EvalCodeWithName () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#45 0x00007f295936acd0 in _PyFunction_Vectorcall () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#46 0x00007f295936b3cc in PyVectorcall_Call () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#47 0x00007f295923344e in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#48 0x00007f2959233ab7 in Py_RunMain () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#49 0x00007f29592342f3 in Py_Main () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#50 0x0000564d3757c429 in main ()
(gdb) quit
```

**Comment by kovidgoyal** [comment]
This bug is already fixed in up-to-date kitty, a quick search of the changelog should get you th ebug number if you care.
