### ISSUE TITLE
AddressSanitizer: heap-buffer-overflow

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#2710]
I started fuzzing kitty again by feeding it random escape codes and other stuff. I'm doing this in a Linux container. This is the stack trace of the first error I just found:
```
==11978==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62c0000df68e at pc 0x7f9ff9fd714f bp 0x7fffd7303900 sp 0x7fffd73038f0
READ of size 2 at 0x62c0000df68e thread T0
    #0 0x7f9ff9fd714e in screen_delete_characters kitty/screen.c:1263
    #1 0x7f9ff9f9c432 in dispatch_csi kitty/parser.c:691
    #2 0x7f9ff9fa2d77 in _parse_bytes_watching_for_pending kitty/parser.c:1109
    #3 0x7f9ff9fa4f02 in do_parse_bytes kitty/parser.c:1227
    #4 0x7f9ff9fa5576 in parse_worker kitty/parser.c:1282
    #5 0x7f9ff9ea400c in do_parse kitty/child-monitor.c:308
    #6 0x7f9ff9ea400c in parse_input kitty/child-monitor.c:383
    #7 0x7f9ff9ea4603 in process_global_state kitty/child-monitor.c:948
    #8 0x7f9ff9ea4a65 in do_state_check kitty/child-monitor.c:930
    #9 0x7f9ff8f8c24b in dispatchTimers glfw/backend_utils.c:208
    #10 0x7f9ff8f8ccd0 in pollForEvents glfw/backend_utils.c:309
    #11 0x7f9ff8f6963c in handleEvents glfw/x11_window.c:71
    #12 0x7f9ff8f69712 in _glfwPlatformWaitEvents glfw/x11_window.c:2671
    #13 0x7f9ff8f48129 in _glfwPlatformRunMainLoop glfw/main_loop.h:30
    #14 0x7f9ff8f284b2 in glfwRunMainLoop glfw/init.c:344
    #15 0x7f9ff9f183ad in run_main_loop kitty/glfw.c:1157
    #16 0x7f9ff9e9396a in main_loop kitty/child-monitor.c:981
    #17 0x7f9ffef1ff49  (/usr/lib/libpython3.8.so.1.0+0x134f49)
    #18 0x7f9ffef090d0 in _PyEval_EvalFrameDefault (/usr/lib/libpython3.8.so.1.0+0x11e0d0)
    #19 0x7f9ffef07653 in _PyEval_EvalCodeWithName (/usr/lib/libpython3.8.so.1.0+0x11c653)
    #20 0x7f9ffef1987c in _PyFunction_Vectorcall (/usr/lib/libpython3.8.so.1.0+0x12e87c)
    #21 0x7f9ffef08d07 in _PyEval_EvalFrameDefault (/usr/lib/libpython3.8.so.1.0+0x11dd07)
    #22 0x7f9ffef07653 in _PyEval_EvalCodeWithName (/usr/lib/libpython3.8.so.1.0+0x11c653)
    #23 0x7f9ffef11634 in _PyObject_FastCallDict (/usr/lib/libpython3.8.so.1.0+0x126634)
    #24 0x7f9ffef24c12 in _PyObject_Call_Prepend (/usr/lib/libpython3.8.so.1.0+0x139c12)
    #25 0x7f9ffefe0e08  (/usr/lib/libpython3.8.so.1.0+0x1f5e08)
    #26 0x7f9ffef1218b in _PyObject_MakeTpCall (/usr/lib/libpython3.8.so.1.0+0x12718b)
    #27 0x7f9ffef0d563 in _PyEval_EvalFrameDefault (/usr/lib/libpython3.8.so.1.0+0x122563)
    #28 0x7f9ffef197e7 in _PyFunction_Vectorcall (/usr/lib/libpython3.8.so.1.0+0x12e7e7)
    #29 0x7f9ffef08d07 in _PyEval_EvalFrameDefault (/usr/lib/libpython3.8.so.1.0+0x11dd07)
    #30 0x7f9ffef197e7 in _PyFunction_Vectorcall (/usr/lib/libpython3.8.so.1.0+0x12e7e7)
    #31 0x7f9ffef08d07 in _PyEval_EvalFrameDefault (/usr/lib/libpython3.8.so.1.0+0x11dd07)
    #32 0x7f9ffef197e7 in _PyFunction_Vectorcall (/usr/lib/libpython3.8.so.1.0+0x12e7e7)
    #33 0x7f9ffef08d07 in _PyEval_EvalFrameDefault (/usr/lib/libpython3.8.so.1.0+0x11dd07)
    #34 0x7f9ffef07653 in _PyEval_EvalCodeWithName (/usr/lib/libpython3.8.so.1.0+0x11c653)
    #35 0x7f9ffefb7b02 in PyEval_EvalCode (/usr/lib/libpython3.8.so.1.0+0x1ccb02)
    #36 0x7f9ffefbce0c  (/usr/lib/libpython3.8.so.1.0+0x1d1e0c)
    #37 0x7f9ffef1a097  (/usr/lib/libpython3.8.so.1.0+0x12f097)
    #38 0x7f9ffef08d07 in _PyEval_EvalFrameDefault (/usr/lib/libpython3.8.so.1.0+0x11dd07)
    #39 0x7f9ffef07653 in _PyEval_EvalCodeWithName (/usr/lib/libpython3.8.so.1.0+0x11c653)
    #40 0x7f9ffef1987c in _PyFunction_Vectorcall (/usr/lib/libpython3.8.so.1.0+0x12e87c)
    #41 0x7f9ffef08d07 in _PyEval_EvalFrameDefault (/usr/lib/libpython3.8.so.1.0+0x11dd07)
    #42 0x7f9ffef07653 in _PyEval_EvalCodeWithName (/usr/lib/libpython3.8.so.1.0+0x11c653)
    #43 0x7f9ffef1987c in _PyFunction_Vectorcall (/usr/lib/libpython3.8.so.1.0+0x12e87c)
    #44 0x7f9ffef2cdd1 in PyObject_Call (/usr/lib/libpython3.8.so.1.0+0x141dd1)
    #45 0x7f9ffefd6ee0  (/usr/lib/libpython3.8.so.1.0+0x1ebee0)
    #46 0x7f9ffee74bad  (/usr/lib/libpython3.8.so.1.0+0x89bad)
    #47 0x7f9ffee48657 in Py_Main (/usr/lib/libpython3.8.so.1.0+0x5d657)
    #48 0x55fe94281647 in run_embedded /home/u/Desktop/kitty/launcher.c:109
    #49 0x55fe9428231d in main /home/u/Desktop/kitty/launcher.c:186
    #50 0x7f9ffe2dd001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
    #51 0x55fe9428121d in _start (/home/u/repos/kitty/kitty/launcher/kitty+0x321d)

0x62c0000df68e is located 18 bytes to the right of 29820-byte region [0x62c0000d8200,0x62c0000df67c)
allocated by thread T0 here:
    #0 0x7f9fff3d9639 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7f9ffeef834f in PyMem_Calloc (/usr/lib/libpython3.8.so.1.0+0x10d34f)

SUMMARY: AddressSanitizer: heap-buffer-overflow kitty/screen.c:1263 in screen_delete_characters
Shadow bytes around the buggy address:
  0x0c5880013e80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5880013e90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5880013ea0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5880013eb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5880013ec0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 04
=>0x0c5880013ed0: fa[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5880013ee0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5880013ef0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5880013f00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5880013f10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5880013f20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==11978==ABORTING
```

Is this enough information for you to fix this bug or can I provide you with additional information?

**Comment by Luflosi** [comment]
`left_shift_line()` is a macro. If you can't find the issue right away, I can try to rewrite the macro as a function and then try to reproduce the crash again. I've reproduced this crash twice now, so it seems to be fairly easy to do it again.
I should probably also record what random garbage I feed to kitty, so that it's easy to reproduce. This will eat a lot of disk space though.

**Comment by Luflosi** [comment]
I converted the macro to a function and the overflow is in `if (((line->gpu_cells[at].attrs) & WIDTH_MASK) != 1) {`

**Comment by Luflosi** [comment]
When was this bug triggered? When the cursor was at the end of the line and a DCH escape code was sent? I'm trying to understand to make sure there is no deeper underlying issue.

**Comment by kovidgoyal** [comment]
yes, that would be the cause.
