### ISSUE TITLE
kitten diff: Exception in callback

### ISSUE THREAD

**Issue by basbebe** [kovidgoyal/kitty#2730]
I'm using Mac OS.

I open kitten diff:
```
~/.config/kitty
❯ kitty + kitten diff kitty.conf kitty.conf.sample
```

I press `a` or `=`

&rarr;

```
Exception in callback Loop._read_ready(<__main__.Dif...t 0x107fbaba8>, 5)
Traceback (most recent call last):
  File "Python/events.py", line 88, in _run
  File "kitty/loop.py", line 222, in _read_ready
  File "kitty/loop.py", line 245, in _on_text
  File "kitty/main.py", line 493, in on_text
  File "kitty/main.py", line 116, in perform_action
ValueError: invalid literal for int() with base 10: 'all'

Press the Enter key to quit
```

`Output of kitty --debug-config`
```
kitty 0.17.4 created by Kovid Goyal
Darwin Bastians-MBP.fritz.box 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.5 BuildVersion:	19F101
Loaded config files: /Users/bastian/.config/kitty/kitty.conf

Config options different from defaults:
active_border_color   Color(red=184, green=186, blue=37)
adjust_line_height    1.2
allow_remote_control  y
background            Color(red=40, green=40, blue=40)
color0                Color(red=40, green=40, blue=40)
color1                Color(red=204, green=36, blue=29)
color10               Color(red=184, green=187, blue=38)
color11               Color(red=250, green=189, blue=45)
color12               Color(red=131, green=165, blue=152)
color13               Color(red=211, green=134, blue=155)
color14               Color(red=142, green=192, blue=124)
color15               Color(red=146, green=131, blue=116)
color2                Color(red=152, green=151, blue=26)
color3                Color(red=215, green=153, blue=33)
color4                Color(red=69, green=133, blue=136)
color5                Color(red=177, green=98, blue=134)
color6                Color(red=104, green=157, blue=106)
color7                Color(red=168, green=153, blue=132)
color8                Color(red=146, green=131, blue=116)
color9                Color(red=251, green=73, blue=52)
cursor                Color(red=146, green=131, blue=116)
disable_ligatures     1
editor                /usr/local/bin/kak
env                   {'LANG': 'de_DE.UTF-8', 'PATH': '/usr/local/bin:/usr/local/sbin:/Applications/kitty.app/Contents/MacOS:/usr/local/sbin:/Users/bastian/.local/bin:/Users/bastian/.cache/dein/repos/github.com/junegunn/fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/TeX/texbin:/usr/local/sbin:/Applications/kitty.app/Contents/MacOS'}
font_family           JetBrains Mono
font_size             13.0
foreground            Color(red=235, green=219, blue=178)
macos_option_as_alt   2
macos_titlebar_color  1
mouse_hide_wait       5.0
resize_draw_strategy  3
selection_background  Color(red=60, green=56, blue=54)
selection_foreground  Color(red=146, green=131, blue=116)
strip_trailing_spaces smart
symbol_map            {(57504, 57507): 'JetBrainsMono Nerd Font', (57536, 57543): 'JetBrainsMono Nerd Font'}
tab_bar_style         separator
window_padding_width  FloatEdges(left=3.0, top=3.0, right=3.0, bottom=3.0)
Added shortcuts:
	 control+l KeyAction(func='combine', args=(KeyAction(func='clear_terminal', args=['scroll', True]), KeyAction(func='send_text', args=['normal,application', b'\x0c'])))
	 super+d KeyAction(func='launch', args=['--location=vsplit'])
	 super+left_bracket KeyAction(func='previous_window', args=())
	 super+right_bracket KeyAction(func='next_window', args=())
	 alt+super+d KeyAction(func='layout_action', args=['rotate', ()])
Changed shortcuts:
	 shift+control+enter KeyAction(func='new_window_with_cwd', args=())
	 super+enter KeyAction(func='new_window_with_cwd', args=())
	 shift+super+d KeyAction(func='launch', args=['--location=hsplit'])

```

The Problem is reproducable for me w/ `kitty --config NONE`.

my `diff.conf`
```
# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

#: Diffing {{{

syntax_aliases pyj:py pyi:py recipe:py

#: File extension aliases for syntax highlight For example, to syntax
#: highlight file.xyz as file.abc use a setting of xyz:abc

num_context_lines 3

#: The number of lines of context to show around each change.

diff_cmd auto

#: The diff command to use. Must contain the placeholder _CONTEXT_
#: which will be replaced by the number of lines of context. The
#: default is to search the system for either git or diff and use
#: that, if found.

replace_tab_by \x20\x20\x20\x20

#: The string to replace tabs with. Default is to use four spaces.

#: }}}

#: Colors {{{

pygments_style native

#: The pygments color scheme to use for syntax highlighting. See
#: pygments colors schemes <https://help.farbox.com/pygments.html> for
#: a list of schemes.

foreground #ebdbb2
background #282828

#: Basic colors

title_fg #fbf1c7
title_bg #32302f

#: Title colors

margin_bg #1d2021
margin_fg #a89984

#: Margin colors

removed_bg           #cc241d
highlight_removed_bg #fb4934
removed_margin_bg    #cc241d

#: Removed text backgrounds

added_bg           #689d6a
highlight_added_bg #acf2bd
added_margin_bg    #689d6a

#: Added text backgrounds

filler_bg #3c3836

#: Filler (empty) line background

margin_filler_bg none

#: Filler (empty) line background in margins, defaults to the filler
#: background

hunk_margin_bg #504945
hunk_bg        #504945

#: Hunk header colors

search_bg #444
search_fg white
select_bg #b4d5fe
select_fg black

#: Highlighting

#: }}}

#: Keyboard shortcuts {{{

map q         quit
map esc       quit
map j         scroll_by 1
map down      scroll_by 1
map k         scroll_by -1
map up        scroll_by -1
map home      scroll_to start
map end       scroll_to end
map page_down scroll_to next-page
map space     scroll_to next-page
map page_up   scroll_to prev-page
map n         scroll_to next-change
map p         scroll_to prev-change
map a         change_context all
map =         change_context default
map +         change_context 5
map -         change_context -5
map /         start_search regex forward
map ?         start_search regex backward
map .         scroll_to next-match
map >         scroll_to next-match
map ,         scroll_to prev-match
map <         scroll_to prev-match
map f         start_search substring forward
map b         start_search substring backward
#: }}}

```

**Comment by kovidgoyal** [comment]
This is already fixed in master.

**Comment by basbebe** [comment]
> This is already fixed in master.

thank you! waiting for next release then
