### ISSUE TITLE
`kitty @ ls` returns KeyError when `--keep-focus` is used for `kitty @ launch`

### ISSUE THREAD

**Issue by marioortizmanero** [kovidgoyal/kitty#2753]
**Describe the bug**
Running `kitty @ ls` after using `kitty @ launch --keep-focus cat` and closing the new window raises a `KeyError`.

**To Reproduce**

1. `kitty @ launch --keep-focus cat`
2. The new window is closed manually with Ctrl + C, for example, otherwise this doesn't happen. Before closing the new window, `kitty @ ls` works fine. For example, it returns this:

<details>
  <summary>Long text</summary>

  
```json
[
  {
    "id": 1,
    "is_focused": true,
    "tabs": [
      {
        "active_window_history": [
          1,
          2
        ],
        "id": 1,
        "is_focused": true,
        "layout": "fat",
        "title": "mario: kitty @ ls",
        "windows": [
          {
            "cmdline": [
              "/bin/zsh"
            ],
            "cwd": "/home/mario",
            "env": {
              "COLORTERM": "truecolor",
              "CONDA_CHANGEPS1": "no",
              "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
              "DESKTOP_SESSION": "bspwm",
              "DISPLAY": ":0",
              "EDITOR": "/usr/bin/nvim",
              "GDMSESSION": "bspwm",
              "GTK_MODULES": "canberra-gtk-module",
              "HOME": "/home/mario",
              "KEYTIMEOUT": "1",
              "KITTY_WINDOW_ID": "1",
              "LANG": "en_US.UTF-8",
              "LG_WEBOS_TV_SDK_HOME": "/home/mario/Android/Sdk/webOS_TV_SDK",
              "LOGNAME": "mario",
              "MAIL": "/var/spool/mail/mario",
              "NNN_OPTS": "ea",
              "NNN_PLUG": "t:preview-tui;d:dragdrop",
              "NNN_SEL": "/tmp/nnn.selection",
              "NNN_TRASH": "1",
              "OLDPWD": "/home/mario",
              "PATH": "/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/mario/.local/bin",
              "PRIVATE_IP": "192.168.1.140",
              "PROMPT_EOL_MARK": "",
              "PWD": "/home/mario",
              "SHELL": "/bin/zsh",
              "SHLVL": "1",
              "TERM": "xterm-kitty",
              "TERMINFO": "/usr/lib/kitty/terminfo",
              "USER": "mario",
              "VIRTUAL_ENV_DISABLE_PROMPT": "12",
              "VISUAL": "nvim",
              "WEBOS_CLI_TV": "/home/mario/Android/Sdk/webOS_TV_SDK/CLI/bin",
              "WINDOWID": "39845902",
              "XAUTHORITY": "/home/mario/.Xauthority",
              "XDG_GREETER_DATA_DIR": "/var/lib/lightdm-data/mario",
              "XDG_RUNTIME_DIR": "/run/user/1000",
              "XDG_SEAT": "seat0",
              "XDG_SEAT_PATH": "/org/freedesktop/DisplayManager/Seat0",
              "XDG_SESSION_CLASS": "user",
              "XDG_SESSION_DESKTOP": "bspwm",
              "XDG_SESSION_ID": "2",
              "XDG_SESSION_PATH": "/org/freedesktop/DisplayManager/Session0",
              "XDG_SESSION_TYPE": "x11",
              "XDG_VTNR": "7",
              "_": "/usr/bin/kitty",
              "_JAVA_AWT_WM_NONREPARENTING": "1"
            },
            "foreground_processes": [
              {
                "cmdline": [
                  "kitty",
                  "@",
                  "ls"
                ],
                "cwd": "/home/mario",
                "pid": 30973
              }
            ],
            "id": 1,
            "is_focused": true,
            "pid": 30916,
            "title": "mario: kitty @ ls"
          },
          {
            "cmdline": [
              "cat"
            ],
            "cwd": "/home/mario",
            "env": {
              "COLORTERM": "truecolor",
              "CONDA_CHANGEPS1": "no",
              "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
              "DESKTOP_SESSION": "bspwm",
              "DISPLAY": ":0",
              "EDITOR": "/usr/bin/nvim",
              "GDMSESSION": "bspwm",
              "GTK_MODULES": "canberra-gtk-module",
              "HOME": "/home/mario",
              "KEYTIMEOUT": "1",
              "KITTY_WINDOW_ID": "2",
              "LANG": "en_US.UTF-8",
              "LG_WEBOS_TV_SDK_HOME": "/home/mario/Android/Sdk/webOS_TV_SDK",
              "LOGNAME": "mario",
              "MAIL": "/var/spool/mail/mario",
              "NNN_OPTS": "ea",
              "NNN_PLUG": "t:preview-tui;d:dragdrop",
              "NNN_SEL": "/tmp/nnn.selection",
              "NNN_TRASH": "1",
              "OLDPWD": "/home/mario",
              "PATH": "/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/mario/.local/bin",
              "PRIVATE_IP": "192.168.1.140",
              "PROMPT_EOL_MARK": "",
              "PWD": "/home/mario",
              "SHELL": "/bin/zsh",
              "SHLVL": "1",
              "TERM": "xterm-kitty",
              "TERMINFO": "/usr/lib/kitty/terminfo",
              "USER": "mario",
              "VIRTUAL_ENV_DISABLE_PROMPT": "12",
              "VISUAL": "nvim",
              "WEBOS_CLI_TV": "/home/mario/Android/Sdk/webOS_TV_SDK/CLI/bin",
              "WINDOWID": "39845902",
              "XAUTHORITY": "/home/mario/.Xauthority",
              "XDG_GREETER_DATA_DIR": "/var/lib/lightdm-data/mario",
              "XDG_RUNTIME_DIR": "/run/user/1000",
              "XDG_SEAT": "seat0",
              "XDG_SEAT_PATH": "/org/freedesktop/DisplayManager/Seat0",
              "XDG_SESSION_CLASS": "user",
              "XDG_SESSION_DESKTOP": "bspwm",
              "XDG_SESSION_ID": "2",
              "XDG_SESSION_PATH": "/org/freedesktop/DisplayManager/Session0",
              "XDG_SESSION_TYPE": "x11",
              "XDG_VTNR": "7",
              "_": "/usr/bin/kitty",
              "_JAVA_AWT_WM_NONREPARENTING": "1"
            },
            "foreground_processes": [
              {
                "cmdline": [
                  "cat"
                ],
                "cwd": "/home/mario",
                "pid": 30956
              }
            ],
            "id": 2,
            "is_focused": false,
            "pid": 30956,
            "title": "cat"
          }
        ]
      }
    ]
  }
]
```

</details>

3. `kitty @ ls` raises the following error:

```
~
❯ kitty @ ls        
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 333, in _handle_remote_command
    response = handle_cmd(self, window, cmd)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 41, in handle_cmd
    ans = c.response_from_kitty(boss, window, PayloadGetter(c, payload))
  File "/usr/bin/../lib/kitty/kitty/rc/ls.py", line 36, in response_from_kitty
    data = list(boss.list_os_windows())
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 216, in list_os_windows
    'tabs': list(tm.list_tabs(active_tab, active_window)),
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 613, in list_tabs
    'active_window_history': list(tab.windows.active_window_history),
  File "/usr/bin/../lib/kitty/kitty/window_list.py", line 163, in active_window_history
    g = gid_map[gid]
KeyError: 2

2
```

**Expected behavior**
No error should appear at all, or at least it should give more details related to the crash

**Enviroment details**
OS: Arch Linux

```
~
❯ kitty --debug-config
kitty 0.17.4 (5f6faa1bf0) created by Kovid Goyal
Linux glowarch 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/mario/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
active_tab_background   Color(red=187, green=192, blue=201)
active_tab_foreground   Color(red=40, green=44, blue=52)
allow_remote_control    y
background              Color(red=40, green=44, blue=52)
bold_font               SF Mono Bold
bold_italic_font        SF Mono Bold Italic
color0                  Color(red=40, green=44, blue=52)
color1                  Color(red=224, green=108, blue=117)
color10                 Color(red=86, green=182, blue=194)
color11                 Color(red=229, green=192, blue=123)
color12                 Color(red=97, green=175, blue=239)
color13                 Color(red=190, green=80, blue=70)
color14                 Color(red=86, green=182, blue=194)
color15                 Color(red=171, green=178, blue=191)
color2                  Color(red=152, green=195, blue=121)
color3                  Color(red=229, green=192, blue=123)
color4                  Color(red=97, green=175, blue=239)
color5                  Color(red=190, green=80, blue=70)
color6                  Color(red=86, green=182, blue=194)
color7                  Color(red=183, green=188, blue=199)
color8                  Color(red=57, green=62, blue=72)
color9                  Color(red=209, green=154, blue=102)
font_family             SF Mono
font_size               12.0
foreground              Color(red=187, green=192, blue=201)
inactive_tab_background Color(red=40, green=44, blue=52)
inactive_tab_foreground Color(red=171, green=178, blue=191)
italic_font             SF Mono Regular Italic
selection_background    Color(red=187, green=192, blue=201)
selection_foreground    Color(red=40, green=44, blue=52)
window_padding_width    FloatEdges(left=10.0, top=10.0, right=10.0, bottom=10.0)
```

**Additional context**
I used an empty config file apart from `allow_remote_control yes`.

**Comment by marioortizmanero** [comment]
Can confirm this was fixed correctly! Cheers :+1:
