### ISSUE TITLE
Kitty does not start on my mac

### ISSUE THREAD

**Issue by esn89** [kovidgoyal/kitty#2793]
**Describe the bug**
Kitty does not start, version 0.17 and 0.18 both do not.

**To Reproduce**
1. Click on the Kitty on my Mac
2. It does not open.

**Expected behavior**
I expect to see the terminal

**Environment details**
Mac: 10.15.5

```
Output of kitty --debug-config:

Loaded config files: /Users/esn89/.config/kitty/kitty.conf
[176 09:46:17.699017] Shortcut: kitty_map+q has unknown modifier, ignoring
[176 09:46:17.699429] The option macos_show_window_title_in_menubar is deprecated. Use macos_show_window_title_in menubar instead.

Config options different from defaults:
active_border_color                Color(red=71, green=75, blue=89)
active_tab_background              Color(red=46, green=52, blue=64)
active_tab_font_style              (True, False)
active_tab_foreground              Color(red=199, green=146, blue=234)
adjust_line_height                 -1
allow_remote_control               y
background                         Color(red=46, green=52, blue=64)
bold_font                          PragmataPro Mono Liga Bold
bold_italic_font                   PragmataPro Mono Liga Bold Italic
color0                             Color(red=59, green=66, blue=82)
color1                             Color(red=191, green=97, blue=106)
color10                            Color(red=163, green=190, blue=140)
color11                            Color(red=235, green=203, blue=139)
color12                            Color(red=129, green=161, blue=193)
color13                            Color(red=180, green=142, blue=173)
color14                            Color(red=143, green=188, blue=187)
color15                            Color(red=180, green=142, blue=173)
color2                             Color(red=163, green=190, blue=140)
color3                             Color(red=235, green=203, blue=139)
color4                             Color(red=129, green=161, blue=193)
color5                             Color(red=180, green=142, blue=173)
color6                             Color(red=136, green=192, blue=208)
color7                             Color(red=229, green=233, blue=240)
color8                             Color(red=76, green=86, blue=106)
color9                             Color(red=191, green=97, blue=106)
cursor                             Color(red=129, green=161, blue=193)
cursor_blink_interval              0.0
font_family                        PragmataPro Mono Liga Regular
font_size                          15.0
foreground                         Color(red=216, green=222, blue=233)
inactive_border_color              Color(red=44, green=50, blue=60)
inactive_tab_background            Color(red=46, green=52, blue=64)
inactive_tab_foreground            Color(red=80, green=73, blue=69)
inactive_text_alpha                0.81
italic_font                        PragmataPro Mono Liga Italic
kitty_mod                          8
macos_custom_beam_cursor           True
macos_option_as_alt                3
macos_quit_when_last_window_closed True
macos_show_window_title_in         window
macos_thicken_font                 0.55
macos_titlebar_color               775176194
shell                              /bin/zsh --login
startup_session                    /Users/esn89/.config/kitty/kitstart.conf
tab_bar_margin_width               605.0
tab_bar_style                      separator
tab_separator                          
window_border_width                1.5
window_margin_width                FloatEdges(left=3.0, top=3.0, right=3.0, bottom=3.0)
window_padding_width               FloatEdges(left=7.0, top=7.0, right=7.0, bottom=7.0)
Added shortcuts:
	 super+a KeyAction(func='goto_layout', args=['tall'])
	 super+i KeyAction(func='next_layout', args=())
	 super+p KeyAction(func='previous_window', args=())
	 super+z KeyAction(func='goto_layout', args=['stack'])
Removed shortcuts:
	 super+a > 1 KeyAction(func='set_background_opacity', args=['1'])
	 super+a > d KeyAction(func='set_background_opacity', args=['default'])
	 super+a > l KeyAction(func='set_background_opacity', args=['-0.1'])
	 super+a > m KeyAction(func='set_background_opacity', args=['+0.1'])
	 super+p > f KeyAction(func='kitten', args=['hints', '--type path --program -'])
	 super+p > h KeyAction(func='kitten', args=['hints', '--type hash --program -'])
	 super+p > l KeyAction(func='kitten', args=['hints', '--type line --program -'])
	 super+p > n KeyAction(func='kitten', args=['hints', '--type linenum'])
	 super+p > w KeyAction(func='kitten', args=['hints', '--type word --program -'])
	 super+p > shift+f KeyAction(func='kitten', args=['hints', '--type path'])
Changed shortcuts:
	 super+1 KeyAction(func='goto_tab', args=(1,))
	 super+2 KeyAction(func='goto_tab', args=(2,))
	 super+3 KeyAction(func='goto_tab', args=(3,))
	 super+4 KeyAction(func='goto_tab', args=(4,))
	 super+5 KeyAction(func='goto_tab', args=(5,))
	 super+h KeyAction(func='neighboring_window', args=['left'])
	 super+j KeyAction(func='neighboring_window', args=['bottom'])
	 super+k KeyAction(func='neighboring_window', args=['top'])
	 super+l KeyAction(func='neighboring_window', args=['right'])
	 super+n KeyAction(func='next_window', args=())
	 super+o KeyAction(func='pass_selection_to_program', args=['/Users/esn89/.config/kitty/selectiontobrowser.sh'])
	 super+q KeyAction(func='goto_tab', args=(9,))
	 super+s KeyAction(func='last_used_layout', args=()
```

Starting kitty in another terminal also shows this:

```
[176 09:41:49.053553] Shortcut: kitty_map+q has unknown modifier, ignoring
[176 09:41:49.054117] The option macos_show_window_title_in_menubar is deprecated. Use macos_show_window_title_in menubar instead.
[176 09:41:49.542552] MemoryError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "kitty/main.py", line 343, in main
  File "kitty/main.py", line 336, in _main
  File "kitty/main.py", line 158, in __call__
  File "kitty/main.py", line 137, in _run_app
  File "kitty/boss.py", line 458, in start
  File "kitty/boss.py", line 179, in startup_first_child
  File "kitty/boss.py", line 204, in add_os_window
  File "kitty/tabs.py", line 484, in __init__
  File "kitty/tabs.py", line 527, in _add_tab
  File "kitty/tabs.py", line 542, in tabbar_visibility_changed
  File "kitty/tab_bar.py", line 266, in layout
SystemError: <method 'resize' of 'fast_data_types.Screen' objects> returned a result with an error set
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
I need a minimal config to reproduce your issue. Bisect your config to
find the problem setting.

**Comment by esn89** [comment]
I found the offending line:
```## Tab-bar colors
## The left offset
#tab_bar_margin_width 605
active_tab_foreground #c792ea
active_tab_background #2E3440
inactive_tab_foreground #504945
inactive_tab_background #2E3440
tab_bar_style separator
tab_separator "    "
```

If I uncomment `tab_bar_margin_width 605` I get this crash.
