### ISSUE TITLE
kitty icat --transfer-mode=file throws an error

### ISSUE THREAD

**Issue by dsanson** [kovidgoyal/kitty#281]
`kitty icat --transfer-mode=detect test.png` works fine. But:

```
$ kitty icat --transfer-mode=file test.png
Traceback (most recent call last):
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/desanso/Software/kitty/kitty.app/Contents/MacOS/../Frameworks/kitty/__main__.py", line 50, in <module>
    main()
  File "/Users/desanso/Software/kitty/kitty.app/Contents/MacOS/../Frameworks/kitty/__main__.py", line 46, in main
    func(sys.argv[1:])
  File "/Users/desanso/Software/kitty/kitty.app/Contents/MacOS/../Frameworks/kitty/__main__.py", line 10, in icat
    main(args)
  File "/Users/desanso/Software/kitty/kitty.app/Contents/MacOS/../Frameworks/kitty/kitty/icat.py", line 384, in main
    process(item, args)
  File "/Users/desanso/Software/kitty/kitty.app/Contents/MacOS/../Frameworks/kitty/kitty/icat.py", line 282, in process
    show(outfile, width, height, fmt, transmit_mode, align=args.align, place=args.place)
  File "/Users/desanso/Software/kitty/kitty.app/Contents/MacOS/../Frameworks/kitty/kitty/icat.py", line 207, in show
    if detect_support.has_files:
AttributeError: 'function' object has no attribute 'has_files'
```

**Comment by dsanson** [comment]
Never mind. This was related to a change I had made to icat.py.
