### ISSUE TITLE
BrokenPipeError when using remote control through socket

### ISSUE THREAD

**Issue by jbrea** [kovidgoyal/kitty#2852]
**Describe the bug**
Sometimes when sending text via a socket I get the following error
```
$ kitty @ --to unix:/tmp/kitty.socket.1 send-text --from-file tmp.txt
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 97, in send
    out.flush()
  File "/usr/lib/python3.8/socket.py", line 687, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 121, in <module>
    main()
  File "/usr/bin/../lib/kitty/__main__.py", line 117, in main
    func(sys.argv[1:])
  File "/usr/bin/../lib/kitty/__main__.py", line 23, in remote_control
    rc_main(args)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 187, in main
    response = do_io(global_opts.to, send, no_response)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 133, in do_io
    io.send(send_data)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 97, in send
    out.flush()
  File "/usr/lib/python3.8/socket.py", line 687, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe
```

**To Reproduce**
1. `kitty -o allow_remote_control=yes --listen-on unix:/tmp/kitty.socket.1`
2. create a file `tmp.txt` with some content (in my case ~200 LOC)
3. Run `kitty @ --to unix:/tmp/kitty.socket.1 send-text --from-file tmp.txt` multiple times (doesn't happen the first time, sometimes the second time....)
4. See error above

**Expected behavior**
No error.

**Environment details**
```
kitty 0.18.1 created by Kovid Goyal
Linux machina 5.7.7-arch1-1 #1 SMP PREEMPT Wed, 01 Jul 2020 14:53:16 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11

Config options different from defaults:
```

**Additional context**
Reproduced the problem with `kitty --config NONE`.

**Comment by kovidgoyal** [comment]
Yeah, I need to re-write the peer comms thread to be a two way pipe to
fix this issue.

**Comment by jbrea** [comment]
Wow, this was quite a bit of work, I guess.
And you did it super quickly, thanks a lot!!
I just tested master and it works beautifully.

**Comment by kovidgoyal** [comment]
You are welcome, this was anyway overdue, as the original talk thread code was hacked and patched to do something that it was not originally designed to do. Having a clean re-implementation was on my TODO list.
