### ISSUE TITLE
Unable to generate documetation using sphinx

### ISSUE THREAD

**Issue by YorkZ** [kovidgoyal/kitty#2893]
**To Reproduce**

1. git clone https://github.com/kovidgoyal/kitty.git
1. `cd kitty/docs`
2. `make texinfo` or `make html`, `make latexpdf` etc

**Expected behavior**

Output files been produced in _build/{html,latex,texinfo} directories.

**Environment details**
OS: Arch Linux

```
Output from `make texinfo`
` makefile

sphinx-build -M texinfo "." "_build" -j auto -T  
Running Sphinx v3.2.0

Traceback (most recent call last):
  File "~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/application.py", line 258, in __init__
    self.config.setup(self)
  File "~/src/kitty/docs/conf.py", line 604, in setup
    write_cli_docs(kn)
  File "~/src/kitty/docs/conf.py", line 254, in write_cli_docs
    from kitty.launch import options_spec as launch_options_spec
  File "~/src/kitty/kitty/launch.py", line 9, in <module>
    from .boss import Boss
  File "~/src/kitty/kitty/boss.py", line 17, in <module>
    from .child import cached_process_data, cwd_of_process
  File "~/src/kitty/kitty/child.py", line 14, in <module>
    import kitty.fast_data_types as fast_data_types
ModuleNotFoundError: No module named 'kitty.fast_data_types'

Exception occurred:
  File "~/src/kitty/kitty/child.py", line 14, in <module>
    import kitty.fast_data_types as fast_data_types
ModuleNotFoundError: No module named 'kitty.fast_data_types'
The full traceback has been saved in /tmp/sphinx-err-teey1v1m.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

`````

```

**Comment by Luflosi** [comment]
You need to compile kitty with `make` first.
