### ISSUE TITLE
GLFW is not initialized

### ISSUE THREAD

**Issue by MaximilianKindshofer** [kovidgoyal/kitty#3]
I tried to start kitty but I got:

```
python3 kitty
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kitty/__main__.py", line 7, in <module>
    main()
  File "kitty/kitty/main.py", line 147, in main
    run_app(opts, args)
  File "kitty/kitty/main.py", line 92, in run_app
    boss = Boss(window, opts, args)
  File "kitty/kitty/boss.py", line 88, in __init__
    cell_size.width, cell_size.height = set_font_family(opts.font_family, opts.font_size)
  File "kitty/kitty/fonts/freetype.py", line 61, in set_font_family
    dpi = get_logical_dpi()
  File "kitty/kitty/utils.py", line 48, in get_logical_dpi
    raw = subprocess.check_output(['xdpyinfo']).decode('utf-8')
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'xdpyinfo'
[glfw error]  The GLFW library is not initialized

```

**Comment by kovidgoyal** [comment]
Install xdpyinfo and you will be fine (I should add it to the dependencies, but I was unaware that any X11 based system came without it already installed).
