### ISSUE TITLE
Why is Kitty invading all sorts of outside terminals with errors?

### ISSUE THREAD

**Issue by oxysoft** [kovidgoyal/kitty#3067]
**Describe the bug**
Several places (everything dealing with shells/terminals?) are printing errors related to Kitty. Examples

- Vim language formatting plugin: 
- Executing shell commands with `!` in Vim:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 119, in <module>
    main()
  File "/usr/bin/../lib/kitty/__main__.py", line 115, in main
    func(sys.argv[1:])
  File "/usr/bin/../lib/kitty/__main__.py", line 22, in remote_control
    main(args)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 175, in main
    response = do_io(global_opts.to, send, no_response)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 119, in do_io
    with io:
  File "/usr/bin/../lib/kitty/kitty/utils.py", line 374, in __enter__
    self.tty_fd, self.original_termios = open_tty(True)
OSError: Failed to open controlling terminal: /dev/tty (identified with ctermid()) with error: No such device or address
```

- Opening other terminals (Alacritty, tilix, etc.)
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 119, in <module>
    main()
  File "/usr/bin/../lib/kitty/__main__.py", line 115, in main
    func(sys.argv[1:])
  File "/usr/bin/../lib/kitty/__main__.py", line 22, in remote_control
    main(args)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 175, in main
    response = do_io(global_opts.to, send, no_response)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 123, in do_io
    received = io.recv(timeout=10)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 103, in recv
    read_command_response(self.tty_fd, timeout, ans)
TimeoutError: Timed out while waiting to read command response. Make sure you are running this command from within the kitty terminal. If you want to run commands from outside, then you have to setup a socket with the --listen-on command line flag.
```

kitty.conf

```
font_family FiraCode-Medium
bolda_font auto
italic_font      auto
bold_italic_font auto
font_size 10.8
disable_ligatures true 
font_features FiraCode-Retina +zero +onum
cursor_shape beam
cursor_blink_interval 0
editor nvim
allow_remote_control true
background_opacity 0.85


# Shortcuts
map ctrl+r paste_from_clipboard
map ctrl+v paste_from_clipboard
map page_up scroll_page_up
map page_down scroll_page_down
```

But the problem persists even with a completely empty kitty.conf

**To Reproduce**
Not sure exactly, I believe this started as soon as I installed Kitty. I have been enduring for now, but seeing as it does it in Vim this is starting to turn into a deal-breaker.

**Expected behavior**
I expect everything Kitty to remain inside of Kitty!

**Screenshots**

Alacritty:
![image](https://user-images.githubusercontent.com/3945277/97484234-df458f80-192e-11eb-963d-ebe729ffc32a.png)

**Environment details**
OS: Linux Mint 20 with awesomewm

```
➜  kitty --debug-config
kitty 0.15.0 created by Kovid Goyal
Linux nuck-pc 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64
Linux Mint 20 Ulyana \n \l
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20
DISTRIB_CODENAME=ulyana
DISTRIB_DESCRIPTION="Linux Mint 20 Ulyana"
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/nuck/.config/kitty/kitty.conf
[302 15:04:56.647050] Ignoring unknown config key: bolda_font
[302 15:04:56.647093] Ignoring unknown config key: font_features
Running under: X11

Config options different from defaults:
allow_remote_control  y
background_opacity    0.85
cursor_blink_interval 0.0
cursor_shape          2
editor                nvim
font_family           FiraCode-Medium
font_size             10.8
update_check_interval 0.0
Added shortcuts:
	page_up KeyAction(func='scroll_page_up', args=())
	page_down KeyAction(func='scroll_page_down', args=())
	control+r KeyAction(func='paste_from_clipboard', args=())
	control+v KeyAction(func='paste_from_clipboard', args=())
```

Any help is greatly appreciated!

**Comment by kovidgoyal** [comment]
Because you added some kitty invocations to your shell/vim rc files.
Remove them and youwill be fine.

**Comment by oxysoft** [comment]
Doh! I was setting the color scheme with remote control in my shell config, no clue how I missed that. Thanks a lot!
