### ISSUE TITLE
Remote control doesn't have effect when called from code

### ISSUE THREAD

**Issue by Mdsp9070** [kovidgoyal/kitty#3166]
**Describe the bug**
I'm writing a CLI app to change kitty config on-the-fly! So, to achieve this, on my code (I'm using Elixir), I call: `System.cmd("kitty", ["@", "set-background-opacity", opacity])` or other params, however I receive this error:

```sh
Traceback (most recent call last):
                                    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
                                                                                                            return _run_code(code, main_globals, None,
                                    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
                                                                                                 exec(code, run_globals)
      File "/usr/bin/../lib/kitty/__main__.py", line 127, in <module>
                                                                         main()
                                                                                 File "/usr/bin/../lib/kitty/__main__.py", line 123, in main
                            func(sys.argv[1:])
                                                File "/usr/bin/../lib/kitty/__main__.py", line 23, in remote_control
                                                                                                                       rc_main(args)
                  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 187, in main
                                                                                             response = do_io(global_opts.to, send, no_response)
                              File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 132, in do_io
                                                                                                          with io:
                                                                                                                    File "/usr/bin/../lib/kitty/kitty/utils.py", line 429, in __enter__
                                                                       self.tty_fd, self.original_termios = open_tty(True)
      OSError: Failed to open controlling terminal: /dev/tty (identified with ctermid()) with error: No such device or address
```

**To Reproduce**
1. starts iex promt
2. execute any remote_control change with System.cmd("kitty", [params])
3. See error

**Expected behavior**
I expect that the remote_control works as same as running this command on kitty

**Screenshots**
![2020-12-14-01-44-42](https://user-images.githubusercontent.com/44469426/102041328-f12fa480-3dad-11eb-9ccc-113caf6f682a.png)

**Environment details**
OS: Arch Linux

```
kitty 0.19.2 created by Kovid Goyal
Linux mdsp 5.9.13-arch1-1 #1 SMP PREEMPT Tue, 08 Dec 2020 12:09:55 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/matthew/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
active_tab_background   Color(red=230, green=230, blue=230)
active_tab_foreground   Color(red=25, green=22, blue=49)
allow_remote_control    y
background              Color(red=25, green=22, blue=34)
bold_font               "MonoLisa-Bold"
bold_italic_font        "MonoLisa-BoldItalic"
color1                  Color(red=255, green=85, blue=85)
color10                 Color(red=90, green=247, blue=142)
color11                 Color(red=234, green=240, blue=141)
color12                 Color(red=202, green=169, blue=250)
color13                 Color(red=255, green=146, blue=208)
color14                 Color(red=170, green=145, blue=227)
color15                 Color(red=230, green=230, blue=230)
color2                  Color(red=80, green=250, blue=123)
color3                  Color(red=239, green=250, blue=120)
color4                  Color(red=189, green=147, blue=249)
color5                  Color(red=255, green=121, blue=198)
color6                  Color(red=141, green=121, blue=186)
color7                  Color(red=191, green=191, blue=191)
color8                  Color(red=77, green=77, blue=77)
color9                  Color(red=255, green=110, blue=103)
copy_on_select          clipboard
cursor                  Color(red=248, green=248, blue=242)
cursor_blink_interval   0.0
cursor_text_color       None
font_family             "MonoLisa-Medium"
font_size               14.0
foreground              Color(red=225, green=225, blue=230)
inactive_tab_background Color(red=98, green=114, blue=164)
inactive_tab_foreground Color(red=68, green=71, blue=111)
initial_window_height   (300, 'px')
initial_window_width    (300, 'px')
italic_font             "MonoLisa-MediumItalic"
open_url_modifiers      2
selection_background    Color(red=248, green=248, blue=242)
selection_foreground    Color(red=68, green=71, blue=90)
term                    xterm-256color
url_color               Color(red=255, green=184, blue=108)
Added shortcuts:
	control+c KeyAction(func='copy_to_clipboard', args=())
	control+v KeyAction(func='paste_from_clipboard', args=())
	super+a KeyAction(func='next_tab', args=())
	super+d KeyAction(func='previous_tab', args=())
	super+e KeyAction(func='new_tab', args=())
	shift+super+q KeyAction(func='close_tab', args=())
Changed shortcuts:
	shift+control+c KeyAction(func='send_text', args=['all', b'\x03'])
```

**Comment by kovidgoyal** [comment]
If you want to use remote control from outside kitty, you need to tell
kitty to listen on a socket. See th --listen-on command line flag.

**Comment by Mdsp9070** [comment]
Thank you for your answer! Could you please give me an example?

**Comment by Mdsp9070** [comment]
Thank you for your answer! I'm now searching more about this feature!

**Comment by Mdsp9070** [comment]
Hey, is it possible to call `kitty --listen-on` without opening a new window? or even start to listen on current window?

**Comment by kovidgoyal** [comment]
No, you have to specify listen-on on the first kitty invocation. If you
want to allow remote control for only specific windows use the launch
command with --alow-remote-control
