### ISSUE TITLE
Showing 'splits' layout is unknow and cannot convert flot to interger in border window_border_width.

### ISSUE THREAD

**Issue by z3n-k3rn3l** [kovidgoyal/kitty#3309]
**Describe the bug**
Kitty is showing below error in my config file

**Screenshots**
![image](https://user-images.githubusercontent.com/75212700/107796651-04c99e00-6d52-11eb-8723-d70095702630.png)

**Environment details**
OS: POP os Latest LTS edition

```
`Output of kitty --debug-config`
```
```
kitty 0.15.0 created by Kovid Goyal
Linux pop-os 5.8.0-7642-generic #47~1612288990~20.04~b8113e7-Ubuntu SMP Wed Feb 3 02:25:36 UTC 2 x86_64
Pop!_OS 20.04 LTS \n \l
DISTRIB_ID=Pop
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Pop!_OS 20.04 LTS"
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/ray/.config/kitty/kitty.conf
[043 16:48:52.359775] Ignoring unknown config key: force_ltr
[043 16:48:52.359908] Ignoring unknown config key: font_features
[043 16:48:52.360111] Ignoring unknown config key: cursor_beam_thickness
[043 16:48:52.360160] Ignoring unknown config key: cursor_underline_thickness
[043 16:48:52.360614] Ignoring unknown config key: url_prefixes
[043 16:48:52.360661] Ignoring unknown config key: detect_urls
[043 16:48:52.360793] Ignoring unknown config key: default_pointer_shape
[043 16:48:52.360839] Ignoring unknown config key: pointer_shape_when_dragging
[043 16:48:52.369698] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 351, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 324, in _main
    create_opts(args, debug_config=True)
  File "/usr/bin/../lib/kitty/kitty/cli.py", line 740, in create_opts
    opts = load_config(*config, overrides=overrides, accumulate_bad_lines=accumulate_bad_lines)
  File "/usr/bin/../lib/kitty/kitty/config.py", line 681, in load_config
    opts = _load_config(Options, defaults, parser, merge_configs, *paths, overrides=overrides)
  File "/usr/bin/../lib/kitty/kitty/conf/utils.py", line 181, in load_config
    vals = parse_config(f)
  File "/usr/bin/../lib/kitty/kitty/config.py", line 499, in parse_config
    parse_config_base(
  File "/usr/bin/../lib/kitty/kitty/conf/utils.py", line 116, in parse_config_base
    _parse(lines, type_map, special_handling, ans, all_keys, accumulate_bad_lines)
  File "/usr/bin/../lib/kitty/kitty/conf/utils.py", line 104, in _parse
    parse_line(line, type_map, special_handling, ans, all_keys, base_path_for_includes)
  File "/usr/bin/../lib/kitty/kitty/conf/utils.py", line 91, in parse_line
    val = tm(val)
  File "/usr/bin/../lib/kitty/kitty/config_data.py", line 563, in to_layout_names
    raise ValueError('The window layout {} is unknown'.format(p))
ValueError: The window layout splits is unknown
```
I will attach my config file to this github issue for your reference in txt format
[kitty.txt](https://github.com/kovidgoyal/kitty/files/5973223/kitty.txt)

**Comment by kovidgoyal** [comment]
Your version of  kitty is too old for the splits layout.

**Comment by z3n-k3rn3l** [comment]
Thanks a lot. Do Linux Mint have latest KItty avaiable..
