### ISSUE TITLE
`ValueError: could not convert string to float` when trying to launch

### ISSUE THREAD

**Issue by CheeseCrustery** [kovidgoyal/kitty#3442]
When using the official example config, kitty won't start.
```
user@user-debian:~/.config$ kitty
[095 10:14:07.892226] Ignoring unknown config key: force_ltr
[095 10:14:07.892327] Ignoring unknown config key: disable_ligatures
[095 10:14:07.892375] Ignoring unknown config key: font_features
[095 10:14:07.892542] Ignoring unknown config key: cursor_beam_thickness
[095 10:14:07.892578] Ignoring unknown config key: cursor_underline_thickness
[095 10:14:07.893039] Ignoring unknown config key: url_prefixes
[095 10:14:07.893081] Ignoring unknown config key: detect_urls
[095 10:14:07.893133] Ignoring unknown config key: strip_trailing_spaces
[095 10:14:07.893179] Ignoring unknown config key: terminal_select_modifiers
[095 10:14:07.893235] Ignoring unknown config key: pointer_shape_when_grabbed
[095 10:14:07.893264] Ignoring unknown config key: default_pointer_shape
[095 10:14:07.893291] Ignoring unknown config key: pointer_shape_when_dragging
[095 10:14:07.893399] Ignoring unknown config key: command_on_bell
[095 10:14:07.896893] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 276, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 264, in _main
    opts = create_opts(args)
  File "/usr/bin/../lib/kitty/kitty/cli.py", line 730, in create_opts
    opts = load_config(*config, overrides=overrides)
  File "/usr/bin/../lib/kitty/kitty/config.py", line 590, in load_config
    opts = _load_config(Options, defaults, parse_config, merge_configs, *paths, overrides=overrides)
  File "/usr/bin/../lib/kitty/kitty/conf/utils.py", line 171, in load_config
    vals = parse_config(f)
  File "/usr/bin/../lib/kitty/kitty/config.py", line 423, in parse_config
    check_keys=check_keys
  File "/usr/bin/../lib/kitty/kitty/conf/utils.py", line 103, in parse_config_base
    _parse(lines, type_map, special_handling, ans, all_keys)
  File "/usr/bin/../lib/kitty/kitty/conf/utils.py", line 96, in _parse
    parse_line(line, type_map, special_handling, ans, all_keys, base_path_for_includes)
  File "/usr/bin/../lib/kitty/kitty/conf/utils.py", line 84, in parse_line
    val = tm(val)
  File "/usr/bin/../lib/kitty/kitty/conf/utils.py", line 24, in positive_float
    return max(0, float(x))
ValueError: could not convert string to float: '0.5pt'
```

**To Reproduce**
Attempt to start kitty from terminal with the [sample config](https://sw.kovidgoyal.net/kitty/_downloads/433dadebd0bf504f8b008985378086ce/kitty.conf) provided in the documentation. The same error occurs when just `window_border_width 0.5pt` is set in the config. `kitty --config NONE` works fine.

**Environment details**
Debian 10, I3wm

**Output of kitty --debug-config**
```
kitty 0.13.3 created by Kovid Goyal
Linux jan-debian 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64
Running under: X11
Debian GNU/Linux 10 \n \l
Loaded config files: /home/jan/.config/kitty/kitty.conf
[095 10:20:11.115724] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 276, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 250, in _main
    create_opts(args, debug_config=True)
  File "/usr/bin/../lib/kitty/kitty/cli.py", line 730, in create_opts
    opts = load_config(*config, overrides=overrides)
  File "/usr/bin/../lib/kitty/kitty/config.py", line 590, in load_config
    opts = _load_config(Options, defaults, parse_config, merge_configs, *paths, overrides=overrides)
  File "/usr/bin/../lib/kitty/kitty/conf/utils.py", line 171, in load_config
    vals = parse_config(f)
  File "/usr/bin/../lib/kitty/kitty/config.py", line 423, in parse_config
    check_keys=check_keys
  File "/usr/bin/../lib/kitty/kitty/conf/utils.py", line 103, in parse_config_base
    _parse(lines, type_map, special_handling, ans, all_keys)
  File "/usr/bin/../lib/kitty/kitty/conf/utils.py", line 96, in _parse
    parse_line(line, type_map, special_handling, ans, all_keys, base_path_for_includes)
  File "/usr/bin/../lib/kitty/kitty/conf/utils.py", line 84, in parse_line
    val = tm(val)
  File "/usr/bin/../lib/kitty/kitty/conf/utils.py", line 24, in positive_float
    return max(0, float(x))
ValueError: could not convert string to float: '0.5pt'
```

**Comment by kovidgoyal** [comment]
Your version of kitty is ancient. Update. https://sw.kovidgoyal.net/kitty/binary.html
