### ISSUE TITLE
Panel kitty crashes with resize/geometry error

### ISSUE THREAD

**Issue by JakeStanger** [kovidgoyal/kitty#3459]
**Describe the bug**

Attempting to run the `panel` kitty causes the panel to render very briefly, before throwing a Python exception and crashing.

**To Reproduce**
1. Run `kitty +kitten panel sh -c 'printf "\n\n\nHello, world."; sleep 5s'`
2. See error:

```
[098 22:59:12.977904] MemoryError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 344, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 337, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 160, in __call__
    _run_app(opts, args, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 139, in _run_app
    boss.start(window_id)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 501, in start
    self.startup_first_child(first_os_window_id)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 183, in startup_first_child
    self.add_os_window(startup_session, os_window_id=os_window_id)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 208, in add_os_window
    tm = TabManager(os_window_id, self.opts, self.args, startup_session)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 502, in __init__
    self._add_tab(Tab(self, session_tab=t))
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 114, in __init__
    self.startup(session_tab)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 140, in startup
    self.new_special_window(cmd)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 337, in new_special_window
    return self.new_window(
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 321, in new_window
    self._add_window(window, location=location, overlay_for=overlay_for)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 295, in _add_window
    self.relayout()
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 192, in relayout
    self.current_layout(self.windows)
  File "/usr/bin/../lib/kitty/kitty/layout/base.py", line 307, in __call__
    self.do_layout(all_windows)
  File "/usr/bin/../lib/kitty/kitty/layout/tall.py", line 187, in do_layout
    self.layout_single_window_group(next(all_windows.iter_all_layoutable_groups()))
  File "/usr/bin/../lib/kitty/kitty/layout/base.py", line 320, in layout_single_window_group
    wg.set_geometry(geom)
  File "/usr/bin/../lib/kitty/kitty/window_list.py", line 100, in set_geometry
    w.set_geometry(geom)
  File "/usr/bin/../lib/kitty/kitty/window.py", line 463, in set_geometry
    self.screen.resize(new_geometry.ynum, new_geometry.xnum)
SystemError: <method 'resize' of 'fast_data_types.Screen' objects> returned a result with an error set
```

**Expected behavior**

The panel should stay open.

**Environment details**

Arch Linux, GNOME 40.

Three displays.

<details>
<summary>`xrandr` output</summary>

```
Screen 0: minimum 8 x 8, current 6400 x 1440, maximum 32767 x 32767
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 connected 1920x1080+4480+360 (normal left inverted right x axis y axis) 509mm x 286mm
   1920x1080     60.00*+  59.94    50.00  
   1680x1050     59.95  
   1440x900      59.89  
   1440x576      50.00  
   1440x480      59.94  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.94    59.93  
HDMI-0 connected (normal left inverted right x axis y axis)
   1280x720      60.00 +  59.94    50.00    29.97    23.98  
   4096x2160     59.94    50.00    29.97    25.00    24.00    23.98  
   3840x2160     59.94    50.00    29.97    25.00    23.98    23.98  
   1920x1080     59.94    50.00    29.97    25.00    23.98  
   720x576       50.00  
   720x480       59.94  
   640x480       59.94    59.93  
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 connected primary 2560x1440+1920+0 (normal left inverted right x axis y axis) 527mm x 296mm
   2560x1440     59.95*+
   1920x1200     59.88  
   1920x1080     60.00    59.94    59.93    50.00  
   1680x1050     59.95  
   1440x900      59.89  
   1366x768      59.79  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.94    59.93  
DP-4 disconnected (normal left inverted right x axis y axis)
DP-5 connected 1920x1080+0+360 (normal left inverted right x axis y axis) 477mm x 268mm
   1920x1080     60.00*+  59.94    50.00  
   1680x1050     59.95  
   1440x900      59.89  
   1360x768      60.02  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x720      60.00    59.94    50.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.94    59.93  

```
</details>

Output of kitty `-debug-config`

```
kitty 0.19.3 created by Kovid Goyal
Linux jessica 5.11.11-arch1-1 #1 SMP PREEMPT Tue, 30 Mar 2021 14:10:17 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/jake/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
active_border_color     Color(red=116, green=115, blue=105)
active_tab_background   Color(red=45, green=45, blue=45)
active_tab_foreground   Color(red=211, green=208, blue=200)
allow_remote_control    y
background              Color(red=45, green=45, blue=45)
bold_font               Jetbrains Mono Nerd Font Mono, Bold
color0                  Color(red=45, green=45, blue=45)
color1                  Color(red=242, green=119, blue=122)
color10                 Color(red=153, green=204, blue=153)
color11                 Color(red=255, green=204, blue=102)
color12                 Color(red=102, green=153, blue=204)
color13                 Color(red=204, green=153, blue=204)
color14                 Color(red=102, green=204, blue=204)
color15                 Color(red=211, green=208, blue=200)
color16                 Color(red=249, green=145, blue=87)
color17                 Color(red=210, green=123, blue=83)
color18                 Color(red=57, green=57, blue=57)
color19                 Color(red=81, green=81, blue=81)
color2                  Color(red=153, green=204, blue=153)
color20                 Color(red=160, green=159, blue=147)
color21                 Color(red=232, green=230, blue=223)
color3                  Color(red=255, green=204, blue=102)
color4                  Color(red=102, green=153, blue=204)
color5                  Color(red=204, green=153, blue=204)
color6                  Color(red=102, green=204, blue=204)
color7                  Color(red=211, green=208, blue=200)
color8                  Color(red=116, green=115, blue=105)
color9                  Color(red=242, green=119, blue=122)
cursor                  Color(red=211, green=208, blue=200)
cursor_shape            2
font_family             Jetbrains Mono Nerd Font Mono
font_size               12.0
foreground              Color(red=211, green=208, blue=200)
inactive_border_color   Color(red=57, green=57, blue=57)
inactive_tab_background Color(red=57, green=57, blue=57)
inactive_tab_foreground Color(red=160, green=159, blue=147)
selection_background    Color(red=211, green=208, blue=200)
selection_foreground    Color(red=45, green=45, blue=45)
url_color               Color(red=160, green=159, blue=147)
url_style               1
window_padding_width    FloatEdges(left=10.0, top=10.0, right=10.0, bottom=10.0)
```

**Additional context**
Occurs with `--config NONE`.

**Comment by kovidgoyal** [comment]
That doesnt repro it for me. Something unusual about your system? And I
just made a commit that will give a better error message in this
situation, so try to run from master.

**Comment by JakeStanger** [comment]
I guess my display setup is a little weird, but other than that I'm not doing anything I'd consider unusual.

I've just built and run the master version and tried to start the kitten from there:

```
[100 13:04:26.702691] Traceback (most recent call last):
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/main.py", line 328, in main
    _main()
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/main.py", line 321, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/main.py", line 171, in __call__
    _run_app(opts, args, bad_lines)
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/main.py", line 150, in _run_app
    boss.start(window_id)
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/boss.py", line 515, in start
    self.startup_first_child(first_os_window_id)
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/boss.py", line 184, in startup_first_child
    self.add_os_window(startup_session, os_window_id=os_window_id)
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/boss.py", line 213, in add_os_window
    tm = TabManager(os_window_id, self.opts, self.args, wclass, wname, startup_session)
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/tabs.py", line 546, in __init__
    self._add_tab(Tab(self, session_tab=t))
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/tabs.py", line 116, in __init__
    self.startup(session_tab)
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/tabs.py", line 143, in startup
    self.new_special_window(cmd)
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/tabs.py", line 379, in new_special_window
    return self.new_window(
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/tabs.py", line 363, in new_window
    self._add_window(window, location=location, overlay_for=overlay_for)
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/tabs.py", line 337, in _add_window
    self.relayout()
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/tabs.py", line 198, in relayout
    self.current_layout(self.windows)
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/layout/base.py", line 307, in __call__
    self.do_layout(all_windows)
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/layout/tall.py", line 187, in do_layout
    self.layout_single_window_group(next(all_windows.iter_all_layoutable_groups()))
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/layout/base.py", line 320, in layout_single_window_group
    wg.set_geometry(geom)
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/window_list.py", line 100, in set_geometry
    w.set_geometry(geom)
  File "/home/jake/Programming/kitty/kitty/launcher/../../kitty/window.py", line 464, in set_geometry
    self.screen.resize(new_geometry.ynum, new_geometry.xnum)
MemoryError
```

**Comment by kovidgoyal** [comment]
That will happen because the window size is incorrect, which in turn
will happen because monitor sizes are incorrect. Those come from glfw,
see the glfwgetvideomode function line 497 is x11_monitor.c

Most likely xrandrd is non-functional on your system. Fix that and you
should be fine.
