### ISSUE TITLE
Tests not passed with Python 3.10

### ISSUE THREAD

**Issue by tim77** [kovidgoyal/kitty#3712]
**Describe the bug**

```
test_multiprocessing_spawn (kitty_tests.tui.TestTUI) ... Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib64/kitty/__main__.py", line 133, in <module>
    main()
  File "/usr/bin/../lib64/kitty/__main__.py", line 124, in main
    namespaced(['+', first_arg[1:]] + sys.argv[2:])
  File "/usr/bin/../lib64/kitty/__main__.py", line 81, in namespaced
    func(args[1:])
  File "/usr/bin/../lib64/kitty/__main__.py", line 28, in runpy
    exec(args[1])
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib64/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/usr/lib64/python3.9/multiprocessing/queues.py", line 25, in <module>
    from . import connection
  File "/usr/lib64/python3.9/multiprocessing/connection.py", line 18, in <module>
    import tempfile
  File "/usr/lib64/python3.10/tempfile.py", line 45, in <module>
    from random import Random as _Random
  File "/usr/lib64/python3.10/random.py", line 58, in <module>
    import _random
ModuleNotFoundError: No module named '_random'
ERROR
test_word_trie (kitty_tests.unicode_input.TestUnicodeInput) ... ok
======================================================================
ERROR: test_multiprocessing_spawn (kitty_tests.tui.TestTUI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/kitty-0.20.3/kitty_tests/tui.py", line 48, in test_multiprocessing_spawn
    test_spawn()
    self = <kitty_tests.tui.TestTUI testMethod=test_multiprocessing_spawn>
    test_spawn = <function test_spawn at 0x3ffb74aaf80>
  File "/builddir/build/BUILD/kitty-0.20.3/kitty/multiprocessing.py", line 68, in test_spawn
    x = q.get(timeout=2)
    ctx = <multiprocessing.context.SpawnContext object at 0x3ffb85aecb0>
    get_context = <bound method DefaultContext.get_context of <multiprocessing.context.DefaultContext object at 0x3ffb85aece0>>
    p = <SpawnProcess name='SpawnProcess-1' pid=361855 parent=361832 stopped exitcode=1>
    q = <multiprocessing.queues.Queue object at 0x3ffb8ae4fa0>
  File "/usr/lib64/python3.10/multiprocessing/queues.py", line 114, in get
    raise Empty
    block = True
    deadline = 88209.015341977
    self = <multiprocessing.queues.Queue object at 0x3ffb8ae4fa0>
    timeout = 1.9999921470007394
_queue.Empty
----------------------------------------------------------------------
Ran 100 tests in 3.117s
FAILED (errors=1, skipped=2)
```

Full build log: https://kojipkgs.fedoraproject.org//work/tasks/9109/69919109/build.log

- Kitty version: 0.21.0
- OS: Fedora Rawhide (35)

**Comment by kovidgoyal** [comment]
Look at the traceback, it is indicating mixed 3.9 and 3.10 on your
system. Keep one and you should be fine.

**Comment by hroncok** [comment]
FTR this was caused by running tests on Python 3.10 with `/usr/bin/kitty` being the previously-built kitty with Python 3.9.

I plan to adapt the Fedora package to have the currently-built kitty on PATH instead of `/usr/bin/kitty` from the previous build.
