### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by xsrvmy** [kovidgoyal/kitty#386]
I am getting this error when launching:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 68, in <module>
    main()
  File "./__main__.py", line 61, in main
    from kitty.main import main
  File "./kitty/main.py", line 11, in <module>
    from .borders import load_borders_program
  File "./kitty/borders.py", line 8, in <module>
    from .fast_data_types import (
ImportError: ./kitty/fast_data_types.so: undefined symbol: hb_ft_font_changed
```
This is a fresh install.

**Comment by kovidgoyal** [comment]
Your version of harfbuzz is too old. Presumably you compiled kitty against a different harfbuzz. You need to use LD_LIBRARY_PATH to ensure that harfbuzz is loaded.

**Comment by Awea** [comment]
I get the same error when I try to launch Kitty builded with Harfbuzz 1.7.6 (I built it from the source, the apt version is not up-to-date).
