### ISSUE TITLE
Bug in kitty --help

### ISSUE THREAD

**Issue by kbd** [kovidgoyal/kitty#3869]
```shell
~$ kitty --help 
[207 15:21:09.164617] Traceback (most recent call last):
  File "lib/python3.9/kitty/main.py", line 344, in main
  File "lib/python3.9/kitty/main.py", line 314, in _main
  File "lib/python3.9/kitty/cli.py", line 748, in parse_args
  File "lib/python3.9/kitty/cli.py", line 517, in parse_cmdline
  File "lib/python3.9/kitty/cli.py", line 464, in needs_arg
  File "lib/python3.9/kitty/cli.py", line 319, in __call__
  File "lib/python3.9/kitty/cli.py", line 206, in prettify
  File "lib/python3.9/re.py", line 210, in sub
  File "lib/python3.9/kitty/cli.py", line 204, in sub
KeyError: 'envvar'

~$:1 kitty --version
kitty 0.22.0 created by Kovid Goyal
```

**Comment by chadcatlett** [comment]
I too got this error. Git bisect led me to [to this change.](https://github.com/kovidgoyal/kitty/commit/624991b9b7227acf3afe37fe9496a11b08f27c8c#diff-66ff0f56a093024dce520ef68a8d8df98ddd86f6808791f4426f42e04c1e8274R42) 

When [this line of code is executed](https://github.com/kovidgoyal/kitty/blob/624991b9b7227acf3afe37fe9496a11b08f27c8c/kitty/cli.py#L204) it tries to end a key named `envvar` but fails. The key `env` is present but not `envvar`.
