### ISSUE TITLE
wayland setCursorImage segmentation fault

### ISSUE THREAD

**Issue by Safari77** [kovidgoyal/kitty#4214]
**Describe the bug**
Nov 09 11:33:56 kernel: kitty[2319636]: segfault at 80000000c ip 00007582b04355de sp 00007ffd55439d60 error 4 in glfw-wayland.so[7582b0429000+1a000]

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007582b04355de in setCursorImage (window=window@entry=0x5428bb0, on_theme_change=on_theme_change@entry=false) at glfw/wl_window.c:130
130	       image = cursorWayland->cursor->images[cursorWayland->currentImage];
[Current thread is 1 (Thread 0x7582bf0d9740 (LWP 2319636))]
(gdb) bt
#0  0x00007582b04355de in setCursorImage (window=window@entry=0x5428bb0, on_theme_change=on_theme_change@entry=false) at glfw/wl_window.c:130
#1  0x00007582b0436d73 in _glfwPlatformSetCursor (window=0x5428bb0, cursor=<optimized out>) at glfw/wl_window.c:1384
#2  0x00007582b042cb9f in glfwSetCursor (windowHandle=<optimized out>, cursorHandle=<optimized out>) at glfw/input.c:1003
#3  0x00007582b1246adb in set_mouse_cursor (type=<optimized out>) at kitty/glfw.c:494
#4  0x00007582b12613fc in mouse_event (button=button@entry=-1, modifiers=4, action=action@entry=-1) at kitty/mouse.c:752
#5  0x00007582b1245eae in cursor_pos_callback (w=0x5428bb0, x=954, y=646) at kitty/glfw.c:334
#6  0x00007582b042be5c in _glfwInputCursorPos (window=<optimized out>, xpos=<optimized out>, ypos=<optimized out>) at glfw/input.c:384
#7  0x00007582b04325b8 in pointerHandleMotion (data=<optimized out>, pointer=<optimized out>, time=<optimized out>, sx=<optimized out>, sy=<optimized out>)
    at glfw/wl_init.c:185
#8  0x00007582b0825c04 in ffi_call_unix64 () at ../src/x86/unix64.S:76
#9  0x00007582b0825107 in ffi_call (cif=cif@entry=0x7ffd55439ff0, fn=<optimized out>, rvalue=<optimized out>, rvalue@entry=0x0, avalue=avalue@entry=0x7ffd5543a0c0)
    at ../src/x86/ffi64.c:525
#10 0x00007582b18bdd10 in wl_closure_invoke (closure=closure@entry=0x7a984d0, target=<optimized out>, target@entry=0x2052eb0, opcode=opcode@entry=2, data=<optimized out>, 
    flags=<optimized out>) at ../src/connection.c:1018
#11 0x00007582b18be42b in dispatch_event (display=display@entry=0x203d6b0, queue=<optimized out>, queue=<optimized out>) at ../src/wayland-client.c:1452
#12 0x00007582b18be61c in dispatch_queue (queue=0x203d780, display=0x203d6b0) at ../src/wayland-client.c:1598
#13 wl_display_dispatch_queue_pending (display=display@entry=0x203d6b0, queue=queue@entry=0x203d780) at ../src/wayland-client.c:1840
#14 0x00007582b18be670 in wl_display_dispatch_pending (display=display@entry=0x203d6b0) at ../src/wayland-client.c:1903
#15 0x00007582b04341de in handleEvents (timeout=-1) at glfw/wl_window.c:674
#16 0x00007582b0436b0e in _glfwPlatformWaitEvents () at glfw/wl_window.c:1170
#17 0x00007582b043357f in _glfwPlatformRunMainLoop (tick_callback=0x7582b12154d8 <process_global_state>, data=0x7582a4117730) at glfw/main_loop.h:30
#18 0x00007582b042b411 in glfwRunMainLoop (callback=<optimized out>, data=<optimized out>) at glfw/init.c:352
#19 0x00007582b12478fb in run_main_loop (cb=cb@entry=0x7582b12154d8 <process_global_state>, cb_data=cb_data@entry=0x7582a4117730) at kitty/glfw.c:1474
#20 0x00007582b12122ef in main_loop (self=0x7582a4117730, a=<optimized out>) at kitty/child-monitor.c:1097
#21 0x00007582bf3c6ff5 in method_vectorcall_NOARGS (func=<method_descriptor at remote 0x7582b186de00>, args=0x2005fa8, nargsf=<optimized out>, kwnames=0x0)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Objects/descrobject.c:434
#22 0x00007582bf3b75eb in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x2005fa8, callable=<method_descriptor at remote 0x7582b186de00>, 
    tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/cpython/abstract.h:118
#23 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x2005fa8, callable=<method_descriptor at remote 0x7582b186de00>)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/cpython/abstract.h:127
#24 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:5075
#25 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:3504
#26 0x00007582bf3b600d in _PyEval_EvalFrame (throwflag=0, 
    f=Frame 0x2005de0, for file /usr/bin/../lib64/kitty/kitty/main.py, line 426, in _run_app (opts=<Options(color_table=<array.array at remote 0x7582b05fecf0>, active_border_color=<kitty.fast_data_types.Color at remote 0x7582b0541090>, active_tab_background=<kitty.fast_data_types.Color at remote 0x7582b074f230>, active_tab_font_style=(True, True), active_tab_foreground=<kitty.fast_data_types.Color at remote 0x7582b074f290>, active_tab_title_template=None, adjust_baseline=0, adjust_column_width=0, adjust_line_height=0, allow_hyperlinks=3, allow_remote_control='n', background=<kitty.fast_data_types.Color at remote 0x7582b05410f0>, background_image=None, background_image_anchor='top-left', background_image_layout='tiled', background_image_linear=False, background_opacity=<float at remote 0x7582b0876870>, background_tint=0, bell_border_color=<kitty.fast_data_types.Color at remote 0x7582b0541050>, bell_on_tab=True, bell_path=None, bold_font='auto', bold_italic_font='auto', box_drawing_scale=(<float at remote 0x7582b0876...(truncated), tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/internal/pycore_ceval.h:40
#27 _PyEval_EvalCode (tstate=<optimized out>, _co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, 
    kwnames=0x0, kwargs=0x7582b05581f0, kwcount=0, kwstep=1, defs=0x7582b1952dd8, defcount=1, kwdefs=0x0, closure=0x0, name='_run_app', qualname='_run_app')
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:4327
#28 0x00007582bf3c3cee in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Objects/call.c:396
#29 0x00007582bf3b738c in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7582b05581d8, callable=<function at remote 0x7582b06000d0>, 
    tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/cpython/abstract.h:118
#30 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7582b05581d8, callable=<function at remote 0x7582b06000d0>)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/cpython/abstract.h:127
#31 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:5075
#32 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:3518
#33 0x00007582bf3b600d in _PyEval_EvalFrame (throwflag=0, 
    f=Frame 0x7582b0558040, for file /usr/bin/../lib64/kitty/kitty/main.py, line 187, in __call__ (self=<AppRunner(cached_values_name='main', first_window_callback=<function at remote 0x7582b0600160>, initial_window_size_func=<function at remote 0x7582b07375e0>) at remote 0x7582b1952e20>, opts=<Options(color_table=<array.array at remote 0x7582b05fecf0>, active_border_color=<kitty.fast_data_types.Color at remote 0x7582b0541090>, active_tab_background=<kitty.fast_data_types.Color at remote 0x7582b074f230>, active_tab_font_style=(True, True), active_tab_foreground=<kitty.fast_data_types.Color at remote 0x7582b074f290>, active_tab_title_template=None, adjust_baseline=0, adjust_column_width=0, adjust_line_height=0, allow_hyperlinks=3, allow_remote_control='n', background=<kitty.fast_data_types.Color at remote 0x7582b05410f0>, background_image=None, background_image_anchor='top-left', background_image_layout='tiled', background_image_linear=False, background_opacity=<float at remote 0x7582b0876870>, background_tint=0, be...(truncated), tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/internal/pycore_ceval.h:40
#34 _PyEval_EvalCode (tstate=<optimized out>, _co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, 
    kwnames=0x0, kwargs=0x7ffd5543a870, kwcount=0, kwstep=1, defs=0x7582b19529e8, defcount=1, kwdefs=0x0, closure=0x0, name='__call__', qualname='AppRunner.__call__')
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:4327
#35 0x00007582bf3c3cee in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Objects/call.c:396
#36 0x00007582bf3bf1d7 in _PyObject_FastCallDictTstate (tstate=0x1e691b0, callable=<function at remote 0x7582b0600280>, args=<optimized out>, nargsf=<optimized out>, 
    kwargs=<optimized out>) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Objects/call.c:118
#37 0x00007582bf3cb07c in _PyObject_Call_Prepend (tstate=0x1e691b0, callable=<function at remote 0x7582b0600280>, obj=<unknown at remote 0x7ffd5543a850>, 
    args=<optimized out>, kwargs=0x0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Objects/call.c:489
#38 0x00007582bf4687f2 in slot_tp_call (
    self=<AppRunner(cached_values_name='main', first_window_callback=<function at remote 0x7582b0600160>, initial_window_size_func=<function at remote 0x7582b07375e0>) at remote 0x7582b1952e20>, 
    args=(<Options(color_table=<array.array at remote 0x7582b05fecf0>, active_border_color=<kitty.fast_data_types.Color at remote 0x7582b0541090>, active_tab_background=<kitty.fast_data_types.Color at remote 0x7582b074f230>, active_tab_font_style=(True, True), active_tab_foreground=<kitty.fast_data_types.Color at remote 0x7582b074f290>, active_tab_title_template=None, adjust_baseline=0, adjust_column_width=0, adjust_line_height=0, allow_hyperlinks=3, allow_remote_control='n', background=<kitty.fast_data_types.Color at remote 0x7582b05410f0>, background_image=None, background_image_anchor='top-left', background_image_layout='tiled', background_image_linear=False, background_opacity=<float at remote 0x7582b0876870>, background_tint=0, bell_border_color=<kitty.fast_data_types.Color at remote 0x7582b0541050>, bell_on_tab=True, bell_path=None, bold_font='auto', bold_italic_font='auto', box_drawing_scale=(<float at remote 0x7582b08766d0>, <float at remote 0x7582b0876870>, <float at remote 0x7582b08769d0>, <float at remote 0...(truncated), kwds=0x0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Objects/typeobject.c:6718
#39 0x00007582bf3bf677 in _PyObject_MakeTpCall (tstate=0x1e691b0, 
    callable=<AppRunner(cached_values_name='main', first_window_callback=<function at remote 0x7582b0600160>, initial_window_size_func=<function at remote 0x7582b07375e0>) at remote 0x7582b1952e20>, args=<optimized out>, nargs=3, keywords=<optimized out>) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Objects/call.c:191
#40 0x00007582bf3bc14e in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x1edd678, callable=<optimized out>, tstate=0x1e691b0)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/cpython/abstract.h:116
#41 _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x1edd678, callable=<optimized out>, tstate=0x1e691b0)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/cpython/abstract.h:103
#42 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x1edd678, callable=<optimized out>)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/cpython/abstract.h:127
#43 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:5075
#44 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:3518
#45 0x00007582bf3c3fe3 in _PyEval_EvalFrame (throwflag=0,
f=Frame 0x1edd4b0, for file /usr/bin/../lib64/kitty/kitty/main.py, line 384, in _main (args=[], cwd_ok=True, cli_opts=<CLIOptions(cls='kitty', name=None, title=None, config=[], override=[], directory='.', detach=False, session=None, hold=False, single_instance=False, instance_group=None, wait_for_single_instance_window_close=False, listen_on=None, start_as='normal', version=False, dump_commands=False, replay_commands=None, dump_bytes=None, debug_rendering=False, debug_keyboard=False, debug_font_fallback=False, watcher=None, execute=False, args=[]) at remote 0x7582b1952310>, rest=[...], bad_lines=[], opts=<Options(color_table=<array.array at remote 0x7582b05fecf0>, active_border_color=<kitty.fast_data_types.Color at remote 0x7582b0541090>, active_tab_background=<kitty.fast_data_types.Color at remote 0x7582b074f230>, active_tab_font_style=(True, True), active_tab_foreground=<kitty.fast_data_types.Color at remote 0x7582b074f290>, active_tab_title_template=None, adjust_baseline=0, adjust_column_width=0, adjust_line...(truncated), tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/internal/pycore_ceval.h:40
#46 function_code_fastcall (tstate=0x1e691b0, co=<optimized out>, args=<optimized out>, nargs=0, globals=<optimized out>)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Objects/call.c:330
#47 0x00007582bf3b738c in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7582b19ec940, callable=<function at remote 0x7582b06008b0>, 
    tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/cpython/abstract.h:118
#48 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7582b19ec940, callable=<function at remote 0x7582b06008b0>)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/cpython/abstract.h:127
#49 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:5075
#50 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:3518
#51 0x00007582bf3c3fe3 in _PyEval_EvalFrame (throwflag=0, f=Frame 0x7582b19ec7c0, for file /usr/bin/../lib64/kitty/kitty/main.py, line 391, in main (), tstate=0x1e691b0)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/internal/pycore_ceval.h:40
#52 function_code_fastcall (tstate=0x1e691b0, co=<optimized out>, args=<optimized out>, nargs=0, globals=<optimized out>)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Objects/call.c:330
#53 0x00007582bf3b738c in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7582b1b1b548, callable=<function at remote 0x7582b0600940>, 
    tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/cpython/abstract.h:118
#54 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7582b1b1b548, callable=<function at remote 0x7582b0600940>)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/cpython/abstract.h:127
#55 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:5075
#56 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:3518
#57 0x00007582bf3c3fe3 in _PyEval_EvalFrame (throwflag=0, 
    f=Frame 0x7582b1b1b3c0, for file /usr/bin/../lib64/kitty/__main__.py, line 147, in main (first_arg='', func=None, kitty_main=<function at remote 0x7582b0600940>), 
    tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/internal/pycore_ceval.h:40
#58 function_code_fastcall (tstate=0x1e691b0, co=<optimized out>, args=<optimized out>, nargs=0, globals=<optimized out>)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Objects/call.c:330
#59 0x00007582bf3b738c in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7582b1973c90, callable=<function at remote 0x7582b1957ee0>, 
    tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/cpython/abstract.h:118
#60 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7582b1973c90, callable=<function at remote 0x7582b1957ee0>)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/cpython/abstract.h:127
#61 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:5075
#62 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:3518
#63 0x00007582bf3b600d in _PyEval_EvalFrame (throwflag=0, f=Frame 0x7582b1973b20, for file /usr/bin/../lib64/kitty/__main__.py, line 409, in <module> (), tstate=0x1e691b0)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/internal/pycore_ceval.h:40
#64 _PyEval_EvalCode (tstate=<optimized out>, _co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, 
    kwnames=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:4327
#65 0x00007582bf432635 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, 
    locals={'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <SourceFileLoader(name='__main__', path='/usr/bin/../lib64/kitty/__main__.py') at remote 0x7582b1a7fd90>, '__spec__': <ModuleSpec(name='__main__', loader=<...>, origin='/usr/bin/../lib64/kitty/__main__.py', loader_state=None, submodule_search_locations=None, _set_fileattr=True, _cached='/usr/bin/../lib64/kitty/__pycache__/__main__.cpython-39.pyc') at remote 0x7582b1a7f040>, '__annotations__': {}, '__builtins__': <module at remote--Type <RET> for more, q to quit, c to continue without paging--
 0x7582b1b79860>, '__file__': '/usr/bin/../lib64/kitty/__main__.py', '__cached__': '/usr/bin/../lib64/kitty/__pycache__/__main__.cpython-39.pyc', 'os': <module at remote 0x7582b1aab4f0>, 'sys': <module at remote 0x7582b1b707c0>, 'List': <_SpecialGenericAlias(_inst=False, _name='List', __origin__=<type at remote 0x7582bf5db380>, __slots__=None, _nparams=1, __doc__='A generic version of list.') at remote 0x7582b1970730>, 'icat': <function at remote 0x7582b19578b0>, 'list_fonts': <function at remote 0x7582b1957940...(truncated), args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, 
    name=0x0, qualname=0x0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:4359
#66 0x00007582bf4325cd in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, 
    kws=<optimized out>, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:4375
#67 0x00007582bf43257f in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:826
#68 0x00007582bf4380f3 in builtin_exec_impl (module=<optimized out>, 
    locals={'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <SourceFileLoader(name='__main__', path='/usr/bin/../lib64/kitty/__main__.py') at remote 0x7582b1a7fd90>, '__spec__': <ModuleSpec(name='__main__', loader=<...>, origin='/usr/bin/../lib64/kitty/__main__.py', loader_state=None, submodule_search_locations=None, _set_fileattr=True, _cached='/usr/bin/../lib64/kitty/__pycache__/__main__.cpython-39.pyc') at remote 0x7582b1a7f040>, '__annotations__': {}, '__builtins__': <module at remote 0x7582b1b79860>, '__file__': '/usr/bin/../lib64/kitty/__main__.py', '__cached__': '/usr/bin/../lib64/kitty/__pycache__/__main__.cpython-39.pyc', 'os': <module at remote 0x7582b1aab4f0>, 'sys': <module at remote 0x7582b1b707c0>, 'List': <_SpecialGenericAlias(_inst=False, _name='List', __origin__=<type at remote 0x7582bf5db380>, __slots__=None, _nparams=1, __doc__='A generic version of list.') at remote 0x7582b1970730>, 'icat': <function at remote 0x7582b19578b0>, 'list_fonts': <function at remote 0x7582b1957940...(truncated), 
    globals={'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <SourceFileLoader(name='__main__', path='/usr/bin/../lib64/kitty/__main__.py') at remote 0x7582b1a7fd90>, '__spec__': <ModuleSpec(name='__main__', loader=<...>, origin='/usr/bin/../lib64/kitty/__main__.py', loader_state=None, submodule_search_locations=None, _set_fileattr=True, _cached='/usr/bin/../lib64/kitty/__pycache__/__main__.cpython-39.pyc') at remote 0x7582b1a7f040>, '__annotations__': {}, '__builtins__': <module at remote 0x7582b1b79860>, '__file__': '/usr/bin/../lib64/kitty/__main__.py', '__cached__': '/usr/bin/../lib64/kitty/__pycache__/__main__.cpython-39.pyc', 'os': <module at remote 0x7582b1aab4f0>, 'sys': <module at remote 0x7582b1b707c0>, 'List': <_SpecialGenericAlias(_inst=False, _name='List', __origin__=<type at remote 0x7582bf5db380>, __slots__=None, _nparams=1, __doc__='A generic version of list.') at remote 0x7582b1970730>, 'icat': <function at remote 0x7582b19578b0>, 'list_fonts': <function at remote 0x7582b1957940...(truncated), source=<code at remote 0x7582b195b500>) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/bltinmodule.c:1026
#69 builtin_exec (module=<optimized out>, args=args@entry=0x1ea3cd0, nargs=<optimized out>)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/clinic/bltinmodule.c.h:396
#70 0x00007582bf3c42cc in cfunction_vectorcall_FASTCALL (func=<built-in method exec of module object at remote 0x7582b1b79860>, args=0x1ea3cd0, nargsf=<optimized out>, 
    kwnames=<optimized out>) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Objects/methodobject.c:430
#71 0x00007582bf3b738c in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x1ea3cd0, 
    callable=<built-in method exec of module object at remote 0x7582b1b79860>, tstate=0x1e691b0)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/cpython/abstract.h:118
#72 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x1ea3cd0, callable=<built-in method exec of module object at remote 0x7582b1b79860>)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/cpython/abstract.h:127
#73 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:5075
#74 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:3518
#75 0x00007582bf3b600d in _PyEval_EvalFrame (throwflag=0, 
    f=Frame 0x1ea3b10, for file /usr/lib64/python3.9/runpy.py, line 343, in _run_code (code=<code at remote 0x7582b195b500>, run_globals={'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <SourceFileLoader(name='__main__', path='/usr/bin/../lib64/kitty/__main__.py') at remote 0x7582b1a7fd90>, '__spec__': <ModuleSpec(name='__main__', loader=<...>, origin='/usr/bin/../lib64/kitty/__main__.py', loader_state=None, submodule_search_locations=None, _set_fileattr=True, _cached='/usr/bin/../lib64/kitty/__pycache__/__main__.cpython-39.pyc') at remote 0x7582b1a7f040>, '__annotations__': {}, '__builtins__': <module at remote 0x7582b1b79860>, '__file__': '/usr/bin/../lib64/kitty/__main__.py', '__cached__': '/usr/bin/../lib64/kitty/__pycache__/__main__.cpython-39.pyc', 'os': <module at remote 0x7582b1aab4f0>, 'sys': <module at remote 0x7582b1b707c0>, 'List': <_SpecialGenericAlias(_inst=False, _name='List', __origin__=<type at remote 0x7582bf5db380>, __slots__=None, _nparams=1, __doc__='A generic version ...(truncated), tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/internal/pycore_ceval.h:40
#76 _PyEval_EvalCode (tstate=<optimized out>, _co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, 
    kwnames=0x0, kwargs=0x1ec7ae0, kwcount=0, kwstep=1, defs=0x7582b1a2daa8, defcount=5, kwdefs=0x0, closure=0x0, name='_run_code', qualname='_run_code')
at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:4327
#77 0x00007582bf3c3cee in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Objects/call.c:396
#78 0x00007582bf3b738c in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x1ec7ab8, callable=<function at remote 0x7582b1938040>, tstate=0x1e691b0)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/cpython/abstract.h:118
#79 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x1ec7ab8, callable=<function at remote 0x7582b1938040>)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/cpython/abstract.h:127
#80 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:5075
#81 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:3518
#82 0x00007582bf3b600d in _PyEval_EvalFrame (throwflag=0, 
    f=Frame 0x1ec7910, for file /usr/lib64/python3.9/runpy.py, line 453, in _run_module_as_main (mod_name='__main__', alter_argv=False, mod_spec=<ModuleSpec(name='__main__', loader=<SourceFileLoader(name='__main__', path='/usr/bin/../lib64/kitty/__main__.py') at remote 0x7582b1a7fd90>, origin='/usr/bin/../lib64/kitty/__main__.py', loader_state=None, submodule_search_locations=None, _set_fileattr=True, _cached='/usr/bin/../lib64/kitty/__pycache__/__main__.cpython-39.pyc') at remote 0x7582b1a7f040>, code=<code at remote 0x7582b195b500>, main_globals={'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <...>, '__spec__': <...>, '__annotations__': {}, '__builtins__': <module at remote 0x7582b1b79860>, '__file__': '/usr/bin/../lib64/kitty/__main__.py', '__cached__': '/usr/bin/../lib64/kitty/__pycache__/__main__.cpython-39.pyc', 'os': <module at remote 0x7582b1aab4f0>, 'sys': <module at remote 0x7582b1b707c0>, 'List': <_SpecialGenericAlias(_inst=False, _name='List', __origin__=<type at remote 0x7582...(truncated), tstate=0x1e691b0) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Include/internal/pycore_ceval.h:40
#83 _PyEval_EvalCode (tstate=<optimized out>, _co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, 
    kwnames=0x0, kwargs=0x7582b1936868, kwcount=0, kwstep=1, defs=0x7582b1a7ec88, defcount=1, kwdefs=0x0, closure=0x0, name='_run_module_as_main', 
    qualname='_run_module_as_main') at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Python/ceval.c:4327
#84 0x00007582bf3c3cee in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Objects/call.c:396
#85 0x00007582bf452ac9 in pymain_run_module (modname=<optimized out>, set_argv0=<optimized out>) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Modules/main.c:291
#86 0x00007582bf32f91c in pymain_run_python (exitcode=0x7ffd5543b630) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Modules/main.c:595
#87 Py_RunMain () at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Modules/main.c:677
#88 0x00007582bf3a4e91 in Py_Main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/python3.9-3.9.7-1.fc34.x86_64/Modules/main.c:719
#89 0x0000000000401386 in main ()
(gdb) p *cursorWayland->cursor->images
Cannot access memory at address 0x80000000c
```

**To Reproduce**
I don't know, I was moving mupdf over the kitty terminal.

**Environment details**
Ctrl+Shift+F6 doesn't work, but I have kitty from git dated Nov 5.
gnome 40.6 on wayland, mesa 21.2.5.
xorg-x11-server-Xwayland-21.1.3-1 (Fedora 34)

**Comment by kovidgoyal** [comment]
same deal as #4156 I am going to need a reproducer or a trace built with make asan
