### ISSUE TITLE
Launching tab on master crashes kitty

### ISSUE THREAD

**Issue by amanjitsk** [kovidgoyal/kitty#4317]
**Describe the bug**
Launching a new tab crashes kitty

**To Reproduce**
1. Run `kitty @ launch --type=tab bash`
4. See error (kitty closes)

**Comment by page-down** [comment]
It seems to be related to the recently added window logo feature.

```c
WindowLogoRenderData *wl = &window->window_logo;
```

```text
kitty/shaders.c:873:41: runtime error: member access within null pointer of type 'Window'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior kitty/shaders.c:873:41 in 
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1029==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000048 (pc 0x0001071d7534 bp 0x7ffeece38d60 sp 0x7ffeece38ce0 T0)
==1029==The signal is caused by a READ memory access.
==1029==Hint: address points to the zero page.
    #0 0x1071d7534 in draw_cells shaders.c:874
    #1 0x106f5a145 in render_os_window child-monitor.c:683
    #2 0x106f526e2 in render child-monitor.c:778
    #3 0x106f4f288 in process_global_state child-monitor.c:1088
    #4 0x1083a9d23 in _glfwDispatchTickCallback cocoa_init.m:701
    #5 0x1083a9ca8 in -[GLFWApplication tick_callback] cocoa_init.m:415
...
```
