### ISSUE TITLE
Kitty does not working in Swaywm, OenGL issues

### ISSUE THREAD

**Issue by peterwilfride** [kovidgoyal/kitty#4436]
**Describe the bug**
I installed kitty in my system (that runs wayland) and when I try to start some errors appears in the terminal.

**To Reproduce**
- Install the software: `sudo pacman -S kitty`
- Start from terminal: `kitty`
- Copy the config file to my .config dir
- Get these erros:
```
[004 15:14:57.052983] Ignoring invalid config line: symbol_map
[004 15:14:57.053672] Ignoring invalid config line: font_features
[004 15:14:57.057761] Ignoring invalid config line: url_excluded_characters
[004 15:14:57.072410] Ignoring invalid config line: env
[004 15:14:57.072740] Ignoring invalid config line: watcher
[004 15:14:57.072954] Ignoring invalid config line: exe_search_path
[004 15:14:57.073966] Ignoring invalid config line: file_transfer_confirmation_bypass
[004 15:14:57.076765] Ignoring invalid config line: action_alias
[004 15:14:57.077068] Ignoring invalid config line: kitten_alias
[004 15:14:57.310455] [glfw error 65543]: EGL: Failed to create context: Arguments are inconsistent
[004 15:14:57.324287] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 401, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 394, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 197, in __call__
    _run_app(opts, args, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 170, in _run_app
    window_id = create_os_window(
ValueError: Failed to create GLFWwindow
```

**Screenshots**
![captura](https://user-images.githubusercontent.com/41086317/148106816-eee515ef-d1d0-4674-831c-048408e1ef33.PNG)

**I've tried**
- Install `glfw-wayland`
- Run `glxgears` and `glxinfo`, apparently nothing wrong with OpenGL

**Details**
OS: endevaouros
WM: Sway
Testing in VirtualBox with 3D acceleration enabled.

**Comment by page-down** [comment]
I remember that the version of OpenGL supported in VirtualBox is not enough.

You need to make sure that you are using software cpu rendering.

https://github.com/kovidgoyal/kitty/discussions/4241

**Comment by kovidgoyal** [comment]
kitty requires opengl 3.3 which is about a decade old at this point.
