### ISSUE TITLE
Weird hang after `git difftool -y`

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#4532]
**Describe the bug**

After pressing ESC out of `git difftool -y`, kitty did _not_ return to the prompt.  I was forced to CTRL+C out of it.

**To Reproduce**
1. `git difftool -y`
2. ESC

**Observed Behavior**

```
$ git difftool -y

^[^[^CException ignored in: <module 'threading' (/home/precor/.local/kitty.app/lib/kitty-extensions/python-lib.bypy.frozen/threading.pyc)>
Traceback (most recent call last):
  File "threading.py", line 1415, in _shutdown
  File "concurrent/futures/process.py", line 95, in _python_exit
  File "threading.py", line 1033, in join
  File "threading.py", line 1049, in _wait_for_tstate_lock
KeyboardInterrupt: 
```

Notice that I had to `CTRL+C`.

**Environment details**
```
kitty 0.24.1 created by Kovid Goyal
Linux byteevo-scm 5.13.0-25-generic #26~20.04.1-Ubuntu SMP Fri Jan 7 16:27:40 UTC 2022 x86_64
Ubuntu 20.04.3 LTS byteevo-scm /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
Running under:X11
Frozen: True
Paths:
  kitty: /home/precor/.local/kitty.app/bin/kitty
  base dir: /home/precor/.local/kitty.app/lib/kitty
  extensions dir: /home/precor/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config files:
  /home/precor/.config/kitty/kitty.conf
Loaded config overrides:
  include /home/precor/.config/kitty/themes/tomorrow_night_blue.conf

Config options different from defaults:
active_tab_font_style         (True, False)
adjust_line_height            1.05
allow_remote_control          y
enabled_layouts               ['tall', 'fat']
font_family                   Hack
inactive_tab_font_style       (True, False)
initial_window_height         (32, 'cells')
initial_window_width          (128, 'cells')
placement_strategy            top-left
remember_window_size          False
scrollback_pager_history_size 16777216
shell_integration             frozenset({'no-cursor'})
tab_bar_edge                  1
tab_bar_margin_height         TabBarMarginHeight(outer=8.0, inner=8.0)
tab_bar_margin_width          8.0
tab_bar_style                 custom
window_border_width           (1.0, 'px')
window_padding_width          FloatEdges(left=1.0, top=1.0, right=1.0, bottom=1.0)
window_resize_step_cells      1
window_resize_step_lines      1
Added shortcuts:
	f12 launch --stdin-source=@screen_scrollback --type=background gedit -
	ctrl+l combine : clear_terminal scrollback active : send_text normal,application \x0c
	ctrl+page_up previous_tab
	ctrl+page_down next_tab
Changed shortcuts:
	ctrl+tab next_window
	shift+ctrl+h launch --stdin-source=@screen_scrollback --stdin-add-formatting --type=overlay ${HOME}/.local/share/precor/kitty-scrollback-helper.sh @input-line-number -R
	shift+ctrl+enter new_window_with_cwd
	shift+ctrl+tab previous_window
Colors:
	background                    #001133   
	color1                        #ff9ca3   
	color10                       #d0f0a8   
	color11                       #ffedac   
	color12                       #badaff   
	color13                       #ebbaff   
	color14                       #99ffff   
	color15                       #fffefe   
	color2                        #d0f0a8   
	color3                        #ffedac   
	color4                        #badaff   
	color5                        #ebbaff   
	color6                        #99ffff   
	color7                        #fffefe   
	color8                        #696969   
	color9                        #ff9ca3   
	cursor                        #fffefe   
	foreground                    #fffefe   
	inactive_tab_background       #3e3e3e   
	inactive_tab_foreground       #9b9b9b   
	selection_background          #2b4f75   
	selection_foreground          #fffefe   
	tab_bar_background            #3e3e3e   
	tab_bar_margin_color          #3e3e3e   
```

**Additional context**

This is the first time this has ever happened.  This operation has reliably worked in the past without any issues.

**Comment by kovidgoyal** [comment]
Doesn't repro for me with those steps. And I am not sure what this has to
do with kitty. Do you mean you are using the diff kitten as the git
difftool? If so I need a proper reproduction scenario.

**Comment by salmankhilji** [comment]
Yes, I am using the diff kitten.  This might be a hard-to-catch timing related issue that does not repro 100% of the time.

**Comment by kovidgoyal** [comment]
Could be but without a repro there isnt much I can do to help. The diff kitten is single threaded once the diff is generated and highlighted, which is presumably when you pressed esc, so I dont see what timing related issue there could be there. If you pressed esc while the diff was still being calculated then possibly there could be an issue, in which case it should be possible to come up with a repro.

**Comment by kovidgoyal** [comment]
And note that if you do press esc before highlighting completes, the kitten will fully quit only after highlighting is done, this is because there is no way to abort threads in python safely.

**Comment by kovidgoyal** [comment]
And this will terminate the highlight worker process during exit, preventing the wait for highlighting to complete: https://github.com/kovidgoyal/kitty/commit/2c0ac895e6f762dfc761a4325160bcb970ae39fb
