### ISSUE TITLE
 segfault when the window size is too large

### ISSUE THREAD

**Issue by page-down** [kovidgoyal/kitty#4648]
**Describe the bug**
There seems to be a problem with sanitizing the window size.
Segfault when size is at maximum.

**To Reproduce**
1. `echo '{"window-size": [100000, 500]}' > ~/.cache/kitty/main.json`
2. `kitty --config=NONE`
3. `Segmentation fault`

**Screenshots**
n/a

**Environment details**
- kitty from master branch

**Additional context**

kitty/os_window_size.py
```python
def sanitize_window_size(x: Any) -> int:
    ans = int(x)
    return max(20, min(ans, 100000))
```

```text
kitty --config=NONE
AddressSanitizer:DEADLYSIGNAL
=================================================================
==13170==ERROR: AddressSanitizer: SEGV on unknown address ...
==13170==The signal is caused by a READ memory access.
==13170==Hint: address points to the zero page.
    ...
    #5 0x7f4c63794f64 in swapBuffersGLX glfw/glx_context.c:184
    #6 0x7f4c6373c110 in _glfwRefreshContextAttribs glfw/context.c:405
    #7 0x7f4c63754109 in glfwCreateWindow glfw/window.c:268
    #8 0x7f4c645bb7ab in create_os_window kitty/glfw.c:806
    ...
```

---

Also, do the following need to be addressed? I don't see any useful information.

```shell
make asan
kitty /usr/bin/true
```

```text
==13438==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 821674 byte(s) in 184 object(s) allocated from:
    #0 0x7f945a311bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f9459f089c7  (/lib/x86_64-linux-gnu/libpython3.8.so.1.0+0x25a9c7)

Direct leak of 5355 byte(s) in 255 object(s) allocated from:
    #0 0x7f945a29a3dd in strdup (/lib/x86_64-linux-gnu/libasan.so.5+0x963dd)
    #1 0x7f94530b2576  (<unknown module>)

Direct leak of 688 byte(s) in 2 object(s) allocated from:
    #0 0x7f945a311bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f9459ed6a08 in _Py_DecodeUTF8Ex (/lib/x86_64-linux-gnu/libpython3.8.so.1.0+0x228a08)
    #2 0x736b726f572f6368  (<unknown module>)

...

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f945a313947 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
    #1 0x7f9451e18efd  (.../kitty/fast_data_types.so+0xbf1efd)

...

SUMMARY: AddressSanitizer: 941436 byte(s) leaked in 581 allocation(s).
```

**Comment by kovidgoyal** [comment]
That's a crash in the OpenGL driver not kitty, I suppose I could know
one zero off the max size, but then its hard to know what the max size
OpenGL will tolerate is, anyway.

As for the leaks on exit, no python and asan cause these, they cant be
fixed in kitty. If there is an allocation in kitty code that is not
released on exit, then yes it needs to be fixed.

**Comment by page-down** [comment]
Thanks for the explanation.
It also seems to be related to different drivers, it is indeed unresolvable.
