### ISSUE TITLE
Tests failing on macOS 10.13.6

### ISSUE THREAD

**Issue by toonn** [kovidgoyal/kitty#4652]
**Describe the bug**
When trying to build Kitty I encounter three failing tests:

```
======================================================================
ERROR: test_path_mapping_receive (kitty_tests.file_transmission.TestFileTransmission)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/nix-build-kitty-0.24.2.drv-0/source/kitty_tests/file_transmission.py", line 413, in test_path_mapping_receive
    tf([b/'r', b/'d'], {b/'r': b/'r', b/'d': b/'d', b/'d'/'r': b/'d'/'r'})
    am = <function TestFileTransmission.test_path_mapping_receive.<locals>.am at 0x1134b2280>
    b = PosixPath('/private/tmp/nix-build-kitty-0.24.2.drv-0/tmpe5oub4je/b')
    gm = <function TestFileTransmission.test_path_mapping_receive.<locals>.gm at 0x1134b21f0>
    opts = <kitty.cli_stub.CLIOptions object at 0x113488c40>
    self = <kitty_tests.file_transmission.TestFileTransmission testMethod=test_path_mapping_receive>
    tf = <function TestFileTransmission.test_path_mapping_receive.<locals>.tf at 0x1134a9f70>
  File "/private/tmp/nix-build-kitty-0.24.2.drv-0/source/kitty_tests/file_transmission.py", line 404, in tf
    files, specs = gm(all_specs)
    all_specs = [PosixPath('/private/tmp/nix-build-kitty-0.24.2.drv-0/tmpe5oub4je/b/r'), PosixPath('/private/tmp/nix-build-kitty-0.24.2.drv-0/tmpe5oub4je/b/d')]
    am = <function TestFileTransmission.test_path_mapping_receive.<locals>.am at 0x1134b2280>
    args = [PosixPath('/private/tmp/nix-build-kitty-0.24.2.drv-0/tmpe5oub4je/b/r'), PosixPath('/private/tmp/nix-build-kitty-0.24.2.drv-0/tmpe5oub4je/b/d')]
    dest = ''
    different_home = ''
    expected = {PosixPath('/private/tmp/nix-build-kitty-0.24.2.drv-0/tmpe5oub4je/b/r'): PosixPath('/private/tmp/nix-build-kitty-0.24.2.drv-0/tmpe5oub4je/b/r'), PosixPath('/private/tmp/nix-build-kitty-0.24.2.drv-0/tmpe5oub4je/b/d'): PosixPath('/private/tmp/nix-build-kitty-0.24.2.drv-0/tmpe5oub4je/b/d'), PosixPath('/private/tmp/nix-build-kitty-0.24.2.drv-0/tmpe5oub4je/b/d/r'): PosixPath('/private/tmp/nix-build-kitty-0.24.2.drv-0/tmpe5oub4je/b/d/r')}
    gm = <function TestFileTransmission.test_path_mapping_receive.<locals>.gm at 0x1134b21f0>
    opts = <kitty.cli_stub.CLIOptions object at 0x113488c40>
    self = <kitty_tests.file_transmission.TestFileTransmission testMethod=test_path_mapping_receive>
  File "/private/tmp/nix-build-kitty-0.24.2.drv-0/source/kitty_tests/file_transmission.py", line 393, in gm
    raise x
    all_specs = [PosixPath('/private/tmp/nix-build-kitty-0.24.2.drv-0/tmpe5oub4je/b/r'), PosixPath('/private/tmp/nix-build-kitty-0.24.2.drv-0/tmpe5oub4je/b/d')]
    files = []
    specs = [('0', '/private/tmp/nix-build-kitty-0.24.2.drv-0/tmpe5oub4je/b/r'), ('1', '/private/tmp/nix-build-kitty-0.24.2.drv-0/tmpe5oub4je/b/d')]
    x = TransmissionError('No permission to read spec')
kitty.file_transmission.TransmissionError: No permission to read spec

======================================================================
FAIL: test_file_get (kitty_tests.file_transmission.TestFileTransmission)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/nix-build-kitty-0.24.2.drv-0/source/kitty_tests/file_transmission.py", line 170, in test_file_get
    self.ae(len(files), 6)
    cwd = '/private/tmp/nix-build-kitty-0.24.2.drv-0/tmp8pzcbqum/cwd'
    f = <_io.TextIOWrapper name='/private/tmp/nix-build-kitty-0.24.2.drv-0/tmp8pzcbqum/home/a' mode='w' encoding='UTF-8'>
    f2 = <_io.TextIOWrapper name='/private/tmp/nix-build-kitty-0.24.2.drv-0/tmp8pzcbqum/home/ad/b' mode='w' encoding='UTF-8'>
    files = {}
    ft = <kitty.file_transmission.TestFileTransmission object at 0x113488280>
    home = '/private/tmp/nix-build-kitty-0.24.2.drv-0/tmp8pzcbqum/home'
    quiet = 2
    self = <kitty_tests.file_transmission.TestFileTransmission testMethod=test_file_get>
AssertionError: 0 != 6

======================================================================
FAIL: test_file_put (kitty_tests.file_transmission.TestFileTransmission)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/nix-build-kitty-0.24.2.drv-0/source/kitty_tests/file_transmission.py", line 329, in test_file_put
    self.ae(st.st_mtime_ns, 13000)
    c = <zlib.Compress object at 0x1134ac450>
    dest = '/private/tmp/nix-build-kitty-0.24.2.drv-0/tmp4hwf7fiy/2.bin'
    f = <_io.TextIOWrapper name='/private/tmp/nix-build-kitty-0.24.2.drv-0/tmp7gskhpwh/3' mode='r' encoding='UTF-8'>
    fid = 1
    ft = <kitty.file_transmission.TestFileTransmission object at 0x113488fd0>
    one = '/private/tmp/nix-build-kitty-0.24.2.drv-0/tmp7gskhpwh/1'
    quiet = 2
    self = <kitty_tests.file_transmission.TestFileTransmission testMethod=test_file_put>
    send = <function TestFileTransmission.test_file_put.<locals>.send at 0x1134b2280>
    st = os.stat_result(st_mode=33279, st_ino=308070476, st_dev=16777219, st_nlink=1, st_uid=501, st_gid=0, st_size=3, st_atime=0, st_mtime=0, st_ctime=1644237784)
    three = '/private/tmp/nix-build-kitty-0.24.2.drv-0/tmp7gskhpwh/3'
    two = '/private/tmp/nix-build-kitty-0.24.2.drv-0/tmp7gskhpwh/2'
AssertionError: 0 != 13000

----------------------------------------------------------------------
Ran 118 tests in 24.039s

FAILED (failures=2, errors=1, skipped=3)
```

I am not sure what the permission problem could be and I'm not sure what is being asserted in the other two cases.

**To Reproduce**
I am trying to build Kitty using Nix on macOS 10.13.6. This is an x86_64 machine, which means Nix is using the 10.12 SDK. (On aarch64 the 11.0 SDK is used.)

**Additional context**
Because of #4576 I figured I would be able to build Kitty again but I still run into failing tests.

**Comment by kovidgoyal** [comment]
This doesnt have anything to do with macOS version, it will be caused by nix. Just build kitty directly without nix and you will be fine. I dont have the time/interest to debug nix issues, but maybe @Luflosi can help you.

**Comment by Luflosi** [comment]
The tests pass on my machine when using Nix. I'm running macOS 10.15.7. I checked out the latest commit 3c709a28f78718a60b6b4881eacb03ec9dec959f, executed `nix-shell --pure`, then `make clean`, `make` and finally `make test`. All tests passed.
Your second failing test seems to suggest that file transmission isn't working, as apparently no files were transferred, while the third test fails because the modification time of a file wasn't set correctly after a file transmission.

**Comment by toonn** [comment]
Here's the [Hydra log](https://hydra.nixos.org/build/166828722/nixlog/1) showing the same errors. @Luflosi, any idea what to look for? I briefly looked at these tests but there's a lot of setup and I'm not really sure what's going wrong.
