### ISSUE TITLE
Kitty 0.24.3 breaks diff kitten getting called by fzf

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#4763]
**Describe the bug**

The diff kitten can no longer be called from within `fzf` in kitty `0.24.3`.
Works correctly in `0.24.2`.
Manually calling the kitten from the command line is still working correctly in `0.24.3`

**To Reproduce**
1. Install `fzf`.  (I have version `0.29.0 (dc975e8)` if that matters.)
2. Save the following script, and `chmod +x` it.

    ```sh
    #!/bin/sh
    
    SUBDIRECTORY_OK=Yes
    . "$(git --exec-path)/git-sh-setup"
    
    get_hash="sed -nr 's/^([a-f0-9]+).*/\1/p'"
    
    git log --color=always --format="%C(auto)%h %s %C(cyan)%C(bold)%cr" "$@" |
    fzf --ansi --layout=reverse --no-multi --no-sort --tiebreak=index --no-hscroll \
      --preview="echo -n {} | $get_hash | xargs -I % git show --color=always --name-only %" \
      --preview-window="right,50%,border-vertical" \
      --bind "space:execute:echo -n {} | $get_hash | xargs -I % git difftool --no-symlinks --dir-diff %^..% "$([ $# = 1 ] && echo "$@")" " |
    eval "$get_hash"
    ```

3. Go to some valid Git repo.
4. Execute the above script.
5. Using the up/down arrow keys, select a commit hash.
6. Press Space bar, which is bound to invoking `git difftool`, which in my machine is pointing to `kitty +kitten diff`.

**Observed Behavior**

The execution of the kitten fails and causes some spew, which gets hidden behind the updated `fzf` window.  Press ESC to exit `fzf` and observe the following spew from kitty:

```
$ git browse-commit
Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "kitty_main.py", line 184, in <module>
  File "kitty_main.py", line 175, in main
  File "kitty_main.py", line 128, in namespaced
  File "kitty_main.py", line 111, in run_kitten
  File "kittens/runner.py", line 120, in run_kitten
  File "runpy.py", line 213, in run_module
  File "runpy.py", line 87, in _run_code
  File "kittens/diff/main.py", line 682, in <module>
  File "kittens/diff/main.py", line 666, in main
  File "kittens/tui/loop.py", line 472, in loop
  File "kittens/tui/loop.py", line 475, in _report_error_loop
  File "kittens/tui/loop.py", line 436, in loop_impl
  File "kitty/utils.py", line 176, in __call__
  File "kitty/utils.py", line 158, in read_screen_size
OSError: [Errno 25] Inappropriate ioctl for device
```

**Expected Behavior**

Press Space bar shall correctly invoke the diff kitten like it used to in version prior to `0.24.3`.

**Environment details**
```
kitty 0.24.3 created by Kovid Goyal
Linux byteevo-scm 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64
Ubuntu 20.04.4 LTS byteevo-scm /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/precor/.local/kitty.app/bin/kitty
  base dir: /home/precor/.local/kitty.app/lib/kitty
  extensions dir: /home/precor/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config files:
  /home/precor/.config/kitty/kitty.conf
Loaded config overrides:
  include /home/precor/.config/kitty/themes/tomorrow_night_blue.conf

Config options different from defaults:
active_tab_font_style         (True, False)
adjust_line_height            1.05
allow_remote_control          y
enabled_layouts               ['tall', 'fat']
font_family                   Hack
inactive_tab_font_style       (True, False)
initial_window_height         (32, 'cells')
initial_window_width          (128, 'cells')
placement_strategy            top-left
remember_window_size          False
scrollback_pager_history_size 16777216
shell_integration             frozenset({'disabled'})
tab_bar_edge                  1
tab_bar_margin_height         TabBarMarginHeight(outer=8.0, inner=8.0)
tab_bar_margin_width          8.0
tab_bar_style                 custom
window_border_width           (1.0, 'px')
window_padding_width          FloatEdges(left=1.0, top=1.0, right=1.0, bottom=1.0)
window_resize_step_cells      1
window_resize_step_lines      1
Added shortcuts:
	f9 → launch --type=background --cwd=current sh -c "xdg-open $(pwd)"
	f12 → launch --stdin-source=@screen_scrollback --type=background gedit -
	ctrl+l → combine : clear_terminal scrollback active : send_text normal,application \x0c
	ctrl+page_up → previous_tab
	ctrl+page_down → next_tab
Changed shortcuts:
	ctrl+tab → next_window
	ctrl+shift+h → launch --stdin-source=@screen_scrollback --stdin-add-formatting --type=overlay ${HOME}/.local/share/precor/kitty-scrollback-helper.sh @input-line-number -R
	ctrl+shift+enter → new_window_with_cwd
	ctrl+shift+tab → previous_window
Colors:
	background                    #001133   
	color1                        #ff9ca3   
	color10                       #d0f0a8   
	color11                       #ffedac   
	color12                       #badaff   
	color13                       #ebbaff   
	color14                       #99ffff   
	color15                       #fffefe   
	color2                        #d0f0a8   
	color3                        #ffedac   
	color4                        #badaff   
	color5                        #ebbaff   
	color6                        #99ffff   
	color7                        #fffefe   
	color8                        #696969   
	color9                        #ff9ca3   
	cursor                        #fffefe   
	foreground                    #fffefe   
	inactive_tab_background       #3e3e3e   
	inactive_tab_foreground       #9b9b9b   
	selection_background          #2b4f75   
	selection_foreground          #fffefe   
	tab_bar_background            #3e3e3e   
	tab_bar_margin_color          #3e3e3e   

Important environment variables seen by the kitty process:
	PATH                                /opt/qt/5.15.2/gcc_64/bin:/home/precor/Android/Sdk/build-tools/30.0.3:/home/precor/Android/Sdk/emulator:/home/precor/Android/Sdk/platform-tools:/home/precor/Android/Sdk/cmdline-tools/latest/bin:/home/precor/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/precor/.local/flutter/bin:/home/precor/.pub-cache/bin
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                precor
	XDG_SESSION_TYPE                    x11
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_MENU_PREFIX                     gnome-
	XDG_CURRENT_DESKTOP                 ubuntu:GNOME
	XDG_SESSION_DESKTOP                 ubuntu
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-ubuntu:/etc/xdg
	XDG_DATA_DIRS                       /usr/share/ubuntu:/usr/local/share/:/usr/share/
```

**Additional context**
.gitconfig
```
[user]
	name = Salman A. Khilji
	email = salman@example.com
[fetch]
	prune = true
[log]
	decorate = no
[color]
	ui = auto
[color "status"]
	branch = green
[diff]
	tool = kitty
	guitool = kitty.gui
	trustExitCode = true
[difftool "kitty"]
	cmd = kitty +kitten diff $LOCAL $REMOTE
[difftool "kitty.gui"]
	cmd = kitty --start-as=fullscreen kitty +kitten diff $LOCAL $REMOTE
[credential]
	helper = /usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret
```

**Comment by kovidgoyal** [comment]
There haven't been any changes to the diff kitten in 0.24.3. Can you
come up with a less complex reproducer.

**Comment by kovidgoyal** [comment]
Your error message indicates that the kitten is being called in a context where the tty device is being removed. I doubt this has anything to do with the kitten. And I'm afraid I dont feel like debugging fzf, sorry. You can probably work around it by running the difftool in a new kitty window.
