### ISSUE TITLE
$PYTHONWARNINGS=default causes hints kitten to fail

### ISSUE THREAD

**Issue by inducer** [kovidgoyal/kitty#482]
Setting `$PYTHONWARNINGS` to `default` (to get that extra dose of Python warnings) leads the JSON received from the hints kitten to be this (yes, including the warning):

```
{"match": "pants-cold.html", "program": "-"}sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/tty' mode='r' encoding='UTF-8'>
```

The JSON parser is pretty unhappy with that:

```
Traceback (most recent call last):
  File "/home/andreas/pack/kitty/kitty/boss.py", line 256, in on_child_death
    window.action_on_close(window)
  File "/home/andreas/pack/kitty/kitty/boss.py", line 516, in on_kitten_finish
    data = json.loads(json_data)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 45 (char 44)
```

**Comment by inducer** [comment]
Thanks!
