### ISSUE TITLE
`kitty --start-as=fullscreen +open` cannot work

### ISSUE THREAD

**Issue by Freed-Wu** [kovidgoyal/kitty#4885]
**Describe the bug**
fullscreen conflict with `+open`

**To Reproduce**
1. `kitty --start-as=fullscreen +open a.txt`

```
Failed to launch child: +open
With error: No such file or directory
Press Enter to exit.
```

**Environment details**

```
kitty 0.24.4 created by Kovid Goyal
Linux desktop 5.16.15-arch1-1 #1 SMP PREEMPT Thu, 17 Mar 2022 00:30:09 +0000 x86_64
Arch Linux 5.16.15-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/wzy/.config/kitty/kitty-desktop.conf

Config options different from defaults:
background_opacity         0.75
bold_font                  JetBrains Mono Bold Nerd Font Complete Mono
bold_italic_font           JetBrains Mono Bold Italic Nerd Font Complete Mono
dynamic_background_opacity True
font_family                JetBrains Mono Regular Nerd Font Complete Mono
font_features:
{'FiraCode-Regular': ('+ss06', '+ss07')}
font_size                  15.0
italic_font                JetBrains Mono Italic Nerd Font Complete Mono
tab_bar_style              powerline
Added shortcuts:
	shift+enter → send_text all \x1b[13;2u
	ctrl+enter → send_text all \x1b[13;5u
	ctrl+shift+space → next_tab
	ctrl+shift+d → scroll_page_down
Changed shortcuts:
	ctrl+shift+g → scroll_home
	ctrl+shift+u → scroll_page_up
	ctrl+shift+z → scroll_end

Important environment variables seen by the kitty process:
	PATH                                /home/wzy/.local/bin:/home/wzy/Applications:/home/wzy/.local/bin:/home/wzy/.local/share/nautilus/scripts:/usr/local/bin:/usr/bin:/usr/local/sbin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin
	LANG                                en_US.UTF-8
	VISUAL                              vi
	EDITOR                              vi
	SHELL                               /usr/bin/zsh
	GLFW_IM_MODULE                      ibus
	DISPLAY                             :1
	USER                                wzy
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
```

**Comment by kovidgoyal** [comment]
I dont know what +open is. If you want to opena  text file use

kitty --start-as fullscreen vim file.txt

replace vim with whatever editor you want.

**Comment by page-down** [comment]
You can also run

kitty +open --start-as fullscreen file:///abs/path/to/file.txt

**Comment by kovidgoyal** [comment]
Ah you were trying to use launch actions. Yes, in that case +open needs to be immediately after kitty. See 

kitty +open --help

**Comment by Freed-Wu** [comment]
`kitty -<Tab>` can display the completion of options (in zsh), however, `kitty +open -<Tab>` cannot display any completion of options. Is it a bug?

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/73cdd87d919fe8c9f4ae7d0710b750a735215f56

**Comment by Freed-Wu** [comment]
Now `kitty +open main.sh` -- main.sh is any simple shell script -- will get this error. However, `kitty +open main.txt` will correctly use vi to open the text file.

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 185, in <module>
    main()
  File "/usr/bin/../lib/kitty/__main__.py", line 176, in main
    namespaced(['+', first_arg[1:]] + sys.argv[2:])
  File "/usr/bin/../lib/kitty/__main__.py", line 129, in namespaced
    func(args[1:])
  File "/usr/bin/../lib/kitty/__main__.py", line 100, in shebang
    os.execvp(cmd[0], cmd + [script_path])
  File "/usr/lib/python3.10/os.py", line 574, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.10/os.py", line 597, in _execvpe
    exec_func(file, *argrest)
FileNotFoundError: [Errno 2] No such file or directory

Press Enter or Esc to exit
```

**Comment by kovidgoyal** [comment]
Works for me.

**Comment by Freed-Wu** [comment]
I try to
```diff -u os.py /usr/lib/python3.10/os.py
--- os.py	2022-05-24 00:14:12.311035193 +0800
+++ /usr/lib/python3.10/os.py	2022-05-24 00:14:39.934385809 +0800
@@ -594,6 +594,7 @@
         env = environ
 
     if path.dirname(file):
+        print(file, *argrest)
         exec_func(file, *argrest)
         return
     saved_exc = None
```

and get:

```
[/usr/bin/zsh] ['[/usr/bin/zsh]', 'a.sh']
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 185, in <module>
    main()
  File "/usr/bin/../lib/kitty/__main__.py", line 176, in main
    namespaced(['+', first_arg[1:]] + sys.argv[2:])
  File "/usr/bin/../lib/kitty/__main__.py", line 129, in namespaced
    func(args[1:])
  File "/usr/bin/../lib/kitty/__main__.py", line 100, in shebang
    os.execvp(cmd[0], cmd + [script_path])
  File "/usr/lib/python3.10/os.py", line 574, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.10/os.py", line 598, in _execvpe
    exec_func(file, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
```

What happened?
