### ISSUE TITLE
Default config throws some errors

### ISSUE THREAD

**Issue by ahmedelgabri** [kovidgoyal/kitty#499]
By just copying & pasting the default config file [here](https://github.com/kovidgoyal/kitty/blob/78002cf3baa458d9fe7f845a0dac9e38d9adb972/kitty/kitty.conf) to `~.config/kitty/kitty.conf` without any modification & trying to run `kitty` I get this error:

```
$ /Applications/kitty.app/Contents/MacOS/kitty
[117 13:20:38.982278] Ignoring unknown config key: kitty_mod

[117 13:20:38.982597] Traceback (most recent call last):
  File "kitty/config.py", line 59, in parse_mods
AttributeError: module 'kitty.fast_data_types' has no attribute 'GLFW_MOD_KITTY_MOD'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kitty/main.py", line 186, in main
  File "kitty/main.py", line 174, in _main
  File "kitty/cli.py", line 574, in create_opts
  File "kitty/config.py", line 459, in load_config
  File "kitty/config.py", line 377, in parse_config
  File "kitty/config_utils.py", line 79, in parse_config_base
  File "kitty/config_utils.py", line 72, in _parse
  File "kitty/config_utils.py", line 41, in parse_line
  File "kitty/config.py", line 348, in special_handling
  File "kitty/config.py", line 151, in parse_key
  File "kitty/config.py", line 84, in parse_shortcut
  File "kitty/config.py", line 62, in parse_mods
AttributeError: 'list' object has no attribute 'join'


[1]    8335 exit 1     /Applications/kitty.app/Contents/MacOS/kitty
```

I had to remove these options to make it run:

- `open_url_modifiers`
- the whole keyboard shortcuts section

Then it ran with this warning:

`[117 13:22:38.731097] Ignoring unknown config key: macos_hide_from_tasks`

**Comment by SolitudeSF** [comment]
this options are implemented on master. you, most likely, running stable.
[here is config for 0.9.0](https://github.com/kovidgoyal/kitty/blob/v0.9.0/kitty/kitty.conf)

**Comment by kovidgoyal** [comment]
Dont copy/paste kitty.conf from the repo unless you are running from master. Instead, press ctrl+shift+f2 to edit kitty.conf.

**Comment by ahmedelgabri** [comment]
@SolitudeSF that's true, I just installed `0.9.0` from homebrew cask, thanks!

Thanks @kovidgoyal 👍

**Comment by wgmayer0** [comment]
What is the root cause of this issue? I am getting:

```
[124 13:30:46.867451] Ignoring unknown config key: kitty
```

When I run `kitty`. What is causing this? Something in my settings? I don't want to lose all the settings I have and they are quite lengthy.

<details>
  <summary>Click to see `kitty.conf`</summary>
  
```
clear_all_shortcuts no
font_family      DejaVuSansMono.ttf
bold_font        DejaVuSansMono-Bold.ttf
italic_font      DejaVuSansMono-Oblique.ttf
bold_italic_font DejaVuSansMono-BoldOblique.ttf
font_size 24.0
force_ltr no
adjust_line_height  0
adjust_column_width 0
adjust_baseline 0
disable_ligatures never
box_drawing_scale 0.001, 1, 1.5, 2
cursor #ffffff
cursor_text_color #000000
cursor_shape block
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0
cursor_blink_interval 0
cursor_stop_blinking_after 0
scrollback_lines 2000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
scrollback_pager_history_size 0
scrollback_fill_enlarged_window no
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 1.0
mouse_hide_wait 3.0
url_color #ffffff
url_style single
open_url_with default
url_prefixes http https file ftp gemini irc gopher mailto news git
detect_urls yes
copy_on_select yes
strip_trailing_spaces always
select_by_word_characters @-./_~?&=%+#
click_interval -1.0
focus_follows_mouse no
pointer_shape_when_grabbed arrow
default_pointer_shape beam
pointer_shape_when_dragging beam
clear_all_mouse_actions yes
mouse_map left            click ungrabbed mouse_click_url_or_select
mouse_map shift+left      click grabbed,ungrabbed mouse_click_url_or_select
mouse_map ctrl+shift+left release grabbed,ungrabbed mouse_click_url
mouse_map ctrl+shift+left press grabbed discard_event
mouse_map middle        release ungrabbed paste_from_selection
mouse_map left          press ungrabbed mouse_selection normal
mouse_map ctrl+alt+left press ungrabbed mouse_selection rectangle
mouse_map left          doublepress ungrabbed mouse_selection word
mouse_map left          triplepress ungrabbed mouse_selection line
mouse_map ctrl+alt+left triplepress ungrabbed mouse_selection line_from_point
mouse_map right press ungrabbed mouse_selection extend
mouse_map shift+middle        release ungrabbed,grabbed paste_selection
mouse_map shift+left          press ungrabbed,grabbed mouse_selection normal
mouse_map shift+ctrl+alt+left press ungrabbed,grabbed mouse_selection rectangle
mouse_map shift+left          doublepress ungrabbed,grabbed mouse_selection word
mouse_map shift+left          triplepress ungrabbed,grabbed mouse_selection line
mouse_map shift+ctrl+alt+left triplepress ungrabbed,grabbed mouse_selection line_from_point
mouse_map shift+right press ungrabbed,grabbed mouse_selection extend
repaint_delay 10
input_delay 1
sync_to_monitor no
enable_audio_bell no
visual_bell_duration 0.0
window_alert_on_bell no
bell_on_tab yes
command_on_bell none
remember_window_size  no
initial_window_width  640
initial_window_height 400
enabled_layouts *
window_resize_step_cells 2
window_resize_step_lines 2
window_border_width 0.5pt
draw_minimal_borders yes
window_margin_width 55
single_window_margin_width -1
window_padding_width 0
placement_strategy center
active_border_color #000000
inactive_border_color #000000
bell_border_color #000000
inactive_text_alpha 1.0
hide_window_decorations yes
resize_debounce_time 0.1
resize_draw_strategy static
resize_in_steps no
confirm_os_window_close 0
tab_bar_edge top
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_bar_style hidden
tab_bar_min_tabs 2
tab_switch_strategy previous
tab_fade 0.25 0.5 0.75 1
tab_separator " ┇"
tab_powerline_style angled
tab_activity_symbol none
tab_title_template "{title}"
active_tab_title_template none
active_tab_foreground   #ffffff
active_tab_background   #000000
active_tab_font_style   bold-italic
inactive_tab_foreground #000000
inactive_tab_background #ffffff
inactive_tab_font_style normal
tab_bar_background #000000
foreground #ffffff
background #000000
background_opacity 1.0
background_image none
background_image_layout tiled
background_image_linear no
dynamic_background_opacity no
background_tint 0.0
dim_opacity 0.75
selection_foreground #000000
selection_background #ffffff
mark1_foreground #ffffff
mark1_background #000000
mark2_foreground #ffffff
mark2_background #000000
mark3_foreground #ffffff
mark3_background #000000
shell .
editor .
close_on_child_death no
allow_remote_control no
listen_on none
update_check_interval 0
startup_session none
clipboard_control write-clipboard write-primary
clipboard_max_size 0
allow_hyperlinks yes
term xterm
wayland_titlebar_color system
kitty_mod ctrl+shift
map kitty_mod+p paste_from_clipboard
map ctrl+minus change_font_size all -2.0
map ctrl+equal change_font_size all +2.0
map kitty_mod+minus change_font_size all 0
map kitty_mod+equal change_font_size all 0
map ctrl+f open_url_with_hints
map shift+space kitten smart_scroll.py scroll_page_up page_up
kitty +kitten show_key
color0 #000000
color1 #ffffff
color2 #ffffff
color3 #ffffff
color4 #ffffff
color5 #ffffff
color6 #ffffff
color7 #ffffff
color8 #ffffff
color9 #ffffff
color10 #ffffff
color11 #ffffff
color12 #ffffff
color13 #ffffff
color14 #ffffff
color15 #ffffff
color16 #ffffff
color17 #ffffff
color18 #ffffff
color19 #ffffff
color20 #ffffff
color21 #ffffff
color22 #ffffff
color23 #ffffff
color24 #ffffff
color25 #ffffff
color26 #ffffff
color27 #ffffff
color28 #ffffff
color29 #ffffff
color30 #ffffff
color31 #ffffff
color32 #ffffff
color33 #ffffff
color34 #ffffff
color35 #ffffff
color36 #ffffff
color37 #ffffff
color38 #ffffff
color39 #ffffff
color40 #ffffff
color41 #ffffff
color42 #ffffff
color43 #ffffff
color44 #ffffff
color45 #ffffff
color46 #ffffff
color47 #ffffff
color48 #ffffff
color49 #ffffff
color50 #ffffff
color51 #ffffff
color52 #ffffff
color53 #ffffff
color54 #ffffff
color55 #ffffff
color56 #ffffff
color57 #ffffff
color58 #ffffff
color59 #ffffff
color60 #ffffff
color61 #ffffff
color62 #ffffff
color63 #ffffff
color64 #ffffff
color65 #ffffff
color66 #ffffff
color67 #ffffff
color68 #ffffff
color69 #ffffff
color70 #ffffff
color71 #ffffff
color72 #ffffff
color73 #ffffff
color74 #ffffff
color75 #ffffff
color76 #ffffff
color77 #ffffff
color78 #ffffff
color79 #ffffff
color80 #ffffff
color81 #ffffff
color82 #ffffff
color83 #ffffff
color84 #ffffff
color85 #ffffff
color86 #ffffff
color87 #ffffff
color88 #ffffff
color89 #ffffff
color90 #ffffff
color91 #ffffff
color92 #ffffff
color93 #ffffff
color94 #ffffff
color95 #ffffff
color96 #ffffff
color97 #ffffff
color98 #ffffff
color99 #ffffff
color100 #ffffff
color101 #ffffff
color102 #ffffff
color103 #ffffff
color104 #ffffff
color105 #ffffff
color106 #ffffff
color107 #ffffff
color108 #ffffff
color109 #ffffff
color110 #ffffff
color111 #ffffff
color112 #ffffff
color113 #ffffff
color114 #ffffff
color115 #ffffff
color116 #ffffff
color117 #ffffff
color118 #ffffff
color119 #ffffff
color120 #ffffff
color121 #ffffff
color122 #ffffff
color123 #ffffff
color124 #ffffff
color125 #ffffff
color126 #ffffff
color127 #ffffff
color128 #ffffff
color129 #ffffff
color130 #ffffff
color131 #ffffff
color132 #ffffff
color133 #ffffff
color134 #ffffff
color135 #ffffff
color136 #ffffff
color137 #ffffff
color138 #ffffff
color139 #ffffff
color140 #ffffff
color141 #ffffff
color142 #ffffff
color143 #ffffff
color144 #ffffff
color145 #ffffff
color146 #ffffff
color147 #ffffff
color148 #ffffff
color149 #ffffff
color150 #ffffff
color151 #ffffff
color152 #ffffff
color153 #ffffff
color154 #ffffff
color155 #ffffff
color156 #ffffff
color157 #ffffff
color158 #ffffff
color159 #ffffff
color160 #ffffff
color161 #ffffff
color162 #ffffff
color163 #ffffff
color164 #ffffff
color165 #ffffff
color166 #ffffff
color167 #ffffff
color168 #ffffff
color169 #ffffff
color170 #ffffff
color171 #ffffff
color172 #ffffff
color173 #ffffff
color174 #ffffff
color175 #ffffff
color176 #ffffff
color177 #ffffff
color178 #ffffff
color179 #ffffff
color180 #ffffff
color181 #ffffff
color182 #ffffff
color183 #ffffff
color184 #ffffff
color185 #ffffff
color186 #ffffff
color187 #ffffff
color188 #ffffff
color189 #ffffff
color190 #ffffff
color191 #ffffff
color192 #ffffff
color193 #ffffff
color194 #ffffff
color195 #ffffff
color196 #ffffff
color197 #ffffff
color198 #ffffff
color199 #ffffff
color200 #ffffff
color201 #ffffff
color202 #ffffff
color203 #ffffff
color204 #ffffff
color205 #ffffff
color206 #ffffff
color207 #ffffff
color208 #ffffff
color209 #ffffff
color210 #ffffff
color211 #ffffff
color212 #ffffff
color213 #ffffff
color214 #ffffff
color215 #ffffff
color216 #ffffff
color217 #ffffff
color218 #ffffff
color219 #ffffff
color220 #ffffff
color221 #ffffff
color222 #ffffff
color223 #ffffff
color224 #ffffff
color225 #ffffff
color226 #ffffff
color227 #ffffff
color228 #ffffff
color229 #ffffff
color230 #ffffff
color231 #ffffff
color232 #ffffff
color233 #ffffff
color234 #ffffff
color235 #ffffff
color236 #ffffff
color237 #ffffff
color238 #ffffff
color239 #ffffff
color240 #ffffff
color241 #ffffff
color242 #ffffff
color243 #ffffff
color244 #ffffff
color245 #ffffff
color246 #ffffff
color247 #ffffff
color248 #ffffff
color249 #ffffff
color250 #ffffff
color251 #ffffff
color252 #ffffff
color253 #ffffff
color254 #ffffff
color255 #ffffff
```
</details>

**Comment by kovidgoyal** [comment]
Seems quite clear to me, it says unknown config key kitty so look for a line that starts with the word kitty

**Comment by wgmayer0** [comment]
Here are my results from: `$ cat kitty.conf |` [rg](https://github.com/BurntSushi/ripgrep) `kitty`

```
kitty_mod ctrl+shift
map kitty_mod+p paste_from_clipboard
map kitty_mod+minus change_font_size all 0
map kitty_mod+equal change_font_size all 0
kitty +kitten show_key
```

**Comment by wgmayer0** [comment]
I forgot what that one does @Luflosi do you remember by any chance? I was just thinking it was that one.

**Comment by Luflosi** [comment]
This is not supposed to be put into the config file.
The documentation you showed, tells you that you can run the command to find out what you need to pass to send_text, when you press a combination of keys.
