### ISSUE TITLE
show_key kitten crashes on on-ASCII keys

### ISSUE THREAD

**Issue by VorpalBlade** [kovidgoyal/kitty#5016]
**Describe the bug**
I have a Swedish keyboard. If i type for example the "ö" key into `kitty +kitten show_key` it crashes with the following python traceback:

```console
$ kitty +kitten show_key 
Press any keys - Ctrl-D will terminate this program
UNIX		send_text
Ã¶		Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 185, in <module>
    main()
  File "/usr/bin/../lib/kitty/__main__.py", line 176, in main
    namespaced(['+', first_arg[1:]] + sys.argv[2:])
  File "/usr/bin/../lib/kitty/__main__.py", line 129, in namespaced
    func(args[1:])
  File "/usr/bin/../lib/kitty/__main__.py", line 112, in run_kitten
    rk(kitten)
  File "/usr/bin/../lib/kitty/kittens/runner.py", line 112, in run_kitten
    runpy.run_module(f'kittens.{kitten}.main', run_name=run_name)
  File "/usr/lib/python3.10/runpy.py", line 212, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/kittens/show_key/main.py", line 80, in <module>
    main(sys.argv)
  File "/usr/bin/../lib/kitty/kittens/show_key/main.py", line 73, in main
    return legacy_main()
  File "/usr/bin/../lib/kitty/kittens/show_key/main.py", line 52, in legacy_main
    read_keys()
  File "/usr/bin/../lib/kitty/kittens/show_key/main.py", line 42, in read_keys
    print_key(raw)
  File "/usr/bin/../lib/kitty/kittens/show_key/main.py", line 27, in print_key
    x = chr(ch).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xc3' in position 0: ordinal not in range(128)
```

Even if it is not able to decode the keypress (one of the things the kitty keyboard protocol tries to simplify), it should presumably show a sensible error instead of just crash.

**To Reproduce**
1. Run `kitty +kitten show_key`
2. Input a key that cannot be decoded in ASCII.
3. See error

**Environment details**
```
kitty 0.25.0 created by Kovid Goyal
Linux athena 5.17.4-arch1-1 #1 SMP PREEMPT Wed, 20 Apr 2022 18:29:28 +0000 x86_64
Arch Linux 5.17.4-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/arvid/.config/kitty/kitty.conf

Config options different from defaults:
font_family                     Terminus (TTF)
font_size                       15.0
scrollback_fill_enlarged_window True
shell_integration               frozenset({'enabled', 'no-rc'})
Added shortcuts:
	shift+left → previous_tab
	shift+right → next_tab
Changed shortcuts:
	ctrl+shift+left → move_tab_backward
	ctrl+shift+right → move_tab_forward

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/arvid/bin
	LANG                                en_GB.UTF-8
	SHELL                               /bin/zsh
	DISPLAY                             :0
	USER                                arvid
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	LC_MONETARY                         sv_SE.UTF-8
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 cinnamon
	XDG_SESSION_TYPE                    x11
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/arvid
	LC_PAPER                            sv_SE.UTF-8
	XDG_CURRENT_DESKTOP                 X-Cinnamon
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	LC_MEASUREMENT                      sv_SE.UTF-8
	XDG_VTNR                            7
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TIME                             sv_SE.UTF-8
	XDG_DATA_DIRS                       /home/arvid/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
	LC_NUMERIC                          sv_SE.UTF-8
```

**Additional context**
Problem is reproducible with `kitty --config NONE`.
Using `kitty +kitten show-key -m kitty` does not have the issue.

**Comment by kovidgoyal** [comment]
You want 

kitty +kitten show_key -m kitty

**Comment by VorpalBlade** [comment]
Right, but even without `-m kitty` it really should not crash in my opinion, as I said above.

**Comment by kovidgoyal** [comment]
Did you not see the commit closing the issue.

**Comment by VorpalBlade** [comment]
No, I missed that. Sorry, was on my phone and in a hurry at the time.

**Comment by kovidgoyal** [comment]
No worries.
