### ISSUE TITLE
[glfw error 65543]: EGL: Failed to create context: Arguments are inconsistent. 

### ISSUE THREAD

**Issue by SatouKuzuma1** [kovidgoyal/kitty#5040]
I can launch kitty on arch linux. 

**Environment details**
 This is a fresh new installation of Arch Linux in a VirtualBox machine.  I'm using a MacBook Pro 16-inch Intel Core i9 16GB ram.

```
$ kitty debug-config
[120 06:48:42.507295] [glfw error 65543]: EGL: Failed to create context: Arguments are inconsistent
[120 06:48:42.515642] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 418, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 410, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 199, in __call__
    _run_app(opts, args, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 172, in _run_app
    window_id = create_os_window(
ValueError: Failed to create GLFWwindow
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

```
$ kitty --config NONE
[120 07:01:54.357347] [glfw error 65543]: EGL: Failed to create context: Arguments are inconsistent
[120 07:01:54.365331] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 418, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 410, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 199, in __call__
    _run_app(opts, args, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 172, in _run_app
    window_id = create_os_window(
ValueError: Failed to create GLFWwindow
```

**Comment by kovidgoyal** [comment]
Your VM has no working GPU drivers. Use software rendering. Or GPU
passthrough in the VM.

**Comment by SatouKuzuma1** [comment]
@kovidgoyal  I don't know how to do that. Can you explain or share any link ? 
Tank you.

**Comment by page-down** [comment]
See https://github.com/kovidgoyal/kitty/discussions/4241

**Comment by SatouKuzuma1** [comment]
@page-down  It worked. Thank you !!!
