### ISSUE TITLE
KeyError: 'FcFontMatch() failed'

### ISSUE THREAD

**Issue by philidor-green** [kovidgoyal/kitty#5073]
`kitty` installed from aur `kitty 0.24.4`, fails with error:

```
kitty --debug-font-fallback   
[128 20:07:42.095013] Ignoring invalid config line: symbol_map
[128 20:07:42.095061] Ignoring invalid config line: narrow_symbols
[128 20:07:42.095147] Ignoring invalid config line: font_features
[128 20:07:42.095884] Ignoring invalid config line: url_excluded_characters
[128 20:07:42.097799] Ignoring invalid config line: env
[128 20:07:42.097844] Ignoring invalid config line: watcher
[128 20:07:42.097868] Ignoring invalid config line: exe_search_path
[128 20:07:42.097977] Ignoring invalid config line: file_transfer_confirmation_bypass
[128 20:07:42.098353] Ignoring invalid config line: action_alias
[128 20:07:42.098395] Ignoring invalid config line: kitten_alias
[128 20:07:42.110928] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 415, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 408, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 198, in __call__
    set_font_family(opts, debug_font_matching=args.debug_font_fallback)
  File "/usr/bin/../lib/kitty/kitty/fonts/render.py", line 190, in set_font_family
    font_map = get_font_files(opts)
  File "/usr/bin/../lib/kitty/kitty/fonts/render.py", line 45, in get_font_files
    return get_font_files_fontconfig(opts)
  File "/usr/bin/../lib/kitty/kitty/fonts/fontconfig.py", line 154, in get_font_files
    font = find_best_match(rf, bold, italic)
  File "/usr/bin/../lib/kitty/kitty/fonts/fontconfig.py", line 120, in find_best_match
    mono_possibility = fc_match(family, False, False, FC_MONO)
  File "/usr/bin/../lib/kitty/kitty/fonts/fontconfig.py", line 72, in fc_match
    return fc_match_impl(family, bold, italic, spacing)
KeyError: 'FcFontMatch() failed'
```

**Environment details**
```
kitty 0.24.4 created by Kovid Goyal
Linux think 5.15.32-1-MANJARO #1 SMP PREEMPT Mon Mar 28 09:16:36 UTC 2022 x86_64
Manjaro Linux 5.15.32-1-MANJARO  (think) (/dev/tty)


DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.6
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/think/.config/kitty/kitty.conf

Config options different from defaults:
cursor_beam_thickness 5.5
enable_audio_bell     False
font_family           Monofur Nerd Font Mono Book
font_size             13.0
initial_window_height (800, 'px')
initial_window_width  (1040, 'px')
remember_window_size  False
update_check_interval 24.0
visual_bell_duration  0.3
window_padding_width  FloatEdges(left=5.0, top=5.0, right=5.0, bottom=5.0)
Added shortcuts:
	super++ → change_font_size all +2.0
	super+, → edit_config_file
	super+- → change_font_size all -2.0
	super+0 → change_font_size all 0
	super+1 → first_window
	super+2 → second_window
	super+3 → third_window
	super+4 → fourth_window
	super+5 → fifth_window
	super+6 → sixth_window
	super+7 → seventh_window
	super+8 → eighth_window
	super+9 → ninth_window
	super+= → change_font_size all +2.0
	super+k → clear_terminal to_cursor active
	super+n → new_os_window
	super+r → start_resizing_window
	super+t → new_tab
	super+w → close_tab
	super+enter → new_window
	super+up → scroll_line_up
	super+down → scroll_line_down
	super+page_up → scroll_page_up
	super+page_down → scroll_page_down
	super+home → scroll_home
	super+end → scroll_end
	shift+super+- → change_font_size all -2.0
	shift+super+= → change_font_size all +2.0
	shift+super+[ → previous_tab
	shift+super+] → next_tab
	shift+super+d → close_window
	shift+super+i → set_tab_title
	shift+super+w → close_os_window
	alt+super+, → debug_config
	alt+super+r → clear_terminal reset active
	alt+super+s → toggle_macos_secure_keyboard_entry
	alt+super+page_up → scroll_line_up
	alt+super+page_down → scroll_line_down
	ctrl+super+space → kitten unicode_input
	ctrl+super+, → load_config_file
	ctrl+super+f → toggle_fullscreen
Colors:
	background            #ffffff   
	color0                #414141   
	color1                #b23670   
	color10               #829428   
	color11               #cc6e33   
	color12               #3b5ea7   
	color13               #a353b2   
	color14               #829428   
	color15               #f1f1f1   
	color2                #66781d   
	color3                #cc6e33   
	color4                #3b5ea7   
	color5                #a353b2   
	color6                #66781d   
	color7                #ffffff   
	color8               0.24.4 #3e3e3e   
	color9                #da3365   
	cursor                #5e76c7   
	foreground            #414141   
	selection_background  #6f6a4e   
	selection_foreground  #ffffff   
	visual_bell_color     #bebebe   

Important environment variables seen by the kitty process:
	PATH                                /home/think/.local/bin:/usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	EDITOR                              /usr/bin/nano
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                think
	XDG_MENU_PREFIX                     gnome-
	LC_ADDRESS                          en_US.UTF-8
	LC_NAME                             en_US.UTF-8
	LC_MONETARY                         en_US.UTF-8
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland
	LC_PAPER                            en_US.UTF-8
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_SESSION_CLASS                   user
	LC_IDENTIFICATION                   en_US.UTF-8
	LC_TELEPHONE                        en_US.UTF-8
	LC_MEASUREMENT                      en_US.UTF-8
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TIME                             en_US.UTF-8
	XDG_DATA_DIRS                       /home/think/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
	LC_NUMERIC                          en_US.UTF-8

```

**Additional context**
`kitty --config NONE` fails with the same error:

```
kitty --config NONE
[128 20:09:40.654493] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 415, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 408, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 198, in __call__
    set_font_family(opts, debug_font_matching=args.debug_font_fallback)
  File "/usr/bin/../lib/kitty/kitty/fonts/render.py", line 190, in set_font_family
    font_map = get_font_files(opts)
  File "/usr/bin/../lib/kitty/kitty/fonts/render.py", line 45, in get_font_files
    return get_font_files_fontconfig(opts)
  File "/usr/bin/../lib/kitty/kitty/fonts/fontconfig.py", line 154, in get_font_files
    font = find_best_match(rf, bold, italic)
  File "/usr/bin/../lib/kitty/kitty/fonts/fontconfig.py", line 120, in find_best_match
    mono_possibility = fc_match(family, False, False, FC_MONO)
  File "/usr/bin/../lib/kitty/kitty/fonts/fontconfig.py", line 72, in fc_match
    return fc_match_impl(family, bold, italic, spacing)
KeyError: 'FcFontMatch() failed'
```
![Screenshot from 2022-05-08 20-12-36](https://user-images.githubusercontent.com/3471384/167307530-3ebb5246-1455-4ef8-a602-68e2a46a08a2.png)

I cant find any settings related to this title, how can I change it?

**Comment by kovidgoyal** [comment]
That indicates fontconfig on your system is broken. It is unable to find
a match for a monospace font.

And why are you installing kitty from aur. Use the official kitty
binaries or at least the official arch package.

**Comment by philidor-green** [comment]
> That indicates fontconfig on your system is broken. It is unable to find
a match for a monospace font.

That's sound strange because all other application able to find monospace font and dont claims about broken fontconfig. 

```
~ % cat .config/fontconfig/fonts.conf
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .config/fontconfig/fonts.conf
       │ Size: 310 B
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ <?xml version='1.0'?>
   2   │ <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
   3   │ <fontconfig>
   4   │   <match target="pattern">
   5   │     <test name="family" qual="any">
   6   │       <string>monospace</string>
   7   │     </test>
   8   │     <edit binding="strong" mode="prepend" name="family">
   9   │       <string>monofur</string>
  10   │     </edit>
  11   │   </match>
  12   │ </fontconfig>
  13   │ 
───────┴─────────────────
```

> And why are you installing kitty from aur. Use the official kitty
binaries or at least the official arch package.

I've tried all kind of binaries, all raise an error above.
