### ISSUE TITLE
Getting error when trying to change tab name

### ISSUE THREAD

**Issue by dkarter** [kovidgoyal/kitty#510]
Hi!

First, thank you for this great project, really love the performance gains on kitty compared to iTerm2 on the mac!

I'm running kitty 0.9.0 on macOS 10.13.4, installed from homebrew.

```
❯ python --version
Python 2.7.14

~
❯ python3 --version
Python 3.6.5
```

When I try to change a tab name I get the following:

```
Unhandled exception running kitten:
Traceback (most recent call last):
  File "kitty/runner.py", line 71, in main
  File "kitty/runner.py", line 53, in launch
  File "kitty/main.py", line 88, in main
ImportError: dlopen(/Applications/kitty.app/Contents/MacOS/../Resources/Python/lib/python3.6/lib-dynload/readline.cpython-36m-darwin.so, 2): Library not loaded: @executable_path/../Frameworks/libreadline.6.dylib
  Referenced from: /Applications/kitty.app/Contents/Resources/Python/lib/python3.6/lib-dynload/readline.cpython-36m-darwin.so
  Reason: image not found
Press Enter to quit...
```

Looks like a missing dependency. I tried `pip3 install libreadline` and `pip3 install readline` but no luck. Any advice on how this fix this error?

Thanks!

**Comment by kovidgoyal** [comment]
dup of #494
