### ISSUE TITLE
listen_on not working

### ISSUE THREAD

**Issue by porjo** [kovidgoyal/kitty#5165]
**Describe the bug**
I have `listen_on` defined in config, however when I attempt to use it I get 'connection refused' errors.

**To Reproduce**
1. add `listen_to` to the config (see additional context)
2. restart kitty
3. execute `kitty @ --to unix:@kitty ls`
```
[ian@laptop ~]$ kitty @ --to unix:@kitty ls
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib64/kitty/__main__.py", line 185, in <module>
    main()
  File "/usr/bin/../lib64/kitty/__main__.py", line 181, in main
    func(sys.argv[1:])
  File "/usr/bin/../lib64/kitty/__main__.py", line 22, in remote_control
    rc_main(args)
  File "/usr/bin/../lib64/kitty/kitty/remote_control.py", line 242, in main
    response = do_io(global_opts.to, send, no_response, response_timeout)
  File "/usr/bin/../lib64/kitty/kitty/remote_control.py", line 151, in do_io
    with io:
  File "/usr/bin/../lib64/kitty/kitty/remote_control.py", line 98, in __enter__
    self.socket.connect(self.address)
ConnectionRefusedError: [Errno 111] Connection refused
```
**Environment details**
```
kitty 0.25.1 created by Kovid Goyal
Linux laptop 5.17.11-300.fc36.x86_64 #1 SMP PREEMPT Wed May 25 15:04:05 UTC 2022 x86_64
S
Kernel 5.17.11-300.fc36.x86_64 on an x86_64 (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/ian/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control y
listen_on            unix:@kitty

Important environment variables seen by the kitty process:
	PATH                                /home/ian/go/bin:/home/ian/.local/bin:/home/ian/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
	LANG                                en_GB.UTF-8
	VISUAL                              vim
	EDITOR                              vim
	SHELL                               /bin/bash
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                ian
	XDG_MENU_PREFIX                     gnome-
	LC_MONETARY                         en_AU.UTF-8
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland
	LC_PAPER                            en_AU.UTF-8
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_SESSION_CLASS                   user
	LC_MEASUREMENT                      en_AU.UTF-8
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TIME                             en_AU.UTF-8
	XDG_DATA_DIRS                       /home/ian/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	LC_NUMERIC                          en_AU.UTF-8
```

**Additional context**

kitty.conf
```
listen_on unix:@kitty
allow_remote_control yes
```

I also tried `listen_on unix:/tmp/kitty` however that didn't help. For now, I am using kitty without `listen_on` defined and remote control works.

**Comment by porjo** [comment]
Based on the docs, my config looks correct. If you disagree, please say how.

**Comment by kovidgoyal** [comment]
Quoting from the docs:

If {kitty_pid} is present, then it is replaced by the PID of the kitty process, otherwise the PID of the kitty process is appended to the value, with a hyphen. This option is ignored unless you also set allow_remote_control to enable remote control.

**Comment by porjo** [comment]
OK, so the config is correct. The issue is with the invocation of remote control command. Remote control command should be something like `kitty @ --to unix:@kitty-1234 ls` where `1234` is the PID of the kitty process?

**Comment by porjo** [comment]
I rebooted my machine and now it works.

**Comment by porjo** [comment]
It worked for awhile and now it is hanging again, and kitty process is consuming 100% cpu. @kovidgoyal should I open a separate issue for this?

**Comment by kovidgoyal** [comment]
Find a way to reproduce your symptoms and I will take a look.

**Comment by porjo** [comment]
I can reliably reproduce the issue with this:
```
kitty @ --to unix:@kitty-6975 set-background-image ~/Pictures/Wallpapers/kitty/bg.png
```

The PNG image is 4MB in size.

When I run strace on the kitty process, I see a lot of this:
```
write(13, "\1\0\0\0\0\0\0\0", 8)        = 8
write(13, "\1\0\0\0\0\0\0\0", 8)        = 8
futex(0x7f73e18ca8e0, FUTEX_WAKE_PRIVATE, 1) = 0
write(13, "\1\0\0\0\0\0\0\0", 8)        = 8
write(13, "\1\0\0\0\0\0\0\0", 8)        = 8
write(13, "\1\0\0\0\0\0\0\0", 8)        = 8
write(13, "\1\0\0\0\0\0\0\0", 8)        = 8
write(13, "\1\0\0\0\0\0\0\0", 8)        = 8
write(13, "\1\0\0\0\0\0\0\0", 8)        = 8
write(13, "\1\0\0\0\0\0\0\0", 8)        = 8
write(13, "\1\0\0\0\0\0\0\0", 8)        = 8
write(13, "\1\0\0\0\0\0\0\0", 8)        = 8
write(13, "\1\0\0\0\0\0\0\0", 8)        = 8
write(13, "\1\0\0\0\0\0\0\0", 8)        = 8
write(13, "\1\0\0\0\0\0\0\0", 8)        = 8
```

If I kill the process and restart without `listen_on` then run the same remote control command (without specifying unix socket), it works fine.

**Comment by porjo** [comment]
I just noticed that I'm getting the same error as before when setting background image:
```
kitty @ --to unix:@kitty-22592 set-background-image /home/ian/Pictures/Wallpapers/kitty/bg.png
Timed out after 10.0 seconds waiting for response from kitty
```
The image does update, but I always see the error. I thought perhaps it was because the image was too large (3.1MB) however it does the same with an image only 500KB in size.

I'm using 0.26.3

**Comment by page-down** [comment]
> ... I'm getting the 'timed out' error when setting background image ...
> ...
> Timed out after 10.0 seconds waiting for response from kitty

@kovidgoyal

The issue first appeared in 0.26.0, and is reproducible in the current master branch.

I also noticed that after the select-window rc command failed once, the window visual selection UI was no longer displayed.

```shell
kitty @ select-window --response-timeout 0
```

```log
Traceback (most recent call last):
...
  File ".../kitty/remote_control.py", line 504, in main
    response = do_io(global_opts.to, send, no_response, response_timeout, encrypter)
  File ".../kitty/remote_control.py", line 318, in do_io
    received = io.simple_recv(timeout=response_timeout)
  File ".../kitty/remote_control.py", line 283, in simple_recv
    m = dcs.search(data)
TypeError: expected string or bytes-like object
```

**Comment by kovidgoyal** [comment]
I'm not going to bother with fixing this as it is re-written anyway in
the go branch which will eventually be merged into master (the errors
dont occur there).
