### ISSUE TITLE
Error with Prewarm tests when building Debian package for version 0.25.2

### ISSUE THREAD

**Issue by lcheylus** [kovidgoyal/kitty#5181]
**Describe the bug**
I'm trying to build Debian Linux packages for Kitty version 0.25.2 but I have an error with `test_prewarming` test.

**To Reproduce**
- Debian Linux testing (bookworm) distribution on amd64.

Steps to reproduce the behavior :

- Clone sources or download .tar.gz for Kitty v0.25.2 => sources in `kitty-tmp/` directory
- Clone sources to build Kitty package for Debian => https://salsa.debian.org/jamessan/kitty.git
- Copy `debian/` directory from step 2 in `kitty-tmp/` directory
- Update `debian/changelog` file for version 0.25.2
- Build Debian package with `dpkg-buildpackage -b` in `kitty-tmp` directory.

=> Build OK but Error with tests `test_prewarming (kitty_tests.prewarm.Prewarm)`

```
$ dpkg-buildpackage -b
(...)
env HOME="/home/fox/tmp/kitty-tmp/debian/fakehome" python3 setup.py --verbose test
(...)
test_prewarming (kitty_tests.prewarm.Prewarm) ... Available builtin kittens:
broadcast
clipboard
transfer
show_key
query_terminal
remote_file
icat
mouse_demo
ask
show_error
resize_window
choose
diff
ssh
hints
hyperlinked_grep
unicode_input
themes
panel
No kitten named prewarm
ERROR
(...)
======================================================================
ERROR: test_prewarming (kitty_tests.prewarm.Prewarm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fox/tmp/kitty-tmp/kitty_tests/prewarm.py", line 28, in test_prewarming
    child = p(pty.slave_fd, [kitty_exe(), '+runpy', """import os, json; from kitty.utils import *; print(json.dumps({
    PrewarmProcess = <class 'kittens.prewarm.main.PrewarmProcess'>
    cols = 117
    cwd = '/tmp'
    env = {'TEST_ENV_PASS': 'xyz'}
    p = <kittens.prewarm.main.PrewarmProcess object at 0x7f55b2fe5d20>
    pty = <kitty_tests.PTY object at 0x7f55b2fe4550>
    self = <kitty_tests.prewarm.Prewarm testMethod=test_prewarming>
    stdin_data = 'from_stdin'
    ttyname = '/dev/pts/16'
  File "/home/fox/tmp/kitty-tmp/kittens/prewarm/main.py", line 137, in __call__
    raise PrewarmProcessFailed('Failed doing I/O with prewarm process')
    argv = ['/usr/bin/kitty', '+runpy', "import os, json; from kitty.utils import *; print(json.dumps({\n        'cterm': os.ctermid(),\n        'ttyname': os.ttyname(sys.stdout.fileno()),\n        'cols': read_screen_size().cols,\n        'cwd': os.getcwd(),\n        'env': os.environ.get('TEST_ENV_PASS'),\n        'pid': os.getpid(),\n        'stdin': sys.stdin.read(),\n\n        'done': 'hello',\n        }, indent=2))"]
    cmd = {'tty_name': '/dev/pts/16', 'cwd': '/tmp', 'argv': ['/usr/bin/kitty', '+runpy', "import os, json; from kitty.utils import *; print(json.dumps({\n        'cterm': os.ctermid(),\n        'ttyname': os.ttyname(sys.stdout.fileno()),\n        'cols': read_screen_size().cols,\n        'cwd': os.getcwd(),\n        'env': os.environ.get('TEST_ENV_PASS'),\n        'pid': os.getpid(),\n        'stdin': sys.stdin.read(),\n\n        'done': 'hello',\n        }, indent=2))"], 'env': {'TEST_ENV_PASS': 'xyz'}, 'stdin_size': 10}
    cwd = '/tmp'
    data = b'{"tty_name": "/dev/pts/16", "cwd": "/tmp", "argv": ["/usr/bin/kitty", "+runpy", "import os, json; from kitty.utils import *; print(json.dumps({\\n        \'cterm\': os.ctermid(),\\n        \'ttyname\': os.ttyname(sys.stdout.fileno()),\\n        \'cols\': read_screen_size().cols,\\n        \'cwd\': os.getcwd(),\\n        \'env\': os.environ.get(\'TEST_ENV_PASS\'),\\n        \'pid\': os.getpid(),\\n        \'stdin\': sys.stdin.read(),\\n\\n        \'done\': \'hello\',\\n        }, indent=2))"], "env": {"TEST_ENV_PASS": "xyz"}, "stdin_size": 10}'
    env = {'TEST_ENV_PASS': 'xyz'}
    event = 16
    fd = 9
    input_buf = b''
    self = <kittens.prewarm.main.PrewarmProcess object at 0x7f55b2fe5d20>
    shm = SharedMemory('', size=532)
    st = 2454464.912769131
    stdin_data = b'from_stdin'
    total_size = 532
    tty_fd = 6
    tty_name = '/dev/pts/16'
kittens.prewarm.main.PrewarmProcessFailed: Failed doing I/O with prewarm process

----------------------------------------------------------------------
Ran 133 tests in 6.371s

FAILED (errors=1, skipped=5)

```

**Comment by kovidgoyal** [comment]
I dont know what the debian packaging scripts do. But downloading the
source code of kitty 0.25.2 and running make && ./test.py produces no
errors for me. And indeed the prewarm kitten exists as can be verified
by

ls kittens/prewarm/

And note that in master the prewarm kitten has been removed in any case.
