### ISSUE TITLE
Error with test_prewarming when building version 0.25.2 on Debian

### ISSUE THREAD

**Issue by lcheylus** [kovidgoyal/kitty#5194]
**Describe the bug**
I'm trying to build Kitty version 0.25.2 on Debian Linux distribution (version testing/bookworm) for amd64 architecture. Build is OK but I have an error on `test_prewarming (kitty_tests.prewarm.Prewarm).`

**To Reproduce**

- Debian Linux distribution testing on amd64 architecture
- gcc version 11.3.0
- Python version 3.10.5

1. Download sources of Kitty v0.25.2
2. Untar archive => `kitty-0.25.2`
3. Build with `make` OK
4. Launch tests with `./test.py` => ERROR on `test_prewarming (kitty_tests.prewarm.Prewarm)`

```
$ make
python3 setup.py
CC: ['gcc'] (11, 0)
[16/16] Generating wayland-text-input-unstable-v3-client-protocol.c ... done
[102/102] Compiling kitty/gl-wrapper.c ... done
[7/7] Linking kittens/choose/subseq_matcher ... done

$ ./test.py
(...)
test_prewarming (kitty_tests.prewarm.Prewarm) ... Available builtin kittens:
choose
ssh
remote_file
icat
unicode_input
query_terminal
panel
mouse_demo
ask
show_error
hyperlinked_grep
broadcast
show_key
diff
transfer
resize_window
themes
hints
clipboard
No kitten named prewarm
ERROR
(...)
======================================================================
ERROR: test_prewarming (kitty_tests.prewarm.Prewarm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fox/tmp/kitty-0.25.2/kitty_tests/prewarm.py", line 28, in test_prewarming
    child = p(pty.slave_fd, [kitty_exe(), '+runpy', """import os, json; from kitty.utils import *; print(json.dumps({
    PrewarmProcess = <class 'kittens.prewarm.main.PrewarmProcess'>
    cols = 117
    cwd = '/tmp'
    env = {'TEST_ENV_PASS': 'xyz'}
    p = <kittens.prewarm.main.PrewarmProcess object at 0x7fe4de03be80>
    pty = <kitty_tests.PTY object at 0x7fe4dc2c0520>
    self = <kitty_tests.prewarm.Prewarm testMethod=test_prewarming>
    stdin_data = 'from_stdin'
    ttyname = '/dev/pts/17'
  File "/home/fox/tmp/kitty-0.25.2/kittens/prewarm/main.py", line 137, in __call__
    raise PrewarmProcessFailed('Failed doing I/O with prewarm process')
    argv = ['/usr/bin/kitty', '+runpy', "import os, json; from kitty.utils import *; print(json.dumps({\n        'cterm': os.ctermid(),\n        'ttyname': os.ttyname(sys.stdout.fileno()),\n        'cols': read_screen_size().cols,\n        'cwd': os.getcwd(),\n        'env': os.environ.get('TEST_ENV_PASS'),\n        'pid': os.getpid(),\n        'stdin': sys.stdin.read(),\n\n        'done': 'hello',\n}, indent=2))"]
    cmd = {'tty_name': '/dev/pts/17', 'cwd': '/tmp', 'argv': ['/usr/bin/kitty', '+runpy', "import os, json; from kitty.utils import *; print(json.dumps({\n        'cterm': os.ctermid(),\n        'ttyname': os.ttyname(sys.stdout.fileno()),\n        'cols': read_screen_size().cols,\n        'cwd': os.getcwd(),\n        'env': os.environ.get('TEST_ENV_PASS'),\n        'pid': os.getpid(),\n        'stdin': sys.stdin.read(),\n\n        'done': 'hello',\n        }, indent=2))"], 'env': {'TEST_ENV_PASS': 'xyz'}, 'stdin_size': 10}
    cwd = '/tmp'
    data = b'{"tty_name": "/dev/pts/17", "cwd": "/tmp", "argv": ["/usr/bin/kitty", "+runpy", "import os, json; from kitty.utils import *; print(json.dumps({\\n        \'cterm\': os.ctermid(),\\n        \'ttyname\': os.ttyname(sys.stdout.fileno()),\\n        \'cols\': read_screen_size().cols,\\n        \'cwd\': os.getcwd(),\\n        \'env\': os.environ.get(\'TEST_ENV_PASS\'),\\n        \'pid\': os.getpid(),\\n        \'stdin\': sys.stdin.read(),\\n\\n        \'done\': \'hello\',\\n        }, indent=2))"], "env": {"TEST_ENV_PASS": "xyz"}, "stdin_size": 10}'
    env = {'TEST_ENV_PASS': 'xyz'}
    event = 16
    fd = 9
    input_buf = b''
    self = <kittens.prewarm.main.PrewarmProcess object at 0x7fe4de03be80>
    shm = SharedMemory('', size=532)
    st = 2871807.65011854
    stdin_data = b'from_stdin'
    total_size = 532
    tty_fd = 6
    tty_name = '/dev/pts/17'
kittens.prewarm.main.PrewarmProcessFailed: Failed doing I/O with prewarm process

----------------------------------------------------------------------
Ran 133 tests in 5.419s

FAILED (errors=1, skipped=5)
```

`prewarm` kitten is present in `kittens/` directory : 

```
$ ls -1 kittens/
ask
broadcast
choose
clipboard
diff
hints
hyperlinked_grep
icat
__init__.py
mouse_demo
panel
prewarm
__pycache__
query_terminal
remote_file
resize_window
runner.py
show_error
show_key
ssh
themes
transfer
tui
unicode_input
```
**Additional context**

I have the same error with `test_prewarming (kitty_tests.prewarm.Prewarm)` when I'm trying to build/tests Kitty from branch `master` with the last commit d5df3013.

```
$ test.py
(...)
test_prewarming (kitty_tests.prewarm.Prewarm) ... Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 185, in <module>
    main()
  File "/usr/bin/../lib/kitty/__main__.py", line 176, in main
    namespaced(['+', first_arg[1:]] + sys.argv[2:])
  File "/usr/bin/../lib/kitty/__main__.py", line 129, in namespaced
    func(args[1:])
  File "/usr/bin/../lib/kitty/__main__.py", line 29, in runpy
    exec(args[1])
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'kitty.prewarm'
ERROR
(...)
======================================================================
ERROR: test_prewarming (kitty_tests.prewarm.Prewarm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fox/tmp/kitty.git/kitty_tests/prewarm.py", line 41, in test_prewarming
    child = p(pty.slave_fd, [kitty_exe(), '+runpy', """\
    cols = 117
    cwd = '/tmp'
    env = {'TEST_ENV_PASS': 'xyz'}
    fork_prewarm_process = <function fork_prewarm_process at 0x7f9ca7cd9b40>
    opts = <kitty.options.types.Options object at 0x7f9ca9550e80>
    p = <kitty.prewarm.PrewarmProcess object at 0x7f9ca8746800>
    pty = <kitty_tests.PTY object at 0x7f9ca8746c80>
    self = <kitty_tests.prewarm.Prewarm testMethod=test_prewarming>
    stdin_data = 'from_stdin'
    ttyname = '/dev/pts/16'
  File "/home/fox/tmp/kitty.git/kitty/prewarm.py", line 169, in __call__
    raise PrewarmProcessFailed('Failed doing I/O with prewarm process')
    argv = ['/usr/bin/kitty', '+runpy', "import os, json; from kitty.utils import *; from kitty.fast_data_types import get_options; print(json.dumps({\n        'cterm': os.ctermid(),\n        'ttyname': os.ttyname(sys.stdout.fileno()),\n        'cols': read_screen_size().cols,\n        'cwd': os.getcwd(),\n        'env': os.environ.get('TEST_ENV_PASS'),\n        'pid': os.getpid(),\n        'font_family': get_options().font_family,\n        'stdin': sys.stdin.read(),\n\n        'done': 'hello',\n        }, indent=2))"]
    cmd = {'tty_name': '/dev/pts/16', 'cwd': '/tmp', 'argv': ['/usr/bin/kitty', '+runpy', "import os, json; from kitty.utils import *; from kitty.fast_data_types import get_options; print(json.dumps({\n        'cterm': os.ctermid(),\n        'ttyname': os.ttyname(sys.stdout.fileno()),\n        'cols': read_screen_size().cols,\n        'cwd': os.getcwd(),\n        'env': os.environ.get('TEST_ENV_PASS'),\n    'pid': os.getpid(),\n        'font_family': get_options().font_family,\n        'stdin': sys.stdin.read(),\n\n        'done': 'hello',\n        }, indent=2))"], 'env': {'TEST_ENV_PASS': 'xyz'}, 'stdin_size': 10}
    cwd = '/tmp'
    data = b'{"tty_name": "/dev/pts/16", "cwd": "/tmp", "argv": ["/usr/bin/kitty", "+runpy", "import os, json; from kitty.utils import *; from kitty.fast_data_types import get_options; print(json.dumps({\\n        \'cterm\': os.ctermid(),\\n        \'ttyname\': os.ttyname(sys.stdout.fileno()),\\n        \'cols\': read_screen_size().cols,\\n        \'cwd\': os.getcwd(),\\n        \'env\': os.environ.get(\'TEST_ENV_PASS\'),\\n        \'pid\': os.getpid(),\\n        \'font_family\': get_options().font_family,\\n        \'stdin\': sys.stdin.read(),\\n\\n        \'done\': \'hello\',\\n        }, indent=2))"], "env": {"TEST_ENV_PASS": "xyz"}, "stdin_size": 10}'
    env = {'TEST_ENV_PASS': 'xyz'}
    event = 16
    fd = 7
    input_buf = b''
    self = <kitty.prewarm.PrewarmProcess object at 0x7f9ca8746800>
    shm = SharedMemory('', size=630)
    st = 2871748.485819567
    stdin_data = b'from_stdin'
    timeout = 4.0
    total_size = 630
    tty_fd = 4
    tty_name = '/dev/pts/16'
kitty.prewarm.PrewarmProcessFailed: Failed doing I/O with prewarm process

----------------------------------------------------------------------
Ran 134 tests in 5.389s

FAILED (errors=1, skipped=5)

```

**Comment by kovidgoyal** [comment]
dup of #5181

**Comment by lcheylus** [comment]
Sorry but it's not a strict duplicate of #5181 : here, I'm not using debian scripts to build package but your standard process to build and tests Kitty release 0.25.2 without modifications. There is an error with tests for prewarm kitten in this release but you don't want to analyze it more precisely.

Thanks for the explanation about master branch, currently broken.

**Comment by kovidgoyal** [comment]
On Mon, Jun 13, 2022 at 09:10:16AM -0700, Laurent Cheylus wrote:
> Sorry but it's not a strict duplicate of #5181 : here, I'm not using debian scripts to build package but your standard process to build and tests Kitty release 0.25.2 without modifications. There is an error with tests for prewarm kitten in this release but you don't want to analyze it more precisely.

As I said on your original bug report it doesnt replicate for me, on the
Linux distributions I use. And I am definitely not installing a debian
vm just to debug it. The kitten is present and importable. Why import is
failing on your machine, I cant tell you. Most likely something to do
with the python installation on your system. And I will note, ubuntu is based on
debian and the test works fine in CI on Ubuntu machines and Arch
machines. Try running

kitty +runpy 'import kittens.prewarm.main'

you might get more error information.

> 
> Thanks for the explanation about master branch, currently broken.

Already fixed.

**Comment by lcheylus** [comment]
Thanks, cherry picking of https://github.com/kovidgoyal/kitty/commit/a7c65efc4557a1b9f1f3ea3e82c171db2bb8ebe3 commit for `test.py` => `kitty_exe` is now OK (`kitty/launcher/kitty`) and prewarm test is successfull.
