### ISSUE TITLE
Kitty crashes on startup (MemoryError)

### ISSUE THREAD

**Issue by ThatOneCalculator** [kovidgoyal/kitty#5273]
**Describe the bug**

Whenever I run `kitty`, I get the following error:

```
~   kitty
[194 09:39:08.990062] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 423, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 415, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 204, in __call__
    _run_app(opts, args, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 183, in _run_app
    boss.start(window_id, startup_sessions)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 743, in start
    self.startup_first_child(first_os_window_id, startup_sessions=startup_sessions)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 280, in startup_first_child
    self.add_os_window(startup_session, os_window_id=os_window_id)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 311, in add_os_window
    tm = TabManager(os_window_id, self.args, wclass, wname, startup_session)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 777, in __init__
    self._add_tab(Tab(self, session_tab=t))
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 134, in __init__
    self.startup(session_tab)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 173, in startup
    self.new_special_window(cmd)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 464, in new_special_window
    return self.new_window(
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 448, in new_window
    self._add_window(window, location=location, overlay_for=overlay_for, overlay_behind=overlay_behind)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 418, in _add_window
    self.relayout()
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 244, in relayout
    self.current_layout(self.windows)
  File "/usr/bin/../lib/kitty/kitty/layout/base.py", line 326, in __call__
    self.do_layout(all_windows)
  File "/usr/bin/../lib/kitty/kitty/layout/tall.py", line 189, in do_layout
    self.layout_single_window_group(next(all_windows.iter_all_layoutable_groups()))
  File "/usr/bin/../lib/kitty/kitty/layout/base.py", line 339, in layout_single_window_group
    wg.set_geometry(geom)
  File "/usr/bin/../lib/kitty/kitty/window_list.py", line 111, in set_geometry
    w.set_geometry(geom)
  File "/usr/bin/../lib/kitty/kitty/window.py", line 699, in set_geometry
    self.screen.resize(new_geometry.ynum, new_geometry.xnum)
MemoryError
```

**To Reproduce**
1. Reboot system
2. Run kitty
3. See error

**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Linux cali 5.18.10-xanmod1-1-native_amd #1 SMP Sat, 09 Jul 2022 03:52:01 +0000 x86_64
Arch Linux 5.18.10-xanmod1-1-native_amd (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/kainoa/.bun/bin:/home/kainoa/.nvm/versions/node/v18.2.0/bin:/home/kainoa/.local/bin:/usr/local/bin:/home/kainoa/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/home/kainoa/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	EDITOR                              micro
	SHELL                               /bin/zsh
	DISPLAY                             :1
	WAYLAND_DISPLAY                     wayland-0
	USER                                kainoa
	LC_ADDRESS                          en_US.UTF-8
	LC_IDENTIFICATION                   en_US.UTF-8
	LC_MEASUREMENT                      en_US.UTF-8
	LC_MONETARY                         en_US.UTF-8
	LC_NAME                             en_US.UTF-8
	LC_NUMERIC                          en_US.UTF-8
	LC_PAPER                            en_US.UTF-8
	LC_TELEPHONE                        en_US.UTF-8
	LC_TIME                             en_US.UTF-8
	XDG_CURRENT_DESKTOP                 hyprland
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SEAT                            seat0
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 
	XDG_SESSION_ID                      2
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_SESSION_TYPE                    wayland
	XDG_VTNR                            2
```

**Additional context**
The problem does NOT occur with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
presumably the saved kitty window size is too large. Use the option in
kitty.conf 

remember_window_size no

**Comment by ThatOneCalculator** [comment]
Yep, that fixed the issue. Unrelated, but how do I disable this message?

![image](https://user-images.githubusercontent.com/44733677/178790091-30673c46-5a41-4fde-9f01-2691f0764291.png)

**Comment by kovidgoyal** [comment]
confirm_os_window_close

**Comment by iver0** [comment]
Still happens, `remember_window_size no` fixes it.

Can this bug be prevented from happening in the first place? Like ignoring incorrect window size which would cause this crash?

**Comment by kovidgoyal** [comment]
What is an incorrect window size?

**Comment by iver0** [comment]
Possibly it still doesn't prevent a window size inside this range which can't be used on a specific display? Idk, it results in a crash

**Comment by kovidgoyal** [comment]
The crash has nothing to do with display. Its a memory error indicating
your machine does not have enough RAM for a window of the size.

**Comment by iver0** [comment]
Probably it's because window size is too big? I have 16 GB RAM, there's swap, and this crash was happening after a reboot as well, meaning there had to be some unreasonable window size that kitty was trying to set.

Don't know how it saved this incorrect window size either, I run it in fullscreen, without changing window size manually.
