### ISSUE TITLE
Kitty crash on start up in Sway(Wayland)

### ISSUE THREAD

**Issue by glyh** [kovidgoyal/kitty#5301]
**Describe the bug**
As title.

**To Reproduce**
1.  
```bash
gdb `which kitty`
```
```
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/lice
nses/gpl.html>
This is free software: you are free to change and redistribute 
it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at
:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/kitty...
(No debugging symbols found in /usr/bin/kitty)
(gdb) r --config NONE
Starting program: /usr/bin/kitty --config NONE
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffea762640 (LWP 12847)]
[New Thread 0x7fffe9e20640 (LWP 12848)]
[New Thread 0x7fffe961f640 (LWP 12849)]
[New Thread 0x7fffe8e1e640 (LWP 12850)]
[New Thread 0x7fffd3fff640 (LWP 12851)]
[New Thread 0x7fffd37fe640 (LWP 12852)]
[New Thread 0x7fffcaffd640 (LWP 12853)]
[New Thread 0x7fffd2ffd640 (LWP 12854)]
[New Thread 0x7fffd27fc640 (LWP 12855)]
[New Thread 0x7fffd1ffb640 (LWP 12856)]
[New Thread 0x7fffd17fa640 (LWP 12857)]
[New Thread 0x7fffd0ff9640 (LWP 12858)]
[New Thread 0x7fffcbfff640 (LWP 12859)]
[New Thread 0x7fffcb7fe640 (LWP 12860)]
[New Thread 0x7fffca7fc640 (LWP 12861)]
[New Thread 0x7fffc9ffb640 (LWP 12862)]
[New Thread 0x7fffc97fa640 (LWP 12863)]
[New Thread 0x7fffc8ff9640 (LWP 12864)]
[New Thread 0x7fff9bfff640 (LWP 12865)]
[New Thread 0x7fff9b7fe640 (LWP 12866)]

Thread 1 "kitty" received signal SIGSEGV, Segmentation fault.
0x00007ffff5dfc9d4 in wl_proxy_get_version () from /usr/lib/lib
wayland-client.so.0
(gdb) bt
#0  0x00007ffff5dfc9d4 in wl_proxy_get_version ()
   from /usr/lib/libwayland-client.so.0
#1  0x00007ffff5e2067f in ?? ()
   from /usr/lib/kitty/kitty/glfw-wayland.so
#2  0x00007ffff5e2532a in ?? ()
   from /usr/lib/kitty/kitty/glfw-wayland.so
#3  0x00007ffff5e186de in ?? ()
   from /usr/lib/kitty/kitty/glfw-wayland.so
#4  0x00007ffff5f83536 in ?? () from /usr/lib/libffi.so.8
#5  0x00007ffff5f80037 in ?? () from /usr/lib/libffi.so.8
#6  0x00007ffff5dfc645 in ?? ()
   from /usr/lib/libwayland-client.so.0
#7  0x00007ffff5dfce03 in ?? ()
   from /usr/lib/libwayland-client.so.0
#8  0x00007ffff5dfcffc in wl_display_dispatch_queue_pending ()
   from /usr/lib/libwayland-client.so.0
#9  0x00007ffff5dffc60 in wl_display_roundtrip_queue ()
   from /usr/lib/libwayland-client.so.0
#10 0x00007ffff5e161db in ?? ()
   from /usr/lib/kitty/kitty/glfw-wayland.so
#11 0x00007ffff5e1db20 in glfwCreateWindow ()
   from /usr/lib/kitty/kitty/glfw-wayland.so
#12 0x00007ffff68042e4 in ?? ()
   from /usr/bin/../lib/kitty/kitty/fast_data_types.so
#13 0x00007ffff7d3b511 in ?? ()
   from /usr/lib/libpython3.10.so.1.0
#14 0x00007ffff7d34deb in _PyObject_MakeTpCall ()
   from /usr/lib/libpython3.10.so.1.0
#15 0x00007ffff7d306eb in _PyEval_EvalFrameDefault ()
   from /usr/lib/libpython3.10.so.1.0
#16 0x00007ffff7d3b9c9 in _PyFunction_Vectorcall ()
   from /usr/lib/libpython3.10.so.1.0
#17 0x00007ffff7d2ad86 in _PyEval_EvalFrameDefault ()
   from /usr/lib/libpython3.10.so.1.0
#18 0x00007ffff7d340db in _PyObject_FastCallDictTstate ()
   from /usr/lib/libpython3.10.so.1.0
#19 0x00007ffff7d447cd in _PyObject_Call_Prepend ()
--Type <RET> for more, q to quit, c to continue without paging-
-
   from /usr/lib/libpython3.10.so.1.0
#20 0x00007ffff7e11bd2 in ?? ()
   from /usr/lib/libpython3.10.so.1.0
#21 0x00007ffff7d34deb in _PyObject_MakeTpCall ()
   from /usr/lib/libpython3.10.so.1.0
#22 0x00007ffff7d2fba4 in _PyEval_EvalFrameDefault ()
   from /usr/lib/libpython3.10.so.1.0
#23 0x00007ffff7d3b9c9 in _PyFunction_Vectorcall ()
   from /usr/lib/libpython3.10.so.1.0
#24 0x00007ffff7d2ad86 in _PyEval_EvalFrameDefault ()
   from /usr/lib/libpython3.10.so.1.0
#25 0x00007ffff7d3b9c9 in _PyFunction_Vectorcall ()
   from /usr/lib/libpython3.10.so.1.0
#26 0x00007ffff7d2ad86 in _PyEval_EvalFrameDefault ()
   from /usr/lib/libpython3.10.so.1.0
#27 0x00007ffff7d3b9c9 in _PyFunction_Vectorcall ()
   from /usr/lib/libpython3.10.so.1.0
#28 0x00007ffff7d2ad86 in _PyEval_EvalFrameDefault ()
   from /usr/lib/libpython3.10.so.1.0
#29 0x00007ffff7d299d0 in ?? ()
   from /usr/lib/libpython3.10.so.1.0
#30 0x00007ffff7dd9ea4 in PyEval_EvalCode ()
   from /usr/lib/libpython3.10.so.1.0
#31 0x00007ffff7de013b in ?? ()
   from /usr/lib/libpython3.10.so.1.0
#32 0x00007ffff7d3bbbf in ?? ()
   from /usr/lib/libpython3.10.so.1.0
#33 0x00007ffff7d2ad86 in _PyEval_EvalFrameDefault ()
   from /usr/lib/libpython3.10.so.1.0
#34 0x00007ffff7d3b9c9 in _PyFunction_Vectorcall ()
   from /usr/lib/libpython3.10.so.1.0
#35 0x00007ffff7d2ad86 in _PyEval_EvalFrameDefault ()
   from /usr/lib/libpython3.10.so.1.0
#36 0x00007ffff7d3b9c9 in _PyFunction_Vectorcall ()
   from /usr/lib/libpython3.10.so.1.0
#37 0x00007ffff7dfda77 in ?? ()
   from /usr/lib/libpython3.10.so.1.0
--Type <RET> for more, q to quit, c to continue without paging-
-
#38 0x00007ffff7c7bf15 in ?? ()
   from /usr/lib/libpython3.10.so.1.0
#39 0x0000555555555593 in main ()
(gdb) 
(gdb) exit
A debugging session is active.

        Inferior 1 [process 12709] will be killed.

Quit anyway? (y or n) y


```

**Additional context**

I can reproduce this when I don't have a mouse plugged to my laptop. But when I plugged it on, it runs smoothly. The issue is very weird and I guess it has something to do with sway.

**Comment by kovidgoyal** [comment]
Does not crash for me with those steps with sway 1.7 and kitty 0.25.2. From the
backtrace the crash apears to be a crash in libwayland-client getting a
version number. You might get more information if you build kitty form
source with make debug.
