### ISSUE TITLE
set_tab_title not working in 0.26.0

### ISSUE THREAD

**Issue by djensenius** [kovidgoyal/kitty#5441]
**Describe the bug**
`set_tab_title` is not working

**To Reproduce**
I have shortcuts to quickly title tabs:
For example:
```
map kitty_mod+shift+c set_tab_title 
```

This fails as following:
```
Failed to parse action

set_tab_title HELLO
'Unknown action: set_tab_title'

Press e to see detailed traceback or any other key to exit
Traceback (most recent call last):
  File "lib/python3.9/kitty/boss.py", line 1304, in combine
  File "lib/python3.9/kitty/options/utils.py", line 945, in resolve_aliases
  File "lib/python3.9/kitty/options/utils.py", line 995, in resolve_aliases_and_parse_actions
  File "lib/python3.9/kitty/options/utils.py", line 921, in parse_key_action
KeyError: 'Unknown action: set_tab_title'

Press Enter or Esc to exit
```

Further, if I try to interactively set the title, it fails silently.

**Screenshots**

**Environment details**
```
kitty 0.26.0 created by Kovid Goyal
Darwin GitHub.local 22.1.0 Darwin Kernel Version 22.1.0: Mon Aug 15 20:07:13 PDT 2022; root:xnu-8792.40.29.161.2~1/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		13.0 BuildVersion:		22A5331f
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/homebrew/bin/fish
Loaded config files:
  /Users/djensenius/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_title_template  {fmt.fg._83b6af}{fmt.bg.default} ﱣ {index}:{f'{title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 13 else title}{' []' if layout_name == 'stack' else ''} 
bell_on_tab                
confirm_os_window_close    0
disable_ligatures          1
font_family                Fira Code
font_size                  13.0
macos_show_window_title_in none
macos_titlebar_color       1
modify_font:
    cell_height 140%
symbol_map:
	U+21b5 - U+21b5 → Hack Nerd Font Mono
	U+23fb - U+23fe → Hack Nerd Font Mono
	U+25b8 - U+25b8 → Hack Nerd Font Mono
	U+2605 - U+2605 → Hack Nerd Font Mono
	U+2630 - U+2630 → Hack Nerd Font Mono
	U+2632 - U+2632 → Hack Nerd Font Mono
	U+2665 - U+2665 → Hack Nerd Font Mono
	U+26a1 - U+26a1 → Hack Nerd Font Mono
	U+2714 - U+2714 → Hack Nerd Font Mono
	U+2b58 - U+2b58 → Hack Nerd Font Mono
	U+e000 - U+e00d → Hack Nerd Font Mono
	U+e0a0 - U+e0a2 → Hack Nerd Font Mono
	U+e0a3 - U+e0a3 → Hack Nerd Font Mono
	U+e0b0 - U+e0b3 → Hack Nerd Font Mono
	U+e0b4 - U+e0c8 → Hack Nerd Font Mono
	U+e0cc - U+e0d2 → Hack Nerd Font Mono
	U+e0d4 - U+e0d4 → Hack Nerd Font Mono
	U+e200 - U+e2a9 → Hack Nerd Font Mono
	U+e300 - U+e3eb → Hack Nerd Font Mono
	U+e5fa - U+e62b → Hack Nerd Font Mono
	U+e615 - U+e615 → Hack Nerd Font Mono
	U+e62b - U+e62b → Hack Nerd Font Mono
	U+e700 - U+e7c5 → Hack Nerd Font Mono
	U+ea60 - U+ebeb → codicon
	U+f000 - U+f2e0 → Hack Nerd Font Mono
	U+f27c - U+f27c → Hack Nerd Font Mono
	U+f300 - U+f313 → Hack Nerd Font Mono
	U+f400 - U+f4a8 → Hack Nerd Font Mono
	U+f500 - U+fd46 → Hack Nerd Font Mono
tab_bar_edge               1
tab_bar_style              custom
tab_fade                   (0, 0, 0, 0)
tab_separator              
tab_title_template         {fmt.fg._415c6d}{fmt.bg.default} ○ {index}:{f'{title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 13 else title}{' []' if layout_name == 'stack' else ''} 
Added shortcuts:
	kitty_mod+a →  set_tab_title HELLO
Removed shortcuts:
	kitty_mod+a > 1 →  set_background_opacity 1
	kitty_mod+a > d →  set_background_opacity default
	kitty_mod+a > l →  set_background_opacity -0.1
	kitty_mod+a > m →  set_background_opacity +0.1
Changed shortcuts:
	kitty_mod+c →  set_tab_title 
	kitty_mod+l →  set_tab_title 
	kitty_mod+t →  set_tab_title

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_CA.UTF-8
	SHELL                               /opt/homebrew/bin/fish
	USER                                djensenius

```

**Additional context**

**Comment by kovidgoyal** [comment]
set_tab_title doesnt take arguments, it's meant for interactive usage only.

```
map f1 set_tab_title
```

will work fine.

**Comment by kovidgoyal** [comment]
And here I have added support for supplying arguments to this action: https://github.com/kovidgoyal/kitty/commit/5b28aed0b116621c7dad5e0b3fe60ef13399fb4c

**Comment by djensenius** [comment]
Awesome!!! Thank you! 

I'm still seeing it not change my tab title, but that could be another issue in my config.

https://user-images.githubusercontent.com/782512/187228470-b7f792c0-95fe-4756-ace6-93b9764bca44.mov

**Comment by kovidgoyal** [comment]
You have some custom tab bar I am guessing, first make sure it works with the default tab bar

**Comment by kovidgoyal** [comment]
Then I need a way to reproduce. Bisect your kitty.conf and post a
minimal version that reproduces.

**Comment by kovidgoyal** [comment]
I tried it with your full config and it works for me, pressing super+shift+i and typing in a new tab title, the title in the tab bar changes, as expected.

**Comment by djensenius** [comment]
https://gist.github.com/djensenius/56e5826695be722913a20c54c967e81e

Here is one without custom tabs. It does not rename the tab, just keeps the path as the title. I'm on macOS.

**Comment by kovidgoyal** [comment]
ah, macOS. You are probably suffering from a side-effect of #5439.

TO confirm start kitty from another terminal as

LANG=en_US.UTF-8 /Applications/kitty.app/Contents/MacOS/kitty

and it should work

**Comment by djensenius** [comment]
Aha! That did indeed work!
