### ISSUE TITLE
Gives this error when i try to run it ValueError: Failed to create GLFWwindow

### ISSUE THREAD

**Issue by Robinvcx** [kovidgoyal/kitty#5498]
Your Wayland compositor does not support server side window decorations, disabling Wayland. You can force Wayland support using the linux_display_server option in kitty.conf See https://drewdevault.com/2018/01/27/Sway-and-client-side-decorations.html for more information.
[254 23:52:46.027478] [glfw error 65540]: Invalid window size 0x0
[254 23:52:46.054393] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 344, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 337, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 160, in __call__
    _run_app(opts, args, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 133, in _run_app
    window_id = create_os_window(
ValueError: Failed to create GLFWwindow

**Comment by kovidgoyal** [comment]
Use the official kitty binaries.
