### ISSUE TITLE
diff kitten crashes

### ISSUE THREAD

**Issue by SolitudeSF** [kovidgoyal/kitty#558]
diff kitten crashes when scrolling up at the start of the diff or when switching to next diff.
```
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kittens/tui/loop.py", line 392, in loop
    key.data(handler)
  File "/usr/bin/../lib/kitty/kittens/tui/loop.py", line 291, in _write_ready
    handler.write_buf[self.iov_limit - 1] = b''.join(handler.write_buf[self.iov_limit - 1:])
IndexError: list assignment index out of range
```

also, what is the difference between `kitten` and `+kitten`?

**Comment by SolitudeSF** [comment]
thanks. im not sure this needs another issue, but diff kitten acts strangely if used as `git difftool`. it crashes on  in one of my repos it crashes after displaying only 3 diffs with 
```
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kittens/tui/loop.py", line 192, in _run_job
    result = func(*args, **kw)
  File "/usr/bin/../lib/kitty/kittens/diff/main.py", line 47, in generate_diff
    return d(context)
  File "/usr/bin/../lib/kitty/kittens/diff/patch.py", line 229, in __call__
    right_lines = lines_for_path(right_path)
  File "/usr/bin/../lib/kitty/kittens/diff/collect.py", line 155, in lines_for_path
    data = data_for_path(path).replace('\t', lines_for_path.replace_tab_by)
TypeError: a bytes-like object is required, not 'str'
```
in all cases it crashes after using context-related keybinds.
```
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kittens/tui/loop.py", line 392, in loop
    key.data(handler)
  File "/usr/bin/../lib/kitty/kittens/tui/loop.py", line 329, in _wakeup_ready
    handler.on_job_done(job_id, entry)
  File "/usr/bin/../lib/kitty/kittens/diff/main.py", line 333, in on_job_done
    self.draw_screen()
  File "/usr/bin/../lib/kitty/kittens/diff/main.py", line 231, in draw_screen
    self.draw_lines(self.num_lines)
  File "/usr/bin/../lib/kitty/kittens/diff/main.py", line 178, in draw_lines
    line = self.diff_lines[lpos]
IndexError: tuple index out of range
```
but, in some cases when using `a` instead of crashing it displays diff shifted and partially duplicated (disregard the colors)
![image](https://user-images.githubusercontent.com/10168645/40302547-1503f486-5cf8-11e8-9d15-de3babfe0cb8.png)

`.gitconfig` stuff copied directly from diff readme.

**Comment by kovidgoyal** [comment]
You have to use --no-symlinks when invoking with git difftool

git difftool --no-symlinks

**Comment by kovidgoyal** [comment]
See the kitten's readme for details.

**Comment by kovidgoyal** [comment]
Feel free to send a PR to improve the wording in the README, I'll be happy to merge. Also, I just committed some code to remove the need for --no-symlinks however --dir-diff is still mandatory
