### ISSUE TITLE
libEGL warning: MESA-LOADER: failed to open radeonsi

### ISSUE THREAD

**Issue by zillem** [kovidgoyal/kitty#5608]
I'm not sure what happened to trigger this.
I run Fedora 36 with wayland. One day kitty stopped working, possibly after an update, I don't use kitty every day, so it's hard to say if that was the trigger.

Is this a kitty bug, or a problem with LLVM?

```
[292 20:07:24.434004] Ignoring invalid config line: url_excluded_characters
libEGL warning: MESA-LOADER: failed to open radeonsi: libLLVM-15git.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix _dri)

libEGL warning: MESA-LOADER: failed to open swrast: libLLVM-15git.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix _dri)

[292 20:07:24.458146] [glfw error 65542]: EGL: Failed to initialize EGL: EGL is not or could not be initialized
[292 20:07:24.459973] Traceback (most recent call last):
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 449, in main
    _main()
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 441, in _main
    run_app(opts, cli_opts, prewarm, bad_lines)
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 205, in __call__
    _run_app(opts, args, prewarm, bad_lines)
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 178, in _run_app
    window_id = create_os_window(
ValueError: Failed to create GLFWwindow
```

**Comment by kovidgoyal** [comment]
That's a GPU driver problem.
