### ISSUE TITLE
Unable to open file with `Open Actions`

### ISSUE THREAD

**Issue by hacker-DOM** [kovidgoyal/kitty#5633]
**Description**
I have

`/Users/dteiml/.config/kitty/open-actions.conf`
```
# Open any file with a fragment in vim, fragments are generated
# by the hyperlink_grep kitten and nothing else so far.
protocol file
fragment_matches [0-9]+
action launch --type=overlay --cwd=current ${EDITOR} +${FRAGMENT} ${FILE_PATH}

# Open text files without fragments in the editor
protocol file
mime text/*
action launch --type=overlay --cwd=current ${EDITOR} ${FILE_PATH}
```

I also have two files:

```
❯ file -I __init__.py
__init__.py: text/x-script.python; charset=us-ascii
❯ file -I .zshrc-old 
.zshrc-old: text/plain; charset=utf-8
```

I run `lsd -a --hyperlink auto`. Fsr, when I click on the first one, it correctly opens in neovim, whereas the second opens in TextEdit.

Similar behavior is observed when right clicking and `Open with .. Kitty.app` in Finder - the first opens in nvim, for the second, I get 

```
Open URL Error

Unknown URL type, cannot open:
  file:///Users/dteiml/Dropbox/config/zsh/.zshrc-old

Press Enter or Esc to exit
```

Fwiw, both of these issues are solved if I rename the file `.zshrc-old  ->  .zshrc-old.py`

**Environment details**
```
kitty 0.26.3 created by Kovid Goyal
Darwin Dominiks-Air.docsis.vodafone.cz 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64
ProductName:		macOS ProductVersion:		13.0 BuildVersion:		22A380
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/dteiml/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_font_style          (False, False)
allow_remote_control           password
background_opacity             0.75
dynamic_background_opacity     True
enabled_layouts                ['horizontal', 'tall']
font_size                      15.0
kitty_mod                      ctrl+cmd
listen_on                      unix:/tmp/mykitty
macos_menubar_title_max_length 25
macos_option_as_alt            3
remote_control_password:
{'foobar': ('ls',)}
scrollback_pager               ['/usr/local/bin/less', '--chop-long-lines', '--RAW-CONTROL-CHARS', '+INPUT_LINE_NUMBER']
startup_session                /Users/dteiml/.config/kitty/default.kitty
tab_bar_align                  center
tab_bar_min_tabs               1
tab_fade                       (0, 0.33, 0.66, 1.0)
tab_powerline_style            round
tab_switch_strategy            left
tab_title_template             {title[:25]} ({num_windows})
watcher:
{'${HOME}/.fig/tools/kitty-integration.py': '${HOME}/.fig/tools/kitty-integration.py'}
window_margin_width            FloatEdges(left=5.0, top=5.0, right=5.0, bottom=5.0)
Added shortcuts:
	kitty_mod+p > shift+h →  kitten hints --type hash --program @
	kitty_mod+p > shift+l →  kitten hints --type line --program @
	kitty_mod+p > shift+n →  kitten hints --type linenum --program @
	kitty_mod+p > shift+w →  kitten hints --type word --program @ --multiple
	kitty_mod+p > shift+y →  kitten hints --type hyperlink --program @
	kitty_mod+shift+, →  scroll_end
	kitty_mod+shift+b →  launch --allow-remote-control kitty +kitten broadcast
	kitty_mod+shift+d →  detach_window ask
	kitty_mod+shift+down →  move_window down
	kitty_mod+shift+h →  combine | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up
	kitty_mod+shift+j →  combine | scroll_line_down | scroll_line_down | scroll_line_down | scroll_line_down | scroll_line_down | scroll_line_down | scroll_line_down | scroll_line_down | scroll_line_down | scroll_line_down | scroll_line_down | scroll_line_down | scroll_line_down | scroll_line_down | scroll_line_down | scroll_line_down | scroll_line_down | scroll_line_down | scroll_line_down | scroll_line_down
	kitty_mod+shift+k →  combine | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up | scroll_line_up
	kitty_mod+shift+left →  move_window left
	kitty_mod+shift+m →  scroll_home
	kitty_mod+shift+right →  move_window right
	kitty_mod+shift+t →  launch --type=overlay
	kitty_mod+shift+up →  move_window up
	kitty_mod+shift+w →  scroll_end
	opt+0 →  nth_window 9
	opt+1 →  nth_window 0
	opt+2 →  nth_window 1
	opt+3 →  nth_window 2
	opt+4 →  nth_window 3
	opt+5 →  nth_window 4
	opt+6 →  nth_window 5
	opt+7 →  nth_window 6
	opt+8 →  nth_window 7
	opt+9 →  nth_window 8
	shift+down →  neighboring_window down
	shift+left →  neighboring_window left
	shift+right →  neighboring_window right
	shift+up →  neighboring_window up
Removed shortcuts:
	ctrl+cmd+, →  load_config_file
	ctrl+cmd+f →  toggle_fullscreen
Changed shortcuts:
	cmd+1 →  goto_tab 1
	cmd+2 →  goto_tab 2
	cmd+3 →  goto_tab 3
	cmd+4 →  goto_tab 4
	cmd+5 →  goto_tab 5
	cmd+6 →  goto_tab 6
	cmd+7 →  goto_tab 7
	cmd+8 →  goto_tab 8
	cmd+9 →  goto_tab 9
	cmd+enter →  launch --cwd=current
	cmd+t →  launch --type=tab --cwd=current --location=neighbor
	kitty_mod+, →  load_config_file
	kitty_mod+b →  launch --allow-remote-control kitty +kitten broadcast --match-tab state:focused
	kitty_mod+escape →  kitty_shell overlay
	kitty_mod+f →  toggle_fullscreen
	kitty_mod+left →  move_tab_backward
	kitty_mod+p > shift+f →  kitten hints --type path --program @
	kitty_mod+p > w →  kitten hints --type word --multiple --program -
	kitty_mod+right →  move_tab_forward
	kitty_mod+s →  send_text all \x17
	kitty_mod+t →  set_tab_title
Colors:
	active_tab_background          #d9bd5f   
	inactive_tab_background        #5f86d9   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                dteiml
```

**Additional context**
Also, the following command is failing:

```
❯ kitty +runpy 'from kitty.fast_data_types import cocoa_set_url_handler; import sys; cocoa_set_url_handler(*sys.argv[1:]); print("OK")' file                         
Traceback (most recent call last):
  File "lib/python3.9/runpy.py", line 197, in _run_module_as_main
  File "lib/python3.9/runpy.py", line 87, in _run_code
  File "lib/python3.9/kitty_main.py", line 7, in <module>
  File "lib/python3.9/kitty/entry_points.py", line 201, in main
  File "lib/python3.9/kitty/entry_points.py", line 152, in namespaced
  File "lib/python3.9/kitty/entry_points.py", line 30, in runpy
  File "<string>", line 1, in <module>
OSError: Failed to set default handler with error code: -50
```

**Comment by kovidgoyal** [comment]
mimetypes are generated from filenames, not file contents. The file
command uses file contents to deduce mimetypes, so file saying a file is
text/plain doesnt mean it is text/plain to kitty.

**Comment by hacker-DOM** [comment]
So there is no way to open a file like `.zshrc` and have it be opened e.g. in `vim`?

**Comment by kovidgoyal** [comment]
write a script and set it as the handler for all mime types and have it
open whatever program you like based on whatever criteria you like.

**Comment by page-down** [comment]
I remember that this issue has been discussed somewhere before.

@hacker-DOM

> So there is no way to open a file like .zshrc ...

Matching file extensions by `ext` works fine.

```conf
protocol file
ext zshrc-old
action launch --type os-window vi ${FILE_PATH}
```

It is also possible to specify the MIME type of any file extension via the `mime.types` configuration file.
So the following will work.

~/.config/kitty/mime.types
```conf
text/plain zshrc-old and whatever you like
```

~/.config/kitty/open-actions.conf
```conf
protocol file
mime text/*
action launch --type os-window vi ${FILE_PATH}
```

These are all described in the documentation.
https://sw.kovidgoyal.net/kitty/open_actions/

I see that you are confused about these, and if you think the document is not clearly expressed, you can bring up improvements.
