### ISSUE TITLE
launch --hold error

### ISSUE THREAD

**Issue by braulio-balanza** [kovidgoyal/kitty#5656]
**Describe the bug**
The launch command's --hold option returns an error.

**To Reproduce**
1. create a session.conf file
2. add the following ```launch --hold sh ```
3. run kitty --session ./session.conf

**Environment details**
```
kitty 0.21.2 created by Kovid Goyal
Linux pop-os 6.0.6-76060006-generic #202210290932~1667401208~22.04~d2df702 SMP PREEMPT_DYNAMIC Wed N x86_>
Pop!_OS 22.04 LTS \n \l
DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"
Running under:X11
Loaded config files:
  /etc/xdg/kitty/kitty.conf
  /home/balanza/.config/kitty/kitty.conf

Config options different from defaults:
background            Color(red=64, green=62, blue=65)
cursor                Color(red=252, green=252, blue=250)
cursor_text_color     Color(red=0, green=0, blue=0)
font_family           FiraCode Nerd Font
foreground            Color(red=252, green=252, blue=250)
selection_background  Color(red=252, green=252, blue=250)
selection_foreground  Color(red=64, green=62, blue=65)
startup_session       /home/balanza/.config/kitty/./sessions/startup_session.conf
update_check_interval 0.0
```

**Additional context**
Stack trace obtained by running kitty --conf NONE --session session.conf: 
```
kitty --config NONE --session .config/kitty/sessions/net_sec_dns.conf 
[314 03:42:16.280545] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/launch.py", line 179, in parse_launch_args
    opts, args = parse_args(result_class=LaunchCLIOptions, args=args, ospec=options_spec)
  File "/usr/bin/../lib/kitty/kitty/cli.py", line 748, in parse_args
    return ans, parse_cmdline(oc, disabled, ans, args=args)
  File "/usr/bin/../lib/kitty/kitty/cli.py", line 517, in parse_cmdline
    needs_arg = oc.needs_arg(parts[0])
  File "/usr/bin/../lib/kitty/kitty/cli.py", line 466, in needs_arg
    opt = self.opt_for_alias(alias)
  File "/usr/bin/../lib/kitty/kitty/cli.py", line 459, in opt_for_alias
    raise SystemExit('Unknown option: {}'.format(emph(alias)))
SystemExit: Unknown option: --hold

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 344, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 337, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 183, in __call__
    _run_app(opts, args, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 162, in _run_app
    boss.start(window_id)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 533, in start
    self.startup_first_child(first_os_window_id)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 188, in startup_first_child
    for startup_session in startup_sessions:
  File "/usr/bin/../lib/kitty/kitty/session.py", line 167, in create_sessions
    yield from parse_session(session_data, opts, getattr(args, 'title', None))
  File "/usr/bin/../lib/kitty/kitty/session.py", line 122, in parse_session
    ans.add_window(rest)
  File "/usr/bin/../lib/kitty/kitty/session.py", line 67, in add_window
    spec = parse_launch_args(cmd)
  File "/usr/bin/../lib/kitty/kitty/launch.py", line 181, in parse_launch_args
    raise ValueError from e
ValueError

```

**Comment by kovidgoyal** [comment]
your version of kitty is too old. update.
