### ISSUE TITLE
UnicodeDecodeError when attempting to open an image

### ISSUE THREAD

**Issue by tenleftfingers** [kovidgoyal/kitty#5705]
**Describe the bug**
When I run the command:
env LIBGL_ALWAYS_SOFTWARE=1 kitty Pictures/tng.png
I get the error.

**To Reproduce**
1. run the command above command on an image
...
2. See error

**Screenshots**
```
env LIBGL_ALWAYS_SOFTWARE=1 kitty Pictures/tng.png 
[328 20:38:02.660572] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 344, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 337, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 183, in __call__
    _run_app(opts, args, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 162, in _run_app
    boss.start(window_id)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 533, in start
    self.startup_first_child(first_os_window_id)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 189, in startup_first_child
    self.add_os_window(startup_session, os_window_id=os_window_id)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 218, in add_os_window
    tm = TabManager(os_window_id, self.args, wclass, wname, startup_session)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 554, in __init__
    self._add_tab(Tab(self, session_tab=t))
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 116, in __init__
    self.startup(session_tab)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 151, in startup
    self.new_special_window(cmd)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 387, in new_special_window
    return self.new_window(
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 363, in new_window
    child = self.launch_child(
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 326, in launch_child
    if f.read(2) == '#!':
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```.

**Environment details**
```
kitty 0.21.2 created by Kovid Goyal
Linux E4310 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64
Ubuntu 22.04.1 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
Running under:Wayland
Loaded config files:
  /etc/xdg/kitty/kitty.conf

Config options different from defaults:
update_check_interval 0.0

```

**Additional context**
 `kitty --config NONE` made no difference.

**Comment by kovidgoyal** [comment]
If you want to view an image in a new kitty instance, the correct command is

kitty kitty +kitten icat --hold image.png
