### ISSUE TITLE
Cancelling out of `kitty +kitten remote_file` shows Traceback

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#5915]
**Describe the bug**
Cancelling out of `kitty +kitten remote_file` shows Traceback

**To Reproduce**
1. Launch kitty like this: `kitty --config NONE`
2. `kitty +kitten remote_file`
3. `ESC` or `C` to cancel

**Observed Behavior**
```
Traceback (most recent call last):
  File "kittens/remote_file/main.py", line 246, in main
  File "kittens/remote_file/main.py", line 312, in handle_action
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Failed with unhandled exception

Press any key to quit
```

**Environment details**
```
kitty 0.26.5 () created by Kovid Goyal
Linux byteevo 5.15.0-58-generic #64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023 x86_64
Ubuntu 20.04.5 LTS byteevo /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/precor/.local/kitty.app/bin/kitty
  base dir: /home/precor/.local/kitty.app/lib/kitty
  extensions dir: /home/precor/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/precor/.nvm/versions/node/v14.18.2/bin:/opt/qt/5.15.2/gcc_64/bin:/home/precor/.local/flutter/bin:/home/precor/.pub-cache/bin:/home/precor/Android/Sdk/build-tools/30.0.3:/home/precor/Android/Sdk/emulator:/home/precor/Android/Sdk/platform-tools:/home/precor/Android/Sdk/cmdline-tools/latest/bin:/home/precor/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                precor
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-ubuntu:/etc/xdg
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 ubuntu
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 ubuntu:GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/share/ubuntu:/usr/local/share/:/usr/share/
```

**Additional context**
- Running Nightly from yesterday.

**Comment by kovidgoyal** [comment]
remote_file is not meant to be run directly, it is used internally by
kitty, see https://sw.kovidgoyal.net/kitty/kittens/remote_file/

when you use it as intended the traceback is not visible since the
overlay window closes on exit.
