### ISSUE TITLE
Kitty crashes with "general protection fault"

### ISSUE THREAD

**Issue by ppwwyyxx** [kovidgoyal/kitty#5940]
**Describe the bug**
Kitty crashes with the following error in `dmesg`:
```
traps: kitty[2069122] general protection fault ip:7f8df838b5c0 sp:7ffdfca00de0 error:0 in libpython3.10.so.1.0[7f8df82bf000+225000]
```

I don't remember what exactly I was doing, but probably just switching tabs or panes.

**To Reproduce**
I don't know how to reproduce it. Just posting in case it helps.

Here is the backtrace from the coredump:
```
#0  0x00007f8df838b5c0 in pymalloc_alloc (ctx=<optimized out>, nbytes=78) at Objects/obmalloc.c:1942
#1  _PyObject_Malloc (nbytes=78, ctx=<optimized out>) at Objects/obmalloc.c:1961
#2  PyObject_Malloc (size=<optimized out>) at Objects/obmalloc.c:685
#3  PyUnicode_New (maxchar=127, size=<optimized out>) at Objects/unicodeobject.c:1463
#4  unicode_decode_utf8 (s=0x7f8df6ffdbcd "dispatch_possible_special_key", size=29, error_handler=_Py_ERROR_UNKNOWN, errors=0x0, consumed=0x0)
    at Objects/unicodeobject.c:5203
#5  0x00007f8df83be726 in PyObject_GetAttrString (v=0x7f8df5f92ad0, name=<optimized out>) at Objects/object.c:812
#6  0x00007f8df84a565f in _PyObject_CallMethod_SizeT (obj=<optimized out>, name=<optimized out>, format=0x7f8df6fef831 "O") at Objects/call.c:644
#7  0x00007f8df6f9065b in ?? () from /usr/bin/../lib/kitty/kitty/fast_data_types.so
#8  0x00007f8df5f3327a in ?? () from /usr/lib/kitty/kitty/glfw-x11.so
#9  0x00007f8df5f32833 in ?? () from /usr/lib/kitty/kitty/glfw-x11.so
#10 0x00007f8df5d4dbc0 in _dbus_pending_call_finish_completion (pending=0x55b29982cd30) at /build/dbus/src/dbus/dbus/dbus-pending-call.c:243
#11 _dbus_pending_call_finish_completion (pending=0x55b29982cd30) at /build/dbus/src/dbus/dbus/dbus-pending-call.c:233
#12 complete_pending_call_and_unlock (connection=<optimized out>, pending=0x55b29982cd30, message=<optimized out>) at /build/dbus/src/dbus/dbus/dbus-connection.c:2332
#13 0x00007f8df5d52120 in dbus_connection_dispatch (connection=0x55b29804a4a0) at /build/dbus/src/dbus/dbus/dbus-connection.c:4651
#14 dbus_connection_dispatch (connection=0x55b29804a4a0) at /build/dbus/src/dbus/dbus/dbus-connection.c:4574
#15 0x00007f8df5f24af9 in glfwRunMainLoop () from /usr/lib/kitty/kitty/glfw-x11.so
#16 0x00007f8df6f69748 in ?? () from /usr/bin/../lib/kitty/kitty/fast_data_types.so
#17 0x000055b297d52610 in ?? ()
#18 0x00007f8df83beae4 in method_vectorcall_NOARGS (func=0x7f8df75db740, args=0x55b2980f5bf0, nargsf=<optimized out>, kwnames=<optimized out>)
    at Objects/descrobject.c:432
#19 0x00007f8df83ab90a in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x55b2980f5bf0, callable=0x7f8df75db740, tstate=0x55b297d52610)
    at ./Include/cpython/abstract.h:114
#20 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x55b2980f5bf0, callable=0x7f8df75db740) at ./Include/cpython/abstract.h:123
#21 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ffdfca01470, tstate=<optimized out>) at Python/ceval.c:5891
#22 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x55b2980f59f0, throwflag=<optimized out>) at Python/ceval.c:4198
#23 0x00007f8df83bc2d9 in _PyEval_EvalFrame (throwflag=0, f=0x55b2980f59f0, tstate=0x55b297d52610) at ./Include/internal/pycore_ceval.h:46
#24 _PyEval_Vector (kwnames=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=0x0, con=0x7f8df62150a0, tstate=0x55b297d52610)
    at Python/ceval.c:5065
#25 _PyFunction_Vectorcall (func=0x7f8df6215090, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:342
#26 0x00007f8df83ab4d6 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=0x7f8df6215090, tstate=0x55b297d52610)
    at ./Include/cpython/abstract.h:114
#27 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=0x7f8df6215090) at ./Include/cpython/abstract.h:123
#28 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ffdfca01630, tstate=<optimized out>) at Python/ceval.c:5891
#29 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7f8df65c4420, throwflag=<optimized out>) at Python/ceval.c:4213
#30 0x00007f8df83b47cb in _PyEval_EvalFrame (throwflag=0, f=0x7f8df65c4420, tstate=0x55b297d52610) at ./Include/internal/pycore_ceval.h:46
#31 _PyEval_Vector (kwnames=0x0, argcount=<optimized out>, args=<optimized out>, locals=0x0, con=0x7f8df6215250, tstate=0x55b297d52610) at Python/ceval.c:5065
#32 _PyFunction_Vectorcall (kwnames=0x0, nargsf=<optimized out>, stack=<optimized out>, func=0x7f8df6215240) at Objects/call.c:342
#33 _PyObject_FastCallDictTstate (tstate=0x55b297d52610, callable=0x7f8df6215240, args=<optimized out>, nargsf=<optimized out>, kwargs=<optimized out>)
    at Objects/call.c:142
#34 0x00007f8df83c4fad in _PyObject_Call_Prepend (tstate=0x55b297d52610, callable=0x7f8df6215240, obj=0x7f8df775f8b0, args=<optimized out>, kwargs=0x0)
    at Objects/call.c:431
#35 0x00007f8df84906c2 in slot_tp_call (self=0x7f8df775f8b0, args=0x7f8df62228e0, kwds=0x0) at Objects/typeobject.c:7494
#36 0x00007f8df83b54eb in _PyObject_MakeTpCall (tstate=0x55b297d52610, callable=0x7f8df775f8b0, args=<optimized out>, nargs=4, keywords=0x0) at Objects/call.c:215
#37 0x00007f8df83b02e4 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>, tstate=<optimized out>)
    at ./Include/cpython/abstract.h:112
#38 _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>, tstate=<optimized out>)
    at ./Include/cpython/abstract.h:99
#39 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at ./Include/cpython/abstract.h:123
#40 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ffdfca01950, tstate=<optimized out>) at Python/ceval.c:5891
#41 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:4213
#42 0x00007f8df83bc2d9 in _PyEval_EvalFrame (throwflag=0, f=0x55b297ec6c20, tstate=0x55b297d52610) at ./Include/internal/pycore_ceval.h:46
#43 _PyEval_Vector (kwnames=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=0x0, con=0x7f8df6215910, tstate=0x55b297d52610)
    at Python/ceval.c:5065
#44 _PyFunction_Vectorcall (func=0x7f8df6215900, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:342
#45 0x00007f8df83ab4d6 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=0x7f8df6215900, tstate=0x55b297d52610)
    at ./Include/cpython/abstract.h:114
#46 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=0x7f8df6215900) at ./Include/cpython/abstract.h:123
#47 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ffdfca01b10, tstate=<optimized out>) at Python/ceval.c:5891
#48 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7f8df78d7880, throwflag=<optimized out>) at Python/ceval.c:4213
#49 0x00007f8df83bc2d9 in _PyEval_EvalFrame (throwflag=0, f=0x7f8df78d7880, tstate=0x55b297d52610) at ./Include/internal/pycore_ceval.h:46
#50 _PyEval_Vector (kwnames=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=0x0, con=0x7f8df62159a0, tstate=0x55b297d52610)
    at Python/ceval.c:5065
#51 _PyFunction_Vectorcall (func=0x7f8df6215990, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:342
#52 0x00007f8df83ab4d6 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=0x7f8df6215990, tstate=0x55b297d52610)
    at ./Include/cpython/abstract.h:114
#53 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=0x7f8df6215990) at ./Include/cpython/abstract.h:123
#54 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ffdfca01cd0, tstate=<optimized out>) at Python/ceval.c:5891
#55 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7f8df78d6f20, throwflag=<optimized out>) at Python/ceval.c:4213
#56 0x00007f8df83bc2d9 in _PyEval_EvalFrame (throwflag=0, f=0x7f8df78d6f20, tstate=0x55b297d52610) at ./Include/internal/pycore_ceval.h:46
#57 _PyEval_Vector (kwnames=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=0x0, con=0x7f8df7794710, tstate=0x55b297d52610)
    at Python/ceval.c:5065
#58 _PyFunction_Vectorcall (func=0x7f8df7794700, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:342
#59 0x00007f8df83ab4d6 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=0x7f8df7794700, tstate=0x55b297d52610)
    at ./Include/cpython/abstract.h:114
#60 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=0x7f8df7794700) at ./Include/cpython/abstract.h:123
#61 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ffdfca01e90, tstate=<optimized out>) at Python/ceval.c:5891
#62 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7f8df79368e0, throwflag=<optimized out>) at Python/ceval.c:4213
#63 0x00007f8df83aa120 in _PyEval_EvalFrame (throwflag=0, f=0x7f8df79368e0, tstate=0x55b297d52610) at ./Include/internal/pycore_ceval.h:46
#64 _PyEval_Vector (tstate=0x55b297d52610, con=0x7ffdfca01f90, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>)
    at Python/ceval.c:5065
#65 0x00007f8df8457b94 in PyEval_EvalCode (co=0x7f8df77133c0, globals=0x7f8df77e5900, locals=0x7f8df77e5900) at Python/ceval.c:1134
#66 0x00007f8df845df1b in builtin_exec_impl (module=<optimized out>, locals=0x7f8df77e5900, globals=0x7f8df77e5900, source=0x7f8df77133c0) at Python/bltinmodule.c:1056
#67 builtin_exec (module=<optimized out>, args=<optimized out>, nargs=<optimized out>) at Python/clinic/bltinmodule.c.h:371
#68 0x00007f8df83bc4cf in cfunction_vectorcall_FASTCALL (func=0x7f8df7940e00, args=0x55b297e39678, nargsf=<optimized out>, kwnames=<optimized out>)
    at Objects/methodobject.c:430
#69 0x00007f8df83ab4d6 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=0x7f8df7940e00, tstate=0x55b297d52610)
    at ./Include/cpython/abstract.h:114
#70 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=0x7f8df7940e00) at ./Include/cpython/abstract.h:123
#71 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ffdfca02160, tstate=<optimized out>) at Python/ceval.c:5891
#72 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x55b297e394c0, throwflag=<optimized out>) at Python/ceval.c:4213
#73 0x00007f8df83bc2d9 in _PyEval_EvalFrame (throwflag=0, f=0x55b297e394c0, tstate=0x55b297d52610) at ./Include/internal/pycore_ceval.h:46
#74 _PyEval_Vector (kwnames=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=0x0, con=0x7f8df77276e0, tstate=0x55b297d52610)
    at Python/ceval.c:5065
#75 _PyFunction_Vectorcall (func=0x7f8df77276d0, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:342
#76 0x00007f8df83ab4d6 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=0x7f8df77276d0, tstate=0x55b297d52610)
    at ./Include/cpython/abstract.h:114
#77 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=<optimized out>, callable=0x7f8df77276d0) at ./Include/cpython/abstract.h:123
#78 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ffdfca02320, tstate=<optimized out>) at Python/ceval.c:5891
#79 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7f8df78d1840, throwflag=<optimized out>) at Python/ceval.c:4213
#80 0x00007f8df83bc2d9 in _PyEval_EvalFrame (throwflag=0, f=0x7f8df78d1840, tstate=0x55b297d52610) at ./Include/internal/pycore_ceval.h:46
#81 _PyEval_Vector (kwnames=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=0x0, con=0x7f8df7727bf0, tstate=0x55b297d52610)
    at Python/ceval.c:5065
#82 _PyFunction_Vectorcall (func=0x7f8df7727be0, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:342
#83 0x00007f8df847c617 in pymain_run_module (modname=<optimized out>, set_argv0=<optimized out>) at Modules/main.c:293
#84 0x00007f8df82fc057 in pymain_run_python (exitcode=0x7ffdfca02484) at Modules/main.c:584
#85 Py_RunMain () at Modules/main.c:666
#86 0x000055b2972fa5cb in main ()
```

**Environment details**
```
kitty 0.26.5 (e1c50cf124) created by Kovid Goyal
Linux KeepRunning 5.15.89-1-lts #1 SMP Wed, 18 Jan 2023 11:24:46 +0000 x86_64
Arch Linux 5.15.89-1-lts (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/wyx/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_font_style             (True, False)
active_tab_title_template         {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}😸{sup.index}{title}
background_image_layout           scaled
background_image_linear           True
background_opacity                0.9
background_tint                   0.8
close_on_child_death              True
cursor_beam_thickness             4.5
cursor_shape                      2
cursor_text_color                 None
dynamic_background_opacity        True
enable_audio_bell                 False
enabled_layouts                   ['splits']
focus_follows_mouse               True
font_size                         19.0
hide_window_decorations           1
linux_display_server              x11
scrollback_fill_enlarged_window   True
scrollback_lines                  10000
scrollback_pager_history_size     10485760
select_by_word_characters         @-._~?&%+#
select_by_word_characters_forward =/
shell_integration                 frozenset({'no-title'})
show_hyperlink_targets            True
strip_trailing_spaces             smart
tab_bar_style                     powerline
tab_title_template                {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{sup.index}{title}
url_excluded_characters           >
Added shortcuts:
	alt+h →  kitten smart_tab.py previous_tab alt+h
	alt+l →  kitten smart_tab.py next_tab alt+l
	ctrl+q > ! →  kitten smart_tab.py detach_window new-tab ctrl+q>!
	ctrl+q > " →  kitten smart_tab.py hsplit ctrl+q>\"
	ctrl+q > % →  kitten smart_tab.py vsplit ctrl+q>%
	ctrl+q > ctrl+h →  kitten smart_tab.py resize_window narrower 5 ctrl+q>ctrl+h
	ctrl+q > ctrl+j →  kitten smart_tab.py resize_window shorter 5 ctrl+q>ctrl+j
	ctrl+q > ctrl+k →  kitten smart_tab.py resize_window taller 5 ctrl+q>ctrl+k
	ctrl+q > ctrl+l →  kitten smart_tab.py resize_window wider 5 ctrl+q>ctrl+l
	ctrl+q > h →  kitten smart_tab.py neighboring_window left ctrl+q>h
	ctrl+q > j →  kitten smart_tab.py neighboring_window down ctrl+q>j
	ctrl+q > k →  kitten smart_tab.py neighboring_window up ctrl+q>k
	ctrl+q > l →  kitten smart_tab.py neighboring_window right ctrl+q>l
	ctrl+q > v →  kitten smart_tab.py vsplit ctrl+q>v
	ctrl+t →  kitten smart_tab.py new_tab ctrl+t
	kitty_mod+h > h →  show_scrollback
	kitty_mod+h > l →  show_last_command_output
	kitty_mod+p > p →  kitten hints --type path --program @
	kitty_mod+p > u →  kitten hints --type regex --regex HIDDEN
	shift+page_down →  scroll_page_down
	shift+page_up →  scroll_page_up
Removed shortcuts:
	ctrl+shift+tab →  previous_tab
	ctrl+tab →  next_tab
	kitty_mod+, →  move_tab_backward
	kitty_mod+. →  move_tab_forward
	kitty_mod+0 →  tenth_window
	kitty_mod+1 →  first_window
	kitty_mod+2 →  second_window
	kitty_mod+3 →  third_window
	kitty_mod+4 →  fourth_window
	kitty_mod+5 →  fifth_window
	kitty_mod+6 →  sixth_window
	kitty_mod+7 →  seventh_window
	kitty_mod+8 →  eighth_window
	kitty_mod+9 →  ninth_window
	kitty_mod+[ →  previous_window
	kitty_mod+] →  next_window
	kitty_mod+` →  move_window_to_top
	kitty_mod+a > 1 →  set_background_opacity 1
	kitty_mod+a > d →  set_background_opacity default
	kitty_mod+a > l →  set_background_opacity -0.1
	kitty_mod+a > m →  set_background_opacity +0.1
	kitty_mod+alt+t →  set_tab_title
	kitty_mod+b →  move_window_backward
	kitty_mod+delete →  clear_terminal reset active
	kitty_mod+e →  open_url_with_hints
	kitty_mod+end →  scroll_end
	kitty_mod+enter →  new_window
	kitty_mod+f →  move_window_forward
	kitty_mod+f1 →  show_kitty_doc overview
	kitty_mod+f10 →  toggle_maximized
	kitty_mod+f11 →  toggle_fullscreen
	kitty_mod+f2 →  edit_config_file
	kitty_mod+f7 →  focus_visible_window
	kitty_mod+f8 →  swap_with_window
	kitty_mod+g →  show_last_command_output
	kitty_mod+h →  show_scrollback
	kitty_mod+home →  scroll_home
	kitty_mod+j →  scroll_line_down
	kitty_mod+k →  scroll_line_up
	kitty_mod+l →  next_layout
	kitty_mod+left →  previous_tab
	kitty_mod+n →  new_os_window
	kitty_mod+o →  pass_selection_to_program
	kitty_mod+p > h →  kitten hints --type hash --program -
	kitty_mod+p > n →  kitten hints --type linenum
	kitty_mod+p > shift+f →  kitten hints --type path
	kitty_mod+p > w →  kitten hints --type word --program -
	kitty_mod+p > y →  kitten hints --type hyperlink
	kitty_mod+page_down →  scroll_page_down
	kitty_mod+page_up →  scroll_page_up
	kitty_mod+q →  close_tab
	kitty_mod+r →  start_resizing_window
	kitty_mod+right →  next_tab
	kitty_mod+s →  paste_from_selection
	kitty_mod+t →  new_tab
	kitty_mod+u →  kitten unicode_input
	kitty_mod+w →  close_window
	kitty_mod+x →  scroll_to_prompt 1
	kitty_mod+z →  scroll_to_prompt -1
	shift+insert →  paste_from_selection
Changed shortcuts:
	kitty_mod+down →  scroll_to_prompt 1
	kitty_mod+p > l →  kitten hints --type hyperlink
	kitty_mod+up →  scroll_to_prompt -1
Colors:
	active_tab_background             #0ab2ff   
	cursor                            #be5160   
	inactive_tab_background           #0a65ff   
	inactive_tab_foreground           #000000   

Important environment variables seen by the kitty process:
	PATH                                HIDDEN
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	GLFW_IM_MODULE                      ibus
	DISPLAY                             :0.0
	USER                                HIDDEN
	XCURSOR_SIZE                        24
	XDG_CONFIG_DIRS                     HIDDEN
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 KDE
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 KDE
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            2
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       HIDDEN

```

**Comment by kovidgoyal** [comment]
Either provide a way to reproduce or build kitty with make asan and post
the trace when it crashes.

**Comment by kovidgoyal** [comment]
No followup. Note that from the back trace above this is likely IME related. If you are able to gather the requested info please update this bug and I will take a look.

**Comment by ppwwyyxx** [comment]
I have not run into this since then. Will come back in the future if I could get more info.
