### ISSUE TITLE
macos13.1 kitty Abnormal exit

### ISSUE THREAD

**Issue by qing-root** [kovidgoyal/kitty#5998]
I tried to open kitty on macos 13.1, but it all exited abnormally.

I try to start again/Applications/Kitty. The app/Contents/MacOS/Kitty,get the following output
```
[040 11:27:08.045389] The font Iosevka Term was not found, falling back to Menlo
[040 11:27:08.045433] The font Iosevka Term was not found, falling back to Menlo
[040 11:27:08.045445] The font Iosevka Term was not found, falling back to Menlo
[040 11:27:08.045454] The font Iosevka Term was not found, falling back to Menlo
[040 11:27:08.048701] Traceback (most recent call last):
  File "lib/python3.9/kitty/launch.py", line 306, in parse_launch_args
  File "lib/python3.9/kitty/cli.py", line 1055, in parse_args
  File "lib/python3.9/kitty/cli.py", line 818, in parse_cmdline
  File "lib/python3.9/kitty/cli.py", line 767, in needs_arg
  File "lib/python3.9/kitty/cli.py", line 760, in opt_for_alias
SystemExit: Unknown option: -zsh

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/python3.9/kitty/main.py", line 528, in main
  File "lib/python3.9/kitty/main.py", line 520, in _main
  File "lib/python3.9/kitty/main.py", line 269, in __call__
  File "lib/python3.9/kitty/main.py", line 239, in _run_app
  File "lib/python3.9/kitty/session.py", line 225, in create_sessions
  File "lib/python3.9/kitty/session.py", line 164, in parse_session
  File "lib/python3.9/kitty/session.py", line 85, in add_window
  File "lib/python3.9/kitty/launch.py", line 308, in parse_launch_args
ValueError
```

Where can I get a more detailed error log？I don't know why it won't start

**Comment by kovidgoyal** [comment]
I cant imagine what a more detailed error log would look like. That log
clearly states you are passing in a command line option named -zsh. Dont
do that.
