### ISSUE TITLE
Build: Weird error when linking

### ISSUE THREAD

**Issue by glensc** [kovidgoyal/kitty#6050]
Compilation errors out on PLD Linux with:

```
/usr/libexec/ccache/x86_64-pld-linux-gcc build/kitty-launcher-main.o -lcrypt -ldl -lm -lm -L/usr/lib64 -lpython3.10 -Xlinker -export-dynamic -o /home/users/glen/tmp/kitty-0.27.1-x86_64-root-glen/usr/bin/kitty            
Traceback (most recent call last):
  File "/home/users/glen/rpm/BUILD/x86_64-linux/kitty-0.27.1/setup.py", line 1778, in <module>
    main()
  File "/home/users/glen/rpm/BUILD/x86_64-linux/kitty-0.27.1/setup.py", line 1753, in main
    package(args, bundle_type='linux-package')
  File "/home/users/glen/rpm/BUILD/x86_64-linux/kitty-0.27.1/setup.py", line 1454, in package
    compile_python(libdir)
  File "/home/users/glen/rpm/BUILD/x86_64-linux/kitty-0.27.1/setup.py", line 1085, in compile_python
    c(base_path, ddir='', rx=exclude, force=True, optimize=optimize, quiet=1, workers=num_workers)
  File "/home/users/glen/rpm/BUILD/x86_64-linux/kitty-0.27.1/setup.py", line 1082, in c
    compileall.compile_dir(base_path, **kw)  # type: ignore
  File "/usr/lib64/python3.10/compileall.py", line 102, in compile_dir
    with ProcessPoolExecutor(max_workers=workers) as executor:
  File "/usr/lib64/python3.10/concurrent/futures/process.py", line 657, in __init__
    self._call_queue = _SafeQueue(
  File "/usr/lib64/python3.10/concurrent/futures/process.py", line 168, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/usr/lib64/python3.10/multiprocessing/queues.py", line 43, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib64/python3.10/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib64/python3.10/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib64/python3.10/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
FileNotFoundError: [Errno 2] No such file or directory
error: Bad exit status from /home/users/glen/tmp/rpm-tmp.wjr7sz (%install)

RPM build errors:
    Bad exit status from /home/users/glen/tmp/rpm-tmp.wjr7sz (%install)
```

**Comment by glensc** [comment]
The error comes from `compileall` call:
- https://github.com/kovidgoyal/kitty/blob/v0.27.1/setup.py#L1082

**Comment by glensc** [comment]
Workaround by setting `num_workers=1` in `setup.py `

**Comment by kovidgoyal** [comment]
compileall is a python stdlib package. Not much I can do about it failing. I suggest reporting it to the cpython project.
