### ISSUE TITLE
"kitty @ set-font-size" cannot use value 0 to reset font-size to default

### ISSUE THREAD

**Issue by devbyP** [kovidgoyal/kitty#6100]
**Describe the bug**
Kitty @ command set-font-size not reset font-size to default with value zero.

**To Reproduce**
`kitty @ set-font-size 0` not reset fontsize to default, and produce following error

```
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 682, in _execute_remote_command
    response = handle_cmd(self, window, pcmd, peer_id, self_window)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 220, in handle_cmd
    ans = c.response_from_kitty(boss, self_window or window, PayloadGetter(c, payload))
  File "/usr/bin/../lib/kitty/kitty/rc/set_font_size.py", line 46, in response_from_kitty
    boss.change_font_size(
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 1164, in change_font_size
    new_size = calc_new_size(current_size)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 1145, in calc_new_size
    new_size = max(MINIMUM_FONT_SIZE, min(new_size, get_options().font_size * 5))
TypeError: '<' not supported between instances of 'float' and 'NoneType'

Error: '<' not supported between instances of 'float' and 'NoneType'
```

**Environment details**
<details>
<summary>Environment ctrl+shift+F6 output</summary>

```
kitty 0.27.1 () created by Kovid Goyal
Linux pui-machine 6.2.2-arch1-2-surface #1 SMP PREEMPT_DYNAMIC Mon, 06 Mar 2023 23:26:15 +0000 x86_64
Manjaro Linux 6.2.2-arch1-2-surface  (pui-machine) (/dev/tty)


DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=22.0.4
DISTRIB_CODENAME=Sikaris
DISTRIB_DESCRIPTION="Manjaro Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/pui/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control    socket-only
background_opacity      0.85
font_family             FiraCode Nerd Font Mono
font_size               12.0
listen_on               unix:/tmp/kitty
Colors:
	active_border_color     #3e8fb0   
	active_tab_background   #393552   
	active_tab_foreground   #e0def4   
	background              #232136   
	color0                  #393552   
	color1                  #eb6f92   
	color10                 #3e8fb0   
	color11                 #f6c177   
	color12                 #9ccfd8   
	color13                 #c4a7e7   
	color14                 #ea9a97   
	color15                 #e0def4   
	color2                  #3e8fb0   
	color3                  #f6c177   
	color4                  #9ccfd8   
	color5                  #c4a7e7   
	color6                  #ea9a97   
	color7                  #e0def4   
	color8                  #6e6a86   
	color9                  #eb6f92   
	cursor                  #56526e   
	cursor_text_color       #e0def4   
	foreground              #e0def4   
	inactive_border_color   #44415a   
	inactive_tab_background #232136   
	inactive_tab_foreground #6e6a86   
	selection_background    #44415a   
	selection_foreground    #e0def4   
	url_color               #c4a7e7   

Important environment variables seen by the kitty process:
	PATH                                /home/pui/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin
	LANG                                en_US.UTF-8
	EDITOR                              /usr/bin/nano
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	USER                                pui
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 i3
	XDG_SESSION_TYPE                    x11
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/pui
	XDG_CURRENT_DESKTOP                 i3
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            7
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/local/share:/usr/share:/var/lib/snapd/desktop
```

</details>

**Additional context**

I've try use default config and the command still produce the same error
(only allow_remote_control to socket-only and listen_on to unix:/tmp/kitty)

**Comment by kovidgoyal** [comment]
dup of #5992
