### ISSUE TITLE
base64 decode error when pasting to selection using escape codes

### ISSUE THREAD

**Issue by omgold** [kovidgoyal/kitty#6139]
**Describe the bug**

Pasting to selection using escape codes does no longer work for certain base64-encoded content. It seems the bug has been introduced between 2.26.5 and 2.27.0 (It works fine with 2.26.5) and is still present in 2.27.1.

It seems, when a newline is added before the `\a` it works. But when I execute the echo onces with that newline, afterwards the version with it also stops working.

**To Reproduce**

1. Enter this into bash running inside kitty:

`echo -n -e '\x1b]52;p;OzsgVG8gY3JlYXRlIGEgZmlsZSwgdmlzaXQgaXQgd2l0aCBDLXggQy1mIGFuZCBlbnRlciB0ZXh0\nIGluIGl0cyBidWZmZXIu\a'`

2. See error (in terminal invoking kitty)

```
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/window.py", line 1260, in clipboard_control
    self.clipboard_request_manager.parse_osc_52(data, is_partial)
  File "/usr/bin/../lib/kitty/kitty/clipboard.py", line 408, in parse_osc_52
    wr.add_base64_data(text)
  File "/usr/bin/../lib/kitty/kitty/clipboard.py", line 298, in add_base64_data
    write_saving_leftover_bytes(data)
  File "/usr/bin/../lib/kitty/kitty/clipboard.py", line 290, in write_saving_leftover_bytes
    self.write_base64_data(data)
  File "/usr/bin/../lib/kitty/kitty/clipboard.py", line 318, in write_base64_data
    d = standard_b64decode(b)
  File "/usr/lib/python3.10/base64.py", line 105, in standard_b64decode
    return b64decode(s)
  File "/usr/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

**Environment details**
```
kitty 0.27.0 () created by Kovid Goyal
Linux mango 6.1.6-arch1-3 #1 SMP PREEMPT_DYNAMIC Mon, 16 Jan 2023 12:51:23 +0000 x86_64
Arch Linux 6.1.6-arch1-3 (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/*REDACTED*/bin
	LANG                                de_DE.UTF-8
	EDITOR                              emacs -nw
	SHELL                               /bin/bash
	GLFW_IM_MODULE                      ibus
	DISPLAY                             :1
	WAYLAND_DISPLAY                     wayland-1
	USER                                *REDACTED*
	XCURSOR_SIZE                        24
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 
	XDG_SESSION_TYPE                    wayland
	XDG_CURRENT_DESKTOP                 
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	LC_MESSAGES                         en_US.UTF-8
	XDG_VTNR                            1
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_COLLATE                          C
	LC_NUMERIC                          C
```

**Additional context**

The above is with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
newlines are not allowed in OSC 52. If you are generating these with
the base64 command, use

base64 -w 0

Or better yet, use the clipboard kitten.
