### ISSUE TITLE
Unable to increase/decrease font size

### ISSUE THREAD

**Issue by johnallen3d** [kovidgoyal/kitty#633]
This stopped working within the past week or so. The mappings for `restore_font_size` and `set_font_size` work as expected but no matter what mapping I use for `increase_font_size` and `decrease_font_size` fail.

### kitty version 

```sh
# tried installing via pre-built release and building locally
❯  kitty --version
kitty 0.11.0 created by Kovid Goyal
```

### OS and OS version

```sh
 macOS High Sierra 10.13.5 17F77 x86_64
```

### related kitty config

```sh
# Font sizes {{{
map super+equal      increase_font_size
map super+minus      decrease_font_size
map super+0          restore_font_size
# To setup shortcuts for specific font sizes, follow the example below:
map ctrl+shift+6     set_font_size 12.0
map ctrl+shift+7     set_font_size 13.0
# }}}
```

### related output from `kitty --debug-keyboard`

```sh
❯  kitty --debug-keyboard
2018-06-12 22:01:53.381 Python[19044:2273833] char_count: 1 cocoa text: <none>
2018-06-12 22:01:53.382 Python[19044:2273833] scancode: 0x18 (=) mods: super text: <none> glfw_key: EQUAL
Traceback (most recent call last):
  File "/Users/johna/tmp/kitty/kitty/boss.py", line 429, in dispatch_special_key
    return self.dispatch_action(key_action)
  File "/Users/johna/tmp/kitty/kitty/boss.py", line 485, in dispatch_action
    passthrough = f(*key_action.args)
  File "/Users/johna/tmp/kitty/kitty/boss.py", line 317, in increase_font_size
    self.set_font_size(min(self.opts.font_size * 5, self.current_font_size + 2.0))
AttributeError: 'Boss' object has no attribute 'current_font_size'
2018-06-12 22:01:54.960 Python[19044:2273833] char_count: 1 cocoa text: <none>
2018-06-12 22:01:54.960 Python[19044:2273833] scancode: 0x1b (-) mods: super text: <none> glfw_key: MINUS
Traceback (most recent call last):
  File "/Users/johna/tmp/kitty/kitty/boss.py", line 429, in dispatch_special_key
    return self.dispatch_action(key_action)
  File "/Users/johna/tmp/kitty/kitty/boss.py", line 485, in dispatch_action
    passthrough = f(*key_action.args)
  File "/Users/johna/tmp/kitty/kitty/boss.py", line 320, in decrease_font_size
    self.set_font_size(self.current_font_size - self.opts.font_size_delta)
AttributeError: 'Boss' object has no attribute 'current_font_size'
2018-06-12 22:01:56.360 Python[19044:2273833] char_count: 1 cocoa text: <none>
2018-06-12 22:01:56.360 Python[19044:2273833] scancode: 0x1d (0) mods: super text: <none> glfw_key: 0
2018-06-12 22:01:59.346 Python[19044:2273833] char_count: 1 cocoa text: <none>
2018-06-12 22:01:59.346 Python[19044:2273833] scancode: 0x16 (6) mods: ctrl+shift text: <none> glfw_key: 6
2018-06-12 22:02:00.302 Python[19044:2273833] char_count: 1 cocoa text: <none>
2018-06-12 22:02:00.302 Python[19044:2273833] scancode: 0x1a (7) mods: ctrl+shift text: <none> glfw_key: 7
```

**Comment by johnallen3d** [comment]
I'm also able to use `kitty @ set-font-size 15` to change fonts successfully.

**Comment by kovidgoyal** [comment]
Use change_font_size

https://sw.kovidgoyal.net/kitty/conf.html#font-sizes
