### ISSUE TITLE
open new tab failed

### ISSUE THREAD

**Issue by iHnR** [kovidgoyal/kitty#6372]
**Describe the bug**
Opening a new tab fails in my kitty window. 2 tabs already open, one of which with 2 windows. Trying to open a new tab fails from every open tab and window with the same error.

 I could not reproduce the bug in a new os window. Probably not a big issue but posting here in case it's an obvious fix.

```
Key action failed

new_tab
[Errno 2] No such file or directory

Press e to see detailed traceback or any other key to exit
Traceback (most recent call last):
  File "kitty/boss.py", line 1534, in combine
  File "kitty/boss.py", line 1491, in dispatch_action
  File "kitty/boss.py", line 2265, in new_tab
  File "kitty/boss.py", line 2261, in _create_tab
  File "kitty/boss.py", line 2253, in _new_tab
  File "kitty/tabs.py", line 1095, in new_tab
  File "kitty/tabs.py", line 154, in __init__
  File "kitty/tabs.py", line 513, in new_window
  File "kitty/tabs.py", line 485, in launch_child
  File "kitty/child.py", line 214, in __init__
  File "posixpath.py", line 379, in abspath
FileNotFoundError: [Errno 2] No such file or directory
Press Enter or Esc to exit

```

**To Reproduce**
Unable to reproduce after restart of kitty.

**Screenshots**

**Environment details**
```
kitty 0.28.1 (07bcc5ba61) created by Kovid Goyal
Linux pop-os 6.2.6-76060206-generic #202303130630~1685473338~22.04~995127e SMP PREEMPT_DYNAMIC Tue M x86_64
Pop!_OS 22.04 LTS pop-os /dev/tty

DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/<username>/.local/kitty.app/bin/kitty
  base dir: /home/<username>/.local/kitty.app/lib/kitty
  extensions dir: /home/<username>/.local/kitty.app/lib/kitty-extensions
  system shell: /usr/bin/fish
Loaded config files:
  /home/<username>/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control       yes
background_opacity         0.95
cursor_shape               2
disable_ligatures          1
dynamic_background_opacity True
enabled_layouts            ['tall:bias=60']
font_family                JetBrains Mono
font_size                  16.0
hide_window_decorations    1
initial_window_height      (25, 'cells')
initial_window_width       (80, 'cells')
listen_on                  unix:/tmp/mykitty
remember_window_size       False
symbol_map:
	U+23fb - U+23fe → Symbols Nerd Font
	U+2500 - U+259f → Symbols Nerd Font # Box Drawing
	U+2665 - U+2665 → Symbols Nerd Font
	U+26a1 - U+26a1 → Symbols Nerd Font
	U+2b58 - U+2b58 → Symbols Nerd Font
	U+e000 - U+e00a → Symbols Nerd Font
	U+e0a0 - U+e0a2 → Symbols Nerd Font
	U+e0a3 - U+e0a3 → Symbols Nerd Font
	U+e0b0 - U+e0b3 → Symbols Nerd Font
	U+e0b4 - U+e0c8 → Symbols Nerd Font
	U+e0ca - U+e0ca → Symbols Nerd Font
	U+e0cc - U+e0d4 → Symbols Nerd Font
	U+e200 - U+e2a9 → Symbols Nerd Font
	U+e300 - U+e3e3 → Symbols Nerd Font
	U+e5fa - U+e6ac → Symbols Nerd Font
	U+e700 - U+e7c5 → Symbols Nerd Font
	U+ea60 - U+ebeb → Symbols Nerd Font
	U+f000 - U+f2e0 → Symbols Nerd Font
	U+f102 - U+f102 → nonicons
	U+f116 - U+f118 → nonicons
	U+f12f - U+f12f → nonicons
	U+f13e - U+f13e → nonicons
	U+f1af - U+f1af → nonicons
	U+f1bf - U+f1bf → nonicons
	U+f1cf - U+f1cf → nonicons
	U+f1ff - U+f1ff → nonicons
	U+f20f - U+f20f → nonicons
	U+f21f - U+f220 → nonicons
	U+f22e - U+f22f → nonicons
	U+f23f - U+f23f → nonicons
	U+f24f - U+f24f → nonicons
	U+f25f - U+f25f → nonicons
	U+f300 - U+f32f → Symbols Nerd Font
	U+f400 - U+f532 → Symbols Nerd Font
	U+e276c - U+e2771 → Symbols Nerd Font # Heavy Angle Brackets
	U+f0001 - U+f1af0 → Symbols Nerd Font
Changed shortcuts:
	kitty_mod+, →  next_tab
	kitty_mod+. →  previous_tab
	kitty_mod+down →  resize_window taller
	kitty_mod+enter →  launch --cwd=current --type=window
	kitty_mod+left →  resize_window narrower
	kitty_mod+n →  launch --cwd=current --type=os-window
	kitty_mod+right →  resize_window wider
	kitty_mod+up →  resize_window shorter
Colors:
	background                 #2c2e34   
	cursor                     #a4a1a1   
	foreground                 #c5cdd9   
	selection_background       #494542   
	selection_foreground       #090200   

Important environment variables seen by the kitty process:
	PATH                                /home/<username>/.cargo/bin:/home/<username>/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/<username>/.npm-global/bin:/home/<username>/.nodejs/bin
	LANG                                en_US.UTF-8
	VISUAL                              /home/<username>/.local/bin/lvim
	EDITOR                              /home/<username>/.local/bin/lvim
	SHELL                               /usr/bin/fish
	DISPLAY                             :1
	USER                                <username>
	LC_TIME                             en_GB.UTF-8
	XDG_SESSION_TYPE                    x11
	LC_MONETARY                         en_GB.UTF-8
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_ADDRESS                          en_GB.UTF-8
	XDG_MENU_PREFIX                     gnome-
	LC_TELEPHONE                        en_GB.UTF-8
	XDG_CURRENT_DESKTOP                 pop:GNOME
	XDG_SESSION_DESKTOP                 pop
	LC_NAME                             en_GB.UTF-8
	LC_MEASUREMENT                      en_GB.UTF-8
	LC_IDENTIFICATION                   en_GB.UTF-8
	XDG_DATA_DIRS                       /usr/share/pop:/usr/share/gnome:/home/<username>/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-pop:/etc/xdg
	LC_NUMERIC                          en_GB.UTF-8
	LC_PAPER                            en_GB.UTF-8

```

**Comment by kovidgoyal** [comment]
That just means you set the shell to open in that instance to something
that is not found in the PATH kitty sees.
