### ISSUE TITLE
Unsupported pixel mode 0?

### ISSUE THREAD

**Issue by TheGag96** [kovidgoyal/kitty#64]
Just built on Ubuntu 17.04 today, got this trying to start it up:

```
Unable to update the static FcBlanks: 0x0600
Unable to update the static FcBlanks: 0x0601
Unable to update the static FcBlanks: 0x0602
Unable to update the static FcBlanks: 0x0603
Unable to update the static FcBlanks: 0x06dd
Unable to update the static FcBlanks: 0x070f
Unable to update the static FcBlanks: 0x2028
Unable to update the static FcBlanks: 0x2029
Unable to update the static FcBlanks: 0xfff9
Unable to update the static FcBlanks: 0xfffa
Unable to update the static FcBlanks: 0xfffb
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 7, in <module>
    main()
  File "./kitty/main.py", line 263, in main
    run_app(opts, args)
  File "./kitty/main.py", line 200, in run_app
    boss = Boss(window, opts, args)
  File "./kitty/boss.py", line 107, in __init__
    self.sprites.do_layout(cell_size.width, cell_size.height)
  File "./kitty/shaders.py", line 65, in do_layout
    self.pre_render()
  File "./kitty/shaders.py", line 76, in pre_render
    send()  # blank
  File "./kitty/shaders.py", line 71, in send
    buf = render_cell(*a, **kw)[0]
  File "./kitty/fonts/render.py", line 41, in render_cell
    first, second = rc(text, bold, italic)
  File "./kitty/fonts/freetype.py", line 260, in render_cell
    bitmap_char = render_char(text, bold, italic, width)
  File "./kitty/fonts/freetype.py", line 183, in render_char
    return render_using_face(font, face, text, width, italic, bold)
  File "./kitty/fonts/freetype.py", line 131, in render_using_face
    bitmap = render_to_bitmap(font, face, text)
  File "./kitty/fonts/freetype.py", line 125, in render_to_bitmap
    format(text, bitmap.pixel_mode)
ValueError: FreeType rendered the glyph for ' ' with an unsupported pixel mode: 0
```

I'm using Infinality, if that changes anything at all. What's the issue here? Thanks!

**Comment by IllanFed** [comment]
https://github.com/kovidgoyal/kitty/issues/52  
  
Update freetype, preferably from source.

**Comment by kovidgoyal** [comment]
Yeah it has something to do with either infinality or freetype being too old. As noted in #52 I'm not a freetype expert, so I cannot be sure what exactly it is. As far as I can tell there is nothing in the kitty freetype code that requires very new freetype versions. If the advice from IllanFed in #52 does not work for you, feel fre to follow up there. I'm closing this bug report as a duplicate.
