### ISSUE TITLE
ValueError: Unknown command in session file: new_tab_with_cwd

### ISSUE THREAD

**Issue by otakutyrant** [kovidgoyal/kitty#6406]
This is my session:

```
layout horizontal
launch
launch
new_tab
layout horizontal
launch
launch
new_tab_with_cwd Projects
launch
```

When I launch `kitty --config NONE --session session`, it complains:

```
[180 11:23:42.337377] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 531, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 523, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 275, in __call__
    _run_app(opts, args, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 241, in _run_app
    startup_sessions = tuple(create_sessions(opts, args, default_session=opts.startup_session))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/kitty/kitty/session.py", line 222, in create_sessions
    yield from parse_session(session_data, opts, environ=environ)
  File "/usr/bin/../lib/kitty/kitty/session.py", line 186, in parse_session
    raise ValueError(f'Unknown command in session file: {cmd}')
ValueError: Unknown command in session file: new_tab_with_cwd
```

EDIT:

I forget to paste the debug output, here it is:

```
kitty 0.28.1 created by Kovid Goyal
Linux PC 6.3.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 20:46:20 +0000 x86_64
Arch Linux 6.3.9-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/otakutyrant/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity      0.8
enabled_layouts         ['splits', 'horizontal', 'vertical']
font_family             JetBrainsMono Nerd Font
font_size               13.0
tab_bar_style           powerline
tab_title_template      {index} : {title}
Added shortcuts:
	alt+- →  goto_layout vertical
	alt+0 →  goto_tab 10
	alt+1 →  goto_tab 1
	alt+2 →  goto_tab 2
	alt+3 →  goto_tab 3
	alt+4 →  goto_tab 4
	alt+5 →  goto_tab 5
	alt+6 →  goto_tab 6
	alt+7 →  goto_tab 7
	alt+8 →  goto_tab 8
	alt+9 →  goto_tab 9
	alt+h →  neighboring_window left
	alt+j →  neighboring_window down
	alt+k →  neighboring_window up
	alt+l →  neighboring_window right
	alt+q →  close_window
	alt+s →  launch --location=hsplit
	alt+v →  launch --location=vsplit
	alt+| →  goto_layout horizontal
Colors:
	active_border_color     #7aa2f7   
	active_tab_background   #7aa2f7   
	active_tab_foreground   #16161e   
	background              #1a1b26   
	color0                  #15161e   
	color1                  #f7768e   
	color10                 #9ece6a   
	color11                 #e0af68   
	color12                 #7aa2f7   
	color13                 #bb9af7   
	color14                 #7dcfff   
	color15                 #c0caf5   
	color16                 #ff9e64   
	color17                 #db4b4b   
	color2                  #9ece6a   
	color3                  #e0af68   
	color4                  #7aa2f7   
	color5                  #bb9af7   
	color6                  #7dcfff   
	color7                  #a9b1d6   
	color8                  #414868   
	color9                  #f7768e   
	cursor                  #c0caf5   
	cursor_text_color       #1a1b26   
	foreground              #c0caf5   
	inactive_border_color   #292e42   
	inactive_tab_background #292e42   
	inactive_tab_foreground #545c7e   
	selection_background    #283457   
	selection_foreground    #c0caf5   
	url_color               #73daca   

Important environment variables seen by the kitty process:
	PATH                                /usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/home/otakutyrant/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	GLFW_IM_MODULE                      ibus
	DISPLAY                             :0
	USER                                otakutyrant
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 i3
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            1
	XDG_SESSION_ID                      1
	LC_CTYPE                            zh_CN.UTF-8
	XDG_RUNTIME_DIR                     /run/user/1000
```

**Comment by kovidgoyal** [comment]
Seems quite clear to me there is no such command. The correct command to
use is launch see the docs.

**Comment by otakutyrant** [comment]
Here is the [doc](https://sw.kovidgoyal.net/kitty/actions/#action-new_tab_with_cwd) and the [source code](https://github.com/kovidgoyal/kitty/blob/master/kitty/boss.py#L2293) of it.

**Comment by kovidgoyal** [comment]
Those are actions that can be bound with *keyboard shortcuts* not things
you can put in a session file. Read the session docs.
