### ISSUE TITLE
Consistent error when scrolling through +kitten themer

### ISSUE THREAD

**Issue by EboniLM** [kovidgoyal/kitty#6410]
**Describe the bug**
When scrolling through the themes, after a certain point an error is received:

```
Error: Paniced: strings: negative Repeat count
```

I've noticed that the number of selections (presses of the down key) until the error is triggered varies depending on which type of theme is being viewed. For `Light` themes, that number seems to be **11**. 

For `Dark` themes, that numbers seems to be **28** and **36** for `All`. 

**To Reproduce**
1. Open `kitty` and enter `kitty +kitten themes` in the terminal
2. Use the down key to traverse through themes
3. See error

**Screenshots**
![Screenshot_2023-06-30_22-29-19](https://github.com/kovidgoyal/kitty/assets/32157169/6992ad2c-c78f-4c70-a385-2f600373fa83)

**Environment details**
```
kitty 0.28.1 created by Kovid Goyal
Linux 6.3.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 20:46:20 +0000 x86_64
Arch Linux 6.3.9-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/ebonilm/.config/kitty/kitty.conf

Config options different from defaults:
bold_font            Fira Mono Bold
bold_italic_font     Fira Mono Bold Italic
font_family          Fira Mono Medium
italic_font          Fira Mono Italic
window_logo_position center
window_padding_width FloatEdges(left=5.0, top=5.0, right=5.0, bottom=5.0)
Colors:
	background           #1e1c44   
	color0               #050404   
	color1               #bc0013   
	color10              #9dff6e   
	color11              #efc11a   
	color12              #1896c6   
	color13              #9a5952   
	color14              #c8f9f3   
	color15              #f5f4fb   
	color2               #49b117   
	color3               #e6741d   
	color4               #0f49c6   
	color5               #665992   
	color6               #6fa497   
	color7               #f8dbc0   
	color8               #4e7bbf   
	color9               #fc5e59   
	cursor               #eebf37   
	foreground           #f8dbc0   
	selection_background #6f6a4e   
	selection_foreground #1e1c44   

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/home/ebonilm/.dotnet/tools:/usr/lib/jvm/default/bin:/opt/nessus/bin:/opt/nessus/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0.0
	USER                                ebonilm
	XDG_CONFIG_DIRS                     /etc/xdg
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	XDG_MENU_PREFIX                     xfce-
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 xfce
	XDG_SESSION_TYPE                    x11
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/ebonilm
	XDG_CURRENT_DESKTOP                 XFCE
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            7
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/local/share:/usr/share

```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

```
kitty 0.28.1 created by Kovid Goyal
Linux 6.3.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 20:46:20 +0000 x86_64
Arch Linux 6.3.9-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/ebonilm/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/home/ebonilm/.dotnet/tools:/usr/lib/jvm/default/bin:/opt/nessus/bin:/opt/nessus/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0.0
	USER                                ebonilm
	XDG_CONFIG_DIRS                     /etc/xdg
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	XDG_MENU_PREFIX                     xfce-
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 xfce
	XDG_SESSION_TYPE                    x11
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/ebonilm
	XDG_CURRENT_DESKTOP                 XFCE
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            7
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/local/share:/usr/share
```

**Comment by kovidgoyal** [comment]
Does not repro for me with those steps in master. There have been a
number of bug fixes in related areas since the last release so try the
kitty nightly.

**Comment by EboniLM** [comment]
@kovidgoyal I switched to the nightly build as you suggested and it is still occurring for me. Even if scrolling through the themes using my down arrow key, or scrolling with the mouse, it crashes with the same error. The crash is immediate when using the mouse scroll wheel, however. 

I thought maybe it could've been due to using an AUR package, so I uninstalled it and did a fresh binary install. It still occurred afterwards, and continues to do so on the nightly. 😞 

I understand that you are unable to repro on your end but I did want to check in to see if you had any other suggestions for me by chance?

```
kitty 0.28.1 (5446aa9ccb) created by Kovid Goyal
Linux 6.3.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 20:46:20 +0000 x86_64
Arch Linux 6.3.9-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: True
Paths:
  kitty: /home/ebonilm/.local/kitty.app/bin/kitty
  base dir: /home/ebonilm/.local/kitty.app/lib/kitty
  extensions dir: /home/ebonilm/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config files:
  /home/ebonilm/.config/kitty/kitty.conf

Config options different from defaults:
bold_font            Fira Mono Bold
bold_italic_font     Fira Mono Bold Italic
font_family          Fira Mono Medium
italic_font          Fira Mono Italic
window_padding_width FloatEdges(left=5.0, top=5.0, right=5.0, bottom=5.0)
Colors:
	background           #1e1c44   
	color0               #050404   
	color1               #bc0013   
	color10              #9dff6e   
	color11              #efc11a   
	color12              #1896c6   
	color13              #9a5952   
	color14              #c8f9f3   
	color15              #f5f4fb   
	color2               #49b117   
	color3               #e6741d   
	color4               #0f49c6   
	color5               #665992   
	color6               #6fa497   
	color7               #f8dbc0   
	color8               #4e7bbf   
	color9               #fc5e59   
	cursor               #eebf37   
	foreground           #f8dbc0   
	selection_background #6f6a4e   
	selection_foreground #1e1c44   

Important environment variables seen by the kitty process:
	PATH                                /home/ebonilm/.local/kitty.app/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/home/ebonilm/.dotnet/tools:/usr/lib/jvm/default/bin:/opt/nessus/bin:/opt/nessus/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0.0
	USER                                ebonilm
	XDG_CONFIG_DIRS                     /etc/xdg
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	XDG_MENU_PREFIX                     xfce-
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 xfce
	XDG_SESSION_TYPE                    x11
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/ebonilm
	XDG_CURRENT_DESKTOP                 XFCE
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            7
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/local/share:/usr/share
```

**Comment by kovidgoyal** [comment]
what size if the kitty window (in cells) and post the error message via copy paste cant read it properly in your screenshot.

**Comment by kovidgoyal** [comment]
The top fel lines of the error message are most important

**Comment by EboniLM** [comment]
Certainly! Sorry about that. @kovidgoyal 

```
[eboni ~]$ kitty +kitten themes

Paniced with error: strings: negative Repeat count
Stacktrace:
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
kitty/tools/tui/loop.(*Loop).Run.func1()
	/tmp/t/plugins-zyolzwb2/src/tools/tui/loop/api.go:256 +0x7b
panic({0x9c1d60, 0xd8cba0})
	/usr/local/go/src/runtime/panic.go:884 +0x213
strings.Repeat({0xd8abe0?, 0x2c?}, 0xc0001d3fa0?)
	/usr/local/go/src/strings/strings.go:538 +0x438
kitty/kittens/themes.center_string({0xc0005eb230, 0x2c}, 0x24)
	/tmp/t/plugins-zyolzwb2/src/kittens/themes/ui.go:401 +0x68
kitty/kittens/themes.(*handler).draw_theme_demo(0xc0000cb800)
	/tmp/t/plugins-zyolzwb2/src/kittens/themes/ui.go:475 +0x433
kitty/kittens/themes.(*handler).draw_browsing_screen(0xc0000cb800)
	/tmp/t/plugins-zyolzwb2/src/kittens/themes/ui.go:332 +0x5ab
kitty/kittens/themes.(*handler).draw_screen(0xc0000cb800)
	/tmp/t/plugins-zyolzwb2/src/kittens/themes/ui.go:144 +0x1f8
kitty/kittens/themes.(*handler).next(0xc0000cb800, 0xa98a5c?, 0x38?)
	/tmp/t/plugins-zyolzwb2/src/kittens/themes/ui.go:228 +0x45
kitty/kittens/themes.(*handler).on_browsing_key_event(0xc0000cb800, 0xc0000ae2a0)
	/tmp/t/plugins-zyolzwb2/src/kittens/themes/ui.go:261 +0x3c5
kitty/kittens/themes.(*handler).on_key_event(0x1?, 0xc0001d3b10?)
	/tmp/t/plugins-zyolzwb2/src/kittens/themes/ui.go:208 +0x30
kitty/tools/tui/loop.(*Loop).handle_key_event(0xc0002421e0, 0xc0000ae2a0)
	/tmp/t/plugins-zyolzwb2/src/tools/tui/loop/run.go:125 +0x36
kitty/tools/tui/loop.(*Loop).handle_csi(0xc0002421e0, {0xc00049a000, 0x1, 0x8})
	/tmp/t/plugins-zyolzwb2/src/tools/tui/loop/run.go:71 +0x205
kitty/tools/wcswidth.(*EscapeCodeParser).dispatch_esc_code(0xc000242228)
	/tmp/t/plugins-zyolzwb2/src/tools/wcswidth/escape-code-parser.go:152 +0xc5
kitty/tools/wcswidth.(*EscapeCodeParser).dispatch_byte(0xc000242228, 0x42)
	/tmp/t/plugins-zyolzwb2/src/tools/wcswidth/escape-code-parser.go:288 +0x345
kitty/tools/wcswidth.(*EscapeCodeParser).ParseByte(0xc000242228, 0x6?)
	/tmp/t/plugins-zyolzwb2/src/tools/wcswidth/escape-code-parser.go:94 +0x16e
kitty/tools/wcswidth.(*EscapeCodeParser).Parse(...)
	/tmp/t/plugins-zyolzwb2/src/tools/wcswidth/escape-code-parser.go:105
kitty/tools/tui/loop.(*Loop).dispatch_input_data(0xc0004d9c78, {0xc00052c024, 0x3, 0x0?})
	/tmp/t/plugins-zyolzwb2/src/tools/tui/loop/read.go:25 +0x99
kitty/tools/tui/loop.(*Loop).run(0xc0002421e0)
	/tmp/t/plugins-zyolzwb2/src/tools/tui/loop/run.go:462 +0x10e7
kitty/tools/tui/loop.(*Loop).Run(0xc000183dc0?)
	/tmp/t/plugins-zyolzwb2/src/tools/tui/loop/api.go:273 +0x6d
kitty/kittens/themes.main(0xc0000cf0e0?, 0xc000451e00, {0xc0000cb180?, 0xc000124000?, 0xc0002cc4e8?})
	/tmp/t/plugins-zyolzwb2/src/kittens/themes/main.go:87 +0x447
kitty/kittens/themes.create_cmd.func1(0x9e0180?, {0xc0000cb180, 0x0, 0x8})
	/tmp/t/plugins-zyolzwb2/src/kittens/themes/cli_generated.go:15 +0x9e
kitty/tools/cli.(*Command).ExecArgs(0x9744b0?, {0xc000124000?, 0xc0000cf770?, 0xc0003da0f0?})
	/tmp/t/plugins-zyolzwb2/src/tools/cli/command.go:544 +0x294
kitty/tools/cli.(*Command).Exec(0xaba94a?, {0x0?, 0x401470?, 0x0?})
	/tmp/t/plugins-zyolzwb2/src/tools/cli/command.go:559 +0x38
main.main()
	/tmp/t/plugins-zyolzwb2/src/tools/cmd/main.go:33 +0x125
Press any key to exit.
```
