### ISSUE TITLE
[kitty 0.29.0] ssh kitten not copying files

### ISSUE THREAD

**Issue by andreagrax** [kovidgoyal/kitty#6443]
**Describe the bug**
I'm trying to use the `ssh` kitten to copy my dotfiles to remote hosts, as seen here : https://sw.kovidgoyal.net/kitty/kittens/ssh/#real-world-ssh-kitten-config , but it does not create any file on the remote host

**To Reproduce**
1. delete `.bashrc` on the remote host
2. add the following lines to `~/.config/kitty/ssh.conf`
```
hostname *
interpreter sh
remote_dir .local/share/kitty-ssh-kitten
#copy .bashrc .vimrc .gitconfig .gitignore_global
copy .bashrc
```
3. launch `kitty +kitten ssh --kitten interpreter=sh  192.168.8.155`
4. See the error

```
> ls .basrhc
ls: cannot access '.basrhc': No such file or directory
```

**Environment details**

```
kitty 0.29.0 (e2b5c6688d) created by Kovid Goyal
Linux ITMILKLR0107 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64
Ubuntu 22.04.2 LTS ITMILKLR0107 /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/andrea/.local/kitty.app/bin/kitty
  base dir: /home/andrea/.local/kitty.app/lib/kitty
  extensions dir: /home/andrea/.local/kitty.app/lib/kitty-extensions
  system shell: /usr/bin/zsh
Loaded config files:
  /home/andrea/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control  yes
bell_on_tab
copy_on_select        clipboard
enable_audio_bell     False
font_size             12.0
scrollback_lines      20000
strip_trailing_spaces smart
term                  xterm-256color
window_alert_on_bell  False
Added shortcuts:
        ctrl+down →  resize_window shorter 3
        ctrl+left →  resize_window narrower
        ctrl+right →  resize_window wider
        ctrl+up →  resize_window taller
        f5 →  launch --type background --stdin-source @screen_scrollback  sh -c "exec tee ~/Downloads/terminal_dumps/terminal_buffer_$(/bin/date +%Y-%m-%d_%H:%M:%S ).txt"
        f8 →  layout_action rotate
        kitty_mod+alt+- →  change_font_size all -2.0
        shift+down →  move_window down
        shift+left →  move_window left
        shift+right →  move_window right
        shift+up →  move_window up
Changed shortcuts:
        kitty_mod+, →  previous_window
        kitty_mod+. →  next_window
        kitty_mod+enter →  new_window_with_cwd
        kitty_mod+f →  launch --type=overlay --stdin-source=@screen_scrollback fzf --no-sort --no-mouse --exact -i
        kitty_mod+t →  new_tab_with_cwd
Colors:
        background            #001b21

Important environment variables seen by the kitty process:
        PATH                                /bin:/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/home/andrea/bin
        LANG                                en_US.UTF-8
        SHELL                               /usr/bin/zsh
        DISPLAY                             :0
        USER                                andrea
        XDG_CONFIG_DIRS                     /etc/xdg/xdg-ubuntu-xorg:/etc/xdg
        XDG_MENU_PREFIX                     gnome-
        LC_ADDRESS                          it_IT.UTF-8
        LC_NAME                             it_IT.UTF-8
        LC_MONETARY                         it_IT.UTF-8
        XDG_SESSION_DESKTOP                 ubuntu-xorg
        XDG_SESSION_TYPE                    x11
        LC_PAPER                            it_IT.UTF-8
        XDG_CURRENT_DESKTOP                 ubuntu:GNOME
        XDG_SESSION_CLASS                   user
        LC_IDENTIFICATION                   it_IT.UTF-8
        LC_TELEPHONE                        it_IT.UTF-8
        LC_MEASUREMENT                      it_IT.UTF-8
        XDG_RUNTIME_DIR                     /run/user/1001
        LC_TIME                             it_IT.UTF-8
        XDG_DATA_DIRS                       /usr/share/ubuntu-xorg:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
        LC_NUMERIC                          it_IT.UTF-8
```

On older versions of kitty, run kitty --debug-config instead

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

with `--config NONE` I get:

![screenshot_2023-07-11_15-43](https://github.com/kovidgoyal/kitty/assets/5119590/4c5028c1-f0c1-4483-a197-93df333d0907)

fails both with interpreter `sh` and `python`

with python I get:

```
> kitty +kitten ssh --kitten interpreter=python  192.168.8.155
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "bootstrap.py", line 306, in <module>
  File "bootstrap.py", line 286, in main
  File "bootstrap.py", line 217, in get_data
  File "bootstrap.py", line 149, in compile_terminfo
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
```

**Comment by kovidgoyal** [comment]
Works for me with your ssh.conf and

kitten ssh <ip_address>

**Comment by andreagrax** [comment]
@kovidgoyal I was using the syntax used in the docs. 

I'll create a PR with updated docs

**Comment by kovidgoyal** [comment]
kitty +kitten ssh
and
kitten ssh

are the same (the former just invokes the latter), so not sure what syntax you are referring to.
