### ISSUE TITLE
Failed to parse popup inside terminal window

### ISSUE THREAD

**Issue by ryanmusante** [kovidgoyal/kitty#6472]
Sometimes when clicking within the terminal, I get a popup message. I can't remember what triggered it the first time. It seems intermittent. Is this due to my configuration?

Output from journal is below
```
Jul 15 19:45:33 xmg kitty.desktop[1772]: Traceback (most recent call last):
Jul 15 19:45:33 xmg kitty.desktop[1772]:   File "/usr/bin/../lib/kitty/kitty/boss.py", line 1526, in combine
Jul 15 19:45:33 xmg kitty.desktop[1772]:     actions = get_options().alias_map.resolve_aliases(action_definition, 'map' if dispatch_type == 'KeyPress' else 'mouse_map')
Jul 15 19:45:33 xmg kitty.desktop[1772]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 15 19:45:33 xmg kitty.desktop[1772]:   File "/usr/bin/../lib/kitty/kitty/options/utils.py", line 955, in resolve_aliases
Jul 15 19:45:33 xmg kitty.desktop[1772]:     return tuple(resolve_aliases_and_parse_actions(definition, self.aliases, map_type))
Jul 15 19:45:33 xmg kitty.desktop[1772]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 15 19:45:33 xmg kitty.desktop[1772]:   File "/usr/bin/../lib/kitty/kitty/options/utils.py", line 1005, in resolve_aliases_and_parse_actions
Jul 15 19:45:33 xmg kitty.desktop[1772]:     yield parse_key_action(defn, map_type)
Jul 15 19:45:33 xmg kitty.desktop[1772]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 15 19:45:33 xmg kitty.desktop[1772]:   File "/usr/bin/../lib/kitty/kitty/options/utils.py", line 932, in parse_key_action
Jul 15 19:45:33 xmg kitty.desktop[1772]:     func, args = parser(func, rest)
Jul 15 19:45:33 xmg kitty.desktop[1772]:                  ^^^^^^^^^^^^^^^^^^
Jul 15 19:45:33 xmg kitty.desktop[1772]:   File "/usr/bin/../lib/kitty/kitty/options/utils.py", line 393, in mouse_selection
Jul 15 19:45:33 xmg kitty.desktop[1772]:     return func, [cmap[rest]]
Jul 15 19:45:33 xmg kitty.desktop[1772]:                   ~~~~^^^^^^
Jul 15 19:45:33 xmg kitty.desktop[1772]: KeyError: 'norma'
```

**Comment by kovidgoyal** [comment]
You've got the string "norma" somewhere in kitty.conf. It should be
normal

**Comment by ryanmusante** [comment]
You're awesome, thanks, it's fixed
