### ISSUE TITLE
[BUG] icat kitten crashes, also killing brave browser

### ISSUE THREAD

**Issue by adpce** [kovidgoyal/kitty#6616]
The icat kitten will, sporadically, when used as a previewer for lf, crash in such a way that renders it **and the brave-browser** inoperable.

**To Reproduce**
1.  Use the following script as a previewer in lf
```
#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5
if [[ "$( file -Lb --mime-type "$file")" =~ ^image ]]; then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" < /dev/null > /dev/tty
    exit 1
fi
if [[ "$( file -Lb --mime-type "$file")" == "application/pdf" ]]; then
    pdftoppm -jpeg -f 1 -singlefile "$file" "$CACHE"
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "${CACHE}.jpg" < /dev/null > /dev/tty
    exit 1
fi
if [[ "$( file -Lb --mime-type "$file")" =~ ^audio|video ]]; then
    mediainfo "$file"
    exit 1
fi
~/Downloads/prog/pistol "$file"
```
2. Use it for a protracted period for previewing image files
3. It crashes
4. Attempts to call icat from command line produce this error:
```
unexpected fault address 0x7f59a281a000
                                       fatal error: fault
                                                         [signal SIGBUS: bus error code=0x2 addr=0x7f59a281a000 pc=0x469c95]

                                                                                                                            goroutine 1 [running]:
                                                                                                                                                  runtime.throw({0xab1329?, 0x0?})
                  	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc0000f7538 sp=0xc0000f7508 pc=0x43645d
                                                                                                                 runtime.sigpanic()
                                                                                                                                   	/usr/local/go/src/runtime/signal_unix.go:834 +0x125 fp=0xc0000f7598 sp=0xc0000f7538 pc=0x44c845
                                                                       runtime.memmove()
                                                                                        	/usr/local/go/src/runtime/memmove_amd64.s:163 +0x115 fp=0xc0000f75a0 sp=0xc0000f7598 pc=0x469c95
                                kitty/kittens/icat.DetectSupport.func3()
                                                                        	/tmp/t/plugins-xbucmfh9/src/kittens/icat/detect.go:75 +0x493 fp=0xc0000f7690 sp=0xc0000f75a0 pc=0x941253
                        kitty/tools/tui/loop.(*Loop).run(0xc0002521e0)
                                                                      	/tmp/t/plugins-xbucmfh9/src/tools/tui/loop/run.go:349 +0xaf7 fp=0xc0000f7a70 sp=0xc0000f7690 pc=0x7ba4d7
                kitty/tools/tui/loop.(*Loop).Run(0xc0000f7ba8?)
                                                               	/tmp/t/plugins-xbucmfh9/src/tools/tui/loop/api.go:261 +0x6d fp=0xc0000f7ac0 sp=0xc0000f7a70 pc=0x7b2bcd
       kitty/kittens/icat.DetectSupport(0x2540be400)
                                                    	/tmp/t/plugins-xbucmfh9/src/kittens/icat/detect.go:125 +0x530 fp=0xc0000f7bf0 sp=0xc0000f7ac0 pc=0x9408f0
 kitty/kittens/icat.main(0xc0004e1400?, 0x9c45e0?, {0xc0004daf00, 0x1, 0x8})
                                                                            	/tmp/t/plugins-xbucmfh9/src/kittens/icat/main.go:204 +0x688 fp=0xc0000f7e00 sp=0xc0000f7bf0 pc=0x942828
                       kitty/kittens/icat.create_cmd.func1(0x9f4d20?, {0xc0004daf00, 0x1, 0x8})
                                                                                               	/tmp/t/plugins-xbucmfh9/src/kittens/icat/cli_generated.go:15 +0x9e fp=0xc0000f7e50 sp=0xc0000f7e00 pc=0x94037e
                                              kitty/tools/cli.(*Command).ExecArgs(0x986fb0?, {0xc000024090?, 0xc0004eca00?, 0xc000110100?})
                                                                                                                                           	/tmp/t/plugins-xbucmfh9/src/tools/cli/command.go:549 +0x2dc fp=0xc0000f7f08 sp=0xc0000f7e50 pc=0x79e67c
                                                                                       kitty/tools/cli.(*Command).Exec(0xad244d?, {0x0?, 0x401470?, 0x0?})
                                                                                                                                                          	/tmp/t/plugins-xbucmfh9/src/tools/cli/command.go:567 +0x38 fp=0xc0000f7f38 sp=0xc0000f7f08 pc=0x79e958
                                                                                                     main.main()
                                                                                                                	/tmp/t/plugins-xbucmfh9/src/tools/cmd/main.go:33 +0x125 fp=0xc0000f7f80 sp=0xc0000f7f38 pc=0x98d345
                                                           runtime.main()
                                                                         	/usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc0000f7fe0 sp=0xc0000f7f80 pc=0x438d47
        runtime.goexit()
                        	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000f7fe8 sp=0xc0000f7fe0 pc=0x468cc1

                                                                                                                           goroutine 2 [force gc (idle)]:
                                                                                                                                                         runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
                                     	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000060fb0 sp=0xc000060f90 pc=0x439176
                                                                                                                               runtime.goparkunlock(...)
                                                                                                                                                        	/usr/local/go/src/runtime/proc.go:387
                                    runtime.forcegchelper()
                                                           	/usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc000060fe0 sp=0xc000060fb0 pc=0x438fb0
                                                                                                                                                       runtime.goexit()
       	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000060fe8 sp=0xc000060fe0 pc=0x468cc1
                                                                                                   created by runtime.init.6
                                                                                                                            	/usr/local/go/src/runtime/proc.go:293 +0x25

           goroutine 3 [GC sweep wait]:
                                       runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
                                                                                   	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000061780 sp=0xc000061760 pc=0x439176
               runtime.goparkunlock(...)
                                        	/usr/local/go/src/runtime/proc.go:387
                                                                                     runtime.bgsweep(0x0?)
                                                                                                          	/usr/local/go/src/runtime/mgcsweep.go:319 +0xde fp=0xc0000617c8 sp=0xc000061780 pc=0x42553e
                                           runtime.gcenable.func1()
                                                                   	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000617e0 sp=0xc0000617c8 pc=0x41a9c6
                                                                                                                                                              runtime.goexit()
              	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000617e8 sp=0xc0000617e0 pc=0x468cc1
                                                                                                           created by runtime.gcenable
                                                                                                                                      	/usr/local/go/src/runtime/mgc.go:178 +0x6b

                  goroutine 4 [GC scavenge wait]:
                                                 runtime.gopark(0xc000088000?, 0xdb3778?, 0x0?, 0x0?, 0x0?)
                                                                                                           	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000061f70 sp=0xc000061f50 pc=0x439176
                                       runtime.goparkunlock(...)
                                                                	/usr/local/go/src/runtime/proc.go:387
                                                                                                             runtime.(*scavengerState).park(0x1189780)
                                                                                                                                                      	/usr/local/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000061fa0 sp=0xc000061f70 pc=0x423433
                                                                                      runtime.bgscavenge(0x0?)
                                                                                                              	/usr/local/go/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000061fc8 sp=0xc000061fa0 pc=0x423a25
                                              runtime.gcenable.func2()
                                                                      	/usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000061fe0 sp=0xc000061fc8 pc=0x41a966
                                                                                                                                                              runtime.goexit()
              	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000061fe8 sp=0xc000061fe0 pc=0x468cc1
                                                                                                           created by runtime.gcenable
                                                                                                                                      	/usr/local/go/src/runtime/mgc.go:179 +0xaa

                  goroutine 5 [finalizer wait]:
                                               runtime.gopark(0x1a0?, 0x118a580?, 0x60?, 0x78?, 0xc000060770?)
                                                                                                              	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000060628 sp=0xc000060608 pc=0x439176
                                       runtime.runfinq()
                                                        	/usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000607e0 sp=0xc000060628 pc=0x419a07
                                                                                                                                                          runtime.goexit()
          	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000607e8 sp=0xc0000607e0 pc=0x468cc1
                                                                                                           created by runtime.createfing
                                                                                                                                        	/usr/local/go/src/runtime/mfinal.go:163 +0x45

                             goroutine 6 [GC worker (idle)]:
                                                            runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
                                                                                                        	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000062750 sp=0xc000062730 pc=0x439176
                                       runtime.gcBgMarkWorker()
                                                               	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000627e0 sp=0xc000062750 pc=0x41c531
                                                                                                                                                       runtime.goexit()
       	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000627e8 sp=0xc0000627e0 pc=0x468cc1
                                                                                                   created by runtime.gcBgMarkStartWorkers
                                                                                                                                          	/usr/local/go/src/runtime/mgc.go:1199 +0x25

                           goroutine 7 [GC worker (idle)]:
                                                          runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
                                                                                                      	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000062f50 sp=0xc000062f30 pc=0x439176
                               runtime.gcBgMarkWorker()
                                                       	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000062fe0 sp=0xc000062f50 pc=0x41c531
                                                                                                                                               runtime.goexit()
                                                                                                                                                               /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000062fe8 sp=0xc000062fe0 pc=0x468cc1
                                                                                          created by runtime.gcBgMarkStartWorkers
                                                                                                                                 	/usr/local/go/src/runtime/mgc.go:1199 +0x25

                   goroutine 8 [GC worker (idle)]:
                                                  runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
                                                                                              	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000063750 sp=0xc000063730 pc=0x439176
                       runtime.gcBgMarkWorker()
                                               	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000637e0 sp=0xc000063750 pc=0x41c531
                                                                                                                                       runtime.goexit()
                                                                                                                                                       	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000637e8 sp=0xc0000637e0 pc=0x468cc1
                                                                                   created by runtime.gcBgMarkStartWorkers
                                                                                                                          	/usr/local/go/src/runtime/mgc.go:1199 +0x25

           goroutine 18 [GC worker (idle)]:
                                           runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
                                                                                       	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00005c750 sp=0xc00005c730 pc=0x439176
               runtime.gcBgMarkWorker()
                                       	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00005c7e0 sp=0xc00005c750 pc=0x41c531
                                                                                                                               runtime.goexit()
                                                                                                                                               	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00005c7e8 sp=0xc00005c7e0 pc=0x468cc1
                                                                           created by runtime.gcBgMarkStartWorkers
                                                                                                                  	/usr/local/go/src/runtime/mgc.go:1199 +0x25

   goroutine 9 [GC worker (idle)]:
                                  runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
                                                                              	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000063f50 sp=0xc000063f30 pc=0x439176
       runtime.gcBgMarkWorker()
                               	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000063fe0 sp=0xc000063f50 pc=0x41c531
                                                                                                                       runtime.goexit()
                                                                                                                                       	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000063fe8 sp=0xc000063fe0 pc=0x468cc1
                                                                   created by runtime.gcBgMarkStartWorkers
                                                                                                          	/usr/local/go/src/runtime/mgc.go:1199 +0x25

                                                                                                                                                           goroutine 34 [GC worker (idle)]:
                           runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
                                                                       	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000508750 sp=0xc000508730 pc=0x439176
                                                                                                                                                               runtime.gcBgMarkWorker()
                       	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0005087e0 sp=0xc000508750 pc=0x41c531
                                                                                                               runtime.goexit()
                                                                                                                               	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005087e8 sp=0xc0005087e0 pc=0x468cc1
                                                           created by runtime.gcBgMarkStartWorkers
                                                                                                  	/usr/local/go/src/runtime/mgc.go:1199 +0x25

                                                                                                                                                   goroutine 35 [GC worker (idle)]:
                   runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
                                                               	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000508f50 sp=0xc000508f30 pc=0x439176
                                                                                                                                                       runtime.gcBgMarkWorker()
               	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000508fe0 sp=0xc000508f50 pc=0x41c531
                                                                                                       runtime.goexit()
                                                                                                                       	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000508fe8 sp=0xc000508fe0 pc=0x468cc1
                                                   created by runtime.gcBgMarkStartWorkers
                                                                                          	/usr/local/go/src/runtime/mgc.go:1199 +0x25

                                                                                                                                           goroutine 10 [GC worker (idle)]:
           runtime.gopark(0x2ba50098ba80?, 0x3?, 0xac?, 0xf?, 0x0?)
                                                                   	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000504750 sp=0xc000504730 pc=0x439176
                                                                                                                                                               runtime.gcBgMarkWorker()
                       	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0005047e0 sp=0xc000504750 pc=0x41c531
                                                                                                               runtime.goexit()
                                                                                                                               	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005047e8 sp=0xc0005047e0 pc=0x468cc1
                                                           created by runtime.gcBgMarkStartWorkers
                                                                                                  	/usr/local/go/src/runtime/mgc.go:1199 +0x25

                                                                                                                                                   goroutine 50 [GC worker (idle)]:
                   runtime.gopark(0x2ba50096df08?, 0x0?, 0x0?, 0x0?, 0x0?)
                                                                          	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000586750 sp=0xc000586730 pc=0x439176
       runtime.gcBgMarkWorker()
                               	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0005867e0 sp=0xc000586750 pc=0x41c531
                                                                                                                       runtime.goexit()
                                                                                                                                       	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005867e8 sp=0xc0005867e0 pc=0x468cc1
                                                                   created by runtime.gcBgMarkStartWorkers
                                                                                                          	/usr/local/go/src/runtime/mgc.go:1199 +0x25

                                                                                                                                                           goroutine 51 [GC worker (idle)]:
                           runtime.gopark(0x2ba5009888bd?, 0x0?, 0x0?, 0x0?, 0x0?)
                                                                                  	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000586f50 sp=0xc000586f30 pc=0x439176
               runtime.gcBgMarkWorker()
                                       	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000586fe0 sp=0xc000586f50 pc=0x41c531
                                                                                                                               runtime.goexit()
                                                                                                                                               	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000586fe8 sp=0xc000586fe0 pc=0x468cc1
                                                                           created by runtime.gcBgMarkStartWorkers
                                                                                                                  	/usr/local/go/src/runtime/mgc.go:1199 +0x25

   goroutine 19 [GC worker (idle)]:
                                   runtime.gopark(0x11bad60?, 0x1?, 0x12?, 0x37?, 0x0?)
                                                                                       	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00005cf50 sp=0xc00005cf30 pc=0x439176
               runtime.gcBgMarkWorker()
                                       	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00005cfe0 sp=0xc00005cf50 pc=0x41c531
                                                                                                                               runtime.goexit()
                                                                                                                                               	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00005cfe8 sp=0xc00005cfe0 pc=0x468cc1
                                                                           created by runtime.gcBgMarkStartWorkers
                                                                                                                  	/usr/local/go/src/runtime/mgc.go:1199 +0x25

   goroutine 20 [GC worker (idle)]:
                                   runtime.gopark(0x2ba50096d6bf?, 0x0?, 0x0?, 0x0?, 0x0?)
                                                                                          	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00005d750 sp=0xc00005d730 pc=0x439176
                       runtime.gcBgMarkWorker()
                                               	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00005d7e0 sp=0xc00005d750 pc=0x41c531
                                                                                                                                       runtime.goexit()
                                                                                                                                                       	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00005d7e8 sp=0xc00005d7e0 pc=0x468cc1
                                                                                   created by runtime.gcBgMarkStartWorkers
                                                                                                                          	/usr/local/go/src/runtime/mgc.go:1199 +0x25

           goroutine 12 [select, locked to thread]:
                                                   runtime.gopark(0xc000504fa8?, 0x2?, 0xf2?, 0x94?, 0xc000504fa4?)
                                                                                                                   	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000504e18 sp=0xc000504df8 pc=0x439176
                                               runtime.selectgo(0xc000504fa8, 0xc000504fa0, 0x0?, 0x0, 0x0?, 0x1)
                                                                                                                 	/usr/local/go/src/runtime/select.go:327 +0x7be fp=0xc000504f58 sp=0xc000504e18 pc=0x448c7e
                                                  runtime.ensureSigM.func1()
                                                                            	/usr/local/go/src/runtime/signal_unix.go:1000 +0x1af fp=0xc000504fe0 sp=0xc000504f58 pc=0x460cef
                runtime.goexit()
                                	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000504fe8 sp=0xc000504fe0 pc=0x468cc1
                                                                                                                                   created by runtime.ensureSigM
                                                                                                                                                               /usr/local/go/src/runtime/signal_unix.go:983 +0xbd

                                                 goroutine 13 [syscall]:
                                                                        runtime.notetsleepg(0x0?, 0x0?)
                                                                                                       	/usr/local/go/src/runtime/lock_futex.go:236 +0x34 fp=0xc0005057a0 sp=0xc000505768 pc=0x40d934
                                     os/signal.signal_recv()
                                                            	/usr/local/go/src/runtime/sigqueue.go:152 +0x2f fp=0xc0005057c0 sp=0xc0005057a0 pc=0x4654ef
                                                                                                                                                           os/signal.loop()
           	/usr/local/go/src/os/signal/signal_unix.go:23 +0x19 fp=0xc0005057e0 sp=0xc0005057c0 pc=0x7b1f99
                                                                                                               runtime.goexit()
                                                                                                                               	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005057e8 sp=0xc0005057e0 pc=0x468cc1
                                                           created by os/signal.Notify.func1.1
                                                                                              	/usr/local/go/src/os/signal/signal.go:151 +0x2a

                                                                                                                                               goroutine 36 [syscall]:
      syscall.Syscall6(0x0?, 0x400000?, 0xc00011b948?, 0x4228e5?, 0x11bad60?, 0x40e6be?, 0x7f597a1abf88?)
                                                                                                         	/usr/local/go/src/syscall/syscall_linux.go:91 +0x36 fp=0xc00011b8f8 sp=0xc00011b870 pc=0x47cd36
                                               syscall.Syscall6(0x10e, 0x9, 0xc00011bdf8, 0xc00011be78, 0xc00011bef8, 0x0, 0x0)
                                                                                                                               	<autogenerated>:1 +0x45 fp=0xc00011b940 sp=0xc00011b8f8 pc=0x47d3c5
                                   golang.org/x/sys/unix.Pselect(0xffffffffffffffff?, 0x0?, 0xc00011bdc8?, 0xc00011bcc1?, 0x9f3f40?, 0xc00011bc88?)
                                                                                                                                                   	/home/kovid/go/pkg/mod/golang.org/x/sys@v0.10.0/unix/zsyscall_linux.go:1360 +0x7e fp=0xc00011b9d0 sp=0xc00011b940 pc=0x68127e
                                                                                                                     kitty/tools/utils.Select(0xc00011ba98?, 0xc00011bdc8?, 0xc00011ba98?, 0x5?, 0xc00011ba80?)
                                               	/tmp/t/plugins-xbucmfh9/src/tools/utils/select_posix.go:15 +0x79 fp=0xc00011ba20 sp=0xc00011b9d0 pc=0x77c919
                                                                                                                                                            kitty/tools/utils.(*Selector).Wait(0xc00011bdf8, 0x4000?)
                                                     	/tmp/t/plugins-xbucmfh9/src/tools/utils/select.go:73 +0x2c8 fp=0xc00011bb08 sp=0xc00011ba20 pc=0x77c7a8
                                                                                                                                                               kitty/tools/utils.(*Selector).WaitForever(...)
                                             	/tmp/t/plugins-xbucmfh9/src/tools/utils/select.go:84
                                                                                                    kitty/tools/tui/loop.read_from_tty.func2()
                                                                                                                                              	/tmp/t/plugins-xbucmfh9/src/tools/tui/loop/read.go:60 +0x4f fp=0xc00011bb68 sp=0xc00011bb08 pc=0x7b888f
                                                                                       kitty/tools/tui/loop.read_from_tty(0xc000518030, 0x0?, 0xc00051e120, 0xc00051a0c0, 0xc00051e180)
                       	/tmp/t/plugins-xbucmfh9/src/tools/tui/loop/read.go:80 +0x3c9 fp=0xc00011bfa8 sp=0xc00011bb68 pc=0x7b8649
                                                                                                                                kitty/tools/tui/loop.(*Loop).run.func2.1()
          	/tmp/t/plugins-xbucmfh9/src/tools/tui/loop/run.go:298 +0x36 fp=0xc00011bfe0 sp=0xc00011bfa8 pc=0x7bc116
                                                                                                                       runtime.goexit()
                                                                                                                                       	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00011bfe8 sp=0xc00011bfe0 pc=0x468cc1
                                                                   created by kitty/tools/tui/loop.(*Loop).run.func2
                                                                                                                    	/tmp/t/plugins-xbucmfh9/src/tools/tui/loop/run.go:298 +0x1b8

                    goroutine 37 [chan receive]:
                                                runtime.gopark(0x0?, 0xc000117b30?, 0x29?, 0x6b?, 0x0?)
                                                                                                       	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000117af8 sp=0xc000117ad8 pc=0x439176
                               runtime.chanrecv(0xc00051a060, 0xc000117cf8, 0x1)
                                                                                	/usr/local/go/src/runtime/chan.go:583 +0x49d fp=0xc000117b88 sp=0xc000117af8 pc=0x4083bd
                runtime.chanrecv2(0x9f3f40?, 0xc000117d98?)
                                                           	/usr/local/go/src/runtime/chan.go:447 +0x18 fp=0xc000117bb0 sp=0xc000117b88 pc=0x407ef8
                                                                                                                                                       kitty/tools/tui/loop.write_to_tty(0xc000518040, 0xc0002ca000, 0x0?, 0xc00051a0c0, 0xc00051e060)
                                                                                      	/tmp/t/plugins-xbucmfh9/src/tools/tui/loop/write.go:182 +0x3c5 fp=0xc000117fa8 sp=0xc000117bb0 pc=0x7bec05
                                  kitty/tools/tui/loop.(*Loop).run.func9()
                                                                          	/tmp/t/plugins-xbucmfh9/src/tools/tui/loop/run.go:346 +0x36 fp=0xc000117fe0 sp=0xc000117fa8 pc=0x7bb956
                       runtime.goexit()
                                       	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000117fe8 sp=0xc000117fe0 pc=0x468cc1
                                                                                                                                   created by kitty/tools/tui/loop.(*Loop).run
              	/tmp/t/plugins-xbucmfh9/src/tools/tui/loop/run.go:346 +0xad0
```
**Environment details**
```
kitty 0.29.2 (95316fc2dc) created by Kovid Goyal
Linux topaz-MS-7B48 5.19.0-32-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jan 30 17:03:34 UTC 2 x86_64
Ubuntu 22.04.3 LTS topaz-MS-7B48 /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
Running under: X11
Frozen: True
Paths:
  kitty: /home/topaz/.local/kitty.app/bin/kitty
  base dir: /home/topaz/.local/kitty.app/lib/kitty
  extensions dir: /home/topaz/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config files:
  /home/topaz/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity 0.9
bold_font          JetBrains Mono Bold
bold_italic_font   JetBrains Mono Bold Italic
editor             /usr/bin/nvim
enable_audio_bell  False
enabled_layouts    ['tall']
font_family        JetBrains Mono Medium
font_size          15.5
italic_font        JetBrains Mono Medium Italic
modify_font:
    cell_height 100%
    cell_width 100%
shell              /bin/fish
symbol_map:
	U+23fb - U+23fe → Symbols Nerd Font Mono
	U+2665 - U+2665 → Symbols Nerd Font Mono
	U+26a1 - U+26a1 → Symbols Nerd Font Mono
	U+2b58 - U+2b58 → Symbols Nerd Font Mono
	U+e000 - U+e00a → Symbols Nerd Font Mono
	U+e0a0 - U+e0a3 → Symbols Nerd Font Mono
	U+e0b0 - U+e0d4 → Symbols Nerd Font Mono
	U+e200 - U+e2a9 → Symbols Nerd Font Mono
	U+e300 - U+e3e3 → Symbols Nerd Font Mono
	U+e5fa - U+e6aa → Symbols Nerd Font Mono
	U+e700 - U+e7c5 → Symbols Nerd Font Mono
	U+ea60 - U+ebeb → Symbols Nerd Font Mono
	U+f000 - U+f2e0 → Symbols Nerd Font Mono
	U+f300 - U+f32f → Symbols Nerd Font Mono
	U+f400 - U+f4a9 → Symbols Nerd Font Mono
	U+f500 - U+f8ff → Symbols Nerd Font Mono
	U+f0001 - U+f1af0 → Symbols Nerd Font Mono
Added shortcuts:
	super+f1 →  launch --type tab
	super+f2 →  launch
	super+f3 →  launch --cwd=current --type=tab nvim
	super+f4 →  launch --cwd=current --type=tab lf
Changed shortcuts:
	kitty_mod+h →  send_text all eval (history | sk)\n
Colors:
	background         #051212   
	color0             #051212   
	color1             #926c2e   
	color10            #23a46e   
	color11            #37be50   
	color12            #c6b139   
	color13            #99d63d   
	color14            #47c285   
	color15            #8bc67b   
	color2             #408669   
	color3             #61936a   
	color4             #b9a747   
	color5             #91a96c   
	color6             #67a385   
	color7             #93b689   
	color8             #666666   
	color9             #cea564   
	foreground         #93b689   

Important environment variables seen by the kitty process:
	PATH                                /home/topaz/.cargo/bin:/home/topaz/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/topaz/scripts:/home/topaz/dwmscripts
	LANG                                en_GB.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                topaz
	XCURSOR_SIZE                        24
	XDG_DATA_DIRS                       /usr/share/plasma:/home/topaz/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CONFIG_DIRS                     /home/topaz/.config/kdedefaults:/etc/xdg/xdg-plasma:/etc/xdg:/usr/share/kubuntu-default-settings/kf5-settings
	XDG_CURRENT_DESKTOP                 KDE
	XDG_SEAT                            seat0
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 KDE
	XDG_SESSION_ID                      3
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_SESSION_TYPE                    x11
	XDG_VTNR                            1

```
**Additional context**
Kitty with no config has this issue too.

Thank you for your time.

**Comment by kovidgoyal** [comment]
Does not reproduce for me, and there is no way the kitten can kill an
unrelated process. I suggest you look at your system logs where you will
likely find the LInux OOM killer is killing your browser.

**Comment by kovidgoyal** [comment]
Thinking about this, the issue is almost certainly /dev/shm running out of space. icat will use /dev/shm to transmit image data to the terminal. The terminal deletes the shared memory file in /dev/shm after reading the image. I am guessing that something about how lf is calling icat is causing stale files to be left in /dev/shm possibly because icat is being killed between the time it creates the shared memory file and transmits the escape code to the terminal asking it to read and delete it.

You can probably work around it by using --transmit-mode=file or --transmit-mode=direct in lf's invocation of icat but the underlying issue should be fixed instead as SHM based transfer is much faster.

**Comment by kovidgoyal** [comment]
And just for the record here is the correct way to invoke icat in an lf previewer script
```sh
if [[ "$( file -Lb --mime-type "$file")" =~ ^image ]]; then
    kitten icat --clear --stdin no --transfer-mode memory --place "${w}x${h}@${x}x${y}" "$file" > /dev/tty
    exit 1
fi
if [[ "$( file -Lb --mime-type "$file")" == "application/pdf" ]]; then
    pdftoppm -jpeg -f 1 -singlefile "$file" "$CACHE"
    kitten icat --clear --stdin no --transfer-mode memory --place "${w}x${h}@${x}x${y}" "${CACHE}.jpg" > /dev/tty
    exit 1
fi
```

**Comment by kovidgoyal** [comment]
lf needs to have some script to clear the preview area as well, otherwise the last viewed image remains on screen.
