### ISSUE TITLE
Unable to install on Linux Mint

### ISSUE THREAD

**Issue by loveencounterflow** [kovidgoyal/kitty#666]
When I try to follow the installation instructions, I get a Python import error:

```
$  curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8249  100  8249    0     0  15412      0 --:--:-- --:--:-- --:--:-- 15389
Using python executable: /usr/bin/python3
Checking for latest release on GitHub...
Will download and install kitty-0.11.1-x86_64.txz
Downloaded 8520320 bytes 
Extracting tarball...
kitty successfully installed to /home/flow/.local/kitty.app
Use /home/flow/.local/kitty.app/bin/kitty to run kitty
Traceback (most recent call last):
  File "python3.6/runpy.py", line 280, in run_path
  File "python3.6/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 96, in <module>
  File "kitty/__main__.py", line 89, in main
  File "kitty/main.py", line 10, in <module>
  File "kitty/borders.py", line 8, in <module>
ImportError: /home/flow/.local/kitty.app/bin/../lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
```

The exact same message appears when I download and unpack the appropriate release archive (kitty-0.11.1-x86_64.txz).

Any ideas how to fix this?

**Comment by kovidgoyal** [comment]
The version of libfreetype on your system is too old, update it and you
will be fine.

**Comment by okdewit** [comment]
Quick way to update to Freetype 2.8 on Ubuntu and derivatives (tested on Mint 18.3):
```
sudo add-apt-repository ppa:glasen/freetype2
sudo apt update
sudo apt upgrade
```
