### ISSUE TITLE
Cannot build on M1 Mac

### ISSUE THREAD

**Issue by aste4** [kovidgoyal/kitty#6735]
**Describe the bug**
Fails to build using
https://sw.kovidgoyal.net/kitty/build/

```
git clone https://github.com/kovidgoyal/kitty.git && cd kitty
./dev.sh build
Cloning into 'kitty'...
remote: Enumerating objects: 72676, done.
remote: Counting objects: 100% (11185/11185), done.
remote: Compressing objects: 100% (592/592), done.
remote: Total 72676 (delta 10702), reused 10982 (delta 10586), pack-reused 61491
Receiving objects: 100% (72676/72676), 47.54 MiB | 24.44 MiB/s, done.
Resolving deltas: 100% (54797/54797), done.
Downloading macos-64.tar.xz
Dependencies downloaded. Now build kitty with: make develop
Traceback (most recent call last):
  File "/private/tmp/kitty/setup.py", line 1889, in <module>
    main()
  File "/private/tmp/kitty/setup.py", line 1847, in main
    build(args)
  File "/private/tmp/kitty/setup.py", line 922, in build
    kitty_env(args), 'kitty/fast_data_types', args.compilation_database, sources, headers
  File "/private/tmp/kitty/setup.py", line 519, in kitty_env
    libcrypto_cflags, libcrypto_ldflags = libcrypto_flags()
  File "/private/tmp/kitty/setup.py", line 223, in libcrypto_flags
    cflags = pkg_config('libcrypto', '--cflags-only-I', fatal=False)
  File "/private/tmp/kitty/setup.py", line 196, in pkg_config
    subprocess.check_output(cmd, env=env, stderr=None if fatal else subprocess.DEVNULL).decode('utf-8')
  File "/private/tmp/kitty/dependencies/darwin-arm64/python/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/private/tmp/kitty/dependencies/darwin-arm64/python/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/private/tmp/kitty/dependencies/darwin-arm64/python/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/private/tmp/kitty/dependencies/darwin-arm64/python/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 86] Bad CPU type in executable: '/tmp/kitty/dependencies/darwin-arm64/bin/pkg-config'
The following build command failed: /tmp/kitty/dependencies/darwin-arm64/python/Python.framework/Versions/Current/bin/python3 setup.py develop
exit status 1
```

```
file /tmp/kitty/dependencies/darwin-arm64/bin/pkg-config
/tmp/kitty/dependencies/darwin-arm64/bin/pkg-config: Mach-O 64-bit executable x86_64
```

**To Reproduce**
follow https://sw.kovidgoyal.net/kitty/build/ on Mac

**Screenshots**

**Environment details**
```
MacBook Air M1, Ventura 13.5
```

**Comment by kovidgoyal** [comment]
Enable rosetta so you can run the pkg-config executable and you should
be fine.

**Comment by aste4** [comment]
@kovidgoyal Thank you for your quick response.

Rosetta will do the job but I would like to build kitty natively. I do not have rosetta installed and would like to keep it that way.
Any chance you would consider addressing this? Thank you.

**Comment by kovidgoyal** [comment]
It's already fixed. Just re-download and you will be fine.

**Comment by aste4** [comment]
Thanks!
