### ISSUE TITLE
Kitty fails to launch after upgrade to 0.30.1

### ISSUE THREAD

**Issue by vfosterm** [kovidgoyal/kitty#6763]
**Describe the bug**
Kitty fails to launch due to ValueError being raised after upgrade from 29.2-2 to 0.30.1-1

```
[301 12:58:22.268437] Ignoring invalid config line: '/* background              #1E1E2E */'
[301 12:58:22.321566] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/utils.py", line 502, in parse_address_spec
    protocol, rest = spec.split(':', 1)
    ^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 559, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 551, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 293, in __call__
    _run_app(opts, args, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 271, in _run_app
    boss = Boss(opts, args, cached_values, global_shortcuts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 364, in __init__
    listen_fd, self.listening_on = listen_on(args.listen_on)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 174, in listen_on
    family, address, socket_path = parse_address_spec(spec)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/kitty/kitty/utils.py", line 504, in parse_address_spec
    raise ValueError(f'Invalid listen-on value: {spec} must be of the form protocol:address')
ValueError: Invalid listen-on value: yes must be of the form protocol:address

```

**To Reproduce**
1. upgrade
2. launch kitty
3. set allow_remote_control to yes
4. set listen_on to yes
5. See error

**Environment details**
Can't launch kitty
Linux 6.1.60-1-lts

**Additional context**
This seems to be caused by having allow_remote_control and listen_on both set to yes

**Comment by kovidgoyal** [comment]
You have an invalid value for listen_on either in your kitty.conf or on
the command line, delete it and you will be fine.
