### ISSUE TITLE
"invalid memory address or nil pointer dereference" for `poi up..` emoji search

### ISSUE THREAD

**Issue by tomsaleeba** [kovidgoyal/kitty#6799]
**Describe the bug**
When trying to search for an emoji (`ctrl+shift+u` mode) and using the input `poi up..`, I get the error:
```
Paniced with error: runtime error: invalid memory address or nil pointer dereference
Stacktrace:
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
kitty/tools/tui/loop.(*Loop).Run.func1()
	kitty/tools/tui/loop/api.go:244 +0x66
panic({0x565336924140?, 0x565336d6be70?})
	runtime/panic.go:914 +0x21f
kitty/tools/utils.(*Set[...]).Len(...)
	kitty/tools/utils/set.go:45
kitty/tools/utils.(*Set[...]).Intersect(0x0?, 0x5653368ac200?)
	kitty/tools/utils/set.go:63 +0x2c
kitty/tools/unicode_names.marks_for_query({0xc0003e4fb0?, 0x0?})
	kitty/tools/unicode_names/query.go:120 +0x17b
kitty/tools/unicode_names.CodePointsForQuery({0xc0003e4fb0?, 0x2?})
	kitty/tools/unicode_names/query.go:130 +0x27
kitty/kittens/unicode_input.(*handler).update_codepoints(0xc000180180)
	kitty/kittens/unicode_input/main.go:244 +0x576
kitty/kittens/unicode_input.(*handler).update_current_char(0xc000180180)
	kitty/kittens/unicode_input/main.go:257 +0x1c
kitty/kittens/unicode_input.(*handler).update_prompt(0xc000180180)
	kitty/kittens/unicode_input/main.go:288 +0x27
kitty/kittens/unicode_input.(*handler).refresh(0xc0001a0800?)
	kitty/kittens/unicode_input/main.go:543 +0x18
kitty/kittens/unicode_input.(*handler).on_text(0xc000180180, {0xc0003e4fa0?, 0xc000180180?}, 0x0?, 0x2c?)
	kitty/kittens/unicode_input/main.go:376 +0x3a
kitty/tools/tui/loop.(*Loop).handle_key_event(0xc0002841e0, 0xc000112c00)
	kitty/tools/tui/loop/run.go:142 +0xad
kitty/tools/tui/loop.(*Loop).handle_csi(0xc0002841e0, {0xc0003e44a0, 0x7, 0x10})
	kitty/tools/tui/loop/run.go:71 +0x1ee
kitty/tools/wcswidth.(*EscapeCodeParser).dispatch_esc_code(0xc000284228)
	kitty/tools/wcswidth/escape-code-parser.go:152 +0xbf
kitty/tools/wcswidth.(*EscapeCodeParser).dispatch_byte(0xc000284228, 0x75)
	kitty/tools/wcswidth/escape-code-parser.go:288 +0x32e
kitty/tools/wcswidth.(*EscapeCodeParser).ParseByte(0xc000284228, 0x6?)
	kitty/tools/wcswidth/escape-code-parser.go:94 +0x149
kitty/tools/wcswidth.(*EscapeCodeParser).Parse(...)
	kitty/tools/wcswidth/escape-code-parser.go:105
kitty/tools/tui/loop.(*Loop).dispatch_input_data(0xc0001b5970?, {0xc000328049, 0x9, 0x0?})
	kitty/tools/tui/loop/read.go:25 +0x95
kitty/tools/tui/loop.(*Loop).run(0xc0002841e0)
	kitty/tools/tui/loop/run.go:462 +0x109b
kitty/tools/tui/loop.(*Loop).Run(0xc0004d1bb8?)
	kitty/tools/tui/loop/api.go:261 +0x65
kitty/kittens/unicode_input.run_loop(0xc00010f0c0)
	kitty/kittens/unicode_input/main.go:593 +0x71c
kitty/kittens/unicode_input.main(0xc0001c7700?, 0x5653368ee140?, {0xc00010f0c0?, 0xc00013c000?, 0xc0003155f8?})
	kitty/kittens/unicode_input/main.go:633 +0x34
kitty/kittens/unicode_input.create_cmd.func1(0x56533691e300?, {0xc0001bb580, 0x0, 0x8})
	kitty/kittens/unicode_input/cli_generated.go:14 +0x9a
kitty/tools/cli.(*Command).ExecArgs(0x56533659892c?, {0xc00013c000?, 0xc0001daa00?, 0xc00050c100?})
	kitty/tools/cli/command.go:549 +0x2b4
kitty/tools/cli.(*Command).Exec(0xc00050c100?, {0x0?, 0x5653365a1200?, 0xc000116058?})
	kitty/tools/cli/command.go:567 +0x32
main.main()
	kitty/tools/cmd/main.go:33 +0x10d
Press any key to exit.
```

**To Reproduce**
1. `ctrl+shift+u` to open emoji search
2. type `poi up..` and when you type the second `.` an error message pops up. While trying to confirm reproducibility, I found the problem wasn't completely deterministic. Some times the error would happen on the first dot and other times on the second.

**Screenshots**
![image](https://github.com/kovidgoyal/kitty/assets/1773838/75aa34c2-77fd-4e80-861a-4d800d7e4628)

Here's a screencast showing:
- with my regular kitty config
  - first input was `poi up..`
  - second input, with slower typing, was `poi up.` (just one dot)
- with `kitty -c NONE`
  - both inputs were with two dots

https://github.com/kovidgoyal/kitty/assets/1773838/7c26bb51-9771-4d4f-bd62-839e2f77d14e

**Environment details**
```
kitty 0.29.2 created by Kovid Goyal
Linux tom-x1eg2 6.1.55-1-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Sep 23 12:13:56 UTC 2023 x86_64
Manjaro Linux 6.1.55-1-MANJARO  (tom-x1eg2) (/dev/tty)


DISTRIB_ID="ManjaroLinux"
DISTRIB_RELEASE="23.0.3"
DISTRIB_CODENAME="Uranos"
DISTRIB_DESCRIPTION="Manjaro Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/bin:/bin
	LANG                                en_AU.UTF-8
	EDITOR                              nvim
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	USER                                tom
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	LC_ADDRESS                          en_AU.UTF-8
	LC_NAME                             en_AU.UTF-8
	LC_MONETARY                         en_AU.UTF-8
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 i3
	XDG_SESSION_TYPE                    x11
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/tom
	LC_PAPER                            en_AU.UTF-8
	XDG_CURRENT_DESKTOP                 i3
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	LC_IDENTIFICATION                   en_AU.UTF-8
	LC_TELEPHONE                        en_AU.UTF-8
	LC_MEASUREMENT                      en_AU.UTF-8
	XDG_VTNR                            7
	XDG_SESSION_ID                      2
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_TIME                             en_AU.UTF-8
	XDG_DATA_DIRS                       /home/tom/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
	LC_NUMERIC                          en_AU.UTF-8
```

**Additional context**
I can reproduce the problem with `kitty --config NONE` (see screencast).

The problem happens for different resolutions, just in case window size matters. I've got 1920x1080 (actually 4K with hidpi mode) and 1920x1080 with a `1.4x` scale to make elements visually bigger (the one in the screencast).

**Comment by tomsaleeba** [comment]
Side note: kitty is _amazing_. I use it everyday. Thanks for all your efforts 😍.

**Comment by kovidgoyal** [comment]
Doesnt reproduce for me with current kitty update and let me know if it still reproduces for you.

**Comment by tomsaleeba** [comment]
Confirmed, doesn't reproduce with `0.31.0`. Sorry, I should've checked that first 🤦
