### ISSUE TITLE
Kitty wont open on Wayland (GLFW problem?)

### ISSUE THREAD

**Issue by TKF05** [kovidgoyal/kitty#6811]
So basically Im running swaywm on wayland and when I run kitty I get errors and it wont start. Other terminal emulators like alacritty and foot work well. Note: I installed glfw-wayland bc some forum said it would probably be helpful.
Tried reinstalling a couple of times and downloading from different repos.

**To Reproduce**
1. download kitty from Artix/Arch repos
2. Be on swaywm/hyprland wayland protocol
3. run kitty command

```
[315 21:00:47.860968] [glfw error 65543]: EGL: Failed to create context: Arguments are inconsistent
[315 21:00:47.876701] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 559, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 551, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 293, in __call__
    _run_app(opts, args, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 266, in _run_app
    window_id = create_os_window(
                ^^^^^^^^^^^^^^^^^
ValueError: Failed to create GLFWwindow

**Comment by kovidgoyal** [comment]
That indicates glfw is failing to create a window, almost certainly some
driver issue on your machine. 

Make sure you are running the official up-to-date kitty binaries from
https://sw.kovidgoyal.net/kitty/binary/ 

and if that does not help you can add

linux_display_server x11

to kitty.conf to bypass wayland.
