### ISSUE TITLE
exception when following web url

### ISSUE THREAD

**Issue by rickysarraf** [kovidgoyal/kitty#685]
Kitty: 0.11.1
OS: Debian
Version: Debian Testing

When running Kitty and hit CTRL + Shift + E, I try to follow the URL. The following exception is raised.

```
rrs@priyasi:~$ .local/kitty.app/bin/kitty
[178 14:13:50.439293] Ignoring unknown config key: font_size_delta

xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:87:34: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:88:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:89:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:90:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:91:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:92:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:93:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:94:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:95:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:96:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:97:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:97:29: too many errors
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:97:29: failed to parse file
[178 14:13:50.451778] [glfw error 65544]: Failed to create XKB compose table
Traceback (most recent call last):
  File "kitty/boss.py", line 261, in on_child_death
  File "kitty/boss.py", line 624, in on_kitten_finish
  File "kitty/runner.py", line 80, in deserialize
ValueError: invalid literal for int() with base 10: '{"match":'
```

**Comment by kovidgoyal** [comment]
That looks like something is outputting junk interspersed with the kittens output. Run it from source with this commit: https://github.com/kovidgoyal/kitty/commit/0c88e11cd70c5b5e032b4466d82ef5fe719b722a and it should give us a more useful error message.

**Comment by kovidgoyal** [comment]
Actually, given #686 this is likely caused by the same issue of mixing two kitty installations. The kitten is running from a different installation than kitty, which makes its output unexpected.
