### ISSUE TITLE
panic from `kitten +ask -t choices -c 'a:<choice>`: bad slice bound

### ISSUE THREAD

**Issue by lemontheme** [kovidgoyal/kitty#6855]
**Describe the bug**

I'm trying to use the 'ask' kitten in the multiple choice mode, i.e. with `--type choices`. Despite reading the --help message carefully, I can't get it to work. _choices.go_ throws a runtime error.

**To Reproduce**

1. Run the command

```shell
kitten ask  -m 'what is up?' -t choices -c 'a:not much' -c 'b:rather a lot'
```

(I've tried formatting the argument to `-c` in various ways.)

2. Get the following error

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
kitty/kittens/ask.GetChoices(0x1400069a140)
	/private/var/folders/wj/cqy1nsyn4wn94d96btkldt0r0000gn/C/t/plugins-96p25cjh/src/kittens/ask/choices.go:96 +0x107c
kitty/kittens/ask.main(0x140002c8400?, 0x1400069a140, {0x140002b4880, 0x0, 0x8})
	/private/var/folders/wj/cqy1nsyn4wn94d96btkldt0r0000gn/C/t/plugins-96p25cjh/src/kittens/ask/main.go:36 +0x1c8
kitty/kittens/ask.create_cmd.func1(0x105224e40?, {0x140002b4880, 0x0, 0x8})
	/private/var/folders/wj/cqy1nsyn4wn94d96btkldt0r0000gn/C/t/plugins-96p25cjh/src/kittens/ask/cli_generated.go:14 +0x90
kitty/tools/cli.(*Command).ExecArgs(0x1400012c000?, {0x140000c4000?, 0x1b?, 0x1400012c000?})
	/private/var/folders/wj/cqy1nsyn4wn94d96btkldt0r0000gn/C/t/plugins-96p25cjh/src/tools/cli/command.go:546 +0x248
kitty/tools/cli.(*Command).Exec(0x1400012c000?, {0x0?, 0x60?, 0x0?})
	/private/var/folders/wj/cqy1nsyn4wn94d96btkldt0r0000gn/C/t/plugins-96p25cjh/src/tools/cli/command.go:564 +0x3c
main.main()
	/private/var/folders/wj/cqy1nsyn4wn94d96btkldt0r0000gn/C/t/plugins-96p25cjh/src/tools/cmd/main.go:34 +0x15c
```

**Environment details**

```
kitty 0.31.0 (6d49686aee) created by Kovid Goyal
Darwin silver-lemon.fritz.box 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020 arm64
ProductName:            macOS ProductVersion:           14.1.1 BuildVersion:            23B81
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh```
```

Maybe I'm doing something wrong?

**Comment by lemontheme** [comment]
Incredibly quick response! Thanks :)

I see now what I was missing: the choice letter must be a character that occurs within the text string. In my example above, `-c 'a:not much'` was invalid because `a` is not part of `not much`. By contrast, `y:Yes` works, as does `y:Anyway`, because both choice texts contain a `y`.

In #6859 I propose a minor change to the help message to make this clearer.
