### ISSUE TITLE
layout resize causes exception

### ISSUE THREAD

**Issue by rickysarraf** [kovidgoyal/kitty#686]
Kitty: 0.11.1
OS: Debian
Version: Debian Testing

I'm not sure why it is picking kitty modules from `/usr` when I've installed the `0.11.1` version from your website.

```
Unhandled exception running kitten:
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kittens/runner.py", line 71, in main
    launch(args)
  File "/usr/bin/../lib/kitty/kittens/runner.py", line 52, in launch
    m = import_kitten_main_module(config_dir, kitten)
  File "/usr/bin/../lib/kitty/kittens/runner.py", line 34, in import_kitten_main_module
    m = importlib.import_module('kittens.{}.main'.format(kitten))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'kittens.resize_window'
Press Enter to quit...
```

**Comment by kovidgoyal** [comment]
You're mixing two kitty installations on your system. Clean them out and you will be fine.
