### ISSUE TITLE
Kitty won't open, crashes with error re EGL and GLFWwindow

### ISSUE THREAD

**Issue by jordan-bravo** [kovidgoyal/kitty#6869]
**Describe the bug**
Kitty crashes when trying to open.

**To Reproduce**

1. Install kitty `v0.31.0` with Nix and Home Manager from `nixpkgs unstable`.
2. Open Gnome Terminal, type `kitty` and press Enter. OR, go to Gnome activities and select Kitty Icon.
3. Error is shown.

```
[333 17:02:45.169215] [glfw error 65542]: EGL: Failed to get EGL display: Success
[333 17:02:45.172191] Traceback (most recent call last):
  File "/nix/store/kmk22fy57pr3yxkf3jn5h5y40rvgryny-kitty-0.31.0/bin/../lib/kitty/kitty/main.py", line 559, in main
    _main()
  File "/nix/store/kmk22fy57pr3yxkf3jn5h5y40rvgryny-kitty-0.31.0/bin/../lib/kitty/kitty/main.py", line 551, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/nix/store/kmk22fy57pr3yxkf3jn5h5y40rvgryny-kitty-0.31.0/bin/../lib/kitty/kitty/main.py", line 293, in __call__
    _run_app(opts, args, bad_lines)
  File "/nix/store/kmk22fy57pr3yxkf3jn5h5y40rvgryny-kitty-0.31.0/bin/../lib/kitty/kitty/main.py", line 265, in _run_app
    window_id = create_os_window(
                ^^^^^^^^^^^^^^^^^
ValueError: Failed to create GLFWwindow
```

**Screenshots**
N/A

**Environment details**
Note: Can't open kitty for debug info.  System info below.

OS: Ubuntu 22.04.3 LTS bare metal (not a VM)
Hardware: ThinkPad P14s
RAM: 32GiB
Processor: 13th Gen Intel Core i7-1360P x 16
Desktop Environment: Gnome
Windowing System: Wayland
Kitty Version: `0.31.0` installed via Nix package manager (with Home Manager) from `nixpkgs unstable`

**Additional context**
Try to reproduce the problem with `kitty --config NONE`: identical error as above.

**Comment by kovidgoyal** [comment]
Use the official kitty binaries. I dont support third party kitty
packages.
