### ISSUE TITLE
Kitty crashes if there is a kitty file in .config

### ISSUE THREAD

**Issue by manimax3** [kovidgoyal/kitty#697]
Accidentally created a invalid (file) symlink named kitty in my ~/.config folder. Kitty crashes with:
```Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 96, in <module>
    main()
  File "/usr/bin/../lib/kitty/__main__.py", line 89, in main
    from kitty.main import main
  File "/usr/bin/../lib/kitty/kitty/main.py", line 10, in <module>
    from .borders import load_borders_program
  File "/usr/bin/../lib/kitty/kitty/borders.py", line 11, in <module>
    from .utils import load_shaders
  File "/usr/bin/../lib/kitty/kitty/utils.py", line 15, in <module>
    from .constants import (
  File "/usr/bin/../lib/kitty/kitty/constants.py", line 49, in <module>
    config_dir = _get_config_dir()
  File "/usr/bin/../lib/kitty/kitty/constants.py", line 45, in _get_config_dir
    os.makedirs(ans, exist_ok=True)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/manimax3/.config/kitty'
```

It would be nice if it would at least start with a simulated empty config and print the error because usually I wouldn't see the python error message.

OS is ArchLinux with Kitty version 0.11.1.

**Comment by kovidgoyal** [comment]
Sadly, this cannot be done. kitty requires a config directory for its operation not a file. If creating the directory does not work, that is fatal. I could of course play games like trying alternate directory names, etc. but that only handles this particular failure case not the general one of being unable to find a suitable config directory.
