### ISSUE TITLE
ImportError after updating

### ISSUE THREAD

**Issue by dampdigits** [kovidgoyal/kitty#7067]
**Describe the bug**
Encountering an error, after updating kitty.

**Screenshots**
![kittyIssue](https://github.com/kovidgoyal/kitty/assets/113439449/977d9556-d518-4718-904d-bdf3a29502c7)

**Error**
```
kitty
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/dampdigits/kitty/__main__.py", line 7, in <module>
    main()
  File "/home/dampdigits/kitty/kitty/entry_points.py", line 194, in main
    from kitty.main import main as kitty_main
  File "/home/dampdigits/kitty/kitty/main.py", line 12, in <module>
    from .boss import Boss
  File "/home/dampdigits/kitty/kitty/boss.py", line 61, in <module>
    from .fast_data_types import (
ImportError: cannot import name 'os_window_focus_counters' from 'kitty.fast_data_types' (/home/dampdigits/kitty/kitty/fast_data_types.so)
```

**Additional context**
I'm an average kitty user, and I can't figure out what's causing this error. It was working fine when I didn't update it.
My daily usage is highly dependent on this terminal, and I would appreciate any help @kovidgoyal 
OS: AntiX-23

**Comment by kovidgoyal** [comment]
You updated it how? I suggest you use the official binaries from kitty
https://sw.kovidgoyal.net/kitty/binary/

**Comment by dampdigits** [comment]
Thanks, I installed it from the official website but I'm encountering another error

```
[027 16:43:03.713544] [glfw error 65543]: GLX: Failed to create context: GLXBadFBConfig
[027 16:43:03.713656] Failed to create GLFW temp window! This usually happens because of old/broken OpenGL drivers. kitty requires working OpenGL 3.3 drivers.
```

Searched and read a few discussions and I came across this hack `LIBGL_ALWAYS_SOFTWARE=true GALLIUM_DRIVER=llvmpipe kitty` and that launches it correctly, however, I have to run this command all the time to launch it. Any tips on how to overcome it?
