### ISSUE TITLE
Regular crashes after a period of inactivity

### ISSUE THREAD

**Issue by amalliar** [kovidgoyal/kitty#7094]
**Describe the bug**
The terminal receives SIGABRT after about 15 to 30 minutes of inactivity.

**Environment details**
```
kitty 0.31.0 created by Kovid Goyal
Linux 00C0CAB10E13 6.6.14-2-lts #1 SMP PREEMPT_DYNAMIC Wed, 31 Jan 2024 09:27:08 +0000 x86_64
Arch Linux 6.6.14-2-lts (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/amalliar/.config/kitty/kitty.conf

Config options different from defaults:
bold_font               JetBrainsMono NF Bold
bold_italic_font        JetBrainsMono NF Bold Italic
clipboard_control       ('write-clipboard', 'write-primary', 'read-clipboard', 'read-primary', 'no-append')
cursor_text_color       None
disable_ligatures       2
enable_audio_bell       False
font_family             JetBrainsMono Nerd Font
hide_window_decorations 1
italic_font             JetBrainsMono NF Italic
Colors:
	active_border_color     #d3869b   
	active_tab_background   #665c54   
	active_tab_foreground   #fbf1c7   
	background              #282828   
	bell_border_color       #8ec07c   
	color0                  #282828   
	color1                  #cc241d   
	color10                 #b8bb26   
	color11                 #fabd2f   
	color12                 #83a598   
	color13                 #d3869b   
	color14                 #8ec07c   
	color15                 #fbf1c7   
	color2                  #98971a   
	color3                  #d79921   
	color4                  #458588   
	color5                  #b16286   
	color6                  #689d6a   
	color7                  #a89984   
	color8                  #7c6f64   
	color9                  #fb4934   
	cursor                  #928374   
	foreground              #fbf1c7   
	inactive_border_color   #665c54   
	inactive_tab_background #3c3836   
	inactive_tab_foreground #a89984   
	selection_background    #ebdbb2   
	selection_foreground    #928374   
	url_color               #83a598   
	visual_bell_color       #8ec07c   

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_GB.UTF-8
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	USER                                amalliar
	XCURSOR_SIZE                        24
	XDG_DATA_DIRS                       /home/amalliar/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 gnome-xorg
	XDG_SESSION_TYPE                    x11

```

**Additional context**
I think it might be worth mentioning that I'm using an nvidia driver 470.223.02-1 (proprietary one). The only thing that is running inside kitty at the time of crash is tmux session with a couple of windows open: one with htop/btop and another with zsh. That's it. I 've also managed to get a full backtrace after another crush, hopefully it will help:
```Gdb
[New Thread 0x7ffff191b6c0 (LWP 138471)]                                                                                                      
[Detaching after fork from child process 138472]                                                                                              
[035 13:40:42.955735] Application escape mode is not supported, the extended keyboard protocol should be used instead
[035 13:40:42.955751] Application escape mode is not supported, the extended keyboard protocol should be used instead

Thread 1 "kitty" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
Downloading source file /usr/src/debug/glibc/glibc/nptl/pthread_kill.c
warning: Source file is more recent than executable.                                                                                          
44	      return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff76ac8a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff765c668 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff76444b8 in __GI_abort () at abort.c:79
#4  0x00007ffff2fdb529 in ?? () from /usr/lib/libnvidia-glcore.so.470.223.02
#5  0x00007ffff3158fba in ?? () from /usr/lib/libnvidia-glcore.so.470.223.02
#6  0x00007ffff316252c in ?? () from /usr/lib/libnvidia-glcore.so.470.223.02
#7  0x00007ffff30decef in ?? () from /usr/lib/libnvidia-glcore.so.470.223.02
#8  0x00007ffff305f350 in ?? () from /usr/lib/libnvidia-glcore.so.470.223.02
#9  0x00007ffff305fcd9 in ?? () from /usr/lib/libnvidia-glcore.so.470.223.02
#10 0x00007ffff2ca4a9d in ?? () from /usr/lib/libnvidia-glcore.so.470.223.02
#11 0x00007ffff6a73e29 in map_buffer (access=35001, idx=<optimized out>) at kitty/gl.c:252
#12 map_vao_buffer (access=35001, bufnum=2, vao_idx=2) at kitty/gl.c:368
#13 cell_update_uniform_block (uniform_buffer=2, os_window=0x5555557eceb0, inverted=false, cursor=0x5555562088c8, crd=0x7fffffffa030, 
    screen=0x555556100570, vao_idx=2) at kitty/shaders.c:303
#14 draw_cells (vao_idx=2, srd=0x5555560dda20, os_window=0x5555557eceb0, is_active_window=true, can_be_focused=true, window=0x5555560dda00)
    at kitty/shaders.c:926
#15 0x00007ffff6a19a46 in render_prepared_os_window (all_windows_have_same_bg=true, num_visible_windows=<optimized out>, 
    active_window_bg=<optimized out>, active_window_id=1, os_window=0x5555557eceb0) at kitty/child-monitor.c:809
#16 render_os_window (ignore_render_frames=false, scan_for_animated_images=<optimized out>, now=<optimized out>, w=<optimized out>)
    at kitty/child-monitor.c:872
#17 render (input_read=<optimized out>, now=<optimized out>) at kitty/child-monitor.c:896
#18 process_global_state (data=0x7ffff5b48e70) at kitty/child-monitor.c:1241
#19 0x00007ffff5a41553 in dispatchTimers.part.0.constprop.0.isra.0 (eld=0x7ffff5a8bb10 <_glfw+133552>) at glfw/backend_utils.c:209
#20 0x00007ffff5a2b92f in dispatchTimers (eld=0x7ffff5a8bb10 <_glfw+133552>) at glfw/backend_utils.c:194
#21 pollForEvents (eld=0x7ffff5a8bb10 <_glfw+133552>, display_callback=0x0, timeout=<optimized out>) at glfw/backend_utils.c:310
#22 handleEvents (timeout=<optimized out>) at glfw/x11_window.c:72
#23 _glfwPlatformWaitEvents () at glfw/x11_window.c:2735
#24 _glfwPlatformRunMainLoop (data=0x7ffff5b48e70, tick_callback=0x7ffff6a18960 <process_global_state>) at glfw/main_loop.h:30
#25 glfwRunMainLoop (callback=0x7ffff6a18960 <process_global_state>, data=0x7ffff5b48e70) at glfw/init.c:355
#26 0x00007ffff6a1201c in run_main_loop (cb=0x7ffff6a18960 <process_global_state>, cb_data=0x7ffff5b48e70) at kitty/glfw.c:1957
#27 main_loop (self=0x7ffff5b48e70, a=<optimized out>) at kitty/child-monitor.c:1266
#28 0x00007ffff7a0bf5e in method_vectorcall_NOARGS (func=0x7ffff7099990, args=0x7ffff7f9f560, nargsf=<optimized out>, kwnames=0x0)
    at Objects/descrobject.c:453
#29 0x00007ffff79f2987 in _PyObject_VectorcallTstate (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, 
    callable=0x7ffff7099990, tstate=0x7ffff7d89378 <_PyRuntime+166328>) at ./Include/internal/pycore_call.h:92
#30 PyObject_Vectorcall (callable=0x7ffff7099990, args=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at Objects/call.c:299
#31 0x00007ffff79e4c23 in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>)
    at Python/ceval.c:4760
#32 0x00007ffff7a0bb90 in _PyEval_EvalFrame (throwflag=0, frame=0x7ffff7f9f408, tstate=0x7ffff7d89378 <_PyRuntime+166328>)
--Type <RET> for more, q to quit, c to continue without paging--c
    at ./Include/internal/pycore_ceval.h:73
#33 _PyEval_Vector (kwnames=<optimized out>, argcount=4, args=0x7fffffffa690, locals=0x0, func=0x7ffff5c5c860, 
    tstate=0x7ffff7d89378 <_PyRuntime+166328>) at Python/ceval.c:6425
#34 _PyFunction_Vectorcall (func=0x7ffff5c5c860, stack=0x7fffffffa690, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:393
#35 0x00007ffff79de1d7 in _PyObject_FastCallDictTstate (tstate=0x7ffff7d89378 <_PyRuntime+166328>, callable=0x7ffff5c5c860, 
    args=<optimized out>, nargsf=<optimized out>, kwargs=<optimized out>) at Objects/call.c:141
#36 0x00007ffff7a1429d in _PyObject_Call_Prepend (tstate=0x7ffff7d89378 <_PyRuntime+166328>, callable=0x7ffff5c5c860, obj=0x7ffff5c58710, 
    args=<optimized out>, kwargs=0x0) at Objects/call.c:482
#37 0x00007ffff7ad7c02 in slot_tp_call (self=0x7ffff5c58710, args=0x7ffff5c8f600, kwds=0x0) at Objects/typeobject.c:7623
#38 0x00007ffff79da8ec in _PyObject_MakeTpCall (tstate=0x7ffff7d89378 <_PyRuntime+166328>, callable=0x7ffff5c58710, args=<optimized out>, 
    nargs=3, keywords=0x0) at Objects/call.c:214
#39 0x00007ffff79e4c23 in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>)
    at Python/ceval.c:4760
#40 0x00007ffff7a9c484 in _PyEval_EvalFrame (throwflag=0, frame=0x7ffff7f9f1b8, tstate=0x7ffff7d89378 <_PyRuntime+166328>)
    at ./Include/internal/pycore_ceval.h:73
#41 _PyEval_Vector (tstate=tstate@entry=0x7ffff7d89378 <_PyRuntime+166328>, func=func@entry=0x7ffff75f5f80, 
    locals=locals@entry=0x7ffff7612b80, args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0) at Python/ceval.c:6425
#42 0x00007ffff7a9be6c in PyEval_EvalCode (co=0x7ffff75a4f30, globals=<optimized out>, locals=0x7ffff7612b80) at Python/ceval.c:1140
#43 0x00007ffff7ab2c42 in builtin_exec_impl (module=<optimized out>, closure=<optimized out>, locals=0x7ffff7612b80, globals=0x7ffff7612b80, 
    source=0x7ffff75a4f30) at Python/bltinmodule.c:1077
#44 builtin_exec (module=<optimized out>, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>)
    at Python/clinic/bltinmodule.c.h:465
#45 0x00007ffff79f383a in cfunction_vectorcall_FASTCALL_KEYWORDS (func=0x7ffff75acf90, args=0x7ffff7f9f180, nargsf=<optimized out>, 
    kwnames=0x0) at ./Include/cpython/methodobject.h:52
#46 0x00007ffff79f2987 in _PyObject_VectorcallTstate (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, 
    callable=0x7ffff75acf90, tstate=0x7ffff7d89378 <_PyRuntime+166328>) at ./Include/internal/pycore_call.h:92
#47 PyObject_Vectorcall (callable=0x7ffff75acf90, args=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at Objects/call.c:299
#48 0x00007ffff79e4c23 in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>)
    at Python/ceval.c:4760
#49 0x00007ffff7a0bb90 in _PyEval_EvalFrame (throwflag=0, frame=0x7ffff7f9f020, tstate=0x7ffff7d89378 <_PyRuntime+166328>)
    at ./Include/internal/pycore_ceval.h:73
#50 _PyEval_Vector (kwnames=<optimized out>, argcount=2, args=0x7ffff719a158, locals=0x0, func=0x7ffff71b54e0, 
    tstate=0x7ffff7d89378 <_PyRuntime+166328>) at Python/ceval.c:6425
#51 _PyFunction_Vectorcall (func=0x7ffff71b54e0, stack=0x7ffff719a158, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:393
#52 0x00007ffff7ac5757 in pymain_run_module (modname=modname@entry=0x7ffff7b68740 L"__main__", set_argv0=set_argv0@entry=0)
    at Modules/main.c:300
#53 0x00007ffff792faa7 in pymain_run_python (exitcode=0x7fffffffad30) at Modules/main.c:598
#54 Py_RunMain () at Modules/main.c:680
#55 0x000055555555660a in run_embedded (run_data=<synthetic pointer>) at kitty/launcher/main.c:215
#56 main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at kitty/launcher/main.c:383
```

**Comment by amalliar** [comment]
Let me know if you need any additional system info

**Comment by kovidgoyal** [comment]
This is a crash in your nvidia driver. I suggest rolling back to a
previous version and/or reporting it to them.
