### ISSUE TITLE
Unknown action: send_key for mouse_map

### ISSUE THREAD

**Issue by guigui64** [kovidgoyal/kitty#7126]
**Describe the bug**
I'd like to map my mouse buttons 4 and 5 to Ctrl+O/I for vim.
I tried this:

```
mouse_map b4 click grabbed send_key ctrl+o
mouse_map b5 click grabbed send_key ctrl+i
```

When I click on one of the buttons, I get the following error:

```
Failed to parse action


send_key ctrl+i
'Unknown action: send_key'

Press e to see detailed traceback or any other key to exit
Traceback (most recent call last):
  File "lib/python3.11/kitty/boss.py", line 1610, in combine
  File "lib/python3.11/kitty/options/utils.py", line 1000, in resolve_aliases
  File "lib/python3.11/kitty/options/utils.py", line 1050, in resolve_aliases_and_parse_actions
  File "lib/python3.11/kitty/options/utils.py", line 976, in parse_key_action
KeyError: 'Unknown action: send_key'



Press Enter or Esc to exit
```

**Environment details**
```
kitty 0.31.0 (b247fda672) created by Kovid Goyal
Darwin Castamere.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:51 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6030 arm64
ProductName:            macOS ProductVersion:           14.2.1 BuildVersion:            23C71
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/guillaume/.config/kitty/kitty.conf

Config options different from defaults:
disable_ligatures       2
font_family             Monaco
font_features:
{'GeistMonoVariable-Bold': ('-liga',),
 'GeistMonoVariable-Medium': ('-liga',),
 'GeistMonoVariable-SemiBold': ('-liga',)}
font_size               13.0
Added mouse actions:
        b4 click grabbed →  send_key ctrl+o
        b5 click grabbed →  send_key ctrl+i
Removed shortcuts:
        cmd+k →  clear_terminal to_cursor active
        cmd+r →  start_resizing_window
        kitty_mod+6 →  sixth_window
        kitty_mod+left →  previous_tab
        kitty_mod+right →  next_tab
Colors:
        active_tab_background   #f2e9e1   
        active_tab_foreground   #575279   
        background              #faf4ed   
        color0                  #f2e9e1   
        color1                  #b4637a   
        color10                 #286983   
        color11                 #ea9d34   
        color12                 #56949f   
        color13                 #907aa9   
        color14                 #d7827e   
        color15                 #575279   
        color2                  #286983   
        color3                  #ea9d34   
        color4                  #56949f   
        color5                  #907aa9   
        color6                  #d7827e   
        color7                  #575279   
        color8                  #9893a5   
        color9                  #b4637a   
        cursor                  #cecacd   
        cursor_text_color       #575279   
        foreground              #575279   
        inactive_tab_background #faf4ed   
        inactive_tab_foreground #9893a5   
        selection_background    #dfdad9   
        selection_foreground    #575279   
        url_color               #907aa9   

Important environment variables seen by the kitty process:
        PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
        LANG                                en_US.UTF-8
        SHELL                               /bin/zsh
        USER                                guillaume
```

**Comment by kovidgoyal** [comment]
update kitty
