### ISSUE TITLE
Crash on Wayland when switching to a virtual console

### ISSUE THREAD

**Issue by danberindei** [kovidgoyal/kitty#7139]
**Describe the bug**
Kitty crashes for me every time I use Ctrl+Alt+F3 to switch to a virtual console.

I opened https://github.com/glfw/glfw/issues/2492 first because there seemed to be no Kitty code in the stacktrace, but I was told that the Kitty fork of glfw has quite a few changes.

**To Reproduce**
1. Run `kitty --config NONE`
2. Press Ctrl+Alt+F3
3. Press Ctrl+Alt+F2 to go back
4. See Kitty crash

**Environment details**
```
kitty 0.31.0 created by Kovid Goyal
Linux denulu-m1 6.6.3-413.asahi.fc39.aarch64+16k #1 SMP PREEMPT_DYNAMIC Sat Jan 27 17:19:54 UTC 2024 aarch64
S
Kernel 6.6.3-413.asahi.fc39.aarch64+16k on an aarch64 (/dev/tty)

Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/dan/.cargo/bin:/home/dan/Tools/bin:/home/dan/.asdf/shims:/home/dan/.asdf/bin:/home/dan/.local/bin:/home/dan/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin
	LANG                                en_US.UTF-8
	EDITOR                              /usr/bin/vim
	SHELL                               /bin/bash
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                dan
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /home/dan/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland
	LC_ADDRESS                          en_GB.UTF-8
	LC_TELEPHONE                        en_GB.UTF-8
	LC_TIME                             en_GB.UTF-8
	XDG_SESSION_CLASS                   user
	XDG_MENU_PREFIX                     gnome-
	LC_PAPER                            en_GB.UTF-8
	XDG_CURRENT_DESKTOP                 GNOME
	LC_NUMERIC                          en_GB.UTF-8
	LC_MONETARY                         en_GB.UTF-8
	LC_MEASUREMENT                      en_GB.UTF-8
```

**Additional context**
Stacktrace

```
#0  0x0000ffff9dd21ee4 in wl_proxy_get_version (proxy=proxy@entry=0x0) at ../src/wayland-client.c:2249
#1  0x0000ffff8fe1f86c in wl_pointer_set_cursor (hotspot_y=11, hotspot_x=10, surface=0xaaab90f42880, serial=71833, wl_pointer=0x0) at /usr/include/wayland-client-protocol.h:4967
#2  setCursorImage (window=<optimized out>, on_theme_change=<optimized out>) at glfw/wl_window.c:204
#3  0x0000ffff8fe25c00 [PAC] in checkScaleChange.part.0.lto_priv.0 (window=0xaaab911b77a0) at glfw/wl_window.c:244
#4  0x0000ffff8fe12cb8 [PAC] in checkScaleChange (window=0xaaab911b77a0) at glfw/wl_window.c:223
#5  surfaceHandleLeave (data=0xaaab911b77a0, surface=<optimized out>, output=<optimized out>) at glfw/wl_window.c:400
#6  0x0000ffff8febc050 [PAC] in ffi_call_SYSV () at ../src/aarch64/sysv.S:127
#7  0x0000ffff8feb63ac in ffi_call_int (cif=cif@entry=0xffffe482f088, fn=<optimized out>, orig_rvalue=0xffff8fed00f0 <ffi_type_pointer>, orig_rvalue@entry=0x0, avalue=avalue@entry=0xffffe482f158, 
    closure=0xffff8fed00f0 <ffi_type_pointer>, closure@entry=0x0) at ../src/aarch64/ffi.c:816
#8  0x0000ffff8feb8a6c [PAC] in ffi_call (cif=cif@entry=0xffffe482f088, fn=<optimized out>, rvalue=rvalue@entry=0x0, avalue=avalue@entry=0xffffe482f158) at ../src/aarch64/ffi.c:825
#9  0x0000ffff9dd21a60 in wl_closure_invoke (closure=closure@entry=0xaaab92e11130, target=<optimized out>, target@entry=0xaaab9116b240, opcode=opcode@entry=1, data=<optimized out>, flags=1)
    at ../src/connection.c:1025
#10 0x0000ffff9dd223fc [PAC] in dispatch_event (display=0xaaab90f493b0, queue=0xaaab90f494a0) at ../src/wayland-client.c:1631
#11 0x0000ffff9dd22724 [PAC] in dispatch_queue (queue=0xaaab90f494a0, display=0xaaab90f493b0) at ../src/wayland-client.c:1777
#12 wl_display_dispatch_queue_pending (display=display@entry=0xaaab90f493b0, queue=queue@entry=0xaaab90f494a0) at ../src/wayland-client.c:2019
#13 0x0000ffff9dd2279c [PAC] in wl_display_dispatch_pending (display=display@entry=0xaaab90f493b0) at ../src/wayland-client.c:2082
#14 0x0000ffff8fe1585c in handleEvents (timeout=<optimized out>) at glfw/wl_window.c:795
#15 _glfwPlatformWaitEvents () at glfw/wl_window.c:1324
#16 _glfwPlatformRunMainLoop (data=0xffff84dbd0d0, tick_callback=0xffff9e89a300 <process_global_state>) at glfw/main_loop.h:30
#17 glfwRunMainLoop (callback=0xffff9e89a300 <process_global_state>, data=0xffff84dbd0d0) at glfw/init.c:355
#18 0x0000ffff9e8932d8 [PAC] in run_main_loop (cb=<optimized out>, cb_data=0xffff84dbd0d0) at kitty/glfw.c:1957
#19 main_loop (self=0xffff84dbd0d0, a=<optimized out>) at kitty/child-monitor.c:1266
#20 0x0000ffff9f7b6b60 [PAC] in method_vectorcall_NOARGS (func=0xffff9f0c40e0, args=0xffff9fcb8560, nargsf=<optimized out>, kwnames=0x0)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.aarch64/Objects/descrobject.c:454
#21 0x0000ffff9f7a32d8 [PAC] in _PyObject_VectorcallTstate (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=0xffff9f0c40e0, tstate=0xffff9fc5bc30 <_PyRuntime+459672>)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.aarch64/Include/internal/pycore_call.h:92
#22 PyObject_Vectorcall (callable=0xffff9f0c40e0, args=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at /usr/src/debug/python3.12-3.12.1-2.fc39.aarch64/Objects/call.c:325
#23 0x0000ffff9f788b64 [PAC] in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0xffff9fcb84a8, throwflag=<optimized out>) at Python/bytecodes.c:2706
#24 0x0000ffff9f77ff74 [PAC] in _PyFunction_Vectorcall (kwnames=0x0, nargsf=<optimized out>, stack=<optimized out>, func=0xffff8ff47c40) at /usr/src/debug/python3.12-3.12.1-2.fc39.aarch64/Objects/call.c:422
#25 _PyObject_FastCallDictTstate (tstate=0xffff9fc5bc30 <_PyRuntime+459672>, callable=0xffff8ff47c40, args=<optimized out>, nargsf=<optimized out>, kwargs=<optimized out>)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.aarch64/Objects/call.c:133
#26 0x0000ffff9f7bb8f8 [PAC] in _PyObject_Call_Prepend (tstate=0xffff9fc5bc30 <_PyRuntime+459672>, callable=0xffff8ff47c40, obj=0xffff9f36d730, args=<optimized out>, kwargs=0x0)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.aarch64/Objects/call.c:508
#27 0x0000ffff9f898018 [PAC] in slot_tp_call (self=self@entry=0xffff9f36d730, args=args@entry=0xffff8ff49680, kwds=kwds@entry=0x0) at /usr/src/debug/python3.12-3.12.1-2.fc39.aarch64/Objects/typeobject.c:8769
#28 0x0000ffff9f77c448 [PAC] in _PyObject_MakeTpCall (tstate=0xffff9fc5bc30 <_PyRuntime+459672>, callable=0xffff9f36d730, args=0xffff9fcb83e8, nargs=3, keywords=0x0)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.aarch64/Objects/call.c:240
#29 0x0000ffff9f788b64 [PAC] in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0xffff9fcb8320, throwflag=<optimized out>) at Python/bytecodes.c:2706
#30 0x0000ffff9f83fac8 [PAC] in PyEval_EvalCode (co=<optimized out>, globals=0xffff9f369c80, locals=0xffff9f369c80) at /usr/src/debug/python3.12-3.12.1-2.fc39.aarch64/Python/ceval.c:578
#31 0x0000ffff9f866bf4 [PAC] in builtin_exec_impl (module=<optimized out>, closure=<optimized out>, locals=0xffff9f369c80, globals=0xffff9f369c80, source=0xffff9f2b55c0)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.aarch64/Python/bltinmodule.c:1096
#32 builtin_exec (module=<optimized out>, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at /usr/src/debug/python3.12-3.12.1-2.fc39.aarch64/Python/clinic/bltinmodule.c.h:586
#33 0x0000ffff9f7a3830 [PAC] in cfunction_vectorcall_FASTCALL_KEYWORDS (func=0xffff9f305e40, args=0xffff9fcb8180, nargsf=<optimized out>, kwnames=<optimized out>)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.aarch64/Include/cpython/methodobject.h:50
#34 0x0000ffff9f7a32d8 [PAC] in _PyObject_VectorcallTstate (kwnames=<optimized out>, nargsf=<optimized out>, args=<optimized out>, callable=0xffff9f305e40, tstate=0xffff9fc5bc30 <_PyRuntime+459672>)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.aarch64/Include/internal/pycore_call.h:92
#35 PyObject_Vectorcall (callable=0xffff9f305e40, args=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at /usr/src/debug/python3.12-3.12.1-2.fc39.aarch64/Objects/call.c:325
#36 0x0000ffff9f788b64 [PAC] in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0xffff9fcb80d8, throwflag=<optimized out>) at Python/bytecodes.c:2706
#37 0x0000ffff9f880520 [PAC] in pymain_run_module (modname=modname@entry=0xffff9f953858 L"__main__", set_argv0=set_argv0@entry=0) at /usr/src/debug/python3.12-3.12.1-2.fc39.aarch64/Modules/main.c:300
#38 0x0000ffff9f87f8f4 [PAC] in pymain_run_python (exitcode=0xffffe482fc44) at /usr/src/debug/python3.12-3.12.1-2.fc39.aarch64/Modules/main.c:626
```

**Comment by kovidgoyal** [comment]
Does not reproduce for me in current gnome with current kitty with those
steps.

**Comment by danberindei** [comment]
Unfortunately kitty-0.32.2-arm64 still crashes for me, just without the debug information:

```
#0  0x0000ffff43397de0 in wl_proxy_get_version () from /home/dan/Github/kitty/bin/../lib/libwayland-client.so.0
#1  0x0000ffff433e315c in ?? () from /home/dan/Github/kitty/lib/kitty-extensions/kitty.glfw-wayland.so
#2  0x0000ffff433e3790 in ?? () from /home/dan/Github/kitty/lib/kitty-extensions/kitty.glfw-wayland.so
#3  0x0000ffff433e5660 in ?? () from /home/dan/Github/kitty/lib/kitty-extensions/kitty.glfw-wayland.so
#4  0x0000ffff4356bc58 in ?? () from /home/dan/Github/kitty/bin/../lib/libffi.so.7
#5  0x0000ffff4356b638 in ?? () from /home/dan/Github/kitty/bin/../lib/libffi.so.7
#6  0x0000ffff4356b6b8 in ffi_call () from /home/dan/Github/kitty/bin/../lib/libffi.so.7
#7  0x0000ffff4339a358 in ?? () from /home/dan/Github/kitty/bin/../lib/libwayland-client.so.0
#8  0x0000ffff43396118 in ?? () from /home/dan/Github/kitty/bin/../lib/libwayland-client.so.0
#9  0x0000ffff43397a10 in wl_display_dispatch_queue_pending () from /home/dan/Github/kitty/bin/../lib/libwayland-client.so.0
#10 0x0000ffff433d01ec in glfwRunMainLoop () from /home/dan/Github/kitty/lib/kitty-extensions/kitty.glfw-wayland.so
```

The crash might be specific to Asahi Linux, if you have any reason to suspect that there's something wrong on their side I would appreciate any pointers.

**Comment by kovidgoyal** [comment]
Build from source with debug info to get a proper traceback, doing so
involves running just a couple of commands. Once you post that against
master, it should be a trivial fix, probably detect a null
pointer and ignore the cursor change event in that case. Of
course it could be something without an easy workaround in which case
you will just have to wait for mutter to get off its ass and implement
cursor shape, or save yourself endless grief and use X11.

See https://sw.kovidgoyal.net/kitty/build/ for how to build.

I'm afraid I try to waste as little of my life as possible on the
trainwreck that is Wayland, so I dont have any idea what the underlying
cause might be. Could be the GPU drivers, the wayland compositor, the
wayland client library, glfw-wayland, mesa, and so on. Or bugs in some
or all of these that interact with each other. 

Wayland is basically optimally designed to waste as many developer hours as
humanly possible just to perform the most trivial of functions, that
have been performed reliably and simply by other platforms for decades, such as
drawing a mouse cursor.

**Comment by kovidgoyal** [comment]
From your otiginal bactrace most likely this will fix it: https://github.com/kovidgoyal/kitty/commit/ce2e1b08132831fe770ec48d1e73eb4edd21c5b5

Cant be sure as I cant reproduce.

**Comment by kovidgoyal** [comment]
Ah yes, pre-built deps are only available for ARM64 on apple not Linux.
You can always build it traditionally using make debug rather than the
dev.sh script. You will need to install the various dependencies,
details are on the build page.

**Comment by danberindei** [comment]
It took a while, I was missing all the dev packages, and I'm on Fedora the package names are different :)

I couldn't reproduce the crash even without your latest change. And to make things more interesting, now I can't reproduce the crash with release 0.32.2 either. 

I removed the dev packages and I'll try again after I restart, but for now your fix looks quite reasonable.
