### ISSUE TITLE
Error on start: "EGL: Failed to create window surface: Arguments are inconsistent"

### ISSUE THREAD

**Issue by mhulscher** [kovidgoyal/kitty#7174]
**Describe the bug**
I can no longer start kitty. It returns this error:

```
[061 09:19:54.294322] [glfw error 65544]: EGL: Failed to create window surface: Arguments are inconsistent
[061 09:19:54.299188] Traceback (most recent call last):
  File "kitty/main.py", line 561, in main
  File "kitty/main.py", line 553, in _main
  File "kitty/main.py", line 296, in __call__
  File "kitty/main.py", line 268, in _run_app
ValueError: Failed to create GLFWwindow
```

There is a non-zero chance that this can be fixed by cleaning some cache or something, but I haven't been able to figure it out so far. Any directions would be greatly appreciated.

**To Reproduce**
1. run `kitty`
2. See error

**Additional information**
This is on Kubuntu 23.10 w/ Wayland.

Some of the packages listed below come from the [oibaf/graphics-drivers](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) repository, which is bleeding edge. As such, I am fully expecting an occasional breakage :)

```
❯ kitty --version    
kitty 0.32.2 created by Kovid Goyal
```

```
❯ dpkg -l | grep -e wayland -e egl
ii  kwayland-data                                            4:5.112.0-0ubuntu1~ubuntu23.10~ppa1         all          Qt library wrapper for Wayland libraries - data files
ii  kwayland-integration:amd64                               4:5.27.10-0ubuntu1~ubuntu23.10~ppa1         amd64        kwayland runtime integration plugins
ii  kwin-wayland                                             4:5.27.10-0ubuntu1~ubuntu23.10~ppa1         amd64        KDE window manager, wayland version, PREVIEW release
ii  libegl-mesa0:amd64                                       24.1~git2403010600.6e33b3~oibaf~m           amd64        free implementation of the EGL API -- Mesa vendor library
ii  libegl-mesa0:i386                                        24.1~git2403010600.6e33b3~oibaf~m           i386         free implementation of the EGL API -- Mesa vendor library
ii  libegl1:amd64                                            1.6.0-1                                     amd64        Vendor neutral GL dispatch library -- EGL support
ii  libegl1:i386                                             1.6.0-1                                     i386         Vendor neutral GL dispatch library -- EGL support
ii  libkf5waylandclient5:amd64                               4:5.112.0-0ubuntu1~ubuntu23.10~ppa1         amd64        Qt library wrapper for Wayland libraries
ii  libqt5waylandclient5:amd64                               5.15.10-2                                   amd64        QtWayland client library
ii  libqt5waylandcompositor5:amd64                           5.15.10-2                                   amd64        QtWayland compositor library
ii  libva-wayland2:amd64                                     2.19.0-1                                    amd64        Video Acceleration (VA) API for Linux -- Wayland runtime
ii  libwayland-client0:amd64                                 1.22.0-2.1                                  amd64        wayland compositor infrastructure - client library
ii  libwayland-client0:i386                                  1.22.0-2.1                                  i386         wayland compositor infrastructure - client library
ii  libwayland-cursor0:amd64                                 1.22.0-2.1                                  amd64        wayland compositor infrastructure - cursor library
ii  libwayland-cursor0:i386                                  1.22.0-2.1                                  i386         wayland compositor infrastructure - cursor library
ii  libwayland-egl1:amd64                                    1.22.0-2.1                                  amd64        wayland compositor infrastructure - EGL library
ii  libwayland-egl1:i386                                     1.22.0-2.1                                  i386         wayland compositor infrastructure - EGL library
ii  libwayland-server0:amd64                                 1.22.0-2.1                                  amd64        wayland compositor infrastructure - server library
ii  libwayland-server0:i386                                  1.22.0-2.1                                  i386         wayland compositor infrastructure - server library
ii  plasma-workspace-wayland                                 4:5.27.10-0ubuntu1~ubuntu23.10~ppa1         amd64        Plasma Workspace for KF5 - Wayland integration
ii  qtwayland5:amd64                                         5.15.10-2                                   amd64        QtWayland platform plugin
ii  wayland-utils                                            1.2.0-1                                     amd64        Wayland utilities
ii  xwayland                                                 2:23.2.0-1ubuntu0.4                         amd64        X server for running X clients under Wayland

```

**Comment by kovidgoyal** [comment]
That's a GPU driver issue, you dont say what graphics card you are
using, but in case its NVIDIA I would suggest switch to x11

**Comment by mhulscher** [comment]
@kovidgoyal I am not using NVIDIA. This is an integrated intel chip.

```
00:02.0 VGA compatible controller: Intel Corporation Alder Lake-P Integrated Graphics Controller (rev 0c) (prog-if 00 [VGA controller])
    Subsystem: Lenovo Alder Lake-P Integrated Graphics Controller
    Flags: bus master, fast devsel, latency 0, IRQ 177, IOMMU group 0
    Memory at 603c000000 (64-bit, non-prefetchable) [size=16M]
    Memory at 4000000000 (64-bit, prefetchable) [size=256M]
    I/O ports at 2000 [size=64]
    Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
    Capabilities: [40] Vendor Specific Information: Len=0c <?>
    Capabilities: [70] Express Root Complex Integrated Endpoint, MSI 00
    Capabilities: [ac] MSI: Enable+ Count=1/1 Maskable+ 64bit-
    Capabilities: [d0] Power Management version 2
    Capabilities: [100] Process Address Space ID (PASID)
    Capabilities: [200] Address Translation Service (ATS)
    Capabilities: [300] Page Request Interface (PRI)
    Capabilities: [320] Single Root I/O Virtualization (SR-IOV)
    Kernel driver in use: i915
    Kernel modules: i915
```

**Comment by kovidgoyal** [comment]
That error basically means EGL was unable to create an OpenGL surface with the capabilities kitty needs. kitty needs pretty basic capabilities so this is definitely a driver issue. You can also try using x11 instead of wayland, wayland generally makes everything worse.

**Comment by ErikReider** [comment]
Facing the same issue, kitty `0.31.0` works while `0.32.2` doesn't start with the same error as the one above. I'm on an AMD GPU.

**Comment by kovidgoyal** [comment]
As I said the issue is in your GPU drivers, literally the ONLY change between 0.31 and o).32.2     is that kitty now explicitly requests sRGB surfaces to ensure colors are correct. If your driver is failing to create such a surface then it is a driver bug.

**Comment by birdspider** [comment]
I have the same issue (on amdgpu/5700xt/wayland), however `KITTY_DISABLE_WAYLAND=1 kitty` mitigates it - would that be a driver bug or rather a glfw bug?

**Comment by kovidgoyal** [comment]
A Wayland driver bug. Like I said, Wayland makes everything worse. FYI,
works fine for me in Wayland with Advanced Micro Devices, Inc. [AMD/ATI]
Cezanne [Radeon Vega Series / Radeon Vega Mobile Series]. You can try
commenting out line 1080 in kitty/glfw.c to confirm it is the srgb
surface request causing it.

**Comment by birdspider** [comment]
@kovidgoyal thx for the response, I narrowed it down to somewhere between mesa-24.0.3 and mesa-main (as-in arch's mesa 24.0.3 works); so it's either my build or something actually bugged out since 24.0.3

**Comment by mhkarimi1383** [comment]
@kovidgoyal 

https://github.com/NVIDIA/egl-wayland/issues/85

I think no need the workaround NVIDIA is fixing it
check out last comment :)

**Comment by kovidgoyal** [comment]
Yes, but kitty can have no idea when the fix is available in various
Linux distros. So the workaround will have to stay for a while at least.
To to mention that mesa also recently broke this in Wayland.

**Comment by vuongtuha** [comment]
>  `KITTY_DISABLE_WAYLAND=1 kitty` 
The temporary solution worked for me. Hope anyone with slow rolling distro can use Kitty well
