### ISSUE TITLE
Cannot use the panel kitten

### ISSUE THREAD

**Issue by DestinyofYeet** [kovidgoyal/kitty#7414]
**Describe the bug**
When running the default command from the doc it doesn't work and I get an error.

**To Reproduce**
1. Open up a kitty window
2. Run `kitty +kitten panel sh -c 'printf "\n\n\nHello, world."; sleep 5s'` 
3. Get an error

```
[127 17:39:08.623985] Ignoring unknown config key: bolit_italic_font
[127 17:39:08.725045] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 561, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 553, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 296, in __call__
    _run_app(opts, args, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 268, in _run_app
    window_id = create_os_window(
                ^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/kitty/kitty/utils.py", line 368, in pre_show_callback
    self.extra_callback(window_handle)
  File "/usr/bin/../lib/kitty/kittens/panel/main.py", line 101, in setup_x11_window
    make_x11_window_a_dock_window(win_id, strut)
TypeError: 'NoneType' object cannot be interpreted as an integer
```

**Screenshots**

**Environment details**
```
kitty 0.33.1 created by Kovid Goyal
Linux kartoffelkiste 6.8.8-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sun, 28 Apr 2024 15:59:30 +0000 x86_64
Garuda Linux 6.8.8-zen1-1-zen (/dev/tty)

DISTRIB_ID=Garuda
DISTRIB_RELEASE=Soaring
DISTRIB_DESCRIPTION="Garuda Linux Bird of Prey"
DISTRIB_CODENAME="BirdOfPrey"
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/ole/.config/kitty/kitty.conf

Config options different from defaults:
background_blur    30
background_opacity 0.8
editor             vim
enable_audio_bell  False
font_family        Comic Code Ligatures
shell              /usr/bin/zsh
shell_integration  frozenset({'enabled', 'no-cursor'})

Important environment variables seen by the kitty process:
	PATH                                /usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/usr/local/go/bin
	LANG                                en_US.UTF-8
	SHELL                               /usr/bin/zsh
	DISPLAY                             :1
	WAYLAND_DISPLAY                     wayland-0
	USER                                ole
	LC_ADDRESS                          de_DE.UTF-8
	LC_IDENTIFICATION                   de_DE.UTF-8
	LC_MEASUREMENT                      de_DE.UTF-8
	LC_MONETARY                         de_DE.UTF-8
	LC_NAME                             de_DE.UTF-8
	LC_NUMERIC                          de_DE.UTF-8
	LC_PAPER                            de_DE.UTF-8
	LC_TELEPHONE                        de_DE.UTF-8
	LC_TIME                             de_DE.UTF-8
	XDG_CONFIG_DIRS                     /home/ole/.config/kdedefaults:/etc/xdg
	XDG_CURRENT_DESKTOP                 KDE
	XDG_DATA_DIRS                       /home/ole/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
	XDG_MENU_PREFIX                     plasma-
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SEAT                            seat0
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 KDE
	XDG_SESSION_ID                      2
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_SESSION_TYPE                    wayland
	XDG_VTNR                            1
```

I am running Arch Linux and installed kitty from the Arch Repository.

**Additional context**
Same error when running kitty with `kitty --config NONE`

**Comment by kovidgoyal** [comment]
You need to update kitty.
