### ISSUE TITLE
Can't use remote control to set background opacity to 0

### ISSUE THREAD

**Issue by hectorBrown** [kovidgoyal/kitty#7483]
**Describe the bug**
When using `kitty @ set-background-opacity 0`, receive an error instead of the intended behaviour. All other background values work as normal. This seems to be just since version 0.35.0.

**To reproduce**
1. Start kitty with minimal config:
```
allow_remote_control  yes
dynamic_background_opacity  yes
```
2. Run `kitty @ set-background opacity 0`.
3. Receive error message:
```
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 707, in _execute_remote_command
    response = handle_cmd(self, window, pcmd, peer_id, self_window)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 247, in handle_cmd
    ans = c.response_from_kitty(boss, self_window or window, PayloadGetter(c, payload))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/kitty/kitty/rc/set_background_opacity.py", line 75, in response_from_kitty
    boss._set_os_window_background_opacity(os_window_id, val)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 1328, in _set_os_window_background_opacity
    change_background_opacity(os_window_id, max(0.1, min(opacity, 1.0)))
                                                     ^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'float' and 'NoneType'

Error: '<' not supported between instances of 'float' and 'NoneType'
```

**Environment details**
```
kitty 0.35.0 created by Kovid Goyal
Linux hexdesk 6.6.32-1-lts #1 SMP PREEMPT_DYNAMIC Sat, 25 May 2024 20:20:51 +0000 x86_64
Arch Linux 6.6.32-1-lts (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: X11
OpenGL: '4.6 (Core Profile) Mesa 24.0.8-arch1.1' Detected version: 4.6
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /etc/xdg/kitty/kitty.conf
  kitty.conf

Config options different from defaults:
allow_remote_control       yes
dynamic_background_opacity True

Important environment variables seen by the kitty process:
	PATH                                /home/hex/.pyenv/shims:/home/hex/.local/share/nvim/mason/bin:/home/hex/.local/share/gem/ruby/3.0.0/bin:/home/hex/.cabal/bin:/home/hex/.ghcup/bin:/home/hex/.local/bin:/usr/local/texlive/2022/bin/x86_64-linux:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/bin:/home/hex/.go/bin:/home/hex/.spicetify
	LANG                                en_GB.UTF-8
	EDITOR                              /home/hex/.local/bin/no-padding nvim
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	USER                                hex
	XDG_SEAT                            seat0
	XDG_SESSION_DESKTOP                 i3
	XDG_SESSION_TYPE                    x11
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            2
	XDG_SESSION_ID                      1
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /home/hex/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
```

**Comment by hectorBrown** [comment]
Thanks for the great terminal!
