### ISSUE TITLE
test_zsh_integration fails with emoji in directory name

### ISSUE THREAD

**Issue by Maytha8** [kovidgoyal/kitty#7495]
**Describe the bug**
test_zsh_integration fails with emoji in directory name of 'testing-cwd-notification'

**To Reproduce**
1. Test kitty with Debian's zsh

**Screenshots**
```
======================================================================
ERROR: test_zsh_integration (kitty_tests.shell_integration.ShellIntegration.test_zsh_integration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/kitty/launcher/../../kitty_tests/shell_integration.py", line 167, in test_zsh_integration
    self.assert_command(pty)
    ps1 = 'left>'
    pty = <kitty_tests.PTY object at 0x7fe76d413d50>
    q = '/tmp/tmp4yph7y23/testing-cwd-notification-🐱'
    redrawn = <function ShellIntegration.test_zsh_integration.<locals>.redrawn at 0x7fe784f3d1c0>
    rps1 = '<right'
    self = <kitty_tests.shell_integration.ShellIntegration testMethod=test_zsh_integration>
  File "/<<PKGBUILDDIR>>/kitty/launcher/../../kitty_tests/shell_integration.py", line 269, in assert_command
    pty.wait_till(lambda: pty.callbacks.last_cmd_cmdline == cmd, timeout_msg=lambda: f'{pty.callbacks.last_cmd_cmdline=!r} != {cmd!r}')
    cmd = 'cd /tmp/tmp4yph7y23/testing-cwd-notification-🐱'
    exit_status = 0
    pty = <kitty_tests.PTY object at 0x7fe76d413d50>
    self = <kitty_tests.shell_integration.ShellIntegration testMethod=test_zsh_integration>
  File "/<<PKGBUILDDIR>>/kitty/launcher/../../kitty_tests/__init__.py", line 377, in wait_till
    raise TimeoutError(f'Timed out: {msg}. Screen contents: \n {repr(self.screen_contents())}')
    end_time = 5002.86597202
    msg = "pty.callbacks.last_cmd_cmdline='cd /tmp/tmp4yph7y23/testing-cwd-notification-????' != 'cd /tmp/tmp4yph7y23/testing-cwd-notification-🐱'"
    q = <function ShellIntegration.assert_command.<locals>.<lambda> at 0x7fe784f3ed40>
    self = <kitty_tests.PTY object at 0x7fe76d413d50>
    timeout = 10
    timeout_msg = <function ShellIntegration.assert_command.<locals>.<lambda> at 0x7fe76d483ec0>
TimeoutError: Timed out: pty.callbacks.last_cmd_cmdline='cd /tmp/tmp4yph7y23/testing-cwd-notification-????' != 'cd /tmp/tmp4yph7y23/testing-cwd-notification-🐱'. Screen contents: 
 'left>printf "%s^G%s" "a" "b"\nab%                                                                             \nleft>cd /tmp/tmp4yph7y23/testing-cwd-notification-<ffffffff><ffffffff><ffffffff>\n<ffffffff>\nleft>'

======================================================================
ERROR: test_zsh_integration (kitty_tests.shell_integration.ShellIntegrationWithKitten.test_zsh_integration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/kitty/launcher/../../kitty_tests/shell_integration.py", line 167, in test_zsh_integration
    self.assert_command(pty)
    ps1 = 'left>'
    pty = <kitty_tests.PTY object at 0x7fe76d3dfe50>
    q = '/tmp/tmpr8ipbwy6/testing-cwd-notification-🐱'
    redrawn = <function ShellIntegration.test_zsh_integration.<locals>.redrawn at 0x7fe76d4993a0>
    rps1 = '<right'
    self = <kitty_tests.shell_integration.ShellIntegrationWithKitten testMethod=test_zsh_integration>
  File "/<<PKGBUILDDIR>>/kitty/launcher/../../kitty_tests/shell_integration.py", line 269, in assert_command
    pty.wait_till(lambda: pty.callbacks.last_cmd_cmdline == cmd, timeout_msg=lambda: f'{pty.callbacks.last_cmd_cmdline=!r} != {cmd!r}')
    cmd = 'cd /tmp/tmpr8ipbwy6/testing-cwd-notification-🐱'
    exit_status = 0
    pty = <kitty_tests.PTY object at 0x7fe76d3dfe50>
    self = <kitty_tests.shell_integration.ShellIntegrationWithKitten testMethod=test_zsh_integration>
  File "/<<PKGBUILDDIR>>/kitty/launcher/../../kitty_tests/__init__.py", line 377, in wait_till
    raise TimeoutError(f'Timed out: {msg}. Screen contents: \n {repr(self.screen_contents())}')
    end_time = 5013.537358038
    msg = "pty.callbacks.last_cmd_cmdline='cd /tmp/tmpr8ipbwy6/testing-cwd-notification-????' != 'cd /tmp/tmpr8ipbwy6/testing-cwd-notification-🐱'"
    q = <function ShellIntegration.assert_command.<locals>.<lambda> at 0x7fe76d49a7a0>
    self = <kitty_tests.PTY object at 0x7fe76d3dfe50>
    timeout = 10
    timeout_msg = <function ShellIntegration.assert_command.<locals>.<lambda> at 0x7fe76d49a700>
TimeoutError: Timed out: pty.callbacks.last_cmd_cmdline='cd /tmp/tmpr8ipbwy6/testing-cwd-notification-????' != 'cd /tmp/tmpr8ipbwy6/testing-cwd-notification-🐱'. Screen contents: 
 'left>printf "%s^G%s" "a" "b"\nab%                                                                             \nleft>cd /tmp/tmpr8ipbwy6/testing-cwd-notification-<ffffffff><ffffffff><ffffffff>\n<ffffffff>\nleft>'

----------------------------------------------------------------------
Ran 144 tests in 26.296s

FAILED (errors=2, skipped=2)
[31mError[39m: Some tests failed!
make[1]: *** [debian/rules:60: override_dh_auto_test] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
make: *** [debian/rules:32: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2

```

**Environment details**
Debian unstable, chroot

**Additional context**
Works when emojis are removed.

**Comment by kovidgoyal** [comment]
Works fine with reasonably recent zsh. I suggest skipping that test on
old ZSH. You can submit a PR for it based on zsh_ok() function just like
the existing bash_ok() function.

**Comment by nileshpatra** [comment]
zsh version is 5.9 which is probably the latest?

**Comment by kovidgoyal** [comment]
it works fine in zsh 5.9 as seen in CI. Check that the test env has
proper utf-8 support setup.

**Comment by nileshpatra** [comment]
Had to do "LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8" to get tests passing.
By default the locale is C.UTF-8 in our CI.

Surprisingly,  that's not needed for bash or fish. TIL, zsh does not render emojis properly on C Locale.
