### ISSUE TITLE
Font error when building from source

### ISSUE THREAD

**Issue by jonwilts** [kovidgoyal/kitty#7611]
**Describe the bug**
I regularly build kitty from source. Since yesterday I've been unable to build (see below)

**To Reproduce**

```
% cd kitty/
% git pull
Already up to date.
% ./dev.sh deps
Downloading linux-64.tar.xz
Dependencies downloaded. Now build kitty with: ./dev.sh build
% ./dev.sh build
The font 'Symbols NERD Font Mono' was not found on your system, please install it
The following build command failed: /home/dev/kitty/dependencies/linux-amd64/bin/python setup.py develop
exit status 1
% pacman -Q | grep nerd
ttf-nerd-fonts-symbols 3.2.1-1
ttf-nerd-fonts-symbols-common 3.2.1-1
%
```

**Environment details**
Can't launch kitty so unable to give full debug details, but

```
% kitty --version
kitty 0.35.2 created by Kovid Goyal
% uname -a
Linux air 6.9.7-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:27 +0000 x86_64 GNU/Linux
% plasmashell --version
plasmashell 6.1.2
% kf5-config --version
Qt: 5.15.14
KDE Frameworks: 5.116.0
kf5-config: 1.0
% go version
go version go1.22.5 linux/amd64
% ./dependencies/linux-amd64/bin/python --version
Python 3.12.4
```

**Additional context**
Trying to launch kitty gives:

```
% kitty --config none
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/dev/kitty/__main__.py", line 7, in <module>
    main()
  File "/home/dev/kitty/kitty/entry_points.py", line 194, in main
    from kitty.main import main as kitty_main
  File "/home/dev/kitty/kitty/main.py", line 47, in <module>
    from .fonts.render import dump_font_debug, set_font_family
  File "/home/dev/kitty/kitty/fonts/render.py", line 12, in <module>
    from kitty.fast_data_types import (
ImportError: cannot import name 'set_builtin_nerd_font' from 'kitty.fast_data_types' (/home/dev/kitty/kitty/fast_data_types.so)
```

**Comment by kovidgoyal** [comment]
And now ./dev/sh deps does it for you automatically: https://github.com/kovidgoyal/kitty/commit/076c882b229b1581ac97fca684f9679bd6928e7f

**Comment by jonwilts** [comment]
That works. Thank you.
