### ISSUE TITLE
Improve error message from kitten ssh when login_shell is not found 

### ISSUE THREAD

**Issue by ecerulm** [kovidgoyal/kitty#7724]
**Is your feature request related to a problem? Please describe.**

I got

```
kitten ssh -F vagrant-ssh default
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/os.py", line 558, in execlp
    execvp(file, args)
  File "/usr/lib/python3.10/os.py", line 575, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.10/os.py", line 617, in _execvpe
    raise last_exc
  File "/usr/lib/python3.10/os.py", line 608, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
```

The root cause is that I modified my `~/.config/kitty/ssh.conf` and added 

```
hostname *
login_shell zsh
```

the  `zsh` is not installed in the target system so I think the `FileNotFoundError` is about `/bin/zsh` not being present, but there is no mention of it in the error message

**Describe the solution you'd like**

I would like to see an explicit mention to `login_shell` and/or `/bin/zsh` in the error message, maybe indicating that `~/.config/kitty/ssh.conf` is the source. 

**Describe alternatives you've considered**

**Additional context**

**Comment by ecerulm** [comment]
20 minutes from report to fix, that is impressive.
