### ISSUE TITLE
--when-focus-on does not allow escaping of user variable values

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#7776]
**Describe the bug**
I'd like to set up conditional mapping when matching against user variables containing _spaces_ (or possibly other characters) in values.

**To Reproduce**

1. Launch kitty with the following command: `kitty --config NONE -o 'map --when-focus-on var:cmdline=adb f1 send_text all WORKS'`.
2. `printf "\e]1337;SetUserVar=cmdline=YWRi\a"` (value is `adb`).
3. Press `F1` and verify that the text `WORKS` appears within the new terminal.
4. Relaunch kitty as follows: `kitty --config NONE -o 'map --when-focus-on var:cmdline="adb shell" f1 send_text all WORKS'`.
5. `printf "\e]1337;SetUserVar=cmdline=YWRiIHNoZWxs\a"` (value is `adb shell`).
6. Press `F1`.

**Screenshots**
![Screenshot from 2024-08-25 22-36-10](https://github.com/user-attachments/assets/7deaa86a-8881-4bf7-8604-aa83d9f963c5)

**Environment details**
```
kitty 0.36.1 (95245ee473) created by Kovid Goyal
Linux byteevo 5.15.0-119-generic #129~20.04.1-Ubuntu SMP Wed Aug 7 13:07:13 UTC 2024 x86_64
Ubuntu 20.04.6 LTS byteevo /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
Running under: X11
OpenGL: '4.6 (Core Profile) Mesa 21.2.6' Detected version: 4.6
Frozen: True
Fonts:
  medium: DejaVuSansMono: /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf:0
  bold: DejaVuSansMono-Bold: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf:0
  italic: DejaVuSansMono-Oblique: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Oblique.ttf:0
  bi: DejaVuSansMono-BoldOblique: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-BoldOblique.ttf:0
Paths:
  kitty: /home/precor/.local/kitty.app/bin/kitty
  base dir: /home/precor/.local/kitty.app/lib/kitty
  extensions dir: /home/precor/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
Loaded config overrides:
  map --when-focus-on var:cmdline=adb\ shell f1 send_text all WORKS

Config options different from defaults:
Added shortcuts:
	f1 →  [--when-focus-on=var:cmdline=adb shell]send_text all WORKS

Important environment variables seen by the kitty process:
	PATH                                /home/precor/.local/lib/precor:/home/precor/.local/bin:/home/precor/.local/node/bin:/opt/qt/5.15.2/gcc_64/bin:/home/precor/Android/Sdk/build-tools/34.0.0:/home/precor/Android/Sdk/emulator:/home/precor/Android/Sdk/platform-tools:/home/precor/Android/Sdk/cmdline-tools/latest/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
	LANG                                en_US.UTF-8
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                precor
	XDG_CONFIG_DIRS                     /etc/xdg/xdg-ubuntu:/etc/xdg
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 ubuntu
	XDG_SESSION_TYPE                    x11
	XDG_CURRENT_DESKTOP                 ubuntu:GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/share/ubuntu:/usr/local/share/:/usr/share/
```

**Additional context**
Also tried, unsuccessfully, using backslash to escape the space, as follows:

```
kitty --config NONE -o 'map --when-focus-on var:cmdline=adb\ shell f1 send_text all WORKS'
```

**Comment by kovidgoyal** [comment]
You need

var:"cmdline=adb shell"

https://sw.kovidgoyal.net/kitty/remote-control/#matching-windows-and-tabs

**Comment by salmankhilji** [comment]
Still does not work.  I tried adding this to kitty.conf:

```
map --when-focus-on var:"cmdline=adb shell" ctrl+l combine : clear_terminal scrollback active : send_key ctrl+[ : send_key ctrl+l
```

```
Invalid key mapping


The match expression var:cmdline=adb shell is not valid for --when-focus-on

Press e to see detailed traceback or any other key to exit
Traceback (most recent call last):
  File "kitty/keys.py", line 126, in matching_key_actions
  File "kitty/boss.py", line 483, in match_windows
  File "kitty/search_query_parser.py", line 297, in search
  File "kitty/search_query_parser.py", line 288, in build_tree
  File "kitty/search_query_parser.py", line 204, in parse
  File "kitty/search_query_parser.py", line 210, in or_expression
  File "kitty/search_query_parser.py", line 224, in and_expression
  File "kitty/search_query_parser.py", line 217, in and_expression
  File "kitty/search_query_parser.py", line 231, in not_expression
  File "kitty/search_query_parser.py", line 243, in location_expression
  File "kitty/search_query_parser.py", line 279, in base_token
kitty.search_query_parser.NoLocation: No location specified before shell
```

**Comment by kovidgoyal** [comment]
map --when-focus-on 'var:"cmdline=adb shell"' ctrl+l combine : clear_terminal scrollback active : send_key ctrl+[ : send_key ctrl+l

**Comment by salmankhilji** [comment]
> map --when-focus-on 'var:"cmdline=adb shell"' ctrl+l combine : clear_terminal scrollback active : send_key ctrl+[ : send_key ctrl+l

That worked :)

For someone wanting to do the same on the command line arguments, you need to escape it like this:

```
set -- -o 'map --when-focus-on '\''var:"cmdline=adb shell"'\'' ctrl+l combine : clear_terminal scrollback active : send_key ctrl+[ : send_key ctrl+l'
```

**Comment by kovidgoyal** [comment]
On Mon, Aug 26, 2024 at 03:53:38AM -0700, salmankhilji wrote:
> > map --when-focus-on 'var:"cmdline=adb shell"' ctrl+l combine : clear_terminal scrollback active : send_key ctrl+[ : send_key ctrl+l
>
> That worked :)
>
> For someone wanting to do the same on the command line arguments, you need to escape it like this:
>
> ```
> set -- -o 'map --when-focus-on '\''var:"cmdline=adb shell"'\'' ctrl+l combine : clear_terminal scrollback active : send_key ctrl+[ : send_key ctrl+l'
> ```

Better is:

-o "map --when-focus-on 'var:\"cmdline=adb shell\"' ..."
