### ISSUE TITLE
Startup Session example throws error

### ISSUE THREAD

**Issue by Gab559** [kovidgoyal/kitty#7845]
**Describe the bug**
I was following the start session example here: https://sw.kovidgoyal.net/kitty/overview/#startup-sessions

But when I use the last part of the example for a complex layout
```# Create a complex layout using multiple splits. Creates two columns of
# windows with two windows in each column. The windows in the first column are
# split 50:50. In the second column the windows are not evenly split.
new_tab complex tab
layout splits
# First window, set a user variable on it so we can focus it later
launch --var window=first
# Create the second column by splitting the first window vertically
launch --location=vsplit
# Create the third window in the second column by splitting the second window horizontally
# Make it take 40% of the height instead of 50%
launch --location=hsplit --bias=40
# Go back to focusing the first window, so that we can split it
focus_matching_window var:window=first
# Create the final window in the first column
launch --location=hsplit
```

I get this error.

```
Traceback (most recent call last):
  File "lib/python3.12/kitty/main.py", line 562, in main
  File "lib/python3.12/kitty/main.py", line 554, in _main
  File "lib/python3.12/kitty/main.py", line 297, in __call__
  File "lib/python3.12/kitty/main.py", line 261, in _run_app
  File "lib/python3.12/kitty/session.py", line 251, in create_sessions
  File "lib/python3.12/kitty/session.py", line 185, in parse_session
  File "lib/python3.12/kitty/session.py", line 106, in add_window
  File "lib/python3.12/kitty/launch.py", line 333, in parse_launch_args
ValueError: Unknown option: ␛[91m--bias␛[39m
```

If I remove the --bias flag, it also throws an error on `focus_matching_window`
```
[0.193] Traceback (most recent call last):
  File "lib/python3.12/kitty/main.py", line 562, in main
  File "lib/python3.12/kitty/main.py", line 554, in _main
  File "lib/python3.12/kitty/main.py", line 297, in __call__
  File "lib/python3.12/kitty/main.py", line 261, in _run_app
  File "lib/python3.12/kitty/session.py", line 251, in create_sessions
  File "lib/python3.12/kitty/session.py", line 206, in parse_session
ValueError: Unknown command in session file: focus_matching_window
```
Removing both `--bias` and `focus_matching_window` Kitty launch as expected.

**To Reproduce**
1. Use example from startup session documentation
2. Launch kitty

**Environment details**
```
kitty 0.35.2 (ad328bfeaa) created by Kovid Goyal
Darwin user-MBP 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		14.6.1 BuildVersion:		23G93
OpenGL: '4.1 Metal - 88.1' Detected version: 4.1
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/user/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control yes
font_family          JetBrainsMono Nerd Font
font_size            15.0
startup_session      /Users/user/.config/kitty/startup.conf
Added shortcuts:
	ctrl+down →  neighboring_window down
	ctrl+left →  neighboring_window left
	ctrl+right →  neighboring_window right
	ctrl+up →  neighboring_window up
	f4 →  launch --location=split
	f5 →  launch --location=hsplit
	f6 →  launch --location=vsplit
	f7 →  layout_action rotate
	shift+down →  move_window down
	shift+left →  move_window left
	shift+right →  move_window right
	shift+up →  move_window up
Removed shortcuts:
	cmd+, →  edit_config_file
	cmd+enter →  new_window
	cmd+h →  hide_macos_app
	cmd+k →  clear_terminal to_cursor active
	cmd+m →  minimize_macos_window
	cmd+n →  new_os_window
	cmd+q →  quit
	cmd+t →  new_tab
	cmd+w →  close_tab
	ctrl+cmd+, →  load_config_file
	ctrl+cmd+f →  toggle_fullscreen
	opt+cmd+h →  hide_macos_other_apps
	opt+cmd+r →  clear_terminal reset active
	opt+cmd+s →  toggle_macos_secure_keyboard_entry
	shift+cmd+/ →  open_url https://sw.kovidgoyal.net/kitty/
	shift+cmd+[ →  previous_tab
	shift+cmd+] →  next_tab
	shift+cmd+d →  close_window
	shift+cmd+w →  close_os_window
Changed shortcuts:
	kitty_mod+down →  layout_action move_to_screen_edge bottom
	kitty_mod+enter →  new_window_with_cwd
	kitty_mod+left →  layout_action move_to_screen_edge left
	kitty_mod+right →  layout_action move_to_screen_edge right
	kitty_mod+up →  layout_action move_to_screen_edge top

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/Users/user/.tug/jh/helper:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/sbin:/usr/local/opt/python@3.11/bin:/usr/local/opt/python@3.10/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/bin:/Users/user/.local/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/iTerm.app/Contents/Resources/utilities
	LANG                                en_US.UTF-8
	VISUAL                              nvim
	EDITOR                              nvim
	SHELL                               /bin/zsh
	USER                                user
	LC_TERMINAL_VERSION                 3.5.4
	LC_TERMINAL                         iTerm2
	XDG_CACHE_HOME                      /Users/user/.cache
	XDG_CONFIG_HOME                     /Users/user/.config
	XDG_DATA_HOME                       /Users/user/.local/share

```

**Comment by kovidgoyal** [comment]
Update kitty.
