### ISSUE TITLE
Kitty GLFWwindow Debian 12 Wayland issues

### ISSUE THREAD

**Issue by anarchopossum** [kovidgoyal/kitty#7853]
Kitty fails to run due to `Failed to create GLFWwindow` under Debian 12 running Wayland. Kitty also fails to create config file.

**To Reproduce**
1. Install Debian 12 without DE
2. apt update...
3. install `Sway`, `xWayland`, and `Kitty` via standard apt repos
4. run `sway`
5. open default terminal and run `kitty`
6. See error:
```zsh
➜  ~ kitty
[257 23:35:42.350229] [glfw error 65543]: EGL: Failed to create context: Arguments are inconsistent
[257 23:35:42.640401] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 477, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 469, in _main
    run_app(opts, cli_opts, prewarm, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 233, in __call__
    _run_app(opts, args, prewarm, bad_lines)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 206, in _run_app
    window_id = create_os_window(
                ^^^^^^^^^^^^^^^^^
ValueError: Failed to create GLFWwindow
 
[257 23:35:43.652458] Prewarm process failed to quit gracefully, killing it
```

**Note**: I also tried installing KDE (wayland) and tried running `kitty` via Konsole with the same error message coming up

**Comment by kovidgoyal** [comment]
I dont provide support for debian kitty packages. Use the official
binaries and you will be fine.

https://sw.kovidgoyal.net/kitty/binary/
