### ISSUE TITLE
kitty -d with non-ascii/unidcode path

### ISSUE THREAD

**Issue by SrTobi** [kovidgoyal/kitty#789]
When using `kitty -d` with a unicode/non-ascii (not sure if it's really that) path, I get the following error

```
$ kitty -d Schuld\ und\ Sühne                                                                            
[216 10:17:21.071903] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 267, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 260, in _main
    run_app(opts, args)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 144, in run_app
    _run_app(opts, args)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 131, in _run_app
    boss = Boss(window_id, opts, args, cached_values, new_os_window_trigger)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 105, in __init__
    self.add_os_window(startup_session, os_window_id=os_window_id)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 116, in add_os_window
    tm = TabManager(os_window_id, self.opts, self.args, startup_session)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 317, in __init__
    self._add_tab(Tab(self, session_tab=t))
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 61, in __init__
    self.startup(session_tab)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 66, in startup
    self.new_special_window(cmd)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 214, in new_special_window
    return self.new_window(False, *special_window)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 200, in new_window
    child = self.launch_child(use_shell=use_shell, cmd=cmd, stdin=stdin, cwd_from=cwd_from, cwd=cwd, env=env)
  File "/usr/bin/../lib/kitty/kitty/tabs.py", line 196, in launch_child
    ans.fork()
  File "/usr/bin/../lib/kitty/kitty/child.py", line 79, in fork
    pid = fast_data_types.spawn(exe, self.cwd, tuple(argv), env, master, slave, stdin_read_fd, stdin_write_fd)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 33-34: surrogates not allowed
```

**Comment by kovidgoyal** [comment]
Works for me, steps I tried:

1) mkdir "Schuld\ und\ Sühne"
2) kitty -d "Schuld\ und\ Sühne"


Make sure you have properly setup a UTF-8 locale on your computer. In particular the LANG env var should be something like

LANG=en_IN.UTF-8
