### ISSUE TITLE
Kitty crashes on session file nearly identical to example session file

### ISSUE THREAD

**Issue by LilyIsTrans** [kovidgoyal/kitty#7899]
**Describe the bug**
Kitty crashes immediately (before even creating a window) when run as `kitty --session sandstorm.session` with the file `sandstorm.session` having the following contents:
```
# Create a complex layout using multiple splits. Creates two columns of
# windows with two windows in each column. The windows in the first column are
# split 50:50. In the second column the windows are not evenly split.
layout splits
cd ~/dev/sandstorm
# First window, set a user variable on it so we can focus it later
launch --var window=first
# Make it take 40% of the height instead of 50%
launch --location=hsplit --bias=15 --cwd=current bacon .
# Go back to focusing the first window, so that we can split it
# focus_matching_window var:window=first
```
Notably, this was literally copy-pasted from [the docs](https://sw.kovidgoyal.net/kitty/overview/#startup-sessions), then modified by removing a bunch of lines, adding `cd ~/dev/sandstorm`, changing the value of the bias, and changing the program in the second window to `bacon`.
Kitty outputs the following error message to the terminal used to start it:
```
[0.053] Traceback (most recent call last):
  File "/usr/bin/../lib64/kitty/kitty/launch.py", line 331, in parse_launch_args
    opts, args = parse_args(result_class=LaunchCLIOptions, args=args, ospec=options_spec)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib64/kitty/kitty/cli.py", line 1061, in parse_args
    return ans, parse_cmdline(oc, disabled, ans, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib64/kitty/kitty/cli.py", line 819, in parse_cmdline
    needs_arg = oc.needs_arg(parts[0])
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib64/kitty/kitty/cli.py", line 768, in needs_arg
    opt = self.opt_for_alias(alias)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib64/kitty/kitty/cli.py", line 761, in opt_for_alias
    raise SystemExit(f'Unknown option: {emph(alias)}')
SystemExit: Unknown option: ␛[91m--bias␛[39m

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 562, in main
    _main()
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 554, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 297, in __call__
    _run_app(opts, args, bad_lines)
  File "/usr/bin/../lib64/kitty/kitty/main.py", line 261, in _run_app
    startup_sessions = tuple(create_sessions(opts, args, default_session=opts.startup_session))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib64/kitty/kitty/session.py", line 242, in create_sessions
    yield from parse_session(session_data, opts, environ=environ)
  File "/usr/bin/../lib64/kitty/kitty/session.py", line 185, in parse_session
    ans.add_window(rest, expand)
  File "/usr/bin/../lib64/kitty/kitty/session.py", line 106, in add_window
    spec = parse_launch_args(cmd)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib64/kitty/kitty/launch.py", line 333, in parse_launch_args
    raise ValueError(str(e)) from e
ValueError: Unknown option: ␛[91m--bias␛[39m
```

**Environment details**
```
kitty 0.35.2 created by Kovid Goyal
Linux lily-laptop 6.6.47-gentoo #2 SMP PREEMPT_DYNAMIC Fri Sep 20 19:07:03 EDT 2024 x86_64

This is lily-laptop (Linux x86_64 6.6.47-gentoo) 21:19:33

DISTRIB_ID="Gentoo"
Running under: Wayland (sway version 1.9) missing: blur
OpenGL: '4.6 (Core Profile) Mesa 24.1.7' Detected version: 4.6
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/lily/.config/kitty/kitty.conf

Config options different from defaults:
bold_font         Fira Code Bold
bold_italic_font  Fira Code Bold Italic
editor            /usr/bin/hx
font_family       Fira Code
font_size         18.0
italic_font       Fira Code Italic
shell             /usr/bin/zsh
shell_integration frozenset({'enabled'})
Added shortcuts:
	f5 →  launch --location=hsplit
	f6 →  launch --location=vsplit
	f7 →  layout_action rotate
Changed shortcuts:
	kitty_mod+enter →  launch --cwd=current
	kitty_mod+t →  launch --type=tab --cwd=current

Important environment variables seen by the kitty process:
	PATH                                /home/lily/dev/java/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/bin:/home/lily/.godot/bin:/home/lily/.jetbrains/bin:/home/lily/.cargo/bin:/home/david/pear/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/bin:/usr/lib/llvm/18/bin
	LANG                                en_US.utf8
	EDITOR                              /usr/bin/hx
	SHELL                               /bin/zsh
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-1
	USER                                lily
	XCURSOR_SIZE                        24
	XDG_CONFIG_DIRS                     /etc/xdg
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    wayland
	XDG_CURRENT_DESKTOP                 sway
	XDG_SESSION_CLASS                   user
	XDG_VTNR                            1
	XDG_SESSION_ID                      1
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /usr/local/share:/usr/share

```

Running with `--config NONE` has absolutely no impact.

**Comment by kovidgoyal** [comment]
update kitty.
