### ISSUE TITLE
I dont know what to do

### ISSUE THREAD

**Issue by RandomAccess-glitch** [kovidgoyal/kitty#7967]
[1.660] [glfw error 65543]: EGL: Failed to create context: Arguments are inconsistent
[1.782] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 528, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 520, in _main
    run_app(opts, cli_opts, bad_lines, talk_fd)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 253, in __call__
    _run_app(opts, args, bad_lines, talk_fd)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 222, in _run_app
    window_id = create_os_window(
                ^^^^^^^^^^^^^^^^^
ValueError: Failed to create GLFWwindow

this appeared when i tried to open kitty

**Comment by kovidgoyal** [comment]
That indicates an issue with your GPU drivers. Fix those and you should
be fine. Or use software rendering via the MESA env var, google and you
will find it.
