### ISSUE TITLE
[Nightly] Kitty occasionally crashes getting scrollback buffer contents

### ISSUE THREAD

**Issue by mikesmithgh** [kovidgoyal/kitty#8044]
**Describe the bug**
Kitty crashes when getting the scrollback buffer contents. 

**To Reproduce**
1. In the Kitty git repo, checkout commit 19cb15811f4b44a400e506d92bf45ef4b5adb821 (this just happened to be the commit I was on to produce output for git status)
2. `git reset HEAD~`
3. Launch Kitty nightly via `/Users/mike/go/src/github.com/kovidgoyal/kitty/kitty/launcher/kitty --config NONE`
4. Perform `git status` eight times
5. Press `ctrl+shift+h` to trigger `show_scrollback` 
6. Kitty crashes with:
```
fish: Job 1,
'/Users/mike/go/src/github.com/k.'
terminated by signal SIGSEGV (Address boundary error)
```

**Screenshots**

https://github.com/user-attachments/assets/fda8c26d-7b51-4a02-b11e-4d8daf5ea0a7

**Environment details**
```
kitty 0.37.0 (19cb15811f) created by Kovid Goyal
Darwin mikes-MacBook-Pro.local 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:11 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6020 arm64
ProductName:		macOS ProductVersion:		15.1 BuildVersion:		24B83
OpenGL: '4.1 Metal - 89.3' Detected version: 4.1
Frozen: False
Fonts:
  medium: MonoLisaVariable-Regular: /Users/mike/Library/Fonts/MonoLisaVariableNormal.ttf
          Features: ('calt', 'liga', 'zero', 'ss04', 'ss06', 'ss07', 'ss08', 'ss10', 'ss11', 'ss12', 'ss13', 'ss15', 'ss16')
    bold: MonoLisaVariableRegular-SemiBold: /Users/mike/Library/Fonts/MonoLisaVariableNormal.ttf
          Features: ('calt', 'liga', 'zero', 'ss04', 'ss06', 'ss07', 'ss08', 'ss10', 'ss11', 'ss12', 'ss13', 'ss15', 'ss16')
  italic: MonoLisaVariable-Italic: /Users/mike/Library/Fonts/MonoLisaVariableItalic.ttf
          Features: ('calt', 'liga', 'zero', 'ss04', 'ss06', 'ss07', 'ss08', 'ss10', 'ss11', 'ss12', 'ss13', 'ss15', 'ss16')
      bi: MonoLisaVariableItalic-SemiBold: /Users/mike/Library/Fonts/MonoLisaVariableItalic.ttf
          Features: ('calt', 'liga', 'zero', 'ss04', 'ss06', 'ss07', 'ss08', 'ss10', 'ss11', 'ss12', 'ss13', 'ss15', 'ss16')
Paths:
  kitty: /Users/mike/go/src/github.com/kovidgoyal/kitty/kitty/launcher/kitty
  base dir: /Users/mike/go/src/github.com/kovidgoyal/kitty
  extensions dir: /Users/mike/go/src/github.com/kovidgoyal/kitty/kitty
  system shell: /opt/homebrew/bin/bash
System color scheme: dark. Applied color theme type: none
Loaded config files:
  /Users/mike/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_font_style           (False, False)
allow_remote_control            socket-only
cursor_blink_interval           (0.0, kitty.options.utils.EasingFunction(), kitty.options.utils.EasingFunction())
cursor_stop_blinking_after      0
cursor_trail                    3
cursor_trail_decay              (0.2, 0.3)
cursor_trail_start_threshold    3
editor                          /Users/mike/bin/nvim
enable_audio_bell               False
enabled_layouts                 ['vertical', 'horizontal', 'fat', 'grid', 'splits', 'stack', 'tall']
env:
{'EDITOR': 'nvim',
 'VIMRUNTIME': '/Users/mike/gitrepos/neovim/runtime',
 'VISUAL': 'nvim'}
font_family                     MonoLisa Variable
font_features:
{'MonoLisaVariable-Italic': ('calt',
                             'liga',
                             'zero',
                             'ss04',
                             'ss06',
                             'ss07',
                             'ss08',
                             'ss10',
                             'ss11',
                             'ss12',
                             'ss13',
                             'ss15',
                             'ss16'),
 'MonoLisaVariable-Regular': ('calt',
                              'liga',
                              'zero',
                              'ss04',
                              'ss06',
                              'ss07',
                              'ss08',
                              'ss10',
                              'ss11',
                              'ss12',
                              'ss13',
                              'ss15',
                              'ss16'),
 'MonoLisaVariableItalic-Black': ('calt',
                                  'liga',
                                  'zero',
                                  'ss04',
                                  'ss06',
                                  'ss07',
                                  'ss08',
                                  'ss10',
                                  'ss11',
                                  'ss12',
                                  'ss13',
                                  'ss15',
                                  'ss16'),
 'MonoLisaVariableItalic-Bold': ('calt',
                                 'liga',
                                 'zero',
                                 'ss04',
                                 'ss06',
                                 'ss07',
                                 'ss08',
                                 'ss10',
                                 'ss11',
                                 'ss12',
                                 'ss13',
                                 'ss15',
                                 'ss16'),
 'MonoLisaVariableItalic-ExtraBold': ('calt',
                                      'liga',
                                      'zero',
                                      'ss04',
                                      'ss06',
                                      'ss07',
                                      'ss08',
                                      'ss10',
                                      'ss11',
                                      'ss12',
                                      'ss13',
                                      'ss15',
                                      'ss16'),
 'MonoLisaVariableItalic-ExtraLight': ('calt',
                                       'liga',
                                       'zero',
                                       'ss04',
                                       'ss06',
                                       'ss07',
                                       'ss08',
                                       'ss10',
                                       'ss11',
                                       'ss12',
                                       'ss13',
                                       'ss15',
                                       'ss16'),
 'MonoLisaVariableItalic-Light': ('calt',
                                  'liga',
                                  'zero',
                                  'ss04',
                                  'ss06',
                                  'ss07',
                                  'ss08',
                                  'ss10',
                                  'ss11',
                                  'ss12',
                                  'ss13',
                                  'ss15',
                                  'ss16'),
 'MonoLisaVariableItalic-Medium': ('calt',
                                   'liga',
                                   'zero',
                                   'ss04',
                                   'ss06',
                                   'ss07',
                                   'ss08',
                                   'ss10',
                                   'ss11',
                                   'ss12',
                                   'ss13',
                                   'ss15',
                                   'ss16'),
 'MonoLisaVariableItalic-SemiBold': ('calt',
                                     'liga',
                                     'zero',
                                     'ss04',
                                     'ss06',
                                     'ss07',
                                     'ss08',
                                     'ss10',
                                     'ss11',
                                     'ss12',
                                     'ss13',
                                     'ss15',
                                     'ss16'),
 'MonoLisaVariableItalic-Thin': ('calt',
                                 'liga',
                                 'zero',
                                 'ss04',
                                 'ss06',
                                 'ss07',
                                 'ss08',
                                 'ss10',
                                 'ss11',
                                 'ss12',
                                 'ss13',
                                 'ss15',
                                 'ss16'),
 'MonoLisaVariableRegular-Black': ('calt',
                                   'liga',
                                   'zero',
                                   'ss04',
                                   'ss06',
                                   'ss07',
                                   'ss08',
                                   'ss10',
                                   'ss11',
                                   'ss12',
                                   'ss13',
                                   'ss15',
                                   'ss16'),
 'MonoLisaVariableRegular-Bold': ('calt',
                                  'liga',
                                  'zero',
                                  'ss04',
                                  'ss06',
                                  'ss07',
                                  'ss08',
                                  'ss10',
                                  'ss11',
                                  'ss12',
                                  'ss13',
                                  'ss15',
                                  'ss16'),
 'MonoLisaVariableRegular-ExtraBold': ('calt',
                                       'liga',
                                       'zero',
                                       'ss04',
                                       'ss06',
                                       'ss07',
                                       'ss08',
                                       'ss10',
                                       'ss11',
                                       'ss12',
                                       'ss13',
                                       'ss15',
                                       'ss16'),
 'MonoLisaVariableRegular-ExtraLight': ('calt',
                                        'liga',
                                        'zero',
                                        'ss04',
                                        'ss06',
                                        'ss07',
                                        'ss08',
                                        'ss10',
                                        'ss11',
                                        'ss12',
                                        'ss13',
                                        'ss15',
                                        'ss16'),
 'MonoLisaVariableRegular-Light': ('calt',
                                   'liga',
                                   'zero',
                                   'ss04',
                                   'ss06',
                                   'ss07',
                                   'ss08',
                                   'ss10',
                                   'ss11',
                                   'ss12',
                                   'ss13',
                                   'ss15',
                                   'ss16'),
 'MonoLisaVariableRegular-Medium': ('calt',
                                    'liga',
                                    'zero',
                                    'ss04',
                                    'ss06',
                                    'ss07',
                                    'ss08',
                                    'ss10',
                                    'ss11',
                                    'ss12',
                                    'ss13',
                                    'ss15',
                                    'ss16'),
 'MonoLisaVariableRegular-SemiBold': ('calt',
                                      'liga',
                                      'zero',
                                      'ss04',
                                      'ss06',
                                      'ss07',
                                      'ss08',
                                      'ss10',
                                      'ss11',
                                      'ss12',
                                      'ss13',
                                      'ss15',
                                      'ss16'),
 'MonoLisaVariableRegular-Thin': ('calt',
                                  'liga',
                                  'zero',
                                  'ss04',
                                  'ss06',
                                  'ss07',
                                  'ss08',
                                  'ss10',
                                  'ss11',
                                  'ss12',
                                  'ss13',
                                  'ss15',
                                  'ss16')}
font_size                       18.0
hide_window_decorations         2
initial_window_height           (1200, 'px')
initial_window_width            (1280, 'px')
listen_on                       unix:/tmp/kitty
macos_option_as_alt             3
menu_map:
{('global', '\U000f011b  \uf004  \ue6ae', 'kitty_scrollback_nvim'): 'kitty_scrollback_nvim',
 ('global', '\U000f011b  \uf004  \ue6ae', 'kitty_scrollback_nvim --config ksb_builtin_last_cmd_output'): 'kitty_scrollback_nvim '
                                                                                                         '--config '
                                                                                                         'ksb_builtin_last_cmd_output'}
narrow_symbols:
{(58923, 58923): 1,
 (59054, 59054): 1,
 (59333, 59333): 1,
 (60115, 60115): 1,
 (61489, 61489): 1,
 (62081, 62081): 1,
 (62309, 62309): 1,
 (62762, 62762): 1}
remember_window_size            False
scrollback_fill_enlarged_window True
scrollback_pager                ['/opt/homebrew/bin/less', '--ignore-case', '--status-column', '--no-init', '--raw-control-chars', '--chop-long-lines', '+INPUT_LINE_NUMBER', '--use-color', '--color=P0.7$', '--prompt=?f \uea7b %f : \U000f011b (kitty) .?m(%T %i of %m) .?lt\ue0a1 %lt-%lb?L/%L. .\U000f1a05 %bB?s/%s. ?e(END) :?pB%pB\\%..%t \uf11c  v=>pipe e=>edit \ue6ae %E $']
scrollback_pager_history_size   2097152
shell                           fish
shell_integration               frozenset({'enabled', 'no-cursor'})
symbol_map:
	U+23fb - U+23fe → FiraCode Nerd Font
	U+2665 - U+2665 → FiraCode Nerd Font
	U+26a1 - U+26a1 → FiraCode Nerd Font
	U+2b58 - U+2b58 → FiraCode Nerd Font
	U+e000 - U+f8ff → FiraCode Nerd Font
tab_bar_align                   center
window_margin_width             FloatEdges(left=2.0, top=2.0, right=2.0, bottom=2.0)
window_padding_width            FloatEdges(left=4.0, top=8.0, right=4.0, bottom=8.0)
Changed mouse actions:
	ctrl+shift+right press ungrabbed →  combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output
Added shortcuts:
	ctrl+w > j →  [--when-focus-on=var:in_editor]no-op, toggle_layout stack, kitten pass_keys.py neighboring_window right  'ctrl+w>l', kitten pass_keys.py neighboring_window left   'ctrl+w>h', kitten pass_keys.py neighboring_window top    'ctrl+w>k', kitten pass_keys.py neighboring_window bottom 'ctrl+w>j'
	shift+down →  move_window down
	shift+left →  move_window left
	shift+right →  move_window right
	shift+up →  move_window up
Changed shortcuts:
	cmd+enter →  launch --cwd=current
	cmd+k →  clear_terminal_and_scrollback
	ctrl+cmd+, →  reload_config
	kitty_mod+enter →  launch --cwd=current
	kitty_mod+f →  kitty_scrollback_nvim --config search
	kitty_mod+g →  kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
	kitty_mod+h →  kitty_scrollback_nvim
	kitty_mod+j →  kitty_scrollback_bobnvim --env NVIM_APPNAME=nvim_kitty_scrollback
	opt+cmd+r →  reset_terminal
	shift+cmd+/ →  open_kitty_website
Colors:
	active_border_color             #53654e   
	active_tab_background           #32302f   
	active_tab_foreground           #a0a0a0   
	background                      #070707   
	bell_border_color               #d3869b   
	color0                          #070707   
	color1                          #ff6961   
	color10                         #53654e   
	color11                         #d6991d   
	color12                         #458588   
	color13                         #b16286   
	color14                         #92bbdf   
	color15                         #b7a7b7   
	color2                          #8faa80   
	color3                          #dbbc5f   
	color4                          #83a598   
	color5                          #d3869b   
	color6                          #9dbad4   
	color7                          #c7c7c7   
	color8                          #968c81   
	color9                          #af3a03   
	cursor                          #c7c7c7   
	cursor_text_color               #504a45   
	foreground                      #c7c7c7   
	inactive_border_color           #1a1a1a   
	inactive_tab_background         #1a1a1a   
	inactive_tab_foreground         #504945   
	macos_titlebar_color            #070707   
	mark1_background                #1a1a1a   
	mark1_foreground                #83a598   
	mark2_background                #1a1a1a   
	mark2_foreground                #dbbc5f   
	mark3_background                #1a1a1a   
	mark3_foreground                #ff6961   
	selection_background            #878787   
	selection_foreground            #3c3836   
	tab_bar_background              #070707   
	tab_bar_margin_color            #070707   
	url_color                       #9dbad4   
	visual_bell_color               #32302f   
	wayland_titlebar_color          #070707   

Important environment variables seen by the kitty process:
	PATH                                /Users/mike/go/src/github.com/kovidgoyal/kitty/kitty/launcher:/Users/mike/bin:/Applications/kitty.app/Contents/MacOS:/opt/homebrew/opt/sdkman-cli/libexec/candidates/kotlin/current/bin:/opt/homebrew/opt/sdkman-cli/libexec/candidates/java/current/bin:/opt/homebrew/opt/sdkman-cli/libexec/candidates/gradle/current/bin:/Users/mike/.local/bin:/opt/homebrew/bin:/Users/mike/go/bin:/Users/mike/.config/pyenv/bin:/Users/mike/.config/pyenv/bin:/Users/mike/gitrepos/neovim/build/bin:/Users/mike/.cargo/bin:/opt/homebrew/opt/libpq/bin:/Users/mike/Library/Application Support/Coursier/bin:/Users/mike/.config/pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/go/bin:.:/opt/homebrew/opt/fzf/bin
	LANG                                en_US.UTF-8
	VISUAL                              nvim
	EDITOR                              nvim
	SHELL                               /opt/homebrew/bin/bash
	USER                                mike
	XDG_RUNTIME_DIR                     /var/folders/52/fp0f1rv10t3_k_q60xk7_lgc0000gn/T/mike.zfKLzCgMHh
	XDG_STATE_HOME                      /Users/mike/.local/state
	XDG_CONFIG_HOME                     /Users/mike/.config
	XDG_DATA_HOME                       /Users/mike/.local/share
	XDG_CACHE_HOME                      /Users/mike/.cache
	XDG_DATA_DIRS                       /usr/local/share
```

**Additional context**

I have nightly tests for kitty-scrollback.nvim, that started failing 3 days ago https://github.com/mikesmithgh/kitty-scrollback.nvim/actions/runs/11755352136

It looks like there are some errors around getting the scrollback text in certain situations. I can reproduce it after using the `git status` command multiple times to scroll past the window.

I've also seen this error:
```
kitty @ --to unix:/Users/mike/gitrepos/kitty-scrollback.nvim/tmp/tmp.E0SjUOSN5E/kitty-scrollback-nvim.sock get-text --extent=all
Error: EOF
```

**Comment by kovidgoyal** [comment]
Doesnt crash for me can you do make debug and post the crash log or
better make asan, run kitty from another terminal and post the crash log
that will be printed there when kitty crashes.

**Comment by mikesmithgh** [comment]
I was receiving the error `fatal error: 'simde/x86/avx2.h' file not found` when I tried `make asan`. However, I was able to do `./dev.sh build --debug --sanitize` which I think is the same thing from the Makefile.

I reproduced the error and got the following:

```
kitty(82652,0x1f6a7f840) malloc: nano zone abandoned due to inability to reserve vm space.
2024-11-11 22:33:50.092 kitty[82652:28610038] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-11 22:33:50.117 kitty[82652:28610038] +[IMKInputSession subclass]: chose IMKInputSession_Modern
kitty/text-cache.c:111:15: runtime error: member access within null pointer of type 'const TextCache' (aka 'const struct TextCache')
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior kitty/text-cache.c:111:15 in 
kitty/text-cache.c:111:15: runtime error: member access within null pointer of type 'const struct (unnamed struct at kitty/text-cache.c:24:5)'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior kitty/text-cache.c:111:15 in 
AddressSanitizer:DEADLYSIGNAL
=================================================================
==82652==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x000103f2a8d4 bp 0x00016f918d80 sp 0x00016f918cd0 T0)
==82652==The signal is caused by a READ memory access.
==82652==Hint: address points to the zero page.
    #0 0x103f2a8d4 in tc_chars_at_index_ansi text-cache.c:111
    #1 0x103e17e8c in line_as_ansi line.c:393
    #2 0x103e25c1c in as_text_generic line.c:914
    #3 0x103ddcfc8 in as_text_history_buf history.c:517
    #4 0x1014fe7f8 in method_vectorcall_VARARGS+0x80 (Python:arm64+0xae7f8)
    #5 0x10162fe98 in _PyEval_EvalFrameDefault+0xce30 (Python:arm64+0x1dfe98)
    #6 0x1014f045c in method_vectorcall+0x210 (Python:arm64+0xa045c)
    #7 0x1016322c8 in _PyEval_EvalFrameDefault+0xf260 (Python:arm64+0x1e22c8)
    #8 0x1014f02fc in method_vectorcall+0xb0 (Python:arm64+0xa02fc)
    #9 0x1014edaa8 in _PyObject_CallFunctionVa+0x94 (Python:arm64+0x9daa8)
    #10 0x1014ee4f4 in _PyObject_CallMethod_SizeT+0x70 (Python:arm64+0x9e4f4)
    #11 0x103df72fc in on_key_input keys.c:229
    #12 0x103d6f584 in key_callback glfw.c:430
    #13 0x10544ce68 in -[GLFWContentView keyDown:] cocoa_window.m:1190
    #14 0x105437f80 in ___glfwPlatformInit_block_invoke cocoa_init.m:860
    #15 0x1956a24b4 in _NSSendEventToObservers+0xf8 (AppKit:arm64e+0x1614b4)
    #16 0x195eba5e8 in -[NSApplication(NSEventRouting) sendEvent:]+0x70 (AppKit:arm64e+0x9795e8)
    #17 0x195ac8898 in -[NSApplication _handleEvent:]+0x38 (AppKit:arm64e+0x587898)
    #18 0x19556eb04 in -[NSApplication run]+0x204 (AppKit:arm64e+0x2db04)
    #19 0x105438ee8 in _glfwPlatformRunMainLoop cocoa_init.m:1064
    #20 0x103c693d8 in main_loop child-monitor.c:1304
    #21 0x1014fe400 in method_vectorcall_NOARGS+0x74 (Python:arm64+0xae400)
    #22 0x10162fe98 in _PyEval_EvalFrameDefault+0xce30 (Python:arm64+0x1dfe98)
    #23 0x1014ebde0 in _PyObject_FastCallDictTstate+0x5c (Python:arm64+0x9bde0)
    #24 0x101581098 in slot_tp_call+0xc4 (Python:arm64+0x131098)
    #25 0x1014eb908 in _PyObject_MakeTpCall+0x7c (Python:arm64+0x9b908)
    #26 0x101630014 in _PyEval_EvalFrameDefault+0xcfac (Python:arm64+0x1e0014)
    #27 0x10162219c in PyEval_EvalCode+0x124 (Python:arm64+0x1d219c)
    #28 0x10161d9fc in builtin_exec+0x194 (Python:arm64+0x1cd9fc)
    #29 0x1015571bc in cfunction_vectorcall_FASTCALL_KEYWORDS+0x58 (Python:arm64+0x1071bc)
    #30 0x10162fe98 in _PyEval_EvalFrameDefault+0xce30 (Python:arm64+0x1dfe98)
    #31 0x1016de298 in pymain_run_module+0x110 (Python:arm64+0x28e298)
    #32 0x1016dda60 in pymain_run_python+0x364 (Python:arm64+0x28da60)
    #33 0x1016dd6b4 in Py_RunMain+0x14 (Python:arm64+0x28d6b4)
    #34 0x1004e8c40 in run_embedded main.c:216
    #35 0x1004e42d0 in main main.c:466
    #36 0x1915e8270  (<unknown module>)

==82652==Register values:
 x[0] = 0x000000016f918be8   x[1] = 0x0000000000000000   x[2] = 0x0000000000000000   x[3] = 0x00000001242007a0  
 x[4] = 0x0000000063000000   x[5] = 0x0000000000000000   x[6] = 0x0000000000000000   x[7] = 0x0000000000000000  
 x[8] = 0x0000000000000000   x[9] = 0x0000000000000003  x[10] = 0x0000000000000000  x[11] = 0x0000000000000242  
x[12] = 0x00000001008d4000  x[13] = 0x0000000100a706e8  x[14] = 0x0000000000000000  x[15] = 0x0000000000000000  
x[16] = 0x0000000301a8dd90  x[17] = 0x00000001009c80a0  x[18] = 0x0000000000000000  x[19] = 0x00006200001ad3e0  
x[20] = 0x0000000000000000  x[21] = 0x0000000000000000  x[22] = 0x0000000000000010  x[23] = 0x0000000000000000  
x[24] = 0x000000002372781c  x[25] = 0x0000007000020000  x[26] = 0x0000000000000000  x[27] = 0x0000000000000000  
x[28] = 0x000000011b93c0e0     fp = 0x000000016f918d80     lr = 0x0000000103f2ab3c     sp = 0x000000016f918cd0  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV text-cache.c:111 in tc_chars_at_index_ansi
==82652==ABORTING
fish: Job 1, '/Users/mike/go/src/github.com/k…' terminated by signal SIGABRT (Abort)
```

**Comment by kovidgoyal** [comment]
Thanks, I was able to guess the cause anyway and committed a fix see if it works for you.

**Comment by mikesmithgh** [comment]
Thanks! that fixed it 👍 🙌
