### ISSUE TITLE
Mysterious crash-on-maximize

### ISSUE THREAD

**Issue by inducer** [kovidgoyal/kitty#812]
I've started seeing somewhat infrequent crashes that seem to happen when a kitty process has been running for a long time, possibly across a few screen hotplugs. I focus the kitty window, push a hotkey to maximize it, and the window disappears and this shows up in `dmesg`:

```
[132344.553824] python3[31021]: segfault at 8 ip 00007fddc8e9d960 sp 00007fff7a02bff8 error 4 in glfw-x11.so[7fddc8e95000+1b000]
```

I'll try to get a less useless backtrace.

**Comment by inducer** [comment]
Thanks! (TIL)

**Comment by kovidgoyal** [comment]
Oh and there definitely seem to be issues with glfw and monitor hotplugs, see for example: #784 

Best I could tell from the trace in that issue is that the monitor stricture glfw maintains goes stale in some circumstances, causing crashes when any function that uses the monitor information is performed.

**Comment by inducer** [comment]
Got one:

```
           PID: 17548 (python3)
           UID: 1000 (andreas)
           GID: 1000 (andreas)
        Signal: 11 (SEGV)
     Timestamp: Tue 2018-08-21 01:38:04 CDT (41s ago)
  Command Line: python3 -X faulthandler /home/andreas/pack/kitty --config=/home/andreas/.config/kitty/kitty.conf --config=/home/andreas/.config/kitty/solarized-dark.conf
    Executable: /usr/bin/python3.6
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (andreas)
       Boot ID: f0f3928a0c7045cab4b22f937bf93ab6
    Machine ID: 4639e3a7968b473fbc19adec4e520df1
      Hostname: bolt
       Storage: /var/lib/systemd/coredump/core.python3.1000.f0f3928a0c7045cab4b22f937bf93ab6.17548.1534833484000000.lz4
       Message: Process 17548 (python3) of user 1000 dumped core.
                
                Stack trace of thread 17548:
                #0  0x00007f14f1e3777b raise (libpthread.so.0)
                #1  0x00007f14f1e378e0 __restore_rt (libpthread.so.0)
                #2  0x00007f14ee114334 n/a (/home/andreas/pack/kitty/kitty/glfw-x11.so)

GNU gdb (Debian 8.1-4) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/python3.6...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 17548]
[New LWP 17552]
[New LWP 17554]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `python3 -X faulthandler /home/andreas/pack/kitty --config=/home/andreas/.config'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
[Current thread is 1 (Thread 0x7f14f1675740 (LWP 17548))]
(gdb) #0  raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  <signal handler called>
#2  vidmodeFromModeInfo (mi=0x0, ci=ci@entry=0x1fef450) at /home/andreas/pack/kitty/glfw/x11_monitor.c:81
#3  0x00007f14ee11490e in _glfwPlatformGetVideoMode (monitor=monitor@entry=0x2266e70, mode=mode@entry=0x2266e9c)
    at /home/andreas/pack/kitty/glfw/x11_monitor.c:414
#4  0x00007f14ee10fa9d in glfwGetVideoMode (handle=0x2266e70) at /home/andreas/pack/kitty/glfw/monitor.c:424
#5  0x00007f14f0c5576d in current_monitor (window=<optimized out>) at /home/andreas/pack/kitty/kitty/glfw.c:309
#6  0x00007f14f0c56427 in get_window_dpi (y=0x1eabe38, x=0x1eabe30, w=<optimized out>)
    at /home/andreas/pack/kitty/kitty/glfw.c:330
#7  set_os_window_dpi (w=w@entry=0x1eabd70) at /home/andreas/pack/kitty/kitty/glfw.c:345
#8  0x00007f14f0c57055 in update_os_window_viewport (window=0x1eabd70, notify_boss=notify_boss@entry=true)
    at /home/andreas/pack/kitty/kitty/glfw.c:35
#9  0x00007f14f0c8481b in process_pending_resizes (now=76359.832997624995)
    at /home/andreas/pack/kitty/kitty/child-monitor.c:703
#10 main_loop (self=0x7f14ee5f3bd0, a=<optimized out>) at /home/andreas/pack/kitty/kitty/child-monitor.c:760
#11 0x000000000050c3a1 in ?? ()
#12 0x000000000050fad9 in _PyEval_EvalFrameDefault ()
#13 0x000000000050b519 in ?? ()
#14 0x000000000050c24d in ?? ()
#15 0x000000000050fad9 in _PyEval_EvalFrameDefault ()
#16 0x000000000050b519 in ?? ()
#17 0x000000000050c24d in ?? ()
#18 0x000000000050fad9 in _PyEval_EvalFrameDefault ()
#19 0x000000000050b519 in ?? ()
#20 0x000000000050c24d in ?? ()
#21 0x000000000050fad9 in _PyEval_EvalFrameDefault ()
#22 0x000000000050b519 in ?? ()
#23 0x000000000050c24d in ?? ()
#24 0x000000000050fad9 in _PyEval_EvalFrameDefault ()
#25 0x000000000050b519 in ?? ()
#26 0x000000000050c24d in ?? ()
#27 0x000000000050fad9 in _PyEval_EvalFrameDefault ()
#28 0x000000000050dee7 in ?? ()
#29 0x000000000051b2ea in ?? ()
#30 0x000000000050c07f in ?? ()
#31 0x000000000050fad9 in _PyEval_EvalFrameDefault ()
#32 0x000000000050dee7 in ?? ()
---Type <return> to continue, or q <return> to quit---#33 0x000000000050b850 in ?? ()
#34 0x000000000050c24d in ?? ()
#35 0x000000000050fad9 in _PyEval_EvalFrameDefault ()
#36 0x000000000050dee7 in ?? ()
#37 0x000000000058ec1d in ?? ()
#38 0x00000000005a6dbe in PyObject_Call ()
#39 0x000000000063902b in ?? ()
#40 0x000000000063a17c in Py_Main ()
#41 0x00000000004b2760 in main ()
(gdb) quit
```

Python-side backtrace from `faulthandler`:

```
Aug 21 01:38:04 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]: Fatal Python error: Segmentation fault
Aug 21 01:38:04 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]: Current thread 0x00007f14f1675740 (most recent call first):
Aug 21 01:38:04 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]:   File "/home/andreas/pack/kitty/kitty/main.py", line 141 in _run_app
Aug 21 01:38:04 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]:   File "/home/andreas/pack/kitty/kitty/main.py", line 151 in run_app
Aug 21 01:38:04 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]:   File "/home/andreas/pack/kitty/kitty/main.py", line 275 in _main
Aug 21 01:38:04 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]:   File "/home/andreas/pack/kitty/kitty/main.py", line 282 in main
Aug 21 01:38:04 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]:   File "/home/andreas/pack/kitty/__main__.py", line 98 in main
Aug 21 01:38:04 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]:   File "/home/andreas/pack/kitty/__main__.py", line 104 in <module>
Aug 21 01:38:04 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]:   File "/usr/lib/python3.6/runpy.py", line 85 in _run_code
Aug 21 01:38:04 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]:   File "/usr/lib/python3.6/runpy.py", line 193 in _run_module_as_main
Aug 21 01:38:04 bolt systemd[1]: Started Process Core Dump (PID 447/UID 0).                                            
                                            Stack trace of thread 17548:
                                            #0  0x00007f14f1e3777b raise (libpthread.so.0)
                                            #1  0x00007f14f1e378e0 __restore_rt (libpthread.so.0)
                                            #2  0x00007f14ee114334 n/a (/home/andreas/pack/kitty/kitty/glfw-x11.so)
Aug 21 01:38:09 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]: [233 01:38:09.670353] Ignoring unknown config key: font_size_delta
Aug 21 01:38:09 bolt org.gnome.Shell.desktop[3451]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2a0000e (kitty)
Aug 21 01:38:10 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]: /home/andreas/pack/kitty/kitty/utils.py:28: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/andreas/pack/kitty/kitty/blit_vertex.glsl' mode='r' encoding='U
Aug 21 01:38:10 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]:   vert = open(os.path.join(BASE, '{}_vertex.glsl'.format(name))).read().replace('GLSL_VERSION', str(GLSL_VERSION), 1)
Aug 21 01:38:10 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]: /home/andreas/pack/kitty/kitty/utils.py:29: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/andreas/pack/kitty/kitty/blit_fragment.glsl' mode='r' encoding=
Aug 21 01:38:10 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]:   frag = open(os.path.join(BASE, '{}_fragment.glsl'.format(name))).read().replace('GLSL_VERSION', str(GLSL_VERSION), 1)
Aug 21 01:38:10 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]: /home/andreas/pack/kitty/kitty/utils.py:28: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/andreas/pack/kitty/kitty/cell_vertex.glsl' mode='r' encoding='U
Aug 21 01:38:10 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]:   vert = open(os.path.join(BASE, '{}_vertex.glsl'.format(name))).read().replace('GLSL_VERSION', str(GLSL_VERSION), 1)
Aug 21 01:38:10 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]: /home/andreas/pack/kitty/kitty/utils.py:29: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/andreas/pack/kitty/kitty/cell_fragment.glsl' mode='r' encoding=
Aug 21 01:38:10 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]:   frag = open(os.path.join(BASE, '{}_fragment.glsl'.format(name))).read().replace('GLSL_VERSION', str(GLSL_VERSION), 1)
Aug 21 01:38:10 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]: /home/andreas/pack/kitty/kitty/utils.py:28: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/andreas/pack/kitty/kitty/graphics_vertex.glsl' mode='r' encodin
Aug 21 01:38:10 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]:   vert = open(os.path.join(BASE, '{}_vertex.glsl'.format(name))).read().replace('GLSL_VERSION', str(GLSL_VERSION), 1)
Aug 21 01:38:10 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]: /home/andreas/pack/kitty/kitty/utils.py:29: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/andreas/pack/kitty/kitty/graphics_fragment.glsl' mode='r' encod
Aug 21 01:38:10 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]:   frag = open(os.path.join(BASE, '{}_fragment.glsl'.format(name))).read().replace('GLSL_VERSION', str(GLSL_VERSION), 1)
Aug 21 01:38:10 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]: /home/andreas/pack/kitty/kitty/utils.py:28: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/andreas/pack/kitty/kitty/border_vertex.glsl' mode='r' encoding=
Aug 21 01:38:10 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]:   vert = open(os.path.join(BASE, '{}_vertex.glsl'.format(name))).read().replace('GLSL_VERSION', str(GLSL_VERSION), 1)
Aug 21 01:38:10 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]: /home/andreas/pack/kitty/kitty/utils.py:29: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/andreas/pack/kitty/kitty/border_fragment.glsl' mode='r' encodin
Aug 21 01:38:10 bolt org.gnome.SettingsDaemon.MediaKeys.desktop[3649]:   frag = open(os.path.join(BASE, '{}_fragment.glsl'.format(name))).read().replace('GLSL_VERSION', str(GLSL_VERSION), 1)
```

(This all is reported as being from `org.gnome.SettingsDaemon.MediaKeys.desktop` because I've started kitty with a hotkey, which gnome handles through that daemon.)

**Comment by inducer** [comment]
Thank you very much for fixing this!

**Comment by kovidgoyal** [comment]
You're welcome, although I have to say that I cannot be sure that I have fixed it, since I have no way to test my fix.

**Comment by inducer** [comment]
I'll keep an eye out and let you know if it recurs. Still grateful
though. :)
