### ISSUE TITLE
`NameError: name 'highlight_collection' is not defined` when running diff

### ISSUE THREAD

**Issue by llimllib** [kovidgoyal/kitty#863]
When testing the diff command as per the README, I got an exception:

```
$ kitty +kitten diff ops/publish_benchmarks.sh ops/integration_test.sh 
Traceback (most recent call last):
  File "Python/runpy.py", line 280, in run_path
  File "Python/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 110, in <module>
  File "kitty/__main__.py", line 101, in main
  File "kitty/__main__.py", line 61, in namespaced
  File "kitty/__main__.py", line 56, in run_kitten
  File "kitty/runner.py", line 95, in run_kitten
  File "Python/runpy.py", line 208, in run_module
  File "Python/runpy.py", line 85, in _run_code
  File "kitty/main.py", line 553, in <module>
  File "kitty/main.py", line 542, in main
NameError: name 'highlight_collection' is not defined
```

The diff seemed to work completely normally though, I only saw the exception when I exited.

**Comment by llimllib** [comment]
The name `highlight_collection` is only conditionally imported on line 33:

```
try:
    from .highlight import initialize_highlighter, highlight_collection
except ImportError:
    initialize_highlighter = None
```

I have no idea why that fails, nor why you would want to let it fail, so I won't submit a PR because I don't know what it ought to do.

**Comment by kovidgoyal** [comment]
It will fail if pygments is missing (used for syntax highlighting of the diff.
