### ISSUE TITLE
Can't run executable

### ISSUE THREAD

**Issue by pranphy** [kovidgoyal/kitty#864]
I tried to build the project failed with error in one of the libpng headers. I downloaded the executable and here is what I got when trying the run the installer from inside `bin` 
   
      Traceback (most recent call last):
      File "python3.7/runpy.py", line 280, in run_path
      File "python3.7/runpy.py", line 85, in _run_code
      File "kitty/__main__.py", line 110, in <module>
      File "kitty/__main__.py", line 103, in main
      File "kitty/main.py", line 10, in <module>
      File "kitty/borders.py", line 7, in <module>
    ImportError: /home/<my_user>/Desktop/kitty-0.12.0-x86_64/bin/../lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

**Comment by kovidgoyal** [comment]
Your version of freetype is too old. Update and you will be fine.

**Comment by pranphy** [comment]
That worked.

Thank you.
