### ISSUE TITLE
Installer fails on Red Hat Enterprise Linux Workstation release 7.5

### ISSUE THREAD

**Issue by cloudyster** [kovidgoyal/kitty#869]
See stacktrace

```
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8249  100  8249    0     0  34300      0 --:--:-- --:--:-- --:--:-- 34370
Using python executable: /usr/bin/python2
Checking for latest release on GitHub...
Will download and install kitty-0.12.0-x86_64.txz
Downloaded 8088464 bytes 
Extracting tarball...
kitty successfully installed to /home/.../.local/kitty.app
Use /home/.../.local/kitty.app/bin/kitty to run kitty
Traceback (most recent call last):
  File "python3.7/runpy.py", line 280, in run_path
  File "python3.7/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 110, in <module>
  File "kitty/__main__.py", line 103, in main
  File "kitty/main.py", line 10, in <module>
  File "kitty/borders.py", line 7, in <module>
ImportError: /home/.../.local/kitty.app/bin/../lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
```

**Comment by pmontrasio** [comment]
Same problem with Ubuntu 16.04. It comes with freetype 2.6. I guess there is no way to update to something newer least an upgrade to 18.04 which ships with version 2.8 (https://launchpad.net/ubuntu/bionic/+source/freetype)

```
$ dpkg -l "*freetype*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                         Version             Architecture        Description
+++-============================-===================-===================-==============================================================
un  libfont-freetype-perl        <none>              <none>              (no description available)
ii  libfreetype6:amd64           2.6.1-0.1ubuntu2.3  amd64               FreeType 2 font engine, shared library files
ii  libfreetype6:i386            2.6.1-0.1ubuntu2.3  i386                FreeType 2 font engine, shared library files
ii  libfreetype6-dev:amd64       2.6.1-0.1ubuntu2.3  amd64               FreeType 2 font engine, development files
```

There is no kitty package for ubuntu. Debian has an old 0.11 https://packages.debian.org/buster/kitty
I guess I'll try again when I'll upgrade to 18.04, it kitty will stay on freetype 2.8.

**Comment by kovidgoyal** [comment]
Yeah if you are on a platform with no updated freetype packages you will have to either build freetype yourself or wait till you can update to use kitty. See #595 for details
