### ISSUE TITLE
Doesn't run on Linux

### ISSUE THREAD

**Issue by LukeB42** [kovidgoyal/kitty#876]
From source:

```
$ python .
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 111, in <module>
    main()
  File "./__main__.py", line 104, in main
    from kitty.main import main
  File "./kitty/main.py", line 10, in <module>
    from .borders import load_borders_program
  File "./kitty/borders.py", line 7, in <module>
    from .fast_data_types import (
ImportError: ./kitty/fast_data_types.so: undefined symbol: hb_ft_font_changed
```
From the binary release:
```
$ bin/kitty 
Traceback (most recent call last):
  File "python3.7/runpy.py", line 280, in run_path
  File "python3.7/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 110, in <module>
  File "kitty/__main__.py", line 103, in main
  File "kitty/main.py", line 10, in <module>
  File "kitty/borders.py", line 7, in <module>
ImportError: /home/luke/Downloads/kitty/bin/../lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
```

Any help would be appreciated. Thanks.

**Comment by kovidgoyal** [comment]
update freetype on your system and you will be fine.
