### ISSUE TITLE
Setting up the `linux-package` fails

### ISSUE THREAD

**Issue by dcow** [kovidgoyal/kitty#889]
I have sphinx and ncurses installed. When I try to build the linux package it fails:

```
dcow@dcx1 ~/D/kitty> python3 setup.py linux-package
CC: gcc (6, 3)
wayland-protocols >= 1.12 is required, found version: 1.7
Disabling building of wayland backend
make docs
make FAIL_WARN= -C docs man
make[1]: Entering directory '/home/dcow/Development/kitty/docs'
python3 .. +launch  -M man "." "_build" -T  
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "../__main__.py", line 111, in <module>
    main()
  File "../__main__.py", line 102, in main
    namespaced(['+', first_arg[1:]] + sys.argv[2:])
  File "../__main__.py", line 62, in namespaced
    func(args[1:])
  File "../__main__.py", line 45, in launch
    runpy.run_path(args[1], run_name='__main__')
  File "/usr/lib/python3.5/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/usr/lib/python3.5/runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '-M'
Makefile:20: recipe for target 'man' failed
make[1]: *** [man] Error 1
make[1]: Leaving directory '/home/dcow/Development/kitty/docs'
Makefile:37: recipe for target 'man' failed
make: *** [man] Error 2
```

**Comment by kovidgoyal** [comment]
That indicates sphinx-build is not in your path, see docs/Makefile
