### ISSUE TITLE
kitty +kitten crashes on python 3.6

### ISSUE THREAD

**Issue by nimbius** [kovidgoyal/kitty#891]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib64/kitty/__main__.py", line 55, in <module>
    main()
  File "/usr/bin/../lib64/kitty/__main__.py", line 46, in main
    namespaced(['+', first_arg[1:]] + sys.argv[2:])
  File "/usr/bin/../lib64/kitty/__main__.py", line 24, in namespaced
    func = namespaced_entry_points[args[1]]
KeyError: 'kitten'

**Comment by kovidgoyal** [comment]
I cannot replicate running from master:
```
kitty +kitten                                                                                                       master 
You must specify the name of a kitten to run
Choose from:

resize_window
ask
unicode_input
hints
ssh
show_error
panel
icat
clipboard
diff
```

**Comment by kovidgoyal** [comment]
You appear to be running an extremely old version of kitty, update and you will be fine.

**Comment by nimbius** [comment]
Correct, my apologies for not checking first.  I will make the update
asap.

Thanks again for your fast response!
