### ISSUE TITLE
glfw error

### ISSUE THREAD

**Issue by marekkon** [kovidgoyal/kitty#98]
I get:
```
[glfw error]  GLX: Failed to create context: BadValue (integer parameter out of range for operation)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 7, in <module>
    main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 292, in main
    run_app(opts, args)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 191, in run_app
    window = Window(viewport_size.width, viewport_size.height, args.cls)
ValueError: Failed to create GLFWwindow
```
when I try to run kitty.

**Comment by kovidgoyal** [comment]
Presumably glfw does not like the saved window size. Turn off the option to remember window size int he kitty config and you should be fine.

**Comment by lsrdg** [comment]
Hi, sorry for posting it here, but just tried to run it after building and got what seems to be the same error:

```
$ python kitty/
[glfw error 65543]: GLX: Failed to create context: GLXBadFBConfig
Failed to create GLFW window with initial size: (width=640, height=400, x_ratio=1.0, y_ratio=1.0)
[glfw error 65543]: GLX: Failed to create context: GLXBadFBConfig
Traceback (most recent call last):
  File "kitty/kitty/main.py", line 186, in run_app
    window = GLFWWindow(viewport_size.width, viewport_size.height, args.cls)
ValueError: Failed to create GLFWwindow

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kitty/__main__.py", line 15, in <module>
    main()
  File "kitty/kitty/main.py", line 295, in main
    run_app(opts, args)
  File "kitty/kitty/main.py", line 191, in run_app
    window = GLFWWindow(viewport_size.width, viewport_size.height, args.cls)
ValueError: Failed to create GLFWwindow
```

Should the commit [6b933e3](https://github.com/kovidgoyal/kitty/commit/6b933e33f5f2d46f65f3342e64c6cf27842b4127) fix this? Please, let me know if I can help with any other information. 

By the way, the `python` command above corresponds to v3.6.3 on Archlinux.
Take care (:

**Comment by kovidgoyal** [comment]
Your error is not related, the relevant error for you is:

[glfw error 65543]: GLX: Failed to create context: GLXBadFBConfig

Which indicates creation of the GLX OpenGl Context failed. That typically happens if your system is lacking opengl drivers/mesa or you are trying to run on wayland without Xwayland.

**Comment by lsrdg** [comment]
Thanks for taking the time and for the feedback. Still getting some erros, but I'll take a look at what you mentioned first. And sorry again for commenting on the wrong place.
Looking forward to give Kitty a try! (:

**Comment by kovidgoyal** [comment]
No worries. You can try running the test program that comes with glfw to debug the reason OpenGL is failing.

**Comment by lsrdg** [comment]
Thanks again, @kovidgoyal! Will certainly give it a try. Xterm is great, but I do need a better unicode support.

Take care

**Comment by wbthomason** [comment]
I'm getting a similar error to the original:

```
❯ kitty
[glfw error 65543]: GLX: Failed to create context: BadValue (integer parameter out of range for operation)
Failed to create GLFW window with initial size: (width=1906, height=1022, x_ratio=1.0, y_ratio=1.0)
[glfw error 65543]: GLX: Failed to create context: BadValue (integer parameter out of range for operation)
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 186, in run_app
    window = GLFWWindow(viewport_size.width, viewport_size.height, args.cls)
ValueError: Failed to create GLFWwindow

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 15, in <module>
    main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 295, in main
    run_app(opts, args)
  File "/usr/bin/../lib/kitty/kitty/main.py", line 191, in run_app
    window = GLFWWindow(viewport_size.width, viewport_size.height, args.cls)
ValueError: Failed to create GLFWwindow
```

This is with no `kitty.conf`; I have also tried using a `kitty.conf` only containing `remember_window_size no`, which failed in the same way (but with different dimensions for the initial size). What should I try to debug?

**Comment by wbthomason** [comment]
Making this stranger, Kitty did run correctly once on this computer.

**Comment by rpdelaney** [comment]
Same problem here after installing stock in Archlinux:

```$ kitty -v
kitty 0.11.0 created by Kovid Goyal
$ kitty --debug-config
kitty 0.11.0 created by Kovid Goyal
Linux io 4.16.13-2-ARCH #1 SMP PREEMPT Fri Jun 1 18:46:11 UTC 2018 x86_64
Running under: X11
Arch Linux \r (\l)

Config options different from defaults:
$ kitty --debug-gl
[164 15:37:47.684084] [glfw error 65543]: GLX: Failed to create context: GLXBadFBConfig
[164 15:37:47.684142] Failed to create GLFW temp window!
$ kitty
[164 15:37:49.416984] [glfw error 65543]: GLX: Failed to create context: GLXBadFBConfig
[164 15:37:49.417040] Failed to create GLFW temp window!
$ exit
```

output from `inxi -c 0 -v 2`:

```System:    Host: io Kernel: 4.16.13-2-ARCH x86_64 (64 bit) Desktop: i3 4.15 Distro: Arch Linux
Machine:   Device: portable System: Dell product: Inspiron 3520
           Mobo: Dell model: 0G8TPV v: A04 BIOS: Dell v: A04 date: 09/28/2012
Battery    BAT0: charge: 44.0 Wh 167.5% condition: 26.3/44.0 Wh (60%)
CPU:       Dual core Intel Celeron B820 (-MCP-) speed/max: 845/1700 MHz
Graphics:  Card: Intel 2nd Generation Core Processor Family Integrated Graphics Controller
           Display Server: X.Org 1.20.0 driver: i915 Resolution: 1366x768@60.01hz
           OpenGL: renderer: N/A version: N/A
Network:   Card-1: Qualcomm Atheros AR9485 Wireless Network Adapter driver: ath9k
           Card-2: Realtek RTL8101/2/6E PCI Express Fast/Gigabit Ethernet controller driver: r8169
           Card-3: Qualcomm Atheros
Drives:    HDD Total Size: 320.1GB (56.7% used)
           ID-1: model: ST320LT020
Info:      Processes: 158 Uptime: 1 day Memory: 1717.9/3811.3MB Client: Shell (bash) inxi: 2.3.27
```

**Comment by rpdelaney** [comment]
Hm, I posted too soon. `glxgears` doesn't even work. I'll troubleshoot that and report back if I still have problems with kitty after it's fixed.

**Comment by gnomechompsky** [comment]
Commenting on a closed issue in case anyone else stumbles across this. I'm running Gentoo, i3 and kitty, and ran into the same issue. I had added my user to the audio group using usermod, and forgot the -a flag, resulting in my user being removed from the video group. I added my user back to the video group, `usermod -a -G video <user>` and everything worked again.
